### ISSUE TITLE
Should faker generate required schema properties? 

### ISSUE THREAD

**Issue by nikmartin** [json-schema-faker/json-schema-faker#114]
I have a schema with several subschemas, each of which have required properties in the required:[] hash. Should json-schema-faker generate those? My tests show it doesn't outside of the randomly generated properties.

**Comment by ducin** [comment]
hello @nikmartin. Could you start with providing an example schema and the results - the actual one and the expected one?

**Comment by nikmartin** [comment]
In this schema: https://gist.github.com/nikmartin/b7cbcbe210a49545c00f
Schema item dAgency_AgencyServiceGroup is a required property of the parent schema. It is an array of objects, and each object is a schema which contains required elements dAgency_[05-08].  When generating a JSON document using this schema, the generated document is wildly random and doesn't contain many elements marked required. Using the online generator, this is an example output:

```
{
  "__s": "al",
  "_id": "cupidatat sit",
  "_info": {
    "agency_id": 92371648,
    "parent_agency_ref": "labore officia",
    "runid_sequence": -23166240,
    "runid_format": "in qui ea",
    "inventory": [
      "nulla",
      "ex veniam proident",
      "do e",
      "dolor sit Lorem ea"
    ]
  },
  "dAgency": {
    "dAgency_01": "irure ex in",
    "dAgency_02": "Ut Duis ",
    "dAgency_04": "05",
    "dAgency_AgencyServiceGroup": [
      {},
      {
        "_attr": {}
      },
      {}
    ],
    "dAgency_09": "9920019",
    "dAgency_11": "9917007",
    "dAgency_12": "1016005",
    "dAgency_13": "9912003",
    "dAgency_14": "1018005",
    "dAgency_AgencyYearGroup": [
      {
        "value": {
          "dAgency_15": 736450548564,
          "dAgency_16": {},
          "dAgency_17": {},
          "dAgency_18": {},
          "dAgency_19": {
            "_attr": {}
          },
          "dAgency_20": {},
          "dAgency_21": {}
        }
      }
    ],
    "dAgency_25": {},
    "dAgency_26": {
      "_attr": {}
    }
  }
}
```
