### ISSUE TITLE
Allow `x-faker` property in addition to `fake` to it can be validated as extension

### ISSUE THREAD

**Issue by zanona** [json-schema-faker/json-schema-faker#115]
Hi guys, I am not sure if this has been discussed before but it would be really good to be able to simply use valid swagger definitions into faker for data generation.
The problem is that the property `faker` is not really a valid property, so it would then invalidate a swagger definition.

As a suggestion I would say it would be great to be able to keep the swagger definition valid whilst preparing it for faker at the same time as per the following object:

```json
{
  "required": [
    "first_name",
    "last_name",
    "email",
  ],
  "properties": {
    "first_name": {
      "type": "string",
      "x-faker": "name.firstName"
    },
    "last_name": {
      "type": "string",
      "x-faker": "name.lastName"
    },
    "email": {
      "type": "string",
      "format": "email",
      "x-faker": "internet.email"
    }
  }
}
```

**Comment by pateketrueke** [comment]
Sounds good, implement such support shouldn't be difficult.

**Comment by ducin** [comment]
@zanona how about [`chance`](http://chancejs.com), `x-chance`? We want to support both the same way.

**Comment by pateketrueke** [comment]
> We want to support both the same way.

I guess yeah, consistency please. ;)

**Comment by ducin** [comment]
@zanona could you please reference the exact part of swagger documentation that states that `x-faker` (or something like this) conforms to swagger spec? And which version of swagger is that compatible with? When introducing it, we need to cover it in jsf docs so that other people might use it and we need details.

**Comment by zanona** [comment]
@ducin there you go man :) thanks for your help.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#vendorExtensions

**Comment by ducin** [comment]
@zanona so it's only swagger 2 (aka *OpenAPI Specification*). Swagger 1 - no?

**Comment by zanona** [comment]
@ducin yes, I trust you are correct. I've started using swagger on version 2 but from checking the documentation on 1.2 I can see it's not mentioned.

**Comment by ducin** [comment]
@pateketrueke @zanona 
So we want [such `x-faker` example](http://json-schema-faker.js.org/#%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22name%22%3A%7B%22type%22%3A%22string%22%2C%22x-faker%22%3A%22name.findName%22%7D%2C%22email%22%3A%7B%22type%22%3A%22string%22%2C%22x-faker%22%3A%22internet.email%22%7D%7D%2C%22required%22%3A%5B%22name%22%2C%22email%22%5D%7D) and [such `x-chance` example](http://json-schema-faker.js.org/#%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22userId%22%3A%7B%22type%22%3A%22string%22%2C%22x-chance%22%3A%22guid%22%7D%2C%22emailAddr%22%3A%7B%22type%22%3A%22string%22%2C%22x-chance%22%3A%7B%22email%22%3A%7B%22domain%22%3A%22fake.com%22%7D%7D%2C%22pattern%22%3A%22.%2B%40fake.com%22%7D%7D%2C%22required%22%3A%5B%22userId%22%2C%22emailAddr%22%5D%7D) to work - is that right? (currently those `x-faker`, `x-chance` are ignored).

**Comment by pateketrueke** [comment]
I understood that: `x-prefixed` properties are soft properties that swagger can ignore without warnings, otherwise it will fail because `faker` and `chance` are unknown properties. I'm right?

By just treating `x-generator` as `generator` within `jsf` would solve this issue...

**Comment by ducin** [comment]
Will get onboard with the upcoming release :) as for now @zanona, please glone `master` branch and see if it satisfies you. I think it does exactly what you intentioned.

**Comment by zanona** [comment]
@ducin @pateketrueke Thanks a lot guys, that's great.
@pateketrueke mention was correct in regards swagger warning about properties without the `x-` prefix.

**Comment by ducin** [comment]
0.3.1 has been released. @zanona please try it out and give feedback.

**Comment by zanona** [comment]
@ducin thanks a lot! Is it already live at  [http://json-schema-faker.js.org](http://json-schema-faker.js.org/#%7B%22type%22%3A%22string%22%2C%22x-faker%22%3A%22address.streetAddress%22%7D)

I've tried there but couldn't make it work?

**Comment by ducin** [comment]
nope, the demo page goes through cdn.js which relies on some kind of npm triggers, it might take a while. But please try to `npm install json-schema-faker` locally and test the behavior.

**Comment by zanona** [comment]
awesome! [tried and tested](https://tonicdev.com/zanona/57114781c79f42110025d056) guys!! looks great! Thanks a lot :100:
