### ISSUE TITLE
travis-CI setup bug

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#118]
Check this build out: https://travis-ci.org/json-schema-faker/json-schema-faker/builds/117661075

On one hand, it's green and it's exit status is 0:

    Done. Your build exited with 0.

On the other, however, there's something significantly wrong with the tests being fired:

```
> json-schema-faker@0.2.14 cover /home/travis/build/json-schema-faker/json-schema-faker
> istanbul cover --root lib --x '**/spec/**' -- jasmine-node spec --coffee
Exception loading helper: /home/travis/build/json-schema-faker/json-schema-faker/spec/helpers.coffee
[TypeError: Cannot read property 'prototype' of undefined]
No coverage information was collected, exit without writing coverage information
```

The same result for all versions of node.js. I'm afraid, none of our tests were fired since some time. @pateketrueke this is an emergency :(

**Comment by pateketrueke** [comment]
D:

**Comment by pateketrueke** [comment]
I found the bug, I've fixed `develop` and push.
