### ISSUE TITLE
[usage question] [fixture generation] [discussion] [test (anti)patterns] Sharing JSON schema between `SUT` and `spec`

### ISSUE THREAD

**Issue by hellboy81** [json-schema-faker/json-schema-faker#120]
There is json-schema in *SUT* as **JSON** file (see `json-schema` library)
This schema is used to _validate_ user input
The same schema can be used to generate fake obejcts (using `json-schema-faker`)

Can I use this `json` file to generate input data for my tests?

- If yes: In this case we are avoiding duplication. Is it OK?
- If not:  the next  question
     -  is sharing between `SUT` and `spec` unit-test antipattern?

**Comment by pateketrueke** [comment]
I don't get it, could you provide some json/code to clarify?

**Comment by ducin** [comment]
@hellboy81could you please give some more details? I read that 5 times and I can't understand what you mean...

**Comment by ducin** [comment]
@hellboy81 if you wish to clarify this one, please do so. Otherwise, it's closed, we can do nothing with it right now...
