### ISSUE TITLE
[online-demo] Issue with some faker generators in "random" category

### ISSUE THREAD

**Issue by amarinelli** [json-schema-faker/json-schema-faker#122]
http://marak.com/faker.js/#random

Some faker generators such as: **word, words, image, locale, alphaNumeric** produce an error in the console on the [demo site](http://json-schema-faker.js.org/).

Works as expected when testing locally as in the [example usage](https://github.com/json-schema-faker/json-schema-faker#example-usage).

The other generators in _random_ seem to work fine in online demo, e.g. `random.number`

> Uncaught Error: unknown faker-generator for "random.locale" in /properties/other

Input schema:
``` javascript
{
  "type": "object",
  "properties": {        
    "other": {
      "type": "string",
      "faker": "random.locale"
    }    
  },
  "required": ["other"]
}
```

Expecting:
``` javascript
{
  "other": "en_GB"
}
```

**Comment by pateketrueke** [comment]
Fixed!

http://json-schema-faker.js.org/#{%22type%22%3A%22object%22%2C%22properties%22%3A{%22other%22%3A{%22type%22%3A%22string%22%2C%22faker%22%3A%22random.locale%22}}%2C%22required%22%3A[%22other%22]}

**Comment by amarinelli** [comment]
Perfect, thank you!
