### ISSUE TITLE
[critical] remove cyclical dependency

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#126]
We've got a cyclical dependency with [traverse.js](https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/util/traverse.js) that is causing following issues:
* node.js (as no other platform) can't handle cyclical dependencies in a normal way, so the code inside traverse.js is *hacked*:
  * instead of loading `var primitives = require('./primitives');` in the top-level, the promitives in set to null, as it will be forgotten anyway; then the module.exports is wrapped with a function that will asynchronously load the primitives. This is a hacky overcome that makes the cyclical dependency work somehow, but it's very hardly readable and error-prone.
* this issue is blocking finalizing migration to typescript, because TS allows imports only on top-level of a module. And that's good.

We have to remove the cyclical dependency - then we'd finish TS migration.

Below is an example of when the cyclical dependency might be found. Use below `test.js` file and use a debugger (e.g. WebStorm):
```
var jsf = require('./index');
console.log(jsf({
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "faker": "name.findName"
    },
    "email": {
      "pattern": "\\w+@\\w+\\.\\w+"
    }
  },
  "required": [
    "name",
    "email"
  ]
}));
```
Then you'd see that - in case of an jsf-object (not a primitive), jsf loads traverse then primitives then object then traverse again:
```
(bottom)
object.js:4 -> var traverse = require('../core/traverse');
primitives.js:6 -> var _object = require('../types/object');
traverse.js:4 -> var primitives = require('./primitives');
jsf.js:2 -> traverse = require('./core/traverse'),
json-schema-faker/index.js:1
test.js:1
(surface)
```

**Comment by ducin** [comment]
Just to make the depedency task more precise, I [auto-generated a dependency graph](https://github.com/pahen/madge) for current jsf on develop:

![jsf](https://cloud.githubusercontent.com/assets/375027/14231611/5744b9d0-f98a-11e5-8d8e-85a34ef4f20c.png)

I know this auto-graph introduces some chaos, but anyway it shows that we do have much work to do here.

**Comment by ducin** [comment]
@pateketrueke I have removed both cycles (traverse -> primitives -> object -> traverse, traverse -> primitives -> array -> traverse), see latest commit on develop. There is a problem with this hacky primitives import still though. A lot smaller one, but it's still there, omg.

**Comment by pateketrueke** [comment]
Interesting...

**Comment by ducin** [comment]
Ok, I solved this bitch as well. THere's just jsf.js to be mirgated and **we're ready to go**!

**Comment by ducin** [comment]
The tests are now passing:

```
> json-schema-faker@0.2.15 test C:\Users\tomasz.ducin\Development\json-schema-faker\json-schema-faker
> npm run dev:lint && npm run dev:spec


> json-schema-faker@0.2.15 dev:lint C:\Users\tomasz.ducin\Development\json-schema-faker\json-schema-faker
> eslint lib


> json-schema-faker@0.2.15 dev:spec C:\Users\tomasz.ducin\Development\json-schema-faker\json-schema-faker
> jasmine-node spec --coffee --noStackTrace --captureExceptions

....................................................................

Finished in 0.632 seconds
68 Tests, 0 Failures, 0 Skipped
```

We've got 4 errors on our codebase during ts compilation:

```
$ ./build/tsc.sh
ts/class/Container.ts(3,26): error TS2307: Cannot find module 'randexp'.
ts/jsf.ts(1,24): error TS2307: Cannot find module 'deref'.
ts/types/array.ts(38,9): error TS2346: Supplied parameters do not match any signature of call target.
ts/types/object.ts(13,9): error TS2346: Supplied parameters do not match any signature of call target.
```

**Comment by pateketrueke** [comment]
I got the same errors on `npm run tsc` do you know what this happens?

**Comment by ducin** [comment]
OK, pull develop now. Please paste the errors you get, I'll explain.

**Comment by pateketrueke** [comment]
First one: `sh: ./build/tsc.sh: Permission denied`

**Comment by pateketrueke** [comment]
Once a `chmod +x build/tsc.sh` I got this:

```
ts/class/Container.ts(1,26): error TS2307: Cannot find module 'randexp'.
ts/jsf.ts(1,24): error TS2307: Cannot find module 'deref'
```

**Comment by ducin** [comment]
so sorry for the wrong file permissions. Could you push the right ones? Thanks in advance.
And the other erros are the very last ones we currentl get (actually it's a huge success!), they mean that TypeScript is unable to determine what randexp and what deref is. I don't know for 100%, but probably we need to ship a `.d.ts` file (definitions file) so that typescript is able to integrate external commonJS modules with our internal code.

**Comment by ducin** [comment]
Anyway, we're damn very close to shipping TypeScript jsf :)
I sent tweets to @basarat who is a friendly TypeScript ninja :) hope he'd suggest us a good way to package jsf.
