### ISSUE TITLE
Is boolean "likelihood" modifier for chance.js honoured?

### ISSUE THREAD

**Issue by amarinelli** [json-schema-faker/json-schema-faker#127]
[Example](http://json-schema-faker.js.org/#%7B%22success%22%3A%7B%22type%22%3A%22boolean%22%2C%22chance%22%3A%7B%22bool%22%3A%7B%22likelihood%22%3A100%7D%7D%7D%7D) should always return `true` but seems to just return default of 50% split between true/false.

**Comment by pateketrueke** [comment]
Did you test the same api for that chance method directly?

**Comment by amarinelli** [comment]
Seems to work as expected directly with the chance api.

`chance.bool({likelihood: 100});` always returns `true` when tested in the console of [this](http://chancejs.com/#bool) page.

**Comment by ducin** [comment]
@amarinelli you're perfectly right, I confirm it is a bug.
Actually, our library is being currently migrated into typescript with heavy refactoring (see `develop` branch). Good news is that this bug is fixed in `develop`, I just checked that :) I got
```
$ node test.js
{ success: true, id: 'http://json-schema.org/schema#' }
```
15 out of 15 times for your schema. So I consider it fixed (check the branch for yourself).

If there's no fire, we'd release the typescript-based version in few days time.

**Comment by ducin** [comment]
btw the original problem was that `boolean` was taken into account in the first step and it didn't try to execute chance.js at all. Now the order/priority of attributes is slightly different.

**Comment by amarinelli** [comment]
Perfect! Thanks for your testing and explanation @ducin.

**Comment by ducin** [comment]
@amarinelli please download new version 0.3 and try your schema - it should return `true` always. The demo page might need some delay because of CDN.js lags on auto-trigger-update

**Comment by ducin** [comment]
Ok, I consider this one as done. A new test case has been added for your case: e29a5e2.
PS @amarinelli we're looking for developers joining our team. Would you like to make jsf more awesome ;)?

**Comment by amarinelli** [comment]
Not sure I have what it takes...but I will keep submitting feedback as I continue to use your tool. Thanks again!
