### ISSUE TITLE
Extending faker throws exception "value.key.split is not a function"

### ISSUE THREAD

**Issue by arjanvanderleden** [json-schema-faker/json-schema-faker#128]
with schema fragment:

```
"name": {
          "type": "string",
          "faker": {
            "ci.subject": ["visual"}
 }
```

where the extension is configured by : 

```
jsf.extend('faker', function(faker){
  faker.locale = "nl";
  
  faker.ci = {
    subject: function(prefix) {
      var descriptor = faker.name.jobDescriptor();
      var area = faker.name.jobArea();
      return `${descriptor} ${area} ${prefix}`;
    }
  };

  return faker;
});
```
jsf throws and exception with message:
"value.key.split is not a function in /properties/projects/items/0/properties/visuals/items/0/properties/name"
The issue comes from types/string.js (line 62)

```
    var contextObject = value.gen;
    if (value.use === "faker") {
      var fakerModuleName = value.key.split('.')[0];
      contextObject = value.gen[fakerModuleName];
    }
```

since value.key is not a string but an object.
Replacing 
`var fakerModuleName = value.key.split('.')[0];`
with
`var fakerModuleName = path.split('.')[0];`
solves the issue in this case, but I don't know if it resolve the issue in general 
jsf generates output `"name": "Central Functionality visual",` as expected

**Comment by ducin** [comment]
this one is to be closed, right?

**Comment by arjanvanderleden** [comment]
Yes, it's closed
