### ISSUE TITLE
automatic testing generated values

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#132]
@pateketrueke is it possible to add spec tests that would not only check if the generator finishes successfully, but also checks the value? The #127 issue requires that 
```
{
  "success": {
    "type": "boolean",
    "chance": {
      "bool": {
        "likelihood": 100
      }
    }
  }
}
```
will always produce `true`. Can we add such test now or do we have to extend the specs to support?

This generator has always worked, but sometimes it randomly returned invalid values, and it shouldn't. I think we'l have more cases like this one (where we test the value quality, not just if it fails or not).

**Comment by pateketrueke** [comment]
Sure, if you add a `equal` property to the spec, the given object must match for `toEqual()` against the generated sample. ;)

**Comment by ducin** [comment]
Ok, added in e29a5e2
