### ISSUE TITLE
chance & faker at the same time

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#135]
Let's say I mistakenly pass both chance and faker definitions:
```
var jsf = require('./index');
var schema = {
  "type": "boolean",
  "chance": {
    "bool": {
      "likelihood": 100
    }
  },
  "faker": "internet.email"
};
console.log(jsf(schema));
```
Currently, chance is taken as the first one. Don't ask. I'd throw an exception in that case. @pateketrueke hat do you think? I'd also add a new spec for that (to expect an error).

**Comment by pateketrueke** [comment]
I think that both generators in the same definition has no sense, you're right.
