### ISSUE TITLE
[design] Unit Tests

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#137]
We are missing unit tests.

@pateketrueke Im aware you like CoffeeScript. However, I'd like to convince you to write unit tests in pure JavaScript. The reasons are:
- I've got very bad experience with it (I had to cancel one project and to rewrite it) and it's high chance I'd not get involved in writing unit tests it they're written in coffee, I just dislike it very much ;)
- no need for TS in tests - fair anough
- JS is something everyone knows and the entry level for contributors would be the lowest possible in case of JS
- the unit tests would consist of simple assertions mostly. No big logic there.

Need to decide on the ecosystem for unit tests (language & library). They would become another step in `npm test` (after lint phase maybe).

What I want to cover with tests is simply to grab a ts module, cover it with some assertions and that's it. First of all, I want to cover simple generators such as `random` and `words`. Then I'd go to more advanced stuff such as `object` and `array`. I don't trust those modules right now. They still base on hidden assumptions and when I change something, the other end might blow unexpectedly.

I don't plan to unit test modules such as `registry` - those tests would be obvious and would not bring us much value.

Awaiting your thoughts. @arjanvanderleden you too :)

**Comment by arjanvanderleden** [comment]
Still on vacation, but a quick answer to start with: I agree with @ducin on writing unit tests in js,  the entry level for contributors is not a big issue though imho,  since typescript will be part of our ecosystem anyway. More important will be the framework and library. At work we'll be making a similar choice one of these days. I'll probe my colleague for arguments in choosing a framework and hope to share some thoughts with you soon.

**Comment by ducin** [comment]
@arjanvanderleden thanks :)
As for the framework, I'd opt for jasmine. It's tdd-bdd style is fair enough for unit tests.

**Comment by pateketrueke** [comment]
:+1: 

> `jsf` is already using `jasmine-node` :)

**Comment by ducin** [comment]
OK, so we shall go with `jasmine-node`. It will be included as a new phase of `npm test` in package.json.

**Comment by ducin** [comment]
See `master` branch and run `npm run dev:unit` to see unit tests happen :-) it's just a beginning ;)

**Comment by pateketrueke** [comment]
Awesome!

**Comment by ducin** [comment]
I have added tslint (linting typescript sources, `master` branch). It will silightly take over eslint (we're not gonna lint the js output). At some point we'd remove js from this repo and keep the sources only - then we might remove eslint at all, but we're not there yet.
