### ISSUE TITLE
Wrong output for object type with patternProperties

### ISSUE THREAD

**Issue by lzrski** [json-schema-faker/json-schema-faker#139]
Extracting this from #77

Consider this JSON Schema document:

``` JSON
{
  "type": "object",
  "minProperties": 1,
  "maxProperties": 20,
  "patternProperties": {
    ".*": {
      "type": "string"
    }
  }
}
```

The output is:

``` JSON
{
  "F@^B\\(\\mdp[eKj>qUbzj7\"QwAmbK,5RTgqV6/'tu#y4IAfc;2N[N7wPlz~tnoFf'OlF/rfw=^^SWpGc\\|h(j# Q)k9\"tNYuL": "ma",
  "velit9f36": {},
  "Ut1750": {},
  "dolorc00bb": {},
  "animb8e86": {},
  "sit842e9f": {},
  "magnac5b9978": {},
  "tempor173d": {},
  "ex23e707d": {},
  "indb17c3f": {},
  "esse4763fb": {},
  "mollita10f79": {}
}
```

As you can see only the first property is correctly generated. Rest are empty objects. 

I've also noticed that first property always has much longer and more complicated name.

**Comment by pateketrueke** [comment]
Interesting issue, we need to improve our object-generator to solve that, let me see what can I do.

Thanks for your feedback!

**Comment by ducin** [comment]
[demo](http://json-schema-faker.js.org/#%7B%22type%22%3A%22object%22%2C%22minProperties%22%3A1%2C%22maxProperties%22%3A20%2C%22patternProperties%22%3A%7B%22.*%22%3A%7B%22type%22%3A%22string%22%7D%7D%7D)

**Comment by lzrski** [comment]
I've read a little through the source and it seems that the logic in `ts/types/objects.ts` could be improved.

It's a tricky business, because there are at least four properties that combined should affect the output. Take a look at spec: http://json-schema.org/latest/json-schema-validation.html#anchor64, esp. the algorithms explained in sections 5.4.4.4. and 8.3.3. Below are some thoughts I had while reading it:

1.   `properties`

    Can be `undefined` or a hashmap of name to schema.

2.  `additionalProperties`

    Can be `undefined`, `boolean` or a schema.

    According to spec `undefined` is the same as `true`.

    The `false` value can be tricky. It means that only properties listed in `properties` or matching `patternProperties` are allowed.

    If schema is given, then properties not matching `patternProperties` or not listed in `properties` should match this schema.

3.  `patternProperties`

    Tricky (edge?) case: overlapping patterns. AFAIK according to [section 8.3.3 of the spec](http://json-schema.org/latest/json-schema-validation.html#anchor137) value must match all the schemas of matching `patternProperties`.

4.  `minProperties` / `maxProperties`

    Question: what if `maxProperties` is `undefined` but `patternProperties` or `additionalProperties` are set? I would expect to get some random keys.

I think for starters we could approach it like that:

Whenever [random key is generated](https://github.com/json-schema-faker/json-schema-faker/blob/53e1dc722f8e8d6caccd357f413a3d53101910a7/ts/types/object.ts#L44) check if the generated key matches any patternProperty and if so, generate it's value using the appropriate schema.

I may shoot for a PR but can't promise. Let me know if you start working on that so we can collaborate instead of duplicating efforts.

**Comment by ducin** [comment]
I was also reading the sources and I have a feeling that most of the object logic might need to be modified. The `optProps`, according to @lzrski 's example, has only one element `.*`. The length it randomized, let's say, 15. So the rest (`length - current` elements) get randexp'ed:
```
  if (current < length) {
    words(length - current).forEach(function(key) {
      props[key + randexp('[a-f\\d]{4,7}')] = sample;
    });
  }
```

This part has to change for sure. The problem here is, however, that I don't clearly understand what do inner variables stand for.

**Comment by ducin** [comment]
@lzrski I think it'd be cool if you could contribute with a PR here :) right, @pateketrueke?

**Comment by pateketrueke** [comment]
@lzrski I you want to tackle this go ahead!

**Comment by lzrski** [comment]
I'll be happy to give it a try on the weekend.

If the #57 is solved indeed then overlapping patterns may not be such a problem. We would have to combine all matching `patternProperties` and generate value for that combined schema.

**Comment by guillemcanal** [comment]
I'll try to have a look at it on a rainy day ;)

**Comment by pateketrueke** [comment]
_¡Changos!_ :monkey:

**Comment by lzrski** [comment]
Something came up and I couldn't get to it this weekend. Sorry.

**Comment by pateketrueke** [comment]
Sorry for the inconveniences, this issue is now solved on `develop`.

I'm closing this in order to release soon! :beers:
