### ISSUE TITLE
number: exclusiveMaximum ignores part of the generation space

### ISSUE THREAD

**Issue by JonathanMontane** [json-schema-faker/json-schema-faker#142]
It seems that exclusiveMaximum shaves off a full integer even when used with a `number` type instead of an `integer`. For instance:

```
{
  "type": "number",
  "minimum": 0,
  "maximum": 2,
  "exclusiveMaximum": true
}
```

will only produce numbers in `[ 0, 1 ]` instead of `[ 0, 2 [`

```
{
  "type": "number",
  "minimum": 0,
  "maximum": 1,
  "exclusiveMaximum": true
}
```

will only output `0` instead of `[ 0, 1 [`

[link to jsf test url](http://json-schema-faker.js.org/#%7B%22type%22%3A%22number%22%2C%22minimum%22%3A0%2C%22maximum%22%3A2%2C%22exclusiveMaximum%22%3Atrue%7D)

**Comment by pateketrueke** [comment]
Reference: http://json-schema.org/latest/json-schema-validation.html#anchor17

> if "exclusiveMaximum" has boolean value true, the instance is valid if it is strictly lower than the value of "maximum".

**Comment by JonathanMontane** [comment]
Consider the following schema:
```
{
  "type": "number",
  "minimum": 1,
  "maximum": 1.5,
  "exclusiveMaximum": true
}
```

It has a valid space of `[ 1, 1.5 [` but will return `null`. The generator fails to generate a valid value, despite having a valid space as an input.

**Comment by pateketrueke** [comment]
Taking into account the constraint for schema validators (applies the same for generators) if you rest `1.5 - 1` gives you `0.5` which produce an invalid range: 1 to 0.5

I consider that to be wrong but not warnings are thrown yet, see: #140 (discussion is open in order to take appropiate actions to mitigate common mistakes)

Back to your main issue: you found a bug!

```json
{
  "type": "number",
  "minimum": 0,
  "maximum": 2,
  "exclusiveMaximum": true
}
```

After simple math happen due "exclusive" constraints we can randomize a number between 0 and 1 but we're never obtaining 1.

Possible values are: 0.123123, 1.8972384, and such `(x >= 0 && x <= 1)`

PR: #144

**Comment by JonathanMontane** [comment]
in `lib/types/number.js`
```
    if (multipleOf) {
        max = Math.floor(max / multipleOf) * multipleOf;
        min = Math.ceil(min / multipleOf) * multipleOf;
    }
    if (value.exclusiveMinimum && value.minimum && min === value.minimum) {
        min += multipleOf || 1;
    }
    if (value.exclusiveMaximum && value.maximum && max === value.maximum) {
        max -= multipleOf || 1;
    }
    if (min > max) {
        return NaN;
    }
    if (multipleOf) {
        return Math.floor(random.number(min, max) / multipleOf) * multipleOf;
    }
    return random.number(min, max, undefined, undefined, true);
```

should probably be changed to:

```
    if (min >= max) {
        if (value.exclusiveMinimum || value.exclusiveMaximum) {
             return NaN;
        } else {
             if (min === max && min === Math.floor(min / multipleOf) * multipleOf) {
                  return min;
             }
             return NaN;
        }
    }
    if (value.exclusiveMinimum && value.minimum && min === value.minimum) {
        min += multipleOf || 0;
    }
    var raw = random.number(min, max, undefined, undefined, true)
    // if raw equal min and min is exclusive, update to a valid number
    if (value.exclusiveMinimum && raw === min) {
        raw += max/2;
    }
    if (multipleOf) {
        raw = Math.floor(raw / multipleOf) * multipleOf;
    }
    return raw;

**Comment by JonathanMontane** [comment]
`integer.js` should also be updated to better manage `multipleOf`, and `exclusive(Max|Min)imum`, but it shouldn't be too hard

**Comment by pateketrueke** [comment]
Indeed `integer.js` reuse the `number.js` module for support that.

BTW; I've updated #144 with a more simple solution, can review it?

**Comment by JonathanMontane** [comment]
Be careful, I've updated the code quite a few times now (fixed a few bugs)

**Comment by pateketrueke** [comment]
My bad, I've never commited the built files (from ./ts to ./lib) and CI (and probably you) was running the older ones...

Now the PR is fully updated and seems to be working!

**Comment by ducin** [comment]
Hi guys! WHat is the status of this - anything to be merged into `master`?

BTW currently we've got both TS sources and JS output. That's crappy, yet, it's only a temporary solution. When either of us have time, we'll remove JS output from the repo.

**Comment by pateketrueke** [comment]
This issue is also gone! >:D
