### ISSUE TITLE
Chance and Faker are always require()'ed by Webpack

### ISSUE THREAD

**Issue by bitantics** [json-schema-faker/json-schema-faker#148]
Hey!

I've found there's undesired behavior when consuming json-schema-faker through Webpack and perhaps other bundlers or compilers.

#### What I expect
Faker/Chance to not be bundled into my app if I'm not using any functions from Faker/Chance.

#### What I get
Faker/Chance is included into my bundle, bloating the size and, in Faker's position, breaking the bundle's sourcemaps.

#### Solutions
A few that come to mind:
- Keep auto-detect behavior, but be smarter for bundler use-cases
- Support bring-your-own-generator through monkeypatching or a global library constructor
- Different entrypoints for different included generators
- Dead code elimination

#### Environment
Webpack v1.13.0
json-schema-faker v0.3.1
Faker v3.1.0
Chance v1.0.2

**Comment by pateketrueke** [comment]
Try requiring `json-schema-faker/lib` instead.

**Comment by bitantics** [comment]
Awesome, that worked, thanks!

The full snippet to use jsf with Chance, but not Faker, is:

```javascript
import rawJsf from 'json-schema-faker/lib';
import { Chance } from 'chance';

// We don't want to import `json-schema-faker` as it will
// import Chance *and* Faker. So we import just
// `json-schema-faker/lib` and manually add Chance back in.
const jsf = rawJsf.extend( 'chance', () => new Chance());
```
