### ISSUE TITLE
Question: is there a way to always fake non required properties?

### ISSUE THREAD

**Issue by MarcosMenegazzo** [json-schema-faker/json-schema-faker#154]
Is there a way to always fake non required properties? It will be very good for some tests to always fake optional properties, because there are cases where an optional property, when included, has required properties itself.

**Comment by pateketrueke** [comment]
I think is related with #81 but I'm not sure, of course all related to configuring `jsf` itself is planned but not ready yet...

**Comment by ruifortes** [comment]
why is this taking so long?

**Comment by pateketrueke** [comment]
> why is this taking so long?

Solved! ;-)

**Comment by ndbroadbent** [comment]
Thanks @pateketrueke! It would be great if this option could be added to the README. I only found this after searching for "optional" in the GitHub issues.
