### ISSUE TITLE
jsf.option() is not defined

### ISSUE THREAD

**Issue by julienvincent** [json-schema-faker/json-schema-faker#155]
In the docs, it mentions that one can set options on jsf by doing the following:

```javascript
jsf.option({
  failOnInvalidTypes: false
});
```

There is however, no method `option` on the exported jsf function that I can see?

**Comment by ducin** [comment]
Hello @julienvincent, thanks for your feedback.
Could you please state exactly how do you use JSF? Is that bower, npm, cnd.js, git or any other way?

Please open http://json-schema-faker.js.org (demo page) where jsf is exported globally. Open dev tools console and type `jsf.option` as below:
![image](https://cloud.githubusercontent.com/assets/375027/15462012/d8df12ea-20bf-11e6-95d5-4b84f8116327.png)

**Comment by julienvincent** [comment]
I apologise - I was not using the latest version of jsf. I just updated and everything is working as expected 👍
