### ISSUE TITLE
JSF drops required properties if not present in the properties field

### ISSUE THREAD

**Issue by JonathanMontane** [json-schema-faker/json-schema-faker#158]
[link to jsf demo](http://json-schema-faker.js.org/#%7B%22properties%22%3A%7B%22test%22%3A%7B%22type%22%3A%22string%22%7D%2C%22count%22%3A%7B%22type%22%3A%22integer%22%7D%7D%2C%22additionalProperties%22%3A%7B%22type%22%3A%22string%22%2C%22faker%22%3A%22internet.email%22%7D%2C%22patternProperties%22%3A%7B%22%5Eignored%22%3A%7B%22type%22%3A%22string%22%7D%2C%22prop%24%22%3A%7B%22faker%22%3A%22name.findName%22%7D%7D%2C%22required%22%3A%5B%22test%22%2C%22count%22%2C%22dropped%22%2C%22ignored-prop%22%5D%7D)

if the required field contains keys that are not present in the properties field, they will be ignored.

The JSON Schema spec does not constrain the required fields to be defined in the `properties` field.
[An object is considered valid wrt the `required` field iff all the keys in its array are also present in the object being validated.](http://json-schema.org/latest/json-schema-validation.html#anchor63)

Therefore the following JSON Schema:

``` js
{
  "properties": {
    "test": {
      "type": "string"
    },
    "count": {
      "type": "integer"
    }
  },
  "additionalProperties": {
    "type": "string",
    "faker": "internet.email"
  },
  "patternProperties": {
    "^ignored": {
      "type": "string"
    },
    "prop$": {
      "faker": "name.findName"
    }
  },
  "required": [
    "test",
    "count",
    "dropped",
    "ignored-prop"
  ]
}
```

should generate an object similar to the following:

``` js
{
  "test": "amet",
  "count": 42811068,
  "dropped": "Jennie_Williamson45@hotmail.com",
  "ignored-prop": "Elroy Thompson"
}
```

instead of

``` js
{
  "test": "esse Duis",
  "count": 55240519,
  "ignored": "fugiat"
}
```

please note that the order in which the resolution of required params should be done is:
- `properties`
- `patternProperties` (it should respect all properties from each matched pattern)
- `additionalProperties`
- `{}` if none was found

**Comment by ducin** [comment]
As #159 is already merged, can we close this #158? @pateketrueke, @JonathanMontane?

**Comment by ducin** [comment]
Ah, no. It needs to be merged from develop into master. @pateketrueke, we'd do that and release a new patch version, huh?

**Comment by pateketrueke** [comment]
Seems like this issue is gone, at least on the `develop` branch. 🎉
