### ISSUE TITLE
key should have quotes surrounding it.  

### ISSUE THREAD

**Issue by sophieyoung717** [json-schema-faker/json-schema-faker#160]
The result data I got is:

{ id: 'pid594',
    name: 'Duis mollit fugiat nostrud',
    brand: null,
    category: 'TV',
    price: 2752,
    amount: 49,
    discount: null },

This is not valid 

id, name,... should be "id","name"

**Comment by pateketrueke** [comment]
Seems like you got a plain object, you should use `JSON.stringify()` in order to quote it properly.

**Comment by sophieyoung717** [comment]
Thank you!!!
