### ISSUE TITLE
Error thrown in certain usage of oneOf / anyOf

### ISSUE THREAD

**Issue by ClayBenson94** [json-schema-faker/json-schema-faker#163]
Hello!

First and foremost, thanks for the awesome lib!

The bug I am encountering is using the [following](http://json-schema-faker.js.org/#%7B%22title%22%3A%22Simpleton%22%2C%22description%22%3A%22An%20individual%20person%22%2C%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22maritalStatus%22%3A%7B%22title%22%3A%22Marital%20Status%22%2C%22description%22%3A%22The%20current%20marital%20state%20%28for%20example%2C%20single%2C%20married%2C%20or%20divorced%29%20of%20the%20person.%22%2C%22oneOf%22%3A%5B%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22maritalCategory%22%3A%7B%22title%22%3A%22Marital%20Category%22%2C%22description%22%3A%22The%20higher-level%20marital%20category%20of%20the%20person.%22%2C%22enum%22%3A%5B%22single%22%2C%22married%22%5D%2C%22type%22%3A%22string%22%7D%7D%2C%22additionalProperties%22%3Afalse%2C%22required%22%3A%5B%22maritalCategory%22%5D%7D%2C%7B%22type%22%3A%22object%22%2C%22maxProperties%22%3A0%7D%5D%7D%7D%2C%22required%22%3A%5B%22maritalStatus%22%5D%2C%22additionalProperties%22%3Afalse%7D) schema. If you open multiple tabs of that link, you'll notice that sometimes only `true` or `false` is displayed in the sample output panel (likely due to the error posted later that I get when I run it locally in my node project).

From what I can tell, this schema should either generate
`{
  "maritalStatus": {
    "maritalCategory": "married"
  }
}`
or
`{
  "maritalStatus": {}
}`

Using [JSON Schema Validator](http://www.jsonschemavalidator.net/) shows that both of these outputs conform to the schema.

Instead what happens is I (sometimes) get the following error in the console:

```
/media/sf_shared_vm/hub-test-harness/node_modules/json-schema-faker/lib/core/run.js:57
            throw new Error(e.message + ' in ' + '/' + e.path.join('/'));
            ^

Error: missing properties for {"title":"Marital Status","description":"The current marital state (for example, single, married, or divorced) of the person.","type":"object","maxProperties":0} in /properties/maritalStatus
    at run (/media/sf_shared_vm/hub-test-harness/node_modules/json-schema-faker/lib/core/run.js:57:19)
    at jsf (/media/sf_shared_vm/hub-test-harness/node_modules/json-schema-faker/lib/index.js:7:12)
    at Object.<anonymous> (/media/sf_shared_vm/hub-test-harness/src/ind2.js:8:28)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

The result is similar when using `anyOf`, except it happens every time instead of happening randomly with `oneOf`.

This bug does not occur when using `allOf`, and instead will _always_ generate a maritalCategory.

**Comment by ClayBenson94** [comment]
Update!

I just noticed that using [this](http://json-schema-faker.js.org/#%7B%22title%22%3A%22Simpleton%22%2C%22description%22%3A%22An%20individual%20person%22%2C%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22maritalStatus%22%3A%7B%22title%22%3A%22Marital%20Status%22%2C%22description%22%3A%22The%20current%20marital%20state%20(for%20example%2C%20single%2C%20married%2C%20or%20divorced)%20of%20the%20person.%22%2C%22oneOf%22%3A%5B%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%22maritalCategory%22%3A%7B%22title%22%3A%22Marital%20Category%22%2C%22description%22%3A%22The%20higher-level%20marital%20category%20of%20the%20person.%22%2C%22enum%22%3A%5B%22single%22%2C%22married%22%5D%2C%22type%22%3A%22string%22%7D%7D%2C%22additionalProperties%22%3Afalse%2C%22required%22%3A%5B%22maritalCategory%22%5D%7D%2C%7B%22type%22%3A%22object%22%2C%22properties%22%3A%7B%7D%2C%22maxProperties%22%3A0%7D%5D%7D%7D%2C%22required%22%3A%5B%22maritalStatus%22%5D%2C%22additionalProperties%22%3Afalse%7D) schema instead of the previous gets rid of the problem. The sad part is, I have about 160 of these schemas provided dynamically to my code, so I cannot manually modify the schema to add this fix.

**Comment by ClayBenson94** [comment]
I noticed I can fix this issue by adding
```
function hasProperties(obj) {
    if(obj.maxProperties == 0) {
        return false;
    }
    var properties = [];
```
on [line 21 of utils.js](https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/core/utils.js#L21). I'm just not 100% sure what effects it might have on other operation. Thoughts?

**Comment by pateketrueke** [comment]
Interesting... let me investigate, thanks for your feedback!

**Comment by pateketrueke** [comment]
Fixed, releasing soon! 🍻
