### ISSUE TITLE
Faker and Chance dependencies still included

### ISSUE THREAD

**Issue by julienvincent** [json-schema-faker/json-schema-faker#164]
As per the readme:

> Since 0.3.0 the faker and chance dependencies aren't shipped by default, in order to use both generators you MUST install them with npm install faker chance --save

However looking at the package.json, both dependencies are still included. Was this a mistake, or do you intend to keep them as dependencies?

**Comment by pateketrueke** [comment]
Let me think... I guess we'll keep that dependencies until the next release is ready, I don't see them being required for projects that doesn't need to use faker/chance.

**Comment by julienvincent** [comment]
I'm not even sure it is necessary to remove them. Projects that do not need faker and chance can just require `json-schema-faker/lib`.

**Comment by pateketrueke** [comment]
FTR; now we have `casual` support, and probably we may want to support almost any generator based on custom keywords (see #134), the issue here is #133 which is critical for end users.

I like the idea of "extending" the keyword support, and then hook built-in generators, etc.

**Comment by pateketrueke** [comment]
JSF is pretty fast and lean now, closing towards the future!
