### ISSUE TITLE
support custom generators

### ISSUE THREAD

**Issue by atian25** [json-schema-faker/json-schema-faker#169]
so I can extend a custom generators such as `mockjs`, then use `{ type: 'string', mockjs: '@title' }`

now I can only extend a format and use `{ type: 'string', format: 'mockjs', mockRule: '@title' }`

**Comment by ducin** [comment]
@atian25 I don't understand what you mean, no idea at all. Can you provide a more detailed description? What you want, what you already have and what schemas you expect to produce what results? Without that, we won't help you.

**Comment by atian25** [comment]
https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/class/Container.js#L13

`faker` and `chance` is build-in mock lib, I just request to offer an interface to add custom mock lib.

for example, we create a mock lib [`mockjs`](http://mockjs.com/)

then extend `jsf` below:
```
const jsf = require('json-schema-faker');
const MockJS = require('mockjs');
jsf.format('mockjs', (gen, schema) => {
  const mockRule = schema.mockRule;
  if (!mockRule) {
    throw Error('mockjs: mockRule property in json scheme is required');
  }
  return MockJS.mock.apply(MockJS, [mockRule]);
});
```

usage: `{ type: 'string', format: 'mockjs', mockRule: '@title' }`

each time we need to repeat `format: 'mockjs'`

so I'm asking add some extend way, so we can just use: `{ type: 'string', mockjs: '@title' }`

that is `mockjs:''` is a keyword just as `faker: 'name.findName'` and `"chance": {"email": {"domain": "fake.com"}}`

**Comment by pateketrueke** [comment]
@ducin

I like the idea of extending generators.

In fact that way we can get rid of `faker`, `chance` and now `casual`. 🤔 

On that case we need a more general solution just because faker use namespaced functions, casual use getters/functions, etc.
