### ISSUE TITLE
reuse of definition results in invalid fake generated

### ISSUE THREAD

**Issue by chrisns** [json-schema-faker/json-schema-faker#172]
Hello,
Occasionally the faker is producing an invalid fake
Hit generate a bunch of times and sometimes you'll see the `{"centre_to": {}}` but the schema defines it as a string, and exactly the same definition as the "centre" which doesn't appear to have the same issue

[demo](http://json-schema-faker.js.org/#%7B%22definitions%22%3A%7B%22centre%22%3A%7B%22type%22%3A%22string%22%7D%7D%2C%22type%22%3A%22object%22%2C%22additionalProperties%22%3Afalse%2C%22properties%22%3A%7B%22centre%22%3A%7B%22%24ref%22%3A%22%23%2Fdefinitions%2Fcentre%22%7D%2C%22centre_to%22%3A%7B%22%24ref%22%3A%22%23%2Fdefinitions%2Fcentre%22%7D%7D%2C%22required%22%3A%5B%22centre%22%2C%22centre_to%22%5D%7D)

```
{
  "centre": "xdxuulcavtpnospkokejycm",
  "centre_to": {}
}
```

expect to consistently see something more like:

```
{
  "centre": "xdxuulcavtpnospkokejycm",
  "centre_to": "randomstringhere"
}
```

[this works however](http://json-schema-faker.js.org/#%7B%22definitions%22%3A%7B%22centre%22%3A%7B%22type%22%3A%22string%22%7D%2C%22centreb%22%3A%7B%22type%22%3A%22string%22%7D%7D%2C%22type%22%3A%22object%22%2C%22additionalProperties%22%3Afalse%2C%22properties%22%3A%7B%22centre%22%3A%7B%22%24ref%22%3A%22%23%2Fdefinitions%2Fcentre%22%7D%2C%22centre_to%22%3A%7B%22%24ref%22%3A%22%23%2Fdefinitions%2Fcentreb%22%7D%7D%2C%22required%22%3A%5B%22centre%22%2C%22centre_to%22%5D%7D) where I make the same definiton twice

**Comment by pateketrueke** [comment]
Sorry for the inconveniences, this issue is now solved on `develop`.

I'm closing this in order to release soon! :beers:
