### ISSUE TITLE
Feature: purposefully generate invalid data based on schema

### ISSUE THREAD

**Issue by mm-gmbd** [json-schema-faker/json-schema-faker#174]
I'm building a API regression tester out of a multitude of tools, and this looks like a great tool for generating valid data based on JSON-schema. However, I'd like to test the API implementation against invalid input, and would therefore like to be able to generate various *invalid* JSON datasets based on a valid schema.

Thoughts on this? I'd be happy to help :smile:

**Comment by ducin** [comment]
Hi @mm-gmbd, I had to read this through few times :) and this is how I understand the situation:
* JSON Schema faker uses schemas to generate valid JSON
* you want to extend `jsf` to generate invalid JSONs based on the same schemas
Am I right?

* first of all, we need contributors very very much. If you are willing to help make `jsf` better, we are more than happy to have you joined the team!
* secondly, I'm afraid `jsf` will *not* have the ability to generate *invalid* JSONs based on valid schemas. This is somehow beyond the scope of jsf. And even if it was, it'd be quite expensive (time) to provide the (optional) wrong behavior. For all features of JSON schema we'd need to provide an evil twin (the evil one) - is that what you mean?

I have a better idea. You could write a tool that stands on top of jsf. It takes an original schema and modifies it a little bit to provide some evil twin behavior. But it just returns a modified, invalid schema. Then, the invalid schema is used to generate invalid JSON. Example: `additionalProperties: false` (original) changed to include a new (random key) required property (which is of course invalid in terms of original schema).

Does that make sense to you?

**Comment by mm-gmbd** [comment]
Hey @ducin, after writing this, I came across [json-schema-test-data-generator](https://github.com/bojand/json-schema-test-data-generator), which seems to already incorporate the "evil twin" functionality, and appears to be based on this library :smile: way to go, open source community!

**Comment by ducin** [comment]
@mm-gmbd I'll close this one. And by the way, you're welcome to help us make `jsf` better - catch me or Alvaro (@pateketrueke) if you will to :)

**Comment by Otto-AA** [comment]
For those who still come across this issue, I've created a non-perfect "invalidator" for my project.

It basically switches the type of one value in the sample.
The downside of this is, that if you have a property with the type number and also `min: 10`, then it won't test values below 10 but only other types.

It can be used like `jsf.resolve(schema).then(makeSampleInvalid).then(invalidSample => doSomethingWithIt(invalidSample))`

<details>
  <summary>Code</summary>

```javascript
// Note: If you don't want to use faker, that's also possible
const faker = require('faker');

function makeSampleInvalid(sample) {
    const numValues = getNestedKeys(sample).length;
    const targetIndex = Math.floor(Math.random() * numValues);

    forEachPropInNestedObj(sample, (obj, key, index) => (index === targetIndex) ? obj[key] = changeValueType(obj[key]) : {});

    return sample;
}

function changeValueType(val) {
    return getRandomVal({ excludeTypes: [ typeof val ] });
}

function getRandomVal( { excludeTypes = [] } = {}) {
    const typeGenerators = {
        undefined: () => undefined,
        object: generateRandomObject,
        boolean: faker.random.boolean,
        number: faker.random.number,
        string: faker.random.words
    };
    excludeTypes.forEach(type => type in typeGenerators ? delete typeGenerators[type] : {});
    const randomGenerator = faker.random.objectElement(typeGenerators);
    return randomGenerator();
}

function generateRandomObject() {
    const obj = {};
    const numProperties = Math.floor(Math.random() * 3);

    for (let i = 0; i < numProperties; i++) {
        const key = faker.random.words();
        const val = getRandomVal();
        obj[key] = val;
    }
    return obj;
}

function getNestedKeys (obj) {
    const keysForNonObjects = Object.keys(obj).filter(key => typeof obj[key] !== "object");
    const keysForObjects = Object.keys(obj).filter(key => typeof obj[key] === "object");
    const nestedKeys = [];
    keysForObjects.forEach((key) => nestedKeys.push(...getNestedKeys(obj[key])));

    return [...keysForNonObjects, ...nestedKeys];
}

function forEachPropInNestedObj(obj, callback, indexObj = { index: 0 }) {
    const keys = Object.keys(obj);

    keys.forEach(key => {
        callback(obj, key, indexObj.index);
        indexObj.index++;

        if (typeof obj[key] === "object") {
            return forEachPropInNestedObj(obj[key], callback, indexObj);
        }
    });
}
```
</details>
