### ISSUE TITLE
inline dereferencing not working with schema provided

### ISSUE THREAD

**Issue by alexandergorskih** [json-schema-faker/json-schema-faker#175]
I tried to use (http://json-schema-faker.js.org/) but URL does not get updated. So I'm going to paste code here.

According to (http://json-schema.org/latest/json-schema-core.html#anchor30) following schema should be valid.

``` json
{
    "type" : "object",
    "id" : "forecast",
    "properties" : {
        "currently" : {
            "$ref" : "#/definitions/datapoint",
            "required" : false
        },
    },
    "definitions": {
        "datapoint": {
            "type" : "object",
            "id" : "datapoint",
            "properties" : {
                "time" : {
                    "type" : "number",
                    "required" : true
                }
            }
        },
        "datablock": {
            "type" : "object",
            "id" : "datablock",
            "properties" : {
                "data" : {
                    "type" : "array",
                    "required" : false,
                    "items" : {
                      "$ref" : "datapoint"
                    }
                }
            }
        }
    }
}
```

Fake data generation not working. How can I reference datapoint from datablock's data property?

**Comment by ducin** [comment]
hi @gorskih, thanks for your submission. Actually:
* your schema has an invalid comma right after `currently`
* the schema should have the `required` attributes in a different place - at least I don't know if you can place `"required": "true"` inline in each property. Below is your definition executed server-side:
```
{
  "type" : "object",
  "id" : "forecast",
  "properties" : {
    "currently" : {
      "$ref" : "#/definitions/datapoint"
    }
  },
  "required": ["currently"],
  "definitions": {
    "datapoint": {
      "type" : "object",
      "id" : "datapoint",
      "properties" : {
        "time" : {
          "type" : "number"
        }
      },
      "required": ["time"]
    },
    "datablock": {
      "type" : "object",
      "id" : "datablock",
      "properties" : {
        "data" : {
          "type" : "array",
          "items" : {
            "$ref" : "datapoint"
          }
        }
      }
    }
  }
}
```

* but after fixing it, we have an error somewhere in our code anyway :( we get `Uncaught ReferenceError: Buffer is not defined`, seems like the browserified bundle is missing some code there.

Need to investigate it further.

**Comment by pateketrueke** [comment]
Sorry for the inconveniences, this issue is now solved on `develop`.

I'm closing this in order to release soon! :beers:
