### ISSUE TITLE
Strange behaviour relating faker produced data.

### ISSUE THREAD

**Issue by gorskih** [json-schema-faker/json-schema-faker#176]
I'm getting strange behaviour relating faker produced data.

Schema:
```json
{
    "type": "object",
    "id": "forecast",
    "properties": {
        "latitude": {
            "type": "number",
            "faker": "address.latitude"
        },
        "longitude": {
            "type": "number",
            "faker": "address.longitude"
        },
        "offset": {
            "type": "number"
        }
    },
    "required": ["latitude", "longitude", "offset"]
}
```

URL: http://json-schema-faker.js.org/#%7B%22type%22%3A%22object%22%2C%22id%22%3A%22forecast%22%2C%22properties%22%3A%7B%22latitude%22%3A%7B%22type%22%3A%22number%22%2C%22faker%22%3A%22address.latitude%22%7D%2C%22longitude%22%3A%7B%22type%22%3A%22number%22%2C%22faker%22%3A%22address.longitude%22%7D%2C%22offset%22%3A%7B%22type%22%3A%22number%22%7D%7D%2C%22required%22%3A%5B%22latitude%22%2C%22longitude%22%2C%22offset%22%5D%7D

Result:
```json
{
  "latitude": "36.1109",
  "longitude": "-89.2872",
  "offset": -29260714.79572223
}
```

Expected result:
```json
{
  "latitude": 36.1109,
  "longitude": -89.2872,
  "offset": -29260714.79572223
}
```

Why types are ignored and I'm getting strings instead of numbers?

Code using Faker:
```
var faker = require('faker');
console.log(faker.address.latitude());
```
Always returns number not string.

**Comment by pateketrueke** [comment]
Actually what you're seeing as `console.log()`output is only the value, not the type of that value:

```js
var faker = require('faker');
console.log(faker.address.latitude()); // -4.1993
console.log(typeof faker.address.latitude()); // string
```

Remember this is Javascript, so not always what you see is what you get, or what you think it is. :beers:

**Comment by gorskih** [comment]
Sad(
