### ISSUE TITLE
extreme future in date-time built-in format

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#180]
When executing [built-in `date-time` format](http://json-schema-faker.js.org/#gist/3119df248bee9b570d748b91b8637207), most of the times I get dates that are far far away in the future such as:
- `"5080-09-15T23:40:37.081Z"`,
- `"4150-04-13T09:32:34.409Z"`, etc.

Although it is correct, according to [JSON Schema spec](http://json-schema.org/latest/json-schema-validation.html#anchor108) and [RFC3339](http://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14), I think it makes no sense to generate such values. Faker is supposed to generate meaningful data, mostly to mock the systems. Dates such as `5080-09-15` are useless imho.

Current code is [here](https://github.com/json-schema-faker/json-schema-faker/blob/4d588c61ca78e275ddc6e06e8c66a69b8669c8ba/ts/generators/dateTime.ts#L9). It is executing `new Date(random.number(0, 100000000000000)).toISOString();`. We've got following boundaries now:
- `new Date(0).toISOString()` -> `"1970-01-01T00:00:00.000Z"`
- `new Date(100000000000000).toISOString()` -> `"5138-11-16T09:46:40.000Z"`

I suggest that we narrow it down to either of the following:
- `new Date(2524608000000).toISOString()` -> `"2050-01-01T00:00:00.000Z"`
- `new Date(10000000000000).toISOString()` -> `"2286-11-20T17:46:40.000Z"`

**Comment by foreseaz** [comment]
Totally agree with @ducin , besides, adding built-in `current-date-time` should be handy for testing.

**Comment by pateketrueke** [comment]
> adding built-in current-date-time should be handy for testing.

Could you expand on this?
