### ISSUE TITLE
Suggestion: Remove TypeScript from logo

### ISSUE THREAD

**Issue by coryhouse** [json-schema-faker/json-schema-faker#188]
I saw the logo and almost walked away thinking I had to use TypeScript. Turns out, this works awesome and has no TS requirement. Thanks!

**Comment by ducin** [comment]
@coryhouse the logo background was to celebrate the migration from JS to TS :) it's meand to be removed, now we have additional motivation.

**Comment by coryhouse** [comment]
Thanks for clarifying. Motivation indeed! :)

Anyway, really enjoying this project 👍
