### ISSUE TITLE
Is there a way to declare static data?

### ISSUE THREAD

**Issue by coryhouse** [json-schema-faker/json-schema-faker#194]
I'd like to declare an array of static objects as part of my schema. Is there a way to do so?

**Comment by pateketrueke** [comment]
You can use `enum`:

```json
{
  "type": "object",
  "properties": {
    "staticData": {
      "enum": [
        { "foo": "bar" }
      ]
    },
    "dynamicData": {
      "anyOf": [
        { "type": "string" },
        { "type": "number" }
      ]
    }
  },
  "required": ["staticData"]
}
```

I'm not sure if there are more clever/clean solutions, but it's valid. ;)

**Comment by coryhouse** [comment]
Great, enum is what I used. But since enum really just conveys "pick one of these at random", I did three things to make it always return the same array (though potentially in a different order)

1. Set minItems and maxItems to the same number so the array length is predictable. 
2. Set uniqueItems to true so each element is unique.

With this approach, the only thing that isn't static is the order of the elements in the array. Good enough for now.

Example:

```
export const schema = {
  "type": "object",
  "properties": {
    "dealerTeam": {
      "type": "array",
      "minItems": 40,
      "maxItems": 40,
      "uniqueItems": true,
      "items": {
        "enum": [
          {
            dealerTeamId: 6,
            name: "Jordon Cremin",
            role: "Manager"
          },
         ...
```

**Comment by ducin** [comment]
@coryhouse do you find this issue resolved or would you suggest any improvement? If so, please give details.

**Comment by coryhouse** [comment]
The approach I outlined works, though it feels clunky. Is there a more elegant way to declare static data as a portion of the schema?

**Comment by pateketrueke** [comment]
> Is there a more elegant way to declare static data as a portion of the schema?

In json-schema there's a `default` property which can be useful for this purpose, did you considered it before?

I'm not sure if there's another solution from the json-schema itself, if not would be interesting hear any ideas.

**Comment by pateketrueke** [comment]
I think the only way to declare static data is using `default` properties, so is not worthy implementing anything outside the standard.

Probably using json-schema keywords for achieving something similar is not clean or clever, but at least it's very portable and reusable.

I'm working on implementing the `default` keyword approach, so this will be solved asap.
