### ISSUE TITLE
Limiting array maxItems and string maxLength

### ISSUE THREAD

**Issue by kylef** [json-schema-faker/json-schema-faker#199]
Hi,

I'm looking at `json-schema-faker` (thanks for all your work on the project) but I see some potential performance problems when the schema is supplied from a user. When a user is in control of the schema, they would be able to set extremely high `maxItems` and `maxLength` which would take an extremely long time to generate that many items for.

As an example, I can ask for a maxItems of `20000000`:

```json
{
  "type": "array",
  "items": {"type": "string"},
  "maxItems": 20000000
}
```

This MAY take json-schema-faker an awfully long time to complete since it using a random number generator against `maxItems`.

A similar problem can be demonstrated with a `string`:

```json
{
  "type": "string",
  "maxLength": 20000000,
  "minLength": 10000000
}
```

I think it would be nice to be able to set a limit to `maxItems`/`maxLength` so that `json-schema-faker` will use the minimum of the configured `maxItems`, even if the `minLength`/`minItems` from the schema is a larger number.

I'm more than happy to provide a pull request for json-schema-faker to be able to allow you to configure maximum limits. Would you be willing to accept some patch for this and how would you like me to design the feature?

Perhaps we could just have custom options `maxLength` and `maxItems`, when set this will limit the `maxLength`/`maxItems` that can be used?

**Comment by pateketrueke** [comment]
I think we need this...

At this moment we can use `jsf.option()` in order to achieve those kind of setup.

Adding support either for `jsf.option({ maxLength: 100 })` or `jsf.option({ defaults: { maxLength: 100 } })` would be enough.

Please also read the [docs](https://github.com/json-schema-faker/json-schema-faker/tree/master/docs) in order to contribute according our guidelines.
