### ISSUE TITLE
json-schema-faker-cli

### ISSUE THREAD

**Issue by oprogramador** [json-schema-faker/json-schema-faker#203]
I was missing a possibility of using this library directly via CLI so I created json-schema-faker-cli module (https://github.com/oprogramador/json-schema-faker-cli). Can I open a PR with updated README with a link to my repo? Or maybe a PR with adding such a possibility to json-schema-faker?

**Comment by pateketrueke** [comment]
> Can I open a PR with updated README with a link to my repo?

Sure, you're welcome to contribute!
