### ISSUE TITLE
How to generate some object which has some same value?

### ISSUE THREAD

**Issue by TingYinHelen** [json-schema-faker/json-schema-faker#204]
If I want to generate an array which has some objects, and I want to indicate some value, but another value I want to fake it. So how to generate this json. Well, the below is the example that I want to get:

![Uploading Screen Shot 2016-10-28 at 3.02.26 PM.png…]()

I want to indicate the value of category, but fake the value of expense. How do I config?

**Comment by TingYinHelen** [comment]
<img width="417" alt="screen shot 2016-10-28 at 3 02 26 pm" src="https://cloud.githubusercontent.com/assets/14006826/19797954/bde0106a-9d20-11e6-9648-294c53216807.png">

**Comment by pateketrueke** [comment]
You can use `enum`:

```json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "category": { "enum": ["Gas", "Retail", "Dining"] },
      "expense": { "type": "number", "minimum": 0, "maximum": 100 }
    },
    "required": ["category", "expense"]
  }
}
```

**Comment by TingYinHelen** [comment]
Well, thanks for you answering. It does work.
