### ISSUE TITLE
if Perform too fast  the result  May be  " {}"

### ISSUE THREAD

**Issue by abnerCrack** [json-schema-faker/json-schema-faker#205]
index.js

```
const jsf = require('json-schema-faker');

let schema = {
    type: 'object',
    properties: { dsfds: { type: 'string', faker: 'random.number' } }
}
console.log(jsf(schema))
```

command:
node index
if Perform too fast  the result  May be  " {}"

**Comment by abnerCrack** [comment]
@pateketrueke

**Comment by pateketrueke** [comment]
Yeah, I'm looking into this.

**Comment by abnerCrack** [comment]
it's bug ?

**Comment by pateketrueke** [comment]
Your schema have no required properties, due that your generated object may have not any property.

Fixed schema:
```json
{
  "type": "object",
  "properties": {
    "dsfds": { "type": "string", "faker": "random.number" }
  },
  "required": ["dsfds"]
}
```

**Comment by pateketrueke** [comment]
> Your schema have no required properties, due that your generated object may have not any property.

I was absolutely wrong, even having only optional properties it doesn't mean you'll got none of them!

Sorry for the inconveniences, this issue is now solved on `develop`.

I'm closing this in order to release soon! :beers:

**Comment by abnerCrack** [comment]
@pateketrueke  thanks

**Comment by pateketrueke** [comment]
Note there is no guarantee of faking all optional properties all the time yet, see: #154
