### ISSUE TITLE
Incorrect link on README.MD

### ISSUE THREAD

**Issue by eXigentCoder** [json-schema-faker/json-schema-faker#206]
The link under the heading `Faking values` has a link to faker.js site that results in a 404

> jsf has built-in generators for core-formats, [Faker.js](http://marak.com/faker.js/) and Chance.js are also supported.

Should go through to https://github.com/marak/Faker.js/ instead

**Comment by ducin** [comment]
@eXigentCoder thanks for the submission! In fact, many links to faker.js in the web are broken due to @marak removing http://marak.com/faker.js/
