### ISSUE TITLE
Extra (random?) keys on data

### ISSUE THREAD

**Issue by thejmazz** [json-schema-faker/json-schema-faker#212]
Works [online](http://json-schema-faker.js.org/#gist/a65c0ccf8b7f5f966383c22468b2cbfe), but in Node, I sometimes get extra, seemingly random, keys on `data`, **if not all keys in `properties` are declared in `required` (?)**:

<img width="1000" alt="screen shot 2016-11-09 at 1 41 30 pm" src="https://cloud.githubusercontent.com/assets/1270998/20150236/c73ee850-a682-11e6-9073-dbc66a3422a5.png">

But if `required` explicitly declared:

<img width="1208" alt="screen shot 2016-11-09 at 1 48 41 pm" src="https://cloud.githubusercontent.com/assets/1270998/20150310/418b29d4-a683-11e6-904f-a56f73685c6c.png">

When not all `properties` are required:
![screen shot 2016-11-09 at 1 56 03 pm](https://cloud.githubusercontent.com/assets/1270998/20150519/558630ae-a684-11e6-84f0-67f8ac004d26.png)

**Comment by pateketrueke** [comment]
Sorry for the inconvenience, you're using the same version `json-schema-faker@0.3.7` in node?

To be honest: we have still bugs on this topics, specifically with objects, references and numbers.

We'll put more effort on fixing several internals to guarantee data consistency, personally I want to work on this issue asap.

**Comment by thejmazz** [comment]
Yes using `0.3.7`:

```bash
▶ cat yarn.lock | grep json-schema-faker
json-schema-faker:
  resolved "https://registry.yarnpkg.com/json-schema-faker/-/json-schema-faker-0.3.7.tgz#8f3ac0a6875b98d2c13b5950649d903fecb98e41"
```

Its no big problem, my current fix is fairly simple:

```js
const cleanDataKeys = ({ data, schema }) => {
  Object.keys(data).forEach(key => Object.keys(schema.properties).indexOf(key) === -1
    ? delete data[key]
    : null
  )

  return data
}
```

**Comment by pateketrueke** [comment]
Sorry for the inconveniences, this issue is now solved on `develop`.

I'm closing this in order to release soon! :beers:
