### ISSUE TITLE
Type definitions aren't always properly applied

### ISSUE THREAD

**Issue by jsayol** [json-schema-faker/json-schema-faker#217]
Demo: http://json-schema-faker.js.org/#gist/9b76b9161b8951d0d555755704de5ac4

I've been seeing the `spec/schema/core/references.json` test failing randomly because of this. Sometimes the type definitions are applied properly and sometimes they're not. I've been trying to find the cause of this issue but I'm stumped.

For the provided demo (lifted directly from the test) the generated data is sometimes correct, like so:

```json
{
  "weakNumber": 36980924,
  "multipleOf5": 40
}
```

But sometimes it's not:

```json
{
  "weakNumber": {},
  "multipleOf5": -69586640
}
```

I've noticed that when this happens, all properties depending of type definitions are affected. That is, either they're all correctly applied or none of them are.

P.S.:  The `"multipleOf": 5` type of the `multipleOf5` property always gets correctly applied as it's not a reference to a type definiton.

**Comment by jsayol** [comment]
I think this is also making the `spec/schema/core/issues/allOf.json` test to fail in some cases.

See the demo for it: http://json-schema-faker.js.org/#gist/56195b74c9937624f001f6384c09c9de

This sometimes generates an output like this:

```json
{
  "anArray": [
    {},
    {},
    {}
  ]
}
```

**Comment by jsayol** [comment]
The strangest thing about this all is that sometimes it works, sometimes it doesn't. this is making it really difficult to find the cause :confused:

**Comment by pateketrueke** [comment]
No longer an issue! :D

Our test-suite is now passing (on `develop`), all the time.
