### ISSUE TITLE
online demo improvements

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#22]
@pateketrueke in #14 you wrote:

1. Semantic-UI/UI-Kit
2. CodeMirror for editing JSON
3. Use localStorage for storing schemas/refs
4. A bulk functionality to download all compiled schemas

Can you describe above points more precisely? I think I understand what you mean in point 3.

**Comment by pateketrueke** [comment]
Forget 1 and 2, that are already solved in #19 :beers:

Currently we can't play with `$ref`'s on the UI, but `jsf` already supports them (inline/provided ones).

If we can store those schemas through localStorage jsf can use them for solve that:

- If the edited schema has an "id" then it could be saved and referenced.
- Any schema saved could be edited through the same UI
- We can create a zip-file with all those schemas

Also I think external schemas can be downloaded easily using a standard `<input>` and them can be stored too.

**Comment by tkoomzaaskz** [comment]
I've found [this](https://stuk.github.io/jszip/) for zipping from javascript.

Why is we can't play with external `$ref`s?

THe problem with localStorage is that the data is available only inside a certain browser (e.g. if I have many computers, localStorage is not synced within my computers).

**Comment by pateketrueke** [comment]
> Why is we can't play with external $refs?

This sample won't work:

```json
{
  "id": "foo",
  "type": "array",
  "items": {
    "$ref": "http://json-schema.org/schema"
  }
}
```

But this works perfectly:

```json
{
  "id": "foo",
  "type": "array",
  "items": {
    "$ref": "#/definitions/bar"
  },
  "definitions": {
    "bar": {
      "type": "string"
    }
  }
}
```

That's exactly what I mean, inlined references resolves fine.

Check out this: https://github.com/pateketrueke/json-schema-faker#using-references

> The problem with localStorage is that the data is available only inside a certain browser (e.g. if I have many computers, localStorage is not synced within my computers).

Totally agree but I don't think this feature should be available across browsers, at least not right now.

Certainly we can store that stuff on Dropbox or something like https://stackedit.io does.

By now we can just use localStorage to solve other "local" `$ref`'s:

```json
{
  "id": "foo",
  "type": "array",
  "items": {
    "$ref": "bar"
  }
}
```

What do you think?

**Comment by ducin** [comment]
This might be done with #97, closing.
