### ISSUE TITLE
Required keyword not working as expected

### ISSUE THREAD

**Issue by meucaa** [json-schema-faker/json-schema-faker#227]
I'm having an issue with the `required` keyword which seems to be ignored.

Here is my schema : http://json-schema-faker.js.org/#gist/938f2c4b9edb8646c3201537f230ac12

The `required` keyword applies perfectly on the website but when I'm using it in my node application as shown in the file attached [faker.js.tar.gz](https://github.com/json-schema-faker/json-schema-faker/files/626830/faker.js.tar.gz), it produces output like those : 
```
{ body: { global_params: 6 } }
{ body: { global_params: 77 } }
{ body: { global_params: 6, map_params: [ 15, 67, 97, 94 ] } }
{ body: 
   { global_params: 52,
     map_params: [ 44, 86, 13, 79 ],
     ocl_params: 64 } 
}
```

The only field always there is `global_params`.

Thank you in advance for your time and help !

**Comment by meucaa** [comment]
I solved the problem by not re-using the same reference twice (see below) : 
```json
{
  "type": "object",
  "properties": {
    "body": {
      "type": "object",
      "properties": {
        "global_params": {
          "$ref": "#/definitions/positiveInt"
        },
        "map_params": {
          "$ref": "#/definitions/Polygon"
        },
        "ocl_params": {
          "$ref": "#/definitions/positiveInt2"
        }
      },
      "required": ["global_params","ocl_params","map_params"]
    }
  },
  "required": [
    "body"
  ],
  "definitions": {
    "positiveInt": {
      "type": "integer",
      "minimum": 0,
      "maximum": 100,
      "minimumExclusive": true
    },
    "positiveInt2": {
      "type": "integer",
      "minimum": 0,
      "maximum": 100,
      "minimumExclusive": true
    },
    "positiveInt3": {
      "type": "integer",
      "minimum": 0,
      "maximum": 100,
      "minimumExclusive": true
    },
    "Polygon": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/positiveInt3"
      },
      "minItems": 4,
      "maxItems": 4
    }
  }
};
```
This way, the `required` keyword seems to be well-interpreted.
This problem should be corrected though because it totally make references useless since you cannot re-use them.

**Comment by web-bert** [comment]
I am having the same issue! Will look into creating a PR

**Comment by web-bert** [comment]
I have created a [branch with a test case that re-creates the issue](https://github.com/web-bert/json-schema-faker/tree/issue-227)

This is a [diff of the files](https://github.com/json-schema-faker/json-schema-faker/compare/master...web-bert:issue-227)

I have spent some time trying to see what is happening, but I don't have enough knowledge of the system to try and fix.

I had to re-use the same $ref many times as sometimes it has more of the required properties than others so wanted to try and fail 100% of the time. It [could be to do with this file](https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/core/run.js#L16) as it seems odd to pick a random number here. Seems to make more sense to set that to something reasonably big like 10/20/50 or something?

**Comment by ojj11** [comment]
I had success running the schema through this library first (to resolve all the references):
https://github.com/BigstickCarpet/json-schema-ref-parser

However, I still find my output is missing required fields when an inner-object has no required fields:

```
{
   "type": "object",
   "required": ["p1"]
   "properties": {
      "p1": {
         "type": "object"
      }
   }
}
```

could still return `{}`. However, adding a required field to the p1 definition seem to avoid this problem.

**Comment by pateketrueke** [comment]
Guys, I've been working too on replacing deref/refaker with `json-schema-ref-parser` which is the perfect solution for dereferencing schemas.

My changes are in the `develop` branch if you want to take a look.

> could still return {}. However, adding a required field to the p1 definition seem to avoid this problem.

Yeah, that's the default behavior.

Do you think this would be more flexible?

**Comment by ojj11** [comment]
I took a look through your commit on develop - it looks good, although I thought json-schema-ref-parser used promises, will this library have to adopt promises now too?

As for the empty objects being removed: my understanding from the json schema validation [document](http://json-schema.org/latest/json-schema-validation.html#rfc.section.5.15) was that if a field is listed in required it should have a property in the resultant object, even if it's just an empty object. Though it looks like this was already raised in #232.

This looks like a good change though - let me know if I can help, perhaps by adding a flag not to remove empty objects? 😊

**Comment by pateketrueke** [comment]
> will this library have to adopt promises now too?

Yes.

```js
const jsf = require('json-schema-faker');
const schema = {
  type: 'object',
  required: ['p1'],
  properties: {
    p1: {
      type: 'object'
    }
  }
};
jsf(schema).then((result) => {
  console.log(JSON.stringify(result, null, 2));
}).catch((error) => {
  console.log(error);
});

```

The next version `v0.5.x` will be async by default, this is a major change for good. :tada:

**Comment by pateketrueke** [comment]
Closing this now, the API for `0.5.x` will remain as-is, just added `jsf.resolve()` for dereferencing remote schemas.
