### ISSUE TITLE
oapi gap between spec and the faker

### ISSUE THREAD

**Issue by osher** [json-schema-faker/json-schema-faker#231]
Bug (i think)

### 1. the JSON Schema content that fails
```
{ "type" : "dateTime" }
```

### 2. the result you get
Thrown error
```
Error: unknown primitive "date" in /type
    at run (C:\ws\nodejs\cwt-oapi-util\node_modules\json-schema-faker\lib\core\run.js:58:19)
    at jsf (C:\ws\nodejs\cwt-oapi-util\node_modules\json-schema-faker\lib\index.js:7:12)
```

### 3. the result you expected
As specified here:
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types

**Comment by pateketrueke** [comment]
I'm reading the link you shared and seems like you're confusing the terms.

It's true that "dateTime" is a "common name" but the table is telling you which `type ` an `format` to use on JSON-Schema to produce that value.

```json
{
  "type": "string",
  "format": "date-time"
}
```

**Comment by osher** [comment]
roger. Thanks!
