### ISSUE TITLE
Reserved keywords as part of schema

### ISSUE THREAD

**Issue by omargon** [json-schema-faker/json-schema-faker#234]
Is there a way to declare a schema that includes the keyword `type` as  one of the key values of properties?

While defining a schema based on the following format: 

```
"token": {
    "properties": {
        "type": "card",
        ....
}
```
I get the following error message

```Error: unknown primitive "card" in /properties/token/properties/type```

**Comment by gregglind** [comment]
"card" isn't a known primitive.  Perhaps you mean a "$ref" somewhere?  

See:  https://spacetelescope.github.io/understanding-json-schema/reference/type.html

**Comment by pateketrueke** [comment]
> Is there a way to declare a schema that includes the keyword type as one of the key values of properties?

Yes.

```json
{
  "type": "object",
  "properties": {
    "type": { "type": "string" },
    "value": { "type": ["string", "boolean", "integer"] }
  },
  "required": ["type"]
}
```

Output:

```json
{
  "type": "non quis",
  "value": 41629793
}
```

Remember you MUST declare a valid schema, passing non compliant objects will not work.

**Comment by pateketrueke** [comment]
Closing this by now, seems like no issues here. :)
