### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by naivefun** [json-schema-faker/json-schema-faker#236]
How can I handle errors?
For example the faker generator is not found I wanna return the default value not throwing exception. Is it possible? Thanks.

**Comment by u982744** [comment]
I use try catch to handle errors like this. Seems reasonable to me. What you have described sounds like an exception.

**Comment by pateketrueke** [comment]
The next version `v0.5.x` will handle it, if a generator doesn't exists the exception is not longer thrown: instead it will try to generate a value as usual.

>  I wanna return the default value

That's interesting, do you think there are more scenarios where we can return the `default` value?

**Comment by pateketrueke** [comment]
Related with #269
