### ISSUE TITLE
Not generating data for null type

### ISSUE THREAD

**Issue by u982744** [json-schema-faker/json-schema-faker#238]
Currently the schema faker is not creating null values for generated data.

eg
http://json-schema-faker.js.org/#gist/9d8805b05b10f4da5dc920f5c0b9a092

This should create an object that includes "isOverseas" property every time, but it does not. It seems that type "null" is being interpreted as the property should not be generated at all but that is incorrect.

**Result I get:**
{
  "addressLine1": "aliquip proident "
}

**Result I expected:**
{
  "isOverseas": null,
  "addressLine1": "aliquip proident "
}

**Comment by pateketrueke** [comment]
This is totally a bug, related with #232 

I'll work on this asap, thanks for your feedback!

**Comment by pateketrueke** [comment]
Seems to be fixed now, closing! :beers:
