### ISSUE TITLE
Cannot generate an array of mixed schemas

### ISSUE THREAD

**Issue by megamit** [json-schema-faker/json-schema-faker#239]
http://json-schema-faker.js.org/#gist/74deb7f1a34dfd2662efb18227e18a65

This is a simple example which generates: 
```json
[
  {
    "foo": "false",
    "bar": "false"
  },
  {
    "foo": "false",
    "bar": "false"
  },
  {
    "foo": "false",
    "bar": "false"
  },
  {
    "foo": "false",
    "bar": "false"
  }
]
```
I would like it to be able to generate:
```json
[
  {
    "foo": "true",
    "bar": "true"
  },
  {
    "foo": "false",
    "bar": "false"
  },
  {
    "foo": "true",
    "bar": "true"
  },
  {
    "foo": "false",
    "bar": "false"
  }
]
```

Is this possible?

**Comment by pateketrueke** [comment]
Interesting, I think it should re-evaluate anyOf/oneOf keywords in order to pick a random sub-schema each time it generates an item.

This is not currently implement and certainly could be improved on JSF, thanks for your feedback!

**Comment by ashishkushwaha** [comment]
Patch/Release 0.5.0 seems to be really helpful for several things we are trying to do with this library. Are there any details on the plan date of publishing the same to master?

I tried looking around the repo for a release date but wasn't able to find anything. Posting on this issue as this is the main one we are looking for.

**Comment by pateketrueke** [comment]
I'm planning a `v0.5.0-rc1` before releasing a stable version soon, I don't have any exact date, meanwhile you can try the following:

```
npm install "json-schema-faker/json-schema-faker#develop" --save
```

package.json

```json
{
  "dependencies": {
    "json-schema-faker": "github:json-schema-faker/json-schema-faker#develop"
  }
}
```

Example:

```js
const jsf = require('json-schema-faker');

const schema = {
  "type": "array",
  "items": {
    "anyOf": [
      {
        "properties": {
          "foo": "true",
          "bar": "true"
        },
         "required": ["foo","bar"]
      },
      {
        "properties": {
          "foo": "false",
          "bar": "false"
        },
        "required": ["foo", "bar"]
      }
    ]
  }
};

// note the new API is asysnc
jsf(schema).then(result => {
  console.log(JSON.stringify(result, null, 2));
});
```

That should work without, if you find more issues please report them asap.

Thanks for your feedback!

**Comment by ashishkushwaha** [comment]
Thanks so much. Gonna try this right now.

**Comment by pateketrueke** [comment]
I'm closing this now I know this is working. :beers:

Thanks for your feedback!
