### ISSUE TITLE
Enhancement: Subtler `additionalProperties` when used to describe a Map

### ISSUE THREAD

**Issue by gregglind** [json-schema-faker/json-schema-faker#240]
0.  `json-schema-faker` is amazing.

1.  We sometimes use jsonschema to describe a `Map`, like this:

```
  "definitions": {
    "boolMap": {
      "type": "object",
      "properties": {},
      "additionalProperties": {
          "type": "boolean",
          "minProperties": 0,
          "maxProperties": 100
      }
    }
  }
```

This implies a Key, Value store, where each value is a boolean.  In this case there are between 0, and 100 properties.

## Expected

Some generated data like this:

```
# between 0, and 100 keys, with Boolean t,f with equal probability
{
  "randomKey1":  true,
  "randomKey2": false,
}
```
## Proposed:

- IIF `properties` is EMPTY *and* `additionalProperties` is not bool 
- then use `addiationalProperties.type` if present.
- for faking, call these `key`, `value` by convention.

## Related code

- Builds on #224 
- Some code here: https://github.com/json-schema-faker/json-schema-faker/master/lib/types/object.js#L23

**Comment by gregglind** [comment]
(for now, I am using a `faker` extension)

**Comment by pateketrueke** [comment]
Could you provide more examples on this please?

**Comment by pateketrueke** [comment]
OK, I just did not get what you meant... 😕 

Closing this by now, if you provide more information please re-open.

**Comment by rodoabad** [comment]
Has this been released?

**Comment by pateketrueke** [comment]
Not sure, I think the output that @gregglind was expecting si achievable with this:

```json
{
  "type": "object",
  "properties": {
    "sample": {
      "$ref": "#/definitions/BoolMap"
    }
  },
  "definitions": {
    "BoolMap": {
      "type": "object",
      "minProperties": 10,
      "maxProperties": 100,
      "patternProperties": {
        "\\w+": {
          "type": "boolean"
        }
      }
    }
  }
}
```

@rodoabad can you confirm this is also what you want? 🤔 

Thank you!
