### ISSUE TITLE
maxReduceDepth causes odd behavour when using repeated $ref to same defintion

### ISSUE THREAD

**Issue by gregglind** [json-schema-faker/json-schema-faker#242]
(edited / expanded)

If you're submitting a bug, please clearly state what is:

1. the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ (paste the schema, click `generate` and grab updated browser address bar URL

link: http://json-schema-faker.js.org/#gist/08f0e289e6c4f176c9bbd6d757a46c0b

2. the result you get

(it varies, but between 1,3 keys are filled - always same as `maxReduceDepth`)

3. the result you expected

All 4 keys filled.

## Suspected cause, and evidence

traverse.js`, has a `resolve(schema)`.  The number of keys filled is always the same as the random number for `maxReduceDepth`.  This is set during `run.js`.  

## Proposed solutions

I believe the goal / reason for this code is to prevent circular `$ref` calls.  

1.  **Whatever**: et it crash / memStack during circular refs.  
2.  **Someone Else**: Have another json-schema-validator do the checking.  (`deref` already guards against this).
3.  **Probablistic**: Set a much much higher limit.

The other reason for it seems to be preventing going to far down in to `allOf / oneOf` and friends.  I am not sure what this is supposed to do.  

## Preferred solution:

Rip out that limit.

**Comment by gregglind** [comment]
Removing this breaks:    1) empty properties (core/issues/empty-props.json) should remove empty objects, e.g. [] {}

I am trying to fix that another way.

**Comment by gregglind** [comment]
Claim:  we actually care about ANCESTORS not being called as part of CHILDREN, not just the number of times a node is seen.

**Comment by pateketrueke** [comment]
I've been checking this issue and seems that is fixed now on `develop` which is using `json-schema-ref-parser` instead.

Thanks for your feedback!

**Comment by pateketrueke** [comment]
Yes, this is fixed now on `0.5.x` - closing. :tada:
