### ISSUE TITLE
Cannot generate non-integer number

### ISSUE THREAD

**Issue by richsilv** [json-schema-faker/json-schema-faker#252]
Example: http://json-schema-faker.js.org/#gist/21bf4fa23918338ca1e57c5b267e47fc

Looking at [the code](https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/types/number.js#L19-L22) it seems there is no way to generate a non-integer number since the `random.number` method uses `getRandomInt` under the hood, and the transform in the `multipleOf` clause does not map to non-integers. 

Issue #13 states that this was fixed in 0.1.6, but I think the introduction of `random.number` has reverted that fix.

I will submit a PR with a fix for this, if it's acceptable.

**Comment by pateketrueke** [comment]
I noticed that `0.2.8` doesn't have this issue, it would be a good idea review that code.

I think that adding a few test cases would be enough for fixing that behavior.

**Comment by pateketrueke** [comment]
I think wee need to fix this for `0.5.x` 🤔

**Comment by pateketrueke** [comment]
I just ported back this functionality and worked again, also I added more coverage for know-issues about decimals on javascript...
