### ISSUE TITLE
publish v0.4.1 to npm?

### ISSUE THREAD

**Issue by bdentino** [json-schema-faker/json-schema-faker#256]
It seems impossible to generate non-integer finance amounts with version 0.4.0, but this is fixed in 0.4.1. Unfortunately, 0.4.1 is not available on npm.

Here's an example gist you can see always generates a whole number (e.g. $140.00) with 0.4.0, but allows decimals in 0.4.1 (e.g. $140.40)

http://json-schema-faker.js.org/#gist/3a15a11d706e5b145c30f943d55c42b2

**Comment by pateketrueke** [comment]
Unfortunately our web-version is bundled and therefore stuck with the versions imported at build time.

On nodejs, you could try installing another version of faker itself (the correct one), and then, extend a bare version of `jsf` with it:

```js
var jsf = require('json-schema-faker/lib')
.extend('faker', function() {
  return require('faker');
});
```

**Comment by bdentino** [comment]
Ok thanks for the quick response, I'll try that. I'm still a bit confused though. Are you saying you can't publish the latest release to npm or that it won't resolve the issue?

**Comment by pateketrueke** [comment]
Actually, I wanted to remove those dependencies from `jsf` on the past due this kind of issues... 

At this time I can release a patch just for upgrading the faker's version, but in future releases (`>=v0.5.x` :bomb:) they will be completely optional, not included as required `dependencies`.

The same will happen with all the external generators support, if not, maintaining `jsf` and all its bundles, bower, cdnjs, etc. will be a big pain. 

Sorry if this is an inconvenient for you, please consider to take a look at `develop` branch for testing the next version:

```
npm install "json-schema-faker/json-schema-faker#develop" --save
```

Thanks for your feedback!

**Comment by bdentino** [comment]
Yeah that makes sense, I can definitely see upgrading multiple 3rd-party generator libraries quickly becoming unmanageable. Not a big inconvenience, I just thought this might have been an oversight since the 0.4.1 release is already tagged in github and just never made it to npm. To be clear, I wasn't asking anyone to upgrade the faker version currently in use, just to publish the latest github release of this project to npm. As its now, your latest patch (https://github.com/json-schema-faker/json-schema-faker/commit/528b6879ebf6f8725f08d0a75c6062b65426735c) doesn't seem to be available on npm. Anyways, thanks for the great work!

**Comment by pateketrueke** [comment]
Sorry for that, fixed right now! 🍻

**Comment by bdentino** [comment]
You rock! Thanks again!
