### ISSUE TITLE
0.5.0 rc1 writing empty object

### ISSUE THREAD

**Issue by idkjs** [json-schema-faker/json-schema-faker#260]
If you're submitting a bug, please clearly state what is:

Just an FYI: The following steps can reproduce the error.
1. Download @coryhouse's (https://github.com/coryhouse/javascript-development-environment/)
2. Change the json-schema-faker version to `"json-schema-faker": "0.5.0-rc1"`.
3. Run `npm run generate-mock-data`
4. Output is an empty object: `{}` with no errors reporting. 

Note: I reproduced this in Webstorm and VS Code Insiders.

**Comment by pateketrueke** [comment]
Please consider that the new API from `0.5.x` and beyond is completely async, so you need to change your code.

So, it returns an empty object because is serializing a promise...

```js
jsf(schema).then(function (json) {
  fs.writeFile("./src/api/db.json", JSON.stringify(json), function (err) {
    if (err) {
      return console.log(chalk.red(err));
    } else {
      console.log(chalk.green("Mock data generated."));
    }
  });
});
```

**Comment by idkjs** [comment]
Cool. Maybe throw an error when generated data object is empty? Thinking out loud. 

That worked. Thank you. @coryhouse
