### ISSUE TITLE
Question: How generate default data?

### ISSUE THREAD

**Issue by israelito3000** [json-schema-faker/json-schema-faker#269]
I am in the situation in which I want to generate a simple json without fake data, I mean: empty values or default values if they are present in schema, is that possible with this library?

**Comment by pateketrueke** [comment]
Can you post an example of what you want to get?

**Comment by pateketrueke** [comment]
Hmmm, so, adding an option like `useDefaults` that skip generating values would work? 🤔

**Comment by pateketrueke** [comment]
See #298
