### ISSUE TITLE
External refs not resolving

### ISSUE THREAD

**Issue by shannoncurnew** [json-schema-faker/json-schema-faker#271]
I'm trying to resolve this ref from `parent_schema.json`:

```
let parent_schema = 
...
"foos": {
			"type": "array",
			"uniqueItems": true,
			"items": {
				"$ref": "bar.json#"
			}
		},
...
```
`bar.json` lives at the same level as `parent_schema.json`.

However, I'm getting the following when I do try to fake with `jsf(parent_schema)`:

`Error: missing items for {"type":"array","uniqueItems":true} in /properties/foos`

**Comment by pateketrueke** [comment]
Which version of `json-schema-faker` are you using?

All versions below `0.5.x` are not able to resolve references, please give a try to `0.5.0-rc1`.

**Comment by shannoncurnew** [comment]
I'm using `develop`.

I am unable to use the tag `#v0.5.0-rc1` in `package.json`. After installing, node cannot find the package.

**Comment by pateketrueke** [comment]
`0.5.0-rc1` It is not a git tag, is a NPM release, try: `npm install json-schema-faker@0.5.0-rc1`

**Comment by shannoncurnew** [comment]
That worked!

I was getting 
`└── json-schema-faker@0.5.0-rc1  invalid`
upon npm install, so I think that "invalid" threw me off.

**Comment by shannoncurnew** [comment]
So the problem persists when the schema files are not at the same level as the calling js code.

i.e.
```
  let schema = require('../some_path/bar.json');
  jsf(schema).then((result) = {console.log(JSON.stringify(result)); });
```
results in:
`TypeError: Cannot read property 'definitions' of undefined`

**Comment by pateketrueke** [comment]
Such case won't work because `jsf` does not know from where are you loading the schema, you are using a `require()` call and therefore the filepath is simply hidden for `jsf`.

You must pass a third argument with the directory for resolving files from there (root).

```js
jsf(schema, [], require('path').resolve(__dirname, '../examples'))
.then((result) => {console.log(JSON.stringify(result)); })
.catch((error) => {console.log(error.stack)});
```

Just consider that all schemas should be referenced from the same root relatively.

**Comment by shannoncurnew** [comment]
Thanks for clarifying.
