### ISSUE TITLE
How can I generate the biggest test data possible?

### ISSUE THREAD

**Issue by chrisdew** [json-schema-faker/json-schema-faker#272]
I am using JSON schema where every field has a maximum, maxLength or maxNum.

How can I use json-schema-faker to generate the longest test data allowable by the schema?

**Comment by pateketrueke** [comment]
> How can I use json-schema-faker to generate the longest test data allowable by the schema?

There is no "special way" for doing it, just try it:

```js
// v0.5.0-rc1 (edge)
jsf(yourSchema).then(result => console.log(JSON.stringify(result, null, 2)));

// v0.4.1 (latest)
console.log(JSON.stringify(jsf(yourSchema), null, 2));
```

I mean, there is no way (yet) for telling jsf "hey, take this schema, and use its max constraints for everything" it will just try to understand and randomize a value between min/max boundaries, etc.

Of course "longest" can mean "most properties of an object" or "most possible items within an array" right? In that case, wrapping your objects within arrays and then using `minItems` could do the trick.

Thanks for your feedback!

**Comment by pateketrueke** [comment]
I think we can add an option for, let's say, "taking the max constraint of any given schema" instead of just randomizing within the constraints?

**Comment by pateketrueke** [comment]
I think it's good having constraints, so generating a 1000 words will never freeze our computers, specially when we're talking on lots of references and/or arrays, etc.

For now, you can rely on the `alwaysFakeOptional` settings to enable most of the properties/items to be generated while respecting the constraints.

I'll evaluate if adding an extra option for handling such cases like yours, of course there will be sane limits.
