### ISSUE TITLE
allOf does not work if array item contains oneOf property

### ISSUE THREAD

**Issue by fedorenkosergiy** [json-schema-faker/json-schema-faker#274]
Version: "0.5.0-rc2"

Here gist http://json-schema-faker.js.org/#gist/3c02503f2280588d708a0bfc29914645

schema:
`{
   "$schema":"http://json-schema.org/draft-04/schema#",
   "type":"object",
   "allOf":[
      {
         "type":"object",
         "properties":{
            "a":{
               "type":"string"
            }
         },
         "required":[
            "a"
         ]
      },
      {
         "oneOf":[
            {
               "type":"object",
               "properties":{
                  "b":{
                     "type":"boolean"
                  }
               },
               "required":[
                  "b"
               ]
            }
         ]
      }
   ]
}`

I expected something like this:
`{
  "a":"",
  "b": true
}`

but I've get 
`{
  "b": true
}`

One property missed in result. This property (**a**) have to be generated from one of the references in "allOf" array. And another (**b**) was generated

This works in version "0.4.1". But "0.4.1" does not support external references for **allOf** array

**Comment by pateketrueke** [comment]
Fortunately this is highly related with #278 because some values are being prunned on the same ways, empty arrays, or even empty objects, nulls, empty strings, all are valid.

There are only rule for keeping them on the resulting object: they should be listed as `required`.

I'll be working on this soon, thanks for your feedback! 🎉

**Comment by pateketrueke** [comment]
Update: this schema is quite complex, because it needs to merge two sub-schemas which should be preresolved in order to work.

I'm still thinking on this...

**Comment by pateketrueke** [comment]
Nevermind, it's fixed now.

Releasing on `0.5.0-rc4` soon!
