### ISSUE TITLE
Need help with using API after recent changes

### ISSUE THREAD

**Issue by whitlockjc** [json-schema-faker/json-schema-faker#276]
I use to be able to use something like the following:

```js
'use strict';

var _ = require('lodash');
var Base64 = require('js-base64').Base64;
var stringMocker = require('json-schema-faker/lib/types/string');

/**
 * We have to filter the schema to avoid a maximum call stack issue by deleting the format property.
 *
 * @param {object} schema - The JSON Schema object
 *
 * @returns {object} The filtered schema
 */
function filterSchema (schema) {
  var cSchema = _.cloneDeep(schema);

  delete cSchema.format;

  return cSchema;
}

// Build the list of custom JSON Schema generator formats
module.exports.byte = function (gen, schema) {
  return Base64.encode(stringMocker(filterSchema(schema)));
};

module.exports.password = function (gen, schema) {
  return stringMocker(filterSchema(schema));
};
```

This was really nice whenever you wanted to _extend_ a `type` or add a custom `format`.  With recent changes from JavaScript to TypeScript, you're now building a single `lib/index.js` file and this is no longer possible.  How should one go about doing such things?

**Comment by whitlockjc** [comment]
I realize this is similar to registering your own [custom format](https://github.com/json-schema-faker/json-schema-faker#custom-formats) but it is not identical.  I basically want to be able to call the faker API directly and then do something with it, like base64 encode a faked string.

**Comment by whitlockjc** [comment]
I'm going back through the documentation to see if I can self-help.

**Comment by whitlockjc** [comment]
I'm an idiot.  It seems like `jsf(schema, ...)` is what I want.  _sigh_

**Comment by ducin** [comment]
@whitlockjc I know you're not :)

**Comment by whitlockjc** [comment]
Thanks @ducin.  :)
