### ISSUE TITLE
empty array not generated, even if required

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#278]
[the schema](http://json-schema-faker.js.org/#gist/f0862b1c602d6adffde7ba450cfd87b6/0.4.1), tested on version `0.4.1`. That's the part of the schema:

```
    "alternateEmails": {
      "type": "array",
      "minItems": 0,
      "maxItems": 2,
      "items": {
        "type": "string",
        "faker": "internet.email"
      }
    }
[...]
  "required": [
    ...,
    "alternateEmails"
  ]
```

There is `alternateEmails` field which ***I expect*** to be an array which might be empty or have at most 2 elements. And the array is required.

**What I get**: _sometimes_ (when random number of items fall to 0) the array (`alternateEmails`) is not there _at all_. And it should be. Only, when random number of items is >0, then the array appears. If I wanted not to have the array there, if empty, I'd mark it as optional (not appear in `required`).

**Comment by ducin** [comment]
Exactly the same thing happens, if there's an object (key-value map) instead of an array.

[Schema](http://json-schema-faker.js.org/#gist/1ecd02173e18b3dafda05f550181230f/0.4.1), under version `0.4.1`. Part of the schema:

```
    "phone": {
      "type": "object",
      "properties": {
        "office": {
          "type": "string",
          "faker": "phone.phoneNumber"
        },
        "home": {
          "type": "string",
          "faker": "phone.phoneNumber"
        },
        "mobile": {
          "type": "string",
          "faker": "phone.phoneNumber"
        }
      }
    }
[...]
  "required": [
    ...,
    "phone"
  ]
```

Same thing happens - if 1 or 2 or 3 sub-phones appear, the whole `phone` object appears. If none - then `phone` does not appear at all.

**Comment by ducin** [comment]
@pateketrueke maybe we could deal with that one as a hotfix, releasing `0.4.2`, rather than merging it into `0.5.x` branch?

**Comment by pateketrueke** [comment]
FTR: https://github.com/ScatteredInk/data-standard/commit/c58f1cac573e8aa693558aa04f4b62d1d94b61a8

I think this can be fixed by improving the prune-strategy, if a property is listed as `required` then it should be skipped from prunning.

Ducid, ok, let me figure out how handle this change on `0.4.3` only.

**Comment by andigan** [comment]
For a hack to work around this bug, you can find and replace a flag string after json-schema-faker does its magic:

Add a custom format
```
jsf.format('replaceWithEmptyArr', function() {
  return "replaceMeWithAnEmptyArr";
});
```

Within the schema:
```
keyName: {
  type: "string",
  format: "replaceWithEmptyArr"
}
```

After the schema is processed
`var json = JSON.stringify(jsf(mockDataSchema)).replace(/"replaceMeWithAnEmptyArr"/g, "[]");
`

**Comment by Ceres6** [comment]
I would like to reopen this issue as it is still happening for key-value objects which are required but don't have any required property.
