### ISSUE TITLE
`random.uuid` returns random word instead

### ISSUE THREAD

**Issue by jbesta** [json-schema-faker/json-schema-faker#279]
# Description
I'm using `faker`'s `random.uuid` to generate ids. Until `v0.4.1` everything works fine, however from `v0.5.0-rc1` random word is being generated instead. And from `v0.5.0-rc2` property name is some random word also (instead of desired `id`). Here's gist: http://json-schema-faker.js.org/#gist/4c3d0cf96ebb921635fa6fc418fcc92e/0.4.1

# Details

## JSON schema:
```
{
  "type": "object",
  "required": [
    "id"
  ],
  "properties": {
    "id": {
      "type": "string",
      "faker": "random.uuid"
    }
  }
}
```

### v0.4.1

*this is expected output*

```
{
  "id": "991da2d9-3d3d-4f01-b1ba-7e6c690013df"
}
```

### v0.5.0-rc1
```
{
  "id": "cupidatat irure esse"
}
```

### v0.5.0-rc2
```
{
  "sede4": -87250246.67271018
}
```

**Comment by pateketrueke** [comment]
Related with #275 - please, register the `faker` generator.

Also, the "id" property is being ommited due #273 and it'll be fixed soon.

**Comment by vjwilson** [comment]
I used json-schema-faker on a couple of projects, back in the 0.3.x versions, and it worked great.
However, when I just installed v0.5.0-rc6, I was getting random Lorem Ipsum output for things like name.firstname, and internet.email. Even when I copied over the exact schema file the worked for 0.3.6, the new version gave similar random output.

I've rolled back to the v0.4.2 for now, and that version is working as expected.

Sorry I don't have time to submit a more thorough bug report.

Here's the schema object that wouldn't work with the latest version (v0.5.0-rc6):

```
export const schema = {
  "type": "object",
  "properties": {
    "users": {
      "type": "array",
      "minItems": 7,
      "maxItems": 12,
      "items": {
        "type": "object",
        "properties": {
          "userId": {
            "type": "number",
            "minimum": 1,
            "maximum": 65535
          },
          "firstName": {
            "type": "string",
            "faker": "name.firstName"
          },
          "lastName": {
            "type": "string",
            "faker": "name.lastName"
          },
          "email": {
            "type": "string",
            "faker": "internet.email"
          }
        },
        "required": ["userId", "firstName", "lastName", "email"]
      }
    }
  },
  "required": ["users"]
};
```

**Comment by pateketrueke** [comment]
Yeah, same issue, please register the faker generator before generating samples.

```js
jsf.extend('faker', () => require('faker'));
```

**Comment by YigalNissan** [comment]
thank you :-)

**Comment by Dauli** [comment]
Thanks for the question from @vjwilson  and answer from @pateketrueke, it solved my issue.
