### ISSUE TITLE
Reference (still) not found

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#28]
Going back to #25. I can see, that `deref@0.3.0` solves this issue. The problem is that `deref@0.3.0` isn't included in `json-schema-faker`. Can we publish version `0.1.7` where, according to `develop` branch, the issue is solved? I think it's a minor fix and there's no need to wait for a bigger release. It's a **bug** afterall ;)

**Comment by pateketrueke** [comment]
Totally agree, I feel a bit guilty for that. :cheers:

**Comment by raitucarp** [comment]
why I still have this?

**Comment by pateketrueke** [comment]
@raitucarp please explain your issue, which schema is still suffering this?

**Comment by raitucarp** [comment]
I have generated json schema from jsonix (convert xsd to json schema), when I use this faker, It cannot resolve the reference.

**Comment by pateketrueke** [comment]
Please show your schema example.

**Comment by ducin** [comment]
@raitucarp please update us on this issue. We can make jsf better only if you provide enough details. So what is the output of jsonix that you have generated? If the issue is invalid, that's fine, just let us know :)

**Comment by raitucarp** [comment]
Forgive me for being late to reply this issue, Honestly I convert awsecommerce xsd with jsonix to json schema..

the xsd url is:
http://webservices.amazon.com/AWSECommerceService/2013-08-01/AWSECommerceService.xsd

jsonix command to generate json schema:
```
java -jar node_modules/jsonix-schema-compiler/lib/jsonix-schema-compiler-full.jar
    -generateJsonSchema
    -p AWSECommerceService
   AWSECommerceService.xsd
```

reference:
https://github.com/highsource/jsonix-schema-compiler/wiki/JSON-Schema-Generation

I can't paste the JSON schema here, because it exceed maximum characters, but you can generate it by yourself. 

The JSON schema is valid though. I think it can't resolve the jsonix reference (external ref maybe)?

**Comment by ducin** [comment]
@raitucarp could you save the JSON schema as a JSON gist? See gist.github.com. It will be A LOT easier for us...

**Comment by raitucarp** [comment]
Ok. Thanks for remind me

Here is the gist:
https://gist.github.com/raitucarp/2ac86c96226371bc80d7

**Comment by ducin** [comment]
I confirm, there is something wrong with resolving references. Take a look at my fork: https://gist.github.com/ducin/b55d0247f6f179884bfb and its comment (quick run guide).

I get the following error:
```
c:\Users\tomasz.ducin\Tests\jsf-reference-not-found\node_modules\json-schema-faker\lib\index.js:24
      throw e;
            ^
Error: Reference not found: http://www.jsonix.org/jsonschemas/w3c/2001/XMLSchema.jsonschema#/definitions/string
    at module.exports (c:\Users\tomasz.ducin\Tests\jsf-reference-not-found\node_modules\json-schema-faker\node_modules\deref\lib\util\find-reference.js:38:11)
    at clone (c:\Users\tomasz.ducin\Tests\jsf-reference-not-found\node_modules\json-schema-faker\node_modules\deref\lib\util\resolve-schema.js:15:17)
    at clone (c:\Users\tomasz.ducin\Tests\jsf-reference-not-found\node_modules\json-schema-faker\node_modules\deref\lib\util\resolve-schema.js:34:19)
    at clone (c:\Users\tomasz.ducin\Tests\jsf-reference-not-found\node_modules\json-schema-faker\node_modules\deref\lib\util\resolve-schema.js:34:19)
    at clone (c:\Users\tomasz.ducin\Tests\jsf-reference-not-found\node_modules\json-schema-faker\node_modules\deref\lib\util\resolve-schema.js:34:19)
    at clone (c:\Users\tomasz.ducin\Tests\jsf-reference-not-found\node_modules\json-schema-faker\node_modules\deref\lib\util\resolve-schema.js:34:19)
    at clone (c:\Users\tomasz.ducin\Tests\jsf-reference-not-found\node_modules\json-schema-faker\node_modules\deref\lib\util\resolve-schema.js:23:16)
    at clone (c:\Users\tomasz.ducin\Tests\jsf-reference-not-found\node_modules\json-schema-faker\node_modules\deref\lib\util\resolve-schema.js:34:19)
    at clone (c:\Users\tomasz.ducin\Tests\jsf-reference-not-found\node_modules\json-schema-faker\node_modules\deref\lib\util\resolve-schema.js:34:19)
    at clone (c:\Users\tomasz.ducin\Tests\jsf-reference-not-found\node_modules\json-schema-faker\node_modules\deref\lib\util\resolve-schema.js:34:19)
```

I think I got the same errors when trying to access schemas from outside world. And I checked - http://www.jsonix.org/jsonschemas/w3c/2001/XMLSchema.jsonschema is accessible.

@raitucarp sorry for all those steps, but believe us, it's a lot faster this way :)

**Comment by raitucarp** [comment]
OK @ducin no problem, thanks for confirm it. :+1:

**Comment by pateketrueke** [comment]
According with the [README](https://github.com/pateketrueke/json-schema-faker/blob/master/README.md#using-references):

> Inline references are fully supported (json-pointers) but external can't be resolved by json-schema-faker.

IMO the only concern of `jsf` is faking data, consider using `refaker` for that.

However, I think that integrating `refaker` into `jsf` isn't a big issue and can be solved later.

What do you think?

**Comment by ducin** [comment]
Imho the best solution is to:
[1] keep refaker as a standalone module and maintain it as it is
[2] include it as a *hard dependency** for jsf. Otherwise jsf is losing a killer-feature. And I guess we want to make using jsf easy and user-friendly (all dependent tols already configured).

I'd suggest something, unfortunately, I'm not familiar with `refaker` yet. I checked the docs, but I don't know RAML as well.

**Comment by pateketrueke** [comment]
> but I don't know RAML as well.

Is not necessary to know RAML in order to use `refaker`, that tool was born from some RAML projects I have, but it's main concern is downloading/faking json-schema references.

BTW; I've been testing with that jsonix samples and `refaker` fails due redirections and other unexpected issues, LOL.

**Comment by highsource** [comment]
Jsonix author here. Let me know if you need support from the Jsonix side.

**Comment by ducin** [comment]
Everybody, what is the status of this issue?
@raitucarp is the issue already solved for you? Can we help you further anyhow?

**Comment by pateketrueke** [comment]
@highsource I've updated https://gist.github.com/pateketrueke/152cf7ab2ad61543cd27 to test against the related schemas, some feedback would be appreciated.

**Comment by raitucarp** [comment]
Hi, I come back. Now with node 6, I got this error
```
TypeError: Cannot read property '$ref' of null 
```
What is the status of this issue?

**Comment by raitucarp** [comment]
This is the schema that I generated from jsonix. Rename txt extension to json

[AWSECommerceService.txt](https://github.com/json-schema-faker/json-schema-faker/files/290392/AWSECommerceService.txt)

**Comment by pateketrueke** [comment]
> What is the status of this issue?

@raitucarp:

I've updated the [previous gist](https://gist.github.com/pateketrueke/152cf7ab2ad61543cd27) with the latest JSON you provided.

Locally, using node 6 I don't see the issue you mention anymore.

Did you tried the provided gist for testing?

Just remember that `jsf` will no download any reference, examine the gist for that.

**Comment by skipjack** [comment]
I'm having some issues with this as well. Reading through [this section][1] in the README gave me the impression that the following would work:

``` js
let schema = {
  properties: {
    something: {
      type: 'object',
      $ref: '#/components/schemas/Something'
    }
  }
}

let refs = [
  { id: '#/components/schemas/Something', type: 'string' }
]

SchemaFaker(schema, refs)
```

However this errors out with the following message:

``` bash
Error: JSON pointer not found: http://json-schema.org/schema#/components/schemas/Something
```

BTW thank you for working and maintaining this package! I think it will be very useful for generating mock or example data. Unfortunately this reference thing is a bit of a blocker as our OpenAPI specs use them heavily. Any advice would be much appreciated.

[1]: https://github.com/json-schema-faker/json-schema-faker#using-references

**Comment by pateketrueke** [comment]
The definition for json-schema itself does not allow `id` to be json-pointers, so your schema is clearly invalid.

I mean, you can't pass any value as `id` and then try to match the same value somewhere else, there are constraints defined by the json-pointer specification.

Please read the following examples: http://json-schema.org/example2.html

**Comment by skipjack** [comment]
> The definition for json-schema itself does not allow id to be json-pointers, so your schema is clearly invalid.

Yes I understand that's invalid as per JSON schema however that's how the README states they need to be formatted:

> ``` js
> var refs = [
>   {
>     id: 'otherSchema',
>     type: 'string'
>   }
> ];
> ```

Am I missing something?

**Comment by pateketrueke** [comment]
Yeah, the shape is the same, but the meaning is completely different.

Schema identifiers are absolute, and then json-pointers are meant to be relative to them.

A reference like `#/definitions/foo` is relative to the current schema since its identifier is empty.

If it were `otherSchema#/definitions/bar` then is relative to `otherSchema`, and the referentied schema should be shaped as:

```json
{
  "id": "otherSchema",
  "definitions": {
    "bar": {
      "type": "string"
    }
  }
}
```

Notice that using `#/components` is bit invalid, I think you can use `#/definitions/SomethingComponent` instead.

AFAIK you can access almost any property from any other schema as long you use their `id` and then a json-pointer reference to it. I suggest you placing all nested refs as _definitions_ within their own schema, or even use different schemas with just definitions.

**Comment by skipjack** [comment]
> Notice that using #/components is bit invalid, I think you can use #/definitions/SomethingComponent instead.

Yeah I think that's one of the things OpenAPI changed in the v3 release -- e.g. it's now `#/components/schemas` rather than `#/definitions` although maybe `#/definitions` is what JSON Schema defines.

> AFAIK you can access almost any property from any other schema as long you use their id and then a json-pointer reference to it. I suggest you placing all nested refs as definitions within their own schema, or even use different schemas with just definitions.

Phew, yeah after a few hours of playing around with things I finally have things working somewhat. It seems I had some other issues caused by the `$ref` transformation I'm doing but I think that would all be resolved by the `resolveReferences` option I mentioned in #290. Thanks again for your patience and assistance... I'll keep digging into it and look into those examples you provided.
