### ISSUE TITLE
JSON from Swagger

### ISSUE THREAD

**Issue by kevincam3** [json-schema-faker/json-schema-faker#281]
Does this still work properly with Swagger JSON. I exported JSON from swagger and tried to use the online tool but it didn't seem to work properly so I just wanted to first know if this should still work with Swagger JSON

**Comment by pateketrueke** [comment]
It **should** still work valid JSON-Schema, and probably some keywords for Swagger...

Please share the JSON you're using to test in order to understand more clearly.

If you're expecting some `x-` keywords or anything else, please do ☝️ 

Thanks for your feedback!

**Comment by kevincam3** [comment]
Hi pateketrueke,

I've attached what I copied and pasted here: http://json-schema-faker.js.org

[kevincam3-Tesla-ModelS-API-0.0.1-swagger.zip](https://github.com/json-schema-faker/json-schema-faker/files/1039936/kevincam3-Tesla-ModelS-API-0.0.1-swagger.zip)

**Comment by pateketrueke** [comment]
Thanks,

- your objects has no `required` properties, so they can be generated (or not), randomly
- yeah, `x-` prefixed properties are not working now, I'll fix that soon (release on the next RC - `0.5.0-rc4`)

**Comment by kevincam3** [comment]
pateketrueke,
These are the responses. Swagger doesn't accept the "required" keyword on responses

**Comment by kevincam3** [comment]
pateketrueke,

I found out how to add set response fields as required. Attached is the new JSON file
[kevincam3-Tesla-ModelS-API-0.0.2-swagger.zip](https://github.com/json-schema-faker/json-schema-faker/files/1039995/kevincam3-Tesla-ModelS-API-0.0.2-swagger.zip)

**Comment by pateketrueke** [comment]
Effectively that was part of the main issue.

For the second issue you must register the `faker` support before,
also you're missing to call `"name.method"` for the `faker` keyword, e.g.

```js
const jsf = require('json-schema-faker')

jsf.extend('faker', () => require('faker'));

const schema = {
  "swagger": "2.0",
  "info": {
    "version": "0.0.2",
    "title": "Tesla Model S API",
    "description": "A demo API to access and control the Tesla Model S"
  },
  "paths": {
    "/vehicle": {
      "get": {
        "summary": "Details about owned vehicle",
        "description": "Get the details about the vehicle",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "properties": {
                "color": {
                  "type": "string",
                  "example": "Red",
                  "x-faker": "commerce.color"
                },
                "display_name": {
                  "type": "string",
                  "example": "Kevin's Model S",
                  "x-faker": "name.firstName"
                },
                "vehicle_id": {
                  "type": "number",
                  "example": 1234,
                  "x-faker": "random.number"
                },
                "vin": {
                  "type": "string",
                  "example": "keff2453lk3",
                  "x-faker": "random.number"
                }
              },
              "required": [
                "color",
                "display_name",
                "vehicle_id",
                "vin"
              ]
            }
          }
        }
      }
    }
  },
  "host": "virtserver.swaggerhub.com",
  "basePath": "/kevincam3/Tesla-ModelS-API/0.0.1",
  "schemes": [
    "https"
  ]
};

console.log(JSON.stringify(jsf(schema), null, 2));
```

PS: the previous support for `x-` properties is missing and will be added on `0.5.0-rc4` soon!

**Comment by kevincam3** [comment]
I was copying and pasting the JSON here: http://json-schema-faker.js.org

**Comment by pateketrueke** [comment]
Hi, I was testing your schema locally, and seemed like for `0.4.x` is working as expected.

Example: http://json-schema-faker.js.org/#gist/8ea3aa459241602788c7ea7278b09bba/0.4.2

Now is also working since `0.5.0-rc5` with the `x-` keyword support too.

**Comment by kevincam3** [comment]
Thanks.

What I was trying to do was what this guy did using the site. How he generated a long list of fake data from the Swagger JSON using x-faker. Is this still possible: https://www.youtube.com/watch?v=CcEdjccZgJc&list=WL&index=5&t=1369s
