### ISSUE TITLE
Order of generated JSON name/value pairs

### ISSUE THREAD

**Issue by YannisMarios** [json-schema-faker/json-schema-faker#285]
Hello,

Am I doing something wrong here?

The order of the generated JSON object name/value pairs is not the same as the order declared in the schema:

```
 {
	"title": "Role",
	"type": "object",
	"properties": {
		"id": {
			"type": "string",
			"pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
		},
		"name": {
			"type": "string",
			"maxLength": 48
		},
		"createdAt": { "type": "string", "format": "date-time" }
	},
	"required": ["name", "createdAt"],
	"additionalProperties": false
}

```

Generated object:

```
{
"createdAt":  "1999-07-13T11:22:20.554Z" ,
"id":  "e09be2eA-a47A-de36-121f-F5Dd2eE7bB2d" ,
"name":  "magna"
}
```

**Comment by YannisMarios** [comment]
I would also point out that sometimes the id is generated and sometimes it doesn't. I don't know why this is happening

**Comment by pateketrueke** [comment]
AFAIK, `json-schema-faker` does not take care of objects' properties order... yet (?)

When the object generator is in turn all the props get mixed and randomized (required props are always first), then we take a property from this list each time we want to generate a new one property, etc.

May be difficult to guarantee the original order of the properties due this strategy, just imagine all the possibilities with `allOf` and such.

You're not doing anything wrong as long your schema is valid and the generated object is working or you.

If you expect something more accurate for your needings please let us know. :)

Thanks for your feedback!

**Comment by pateketrueke** [comment]
> I would also point out that sometimes the id is generated and sometimes it doesn't. I don't know why this is happening

For this, you're simply not adding the `id` field as `required` in your schema.

This is because `required` props are always generated and the other are generated randomly.

**Comment by skipjack** [comment]
> AFAIK, `json-schema-faker` does not take care of objects' properties order... yet (?)

Would you be willing to accept a PR for this? It seems the only way to guarantee order now is by using `required`.

> May be difficult to guarantee the original order of the properties due this strategy, just imagine all the possibilities with `allOf` and such.

Yeah I think you're probably right but maybe there's some base level of ordering we could get to that would knock out 90% of use cases.

Side question, is there any chatroom for this package/suite (e.g. gitter) where we can ask questions that might not fit well in issues? I'm finding this utility very helpful and would be willing to contribute but I have some questions and want to avoid cluttering/creating issues.

**Comment by pateketrueke** [comment]
Hi, thanks for your interest on this project!

> Would you be willing to accept a PR for this?

My advice here is just keeping the definition clean, if this can be solved without any other property added to the original schema it will work.

> is there any chatroom for this?

Not yet, but I already created one!

Feel free to discuss anything related there. 🍺
