### ISSUE TITLE
generating multiple results

### ISSUE THREAD

**Issue by jamesdixon** [json-schema-faker/json-schema-faker#288]
Hi, is it possible to generate multiple results? For example:

```jsf.resolve(schema, 10)...```

Would generate 10 results?

THanks!

**Comment by pateketrueke** [comment]
Yeah, it can be useful... why not to wrap the object within an array using `$ref`s?

```json
{
  "type": "array",
  "items": {
    "$ref": "your-schema.json"
  }
}
```

**Comment by prakashgp** [comment]
Also use `minItems` and `maxItems` to get fixed number of items ?

**Comment by pateketrueke** [comment]
Definitely using `array` schemas solves this issue and grants great portability.
