### ISSUE TITLE
Discuss: can jsf support ignore `not found JSON pointer`?

### ISSUE THREAD

**Issue by mansonchor** [json-schema-faker/json-schema-faker#290]
**version:** 0.5.0-rc6
**example:**

```js
var jsf = require('json-schema-faker');

const schema = {
  "definitions": {
    "nameModel": {
      "type": "string"
    },
  },
  "required": [
    "name"
  ],
  "type": "object",
  "properties": {
    "name": {
      "$ref": "#/definitions/xxxx"
    },
    "otherField": {
      type: "string"
    }
  }
};

const ss = jsf(schema);
```

then I will get an error throw

```shell
throw new Error('JSON pointer not found: ' + path);
      ^

Error: JSON pointer not found: http://json-schema.org/schema#/definitions/xxxx
```

actually I prefer jsf will return this result

```js
{
  // drop the name field when pointer not found
  otherField: "abcdef"
}
```

----

**can we ignore the not found pointer??**

because in a big json-schema object, may be just have one not found pointer. But I don't want to effect the hold data generated

in my opinion, that is useful for some scenes such as the `definitions` and `schema` is maintained separately, when I delete the `definitions` will not effect the existing `schema`

**Comment by pateketrueke** [comment]
Yeah, this make sense, I'll be collecting issues about jsf options, so this will be take into account.

Thanks for your feedback! ;-)

**Comment by mansonchor** [comment]
I found the `throw error` code in `deref`

https://github.com/json-schema-faker/deref/blob/master/lib/util/find-reference.js#L14

May be just need to add a `boolean options` in `deref` to control not `throw error`?

**Comment by mansonchor** [comment]
if I have time may be I can contribution a pr 😃

**Comment by pateketrueke** [comment]
Yeah, it can be, but please make sure both `jsf()` and `jsf.resolve()` works the same way.

**Comment by skipjack** [comment]
I'm also running into this and left [a comment](https://github.com/json-schema-faker/json-schema-faker/issues/28#issuecomment-321605411) on #28 with similar example. Maybe instead of an ignore flag, a custom `resolveRef` option could be passed as an option to `jsf`? This would allow a variety of behaviors including ignoring.

**Comment by pateketrueke** [comment]
Yeah, I'm totally agree with you. 👍 

Adding an option for extending built-in resolvers is a good idea.

**Comment by pateketrueke** [comment]
Fixed on develop, releasing soon!
