### ISSUE TITLE
unique integer id

### ISSUE THREAD

**Issue by QuantumHive** [json-schema-faker/json-schema-faker#291]
I'm not sure if this is a bug or that I'm just missing something.

Is it possible to generate a unique integer in `v0.5.0-rc6`?

When I'm using the `"unique": true` with `"type": "integer"` for an object property, I'm not getting unique numbers.

Example schema:

```
{
  "type": "object",
  "properties": {
    "id": {
      "type": "integer",
      "minimum": 1,
      "unique": true
    },
  },
  "required": ["id"]
}
```

**Comment by pateketrueke** [comment]
Uniqueness is difficult to achieve without context, against what it should be unique?

Using a plain object gives no clues about this, but when you use an array the uniqueness makes more sense: a list of unique values.

I see you want to generate a list of objects, which also have unique properties, like the id... I'm right?

Reasoning how smart the schema should be to achieve uniqueness on complex values is not easy, and IMO this will not be solved soon.

So far this is not a bug, or lack of feature, just a good discussion about the main jsf concerns.

Thanks for your feedback!

**Comment by QuantumHive** [comment]
I'm sorry, I've made a mistake in my example. Indeed your assumption is right about that it should be an array of objects, where every object has an id property, and that has to be unique (e.g. mocking a database primary key unique column).

So in my example given above, the context doesn't make any sense. So let me fix that first:

```
{
  "type": "array",
  "minItems": 3,
  "maxItems": 10,
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "number",
        "unique": true,
        "minimum": 1
      },
    "required": ["id"]
  }
}
```

Okay so this feature was never in JSF before? Because [Cory House](https://github.com/coryhouse) has a [schema](https://github.com/coryhouse/javascript-development-environment/blob/master/buildScripts/mockDataSchema.js) (where I've got my example from), that he uses as an example in one of his [Pluralsight courses](https://app.pluralsight.com/player?course=javascript-development-environment&author=cory-house&name=javascript-development-environment-m10&clip=9&mode=live). He uses json-schema-faker **v0.3.6** as his package version in his course. I had the impression that the generated ids where unique, but perhaps that was never there?

**Comment by pateketrueke** [comment]
I think that feature does not exist yet, back to `0.3.6` is still missing: http://json-schema-faker.js.org/#gist/011f74543a03850c957caff46a40a776/0.3.6

I hope enough random numbers are enough to generate "unique" values, but there is no guarantee on this.

It would be helpful if we can guarantee uniqueness not only for simple values... I would like to invest some time on digging this, thanks for your comments.

**Comment by QuantumHive** [comment]
Yes, as a workaround we can just generate numbers between a vast range to minimize the chance on clashing numbers. The bigger the range, the lesser there is a chance on a clash.

So the `unique` property in v`0.3.6` actually had no functionality?

**Comment by pateketrueke** [comment]
The `unique` property did never existed, but `uniqueItems` is able of something similar...

According the spec: https://github.com/json-schema-org/json-schema-spec/blob/master/jsonschema-validation.xml#L421-L433

Since there is no semantics about how validate/generate unique values from objects I guess we can plan something to achieve this.

Any suggestion?

**Comment by pateketrueke** [comment]
Hi, I've been looking into this and I got news:

Now you'll be able to set `autoIncrement` as special keyword, it will take any `minimum` as initial value, then start to increment on each call, e.g.

```json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer",
        "autoIncrement": true
      },
      "key": {
        "type": "integer",
        "minimum": 99,
        "autoIncrement": true
      },
    },
    "required": ["id"]
  }
}
```

It will output something like this:

```json
[
  {
    "id": 1
  },
  {
    "id": 2,
    "key": 99
  },
  {
    "id": 3
  },
  {
    "id": 4,
    "key": 100
  }
]
```

This is available on development, releasing soon!

**Comment by kinduff** [comment]
@pateketrueke Was this finished or developed? Sorry if I missed it.

**Comment by pateketrueke** [comment]
The `autoIncrement` keyword is already shipped on the latest RC16, just use `npm i json-schema-faker@^0.5.0-rc16` to get it right away.
