### ISSUE TITLE
Include definition files

### ISSUE THREAD

**Issue by jvanharn** [json-schema-faker/json-schema-faker#293]
I was happy to see the use of TypeScript in this project, so I can potentially integrate it more easily with my projects. However, there are no definition files provided in the npm package. It should be super easy to include these in your npm package.

This would help me and other TS developers more easily start using the library, and provides static typing to the editors of both people using TS and JS.

**Comment by pateketrueke** [comment]
ping: @ducin

**Comment by pateketrueke** [comment]
Do you think we can use [dts-gen](https://github.com/Microsoft/dts-gen) for this?

**Comment by pateketrueke** [comment]
I hope someone versed on TypeScript help us now that we reverted back to JavaScript, until then, It won't be fixed soon.
