### ISSUE TITLE
Doesn't generate a $ref property containing an anyOf (broke in 0.5.x)

### ISSUE THREAD

**Issue by n3ps** [json-schema-faker/json-schema-faker#297]
1. JSON schema faker gist:
http://json-schema-faker.js.org/#gist/0f2ab394378e7d3fff0198c7c9c58f03/0.5.0-rc7

```
{
  "definitions": {
    "shared": {
      "type": "object",
      "properties": {"name": {"type": "string"}},
      "anyOf": [
        {"required": ["name"]}
      ]
    }
  },
  "type": "object",
  "properties": {
    "shared": {"$ref": "#/definitions/shared"},
    "name": {"type": "string"}
  }
}
```

2. Result:
After repeated attempts, only generates the "name" property

3. Expected:
Generates both "name" and "shared" properties

Confirmed working in 0.4.2

**Comment by pateketrueke** [comment]
Sorry for broke everything, I've fixed that behavior and released a RC8, so much thanks for your feedback!

**Comment by n3ps** [comment]
Thank you for the quick turnaround!
