### ISSUE TITLE
Generate Relational Data

### ISSUE THREAD

**Issue by stelioschar** [json-schema-faker/json-schema-faker#299]
First of all I would like to say a big thank you for all the work you have done.

What I would like to ask is that if there is a way to have relationship between two collections of data.

Let's assume that we have a collection of `environments` and `reports` which are connected with `environmentId`.
```json
{
  "environments": [
    { "id": 12 },
    { "id": 19 }
  ],
  "reports": [
    { "id": 17, "environmentId": 12 },
    { "id": 25, "environmentId": 12 },
    { "id": 26, "environmentId": 19 }
  ]
}
```

When I hit ` /environments/19/report` I should get a list that only contains the report with id *26*.

I'm using the json-schema-faker through the `json-server` tool which parses successfully the structure above but I can't figure out who I can achieve to have `foreign` keys that are based in the generated `primary` keys, once `json-schema-faker` does not allow me to declare relations.

*Another relative question is [here](https://stackoverflow.com/questions/41880382/describing-relationships-in-json-schema-so-that-paw-can-generate-payload)*

Is there any way to define a relationship between two collections?

**Comment by pateketrueke** [comment]
Hi, I'm sorry for saying this but currently JSF does not support any kind of relationhips. :(

This is a requested feature which we want to provide asap, thanks for your feedback!

**Comment by pateketrueke** [comment]
Hello again!

Now, this kind of basic relationships are supported:

```js
jsf.option({
  resolveJsonPath: true,
  alwaysFakeOptionals: true,
});

const schema = {
  properties: {
    environments: {
      type: 'array',
      items: {
        properties: {
          id: {
            type: 'integer',
            minimum: 1,
          },
        },
      },
    },
    reports: {
      type: 'array',
      items: {
        properties: {
          id: {
            type: 'integer',
            minimum: 1,
          },
          environmentId: {
            type: 'integer',
            jsonPath: '$..environments[*].id'
          },
        },
      },
    },
  },
};

console.log(JSON.stringify(jsf(schema), null, 2));
```

It will output something like this:

```json
{
  "environments": [
    {
      "id": 51187719
    },
    {
      "id": 37995379
    }
  ],
  "reports": [
    {
      "id": 94277898,
      "environmentId": 37995379
    },
    {
      "id": 50332150,
      "environmentId": 51187719
    }
  ]
}
```

The only new stuff you need to learn is `json-path` which IMO is cool!

I'm closing this since is related with #11 :tada:

**Comment by ktersius** [comment]
Is this still working? I copied this exact sample and the data generated does not reference correct ids but rather generate random ones.

**Comment by pateketrueke** [comment]
Effectively the example is wrong, and it not longer works.

I'll be fixing this asap, so much thanks!
