### ISSUE TITLE
why does JSF add properties that are not defined in the schema?

### ISSUE THREAD

**Issue by donalmurtagh** [json-schema-faker/json-schema-faker#303]
I've created a [Plunker demo](https://plnkr.co/edit/Ml3c42TqznHDPPY6CDuf?p=preview) that uses the latest release (0.5.0-rc10) to generate a dataset that conforms to a schema. Simply click the "Generate Data" button and the data is shown.

The schema used by the demo is defined in `app.js` and all the properties are named `X_Y` or `X-Y` where X and Y are both numbers.

However, when JSF generates the data, it usually (but not always) adds a couple of properties to the JSON document with Lorem Ipsum style names, which are _not_ defined in the schema. Here is an example of the data generated

```
{
  "4_1": "no",
  "4_3": "No",
  "4_6": "No - you may be able to get Statutory Sick Pay instread of Employment and Support Allowance. Ask your employer about Statutory Sick Pay before you fill in this form.",
  "5_1": "ea minim",
  "5_2": "No- Fill in the answer box under You on pages 2 to 24. Then go to page 45.",
  "5_4": "No, please go to Part 2",
  "6_1": "Duis",
  "6_4": "occaecat",
  "6_6": "magna est",
  "6_7": "TR487333A",
  "6_8": "dolore incididu",
  "6_15": "id nulla par",
  "6_16": "velit cupidatat",
  "6_19": "adipisicing velit",
  "6_21": "dolore laborum anim",
  "6_22": "AZ945012D",
  "6_25": -93995172.83783534,
  "6_30": "ut tempor incididunt eu",
  "7_11": "yes",
  "mollitfd": false,
  "ina": -58665520.27369134
}
```

In the example above, the properties `mollitfd` and `ina` are not defined in the schema. Why are these properties being added? Is there a way to configure JSF to only generate properties which _are_ defined in the schema?

It seems that adding `additionalProperties: {}` to the schema resolves this problem, however according to the [JSON schema spec](https://tools.ietf.org/html/draft-fge-json-schema-validation-00#page-13) this should not be necessary because:

> If "additionalProperties" is absent, it may be considered present with an empty schema as a value.

**Comment by pateketrueke** [comment]
Thanks for pointing this out, definitely these properties are not expected.

I'll add this issue to the current milestone, so I think we can work on this asap. 👍

**Comment by fireproofsocks** [comment]
According to the JSON Schema spec, if you omit `additionalProperties`, it assumes a default value of an empty schema: `{}`, which DOES allow for any additional properties.  So it's valid for unexpected properties/values to be added: the response will still be valid against the schema (try validating a result against your schema -- you will see many warnings because of your custom keywords like "validationMessage", but the extra properties are valid.  Try an online validator like https://json-schema-validator.herokuapp.com/

E.g. this value:
```
{"x": "no", "y": "Surprise!"}
```
Is valid against this schema:
```
{
    "type": "object",
    "properties": {
      "x": {
        "type": "string",
        "enum": ["no","yes"]
      }
   }
}
```
but it is NOT valid against this schema:
```
{
    "type": "object",
    "properties": {
      "x": {
        "type": "string",
        "enum": ["no","yes"]
      }
   },
   "additionalProperties": false
}
```

**Comment by pateketrueke** [comment]
Fixed under development, added some options for handling this cases.
