### ISSUE TITLE
【0.5.0-rc10】allOf generate bug still exists

### ISSUE THREAD

**Issue by mansonchor** [json-schema-faker/json-schema-faker#304]
Relate to this old issue: https://github.com/json-schema-faker/json-schema-faker/issues/292

that case is fixed, but I got another bug case~~!!!

----

gist: http://json-schema-faker.js.org/#gist/eaf58438cbfb57e98d42b8d0eeafc509/0.5.0-rc10
version: **0.5.0-rc10**

```js
{
    "type": "object",
    "allOf": [
        {
            "type": "object",
            "properties": {
                "a": {
                    "type": "string"
                },
                "b": {
                    "type": "integer"
                }
            },
            "required": [
                "a",
                "b"
            ]
        },
        {
            "type": "object",
            "properties": {
                "b": {
                    "type": "integer"
                },
                "c": {
                    "type": "boolean"
                }
            },
            "required": [
                "b",
                "c"
            ]
        }
    ]
}
```

expect

```js
{
  "a": "eu",
  "b": -50654735,
  "c": false,
}
```

but get a extra wrong field key
```js
{
  "a": "qui",
  "b": -58444817,
  "c": false,
  "officia1": "et"
}
```

**Comment by pateketrueke** [comment]
Sorry for the lag, I'll work on this asap.

Thanks for catching this bugs! 🍺

**Comment by mansonchor** [comment]
When can this issue fix?

**Comment by pateketrueke** [comment]
Hi,

Do you know if this is related with #303 ?

Notes:
- I just tested your schema with `additionalProperties` as `false` and now we have more bugs!
- I think we might to solve all object-generator support, so it will take more time.

**Comment by pateketrueke** [comment]
Fixed and under development, releasing patch soon!
