### ISSUE TITLE
Static fields set to 0 cause random output

### ISSUE THREAD

**Issue by mozrila** [json-schema-faker/json-schema-faker#309]
This is a case where it fails.  The ID should be statically set to 0.
http://json-schema-faker.js.org/#gist/8cd65febfd5436c173459eee3c019062/0.4.3

If you set it to any other value this works.
http://json-schema-faker.js.org/#gist/4c522bffec50b6b1b8a48086accf7f31/0.4.3

This persists in all the new release candidates and has existed since the support of static fields.

**Comment by pateketrueke** [comment]
Hi, thanks for pointing this out:

Actually those static fields are not valid JSON-Schema, so I think they simply won't work that way.

In such case, the value of `id` should be an object, it can't be a number, string, or anything else.

Test that schema on this site (against draft-v4): http://www.jsonschemavalidator.net/

The validation error I got: `Invalid type. Expected Object but got Integer.`

So, if you pass an invalid schema to `jsf`, it shall yield weird results.

> since the support of static fields.

I don't see "static fields" as a feature due the described issue above, of course seems to be useful on a first sight but on the end is not a valid schema.

I hope you get my point, but also if you think "static fields" _can_ be a feature please describe it, and try to make use of valid schema definitions.

Again, so much thanks for your feedback!

**Comment by sebashwa** [comment]
Hello 👋 ,

thanks for this awesome library!
I have a similar issue and I'd like to support a constant value in my schema.
According to the JSON-Schema specification, this should be valid and force `constantValue` to be `'SOME_CONSTANT'`

```
{
  "type": "object",
  "properties": {
      "constantValue": { "type": "string", "const": "SOME_CONSTANT" }
  },
  "required": ["constantValue"]
}
```
Unfortunately the const validation seems to be ignored 🙀 
Is there a way dealing with this? Can I contribute somehow to fix the issue?

**Comment by pateketrueke** [comment]
I think this can be solved as follows:

```js
jsf.define('const', (value, schema) => {
  // you have access to the whole schema too:
  console.log(schema.const === value);

  return value;
});

console.log(jsf({
  type: 'string',
  const: 'the_truth',
}));
```

This is an undocumented feature (done but not perfect) for the next minor release and is not backported yet to `0.4.x`, sorry for this inconvenience.

If you want to try please use the latest RC `0.5.0-rc10` instead. 

> Can I contribute somehow to fix the issue?

Sure!

If you think this feature can be ported back to `0.4.x` we're open to PRs.

**Comment by mozrila** [comment]
That is actually a very awesome feature.  Do you know if there is a way to make auto-incrementing IDs each time that JSF is called?

**Comment by pateketrueke** [comment]
Well, the auto-incrementing thing can be done using a custom generator like the above, or using a custom format, e.g `{ "format": "auto-increment" }` but that would lead to invalid schemas since `format` is just for strings.

So, you can do this:

```js
let count = 0;

jsf.define('autoIncrement', () => {
  return ++count;
});

console.log(jsf({
  type: 'array',
  items: {
    type: 'object',
    properties: {
      id: {
        type: 'number',
        autoIncrement: true,
      },
    },
    required: ['id'],
  },
  minItems: 10,
}));
```

I hope this help you.

**Comment by mozrila** [comment]
Could this be extended for something like this?


`
{
  "type": "object",
  "properties": {
    "Type": {
      "type": "string",
      "chance": {
        "weighted": [
          ["AILTN"],
          [1]
        ]
      }
    },
    "UserID": {
      "type": "integer",
      "id": [
        0,
        10000,
        4
            ]
    },
    "OrgId": {
      "type": "integer",
      "id": [
        1,
        1000,
        3
            ]
    }
  },
  "required": [
    "Type",
    "UserID",
    "OrgId"
  ]
}

`

Where in the array, you define a minimum, a maximum, and an increment?
Your previous solution wouldn't really work for multiple IDs

Thanks!

**Comment by pateketrueke** [comment]
Yeah, it could, but your schema will not be longer valid.

You need to put more logic for handling multiple IDs, but yeah, it would work.

**Comment by mozrila** [comment]
@pateketrueke 

I have a working version here: 

```javascript

**Comment by pateketrueke** [comment]
I think using `JSON.stringify(schema)` could work as key but is horrible... so we need to find out a way we can get references from the contaning schema, so much related with #63 and #11

Can you take a look?
