### ISSUE TITLE
extend CONTRIBUTING.md with how the project is tested

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#31]
The [CONTRIBUTING.md](CONTRIBUTING.md) has very little content. Need to extend it.

A small guide of how the tests are organised, how to run them and add new ones would be welcome.

**Comment by pateketrueke** [comment]
OK, I'll work on this asap. :beers:

**Comment by tkoomzaaskz** [comment]
Need to add that a developer needs a coveralls.io account synced with github. I didn't know that and it took me some time until I figured out what does the 422 error mean...

**Comment by tkoomzaaskz** [comment]
One more think needs there. Publishing new version on npm needs re-browserifying gh-pages

**Comment by tkoomzaaskz** [comment]
I'll add info about upgrading jsf in the demo (`gh-pages` branch) to CONTRIBUTING.md. And re-release it up to `0.1.10`.

**Comment by tkoomzaaskz** [comment]
`0.1.10` demo re-released.

**Comment by tkoomzaaskz** [comment]
added demo-re-release info to CONTRIBUTING.md. By the way, would you try to re-release the demo page next time you release jsf? It is simply three steps:
* update package.json version of jsf
* npm install
* `grunt`

**Comment by ducin** [comment]
Thanks to [grunt-npm-install](https://github.com/iclanzan/grunt-npm-install), there's one step less to update the demo page:
* update jsf version manually in `package.json` file
* `grunt`

**Comment by pateketrueke** [comment]
I've never heard about `grunt-npm-install` but sounds great! :beers:

**Comment by ducin** [comment]
coveralls.io needed for a push-commit-developer mentioned in 4d7390b82eac8196b5aafa51621da2467c9a12e8.
@pateketrueke: would appreciate few sentences of test architecture description :)

**Comment by pateketrueke** [comment]
Seems to be solved in `develop` branch.
