### ISSUE TITLE
Generation of an object with field 'id' of type number generates object with random property

### ISSUE THREAD

**Issue by lhugsereg** [json-schema-faker/json-schema-faker#311]
Bug report

1. Schema content/test code:
jsf.resolve({
	"type": "object",
	"required": [ "id" ],
	"properties": {
		"id": {
			"type": "number"
		}}})
.then(data => console.log(data));

2. Expected output:
{ id: 2345.456 }

3. Actual output:
{ nisi25: -51587709.703035526 }

4. System info
json-schema-faker 0.5.0-rc3
glob 7.1.2
json-stable-stringify 1.0.1
typescript 2.4.2
yargs 8.0.2

Thanks for your software, it's super useful!

**Comment by pateketrueke** [comment]
Thanks for your feedback!

Unfortunately the `0.5.0-rc3` version is totally broken, please use the latest `0.5.0-rc10` instead.

**Comment by lhugsereg** [comment]
Thanks, works. I didn't check the github releases which I should have. Enjoy your weekend!
