### ISSUE TITLE
Clarifications to the CONTRIBUTING

### ISSUE THREAD

**Issue by fireproofsocks** [json-schema-faker/json-schema-faker#312]
I'm looking at contributing to the project, but I'm confused by the CONTRIBUTING.md file... 

Could you clarify what you mean by "* When submitting *PRs*, ship them under the `develop` branch."  Do you mean we should request to merge with the `develop` branch?

What is the branching strategy?  Could you elaborate on a the forking process that you want to see?

When you say "If you're submitting a bug, please clearly state what is:" -- do you mean "If you're submitting a bug fix, please clearly include the following:" ?

Are some of these questions better addressed in Gitter or somewhere else?  

Sorry to clutter up the issue tracker.

**Comment by pateketrueke** [comment]
> Do you mean we should request to merge with the develop branch?

Yes please, the `master` branch is our edge release. All new features are integrated first on the `develop` branch. Also, we have a `0.4.x` branch for the latest release (stable).

We are working now on the next minor release (unstable), currently on `0.5.0-rc10` which is under the `develop` branch.

> What is the branching strategy? Could you elaborate on a the forking process that you want to see?

Actually nothing special is needed here, just fork and checkout from the develop branch each time you want to change something.

> do you mean "If you're submitting a bug fix, please clearly include the following:" ?

Definitely, sorry for the bad english. We aren't native english-speakers so we try our best.

Of course, PRs on documentation and typos are also welcome.

> Are some of these questions better addressed in Gitter or somewhere else?

No, we don't use any space like that yet... but if you think it can be useful go ahead, and we'll join there!

> Sorry to clutter up the issue tracker.

Also I think addressing questions on another place, or even building a FAQ would be better than opening issues for simple questions.

Do you have something in mind?

**Comment by fireproofsocks** [comment]
Thanks for the response!  I submitted a PR: https://github.com/json-schema-faker/json-schema-faker/pull/313  -- please let me know if it is appropriate.

I am interested in working on issue #310 but I have some questions about where to work on the code (sorry, I am new to Node.js -- I wrote a similar PHP package before I found yours: https://packagist.org/packages/jenerator/jenerator)

**Comment by pateketrueke** [comment]
Ok, let's move to #310 instead. 👍
