### ISSUE TITLE
Pointer inside chance/faker

### ISSUE THREAD

**Issue by RyanMulready** [json-schema-faker/json-schema-faker#327]
http://json-schema-faker.js.org/#gist/675dccf7e9468854e65eebc438324a17/0.4.3

Got: 

`{
  "user": {
    "id": {
      "type": "array",
      "items": {
        "enum": [
          "red",
          "green",
          "blue",
          "yellow"
        ]
      }
    },
    "idList": [
      "yellow",
      "red"
    ]
  }
}`

Expect:
`{
  "user": {
    "id": "red",
    "idList": [
      "yellow",
      "red"
    ]
  }
}`

Is this possible?

**Comment by RyanMulready** [comment]
I figured as much, though I disagree that it is odd.  The use case is simple, I have an array of objects that is shown in a list.  Those object contain a property that is a color.  The user can edit each item in the array and change the color.  The colors are predefined so they are used twice in my schema.  They are used once in the array of objects then again as metadata for a select list so the user can change the color.

**Comment by RyanMulready** [comment]
For those wondering I was able to successfully accomplish this by defining my static items in a separate file then importing them.  Reference the import in chance/fs and then both resolved correctly.

**Comment by pateketrueke** [comment]
Hi, I'm glad you got something working. 👍 

Would you like to share your finished schema just to understand clearly?

I was playing around and I ended up with this:

```json
{
  "type": "object",
  "properties": {
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/idColor"
        },
        "idList": {
          "type": "array",
          "items": {
            "anyOf": [
              {"$ref": "#/definitions/idColor"}
            ]
          }
        }
      },
      "required": [
        "id", "idList"
      ]
    }
  },
  "required": [
    "user"
  ],
  "definitions": {
    "idList": {
      "type": "array",
      "items": { "$ref": "#/definitions/idColor" }
    },
    "idColor": {
      "type": "string",
      "enum": [
        "red",
        "green",
        "blue",
        "yellow"
      ]
    }
  }
}
```

Source: http://json-schema-faker.js.org/#gist/fc46cc7d461beede28e02d3dd4547d01/0.5.0-rc10
