### ISSUE TITLE
Support for JSON Schema v6

### ISSUE THREAD

**Issue by anweiss** [json-schema-faker/json-schema-faker#328]
Any updates in the works to support v6 of JSON Schema?

**Comment by pateketrueke** [comment]
Hi, unfortunately that's currently not supported and there are no plans for supporting it soon.

TBH I don't know exactly the differences, but once v5 is landed we'll consider adding more support.

Thanks for your feedback!

**Comment by anweiss** [comment]
Thanks @pateketrueke ... heads up, v5 is non-existent per -> http://json-schema.org/draft-06/json-schema-migration-faq.html#q-what-happened-to-draft-05.

draft-06 is the current schema -> http://json-schema.org/documentation.html

**Comment by pateketrueke** [comment]
Sorry, I was talking about the v5 of this library, which aims to support draft-04 of json-schema. 🤒

**Comment by pateketrueke** [comment]
Closing, see #289
