### ISSUE TITLE
Required, nested arrays are omitted when their items schema is empty

### ISSUE THREAD

**Issue by tsiq-rob** [json-schema-faker/json-schema-faker#331]
Minimal example: http://json-schema-faker.js.org/#gist/5d935c722305334c44f6ecd047d04701/0.5.0-rc10

Expected: `a` is included e.g. as an empty array.

Actual: `a` is absent

This is a regression, it worked as expected in rc3 and fails since rc4.

**Comment by pateketrueke** [comment]
Totally a regression, so much thanks for your feedback!

**Comment by pateketrueke** [comment]
Fixed now under development, thanks for your feedback!
