### ISSUE TITLE
tslib not included as a dependency in package.json in 0.4.5

### ISSUE THREAD

**Issue by Burr** [json-schema-faker/json-schema-faker#334]
With the [0.4.5 version of index.js](https://github.com/json-schema-faker/json-schema-faker/blob/5e9fcc1cd6340f9d422646c41685494c585cd76c/lib/index.js#L4), `tslib` is required. However, in the [package.json](https://github.com/json-schema-faker/json-schema-faker/blob/0.4.x/package.json#L83) of that version, it's only listed in `devDependencies`. As a result, any library that depends on this library (e.g. https://github.com/apiaryio/fury-adapter-swagger) but does not include a reference to `tslib` will fail.

**Comment by pateketrueke** [comment]
Oh, sorry for that. I've released `v0.4.6` for solving this.

**Comment by Burr** [comment]
Great, that's fixed our issue, many thanks!
