### ISSUE TITLE
oneOf is not working as expected.

### ISSUE THREAD

**Issue by abys890** [json-schema-faker/json-schema-faker#336]
oneOf produce undesirable output with version 0.5.0-rc11.

Here is the JSON Schema content.

{
  "title": "timesync",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "sntp": {
      "type": "boolean"
    },
    "timep": {
      "type": "boolean"
    },
    "timep-or-sntp": {
      "type": "boolean"
    },
    "ntp": {
      "type": "boolean"
    }
  },
  "oneOf": [
    {
      "required": [
        "sntp"
      ]
    },
    {
      "required": [
        "timep"
      ]
    },
    {
      "required": [
        "timep-or-sntp"
      ]
    },
    {
      "required": [
        "ntp"
      ]
    }
  ],
  "additionalProperties": false
}

Here is the sample generated using web tool of JSON schema faker.

{
  "timep-or-sntp": false,
  "sntp": false,
  "timep": true
}
JSON schema validator is throwing error for  this input.
Expected 
{
	"timep": true
}

Since all the properties are marked under oneOf,  only one property is expected when generating input.

Any help figuring out why it is failing would be greatly appreciated.

Thanks!

**Comment by pateketrueke** [comment]
Oh, I got it. It seems logic, just one-of all properties is required, not all.

I'll work on this asap, thanks for your feedback!

**Comment by abys890** [comment]
Thank you so much..  Please let me know when will be v0.5.0..

**Comment by pateketrueke** [comment]
Fixed under development, releasing patch soon!

**Comment by abys890** [comment]
thank you so much .. I will test against and update the  results.

**Comment by abys890** [comment]
After pulling the latest changes also am seeing the issue.  Any help is appreciated.

**Comment by pateketrueke** [comment]
> After pulling the latest changes also am seeing the issue. Any help is appreciated.

Sorry, I forget to commit the built library, I just published it right now!

If you prefer, you can install it directly from github: `npm install json-schema-faker/json-schema-faker#develop`

Example:

```js
const jsf = require('json-schema-faker');

const schema = {
  "title": "timesync",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "sntp": {
      "type": "boolean"
    },
    "timep": {
      "type": "boolean"
    },
    "timep-or-sntp": {
      "type": "boolean"
    },
    "ntp": {
      "type": "boolean"
    }
  },
  "oneOf": [
    {
      "required": [
        "sntp"
      ]
    },
    {
      "required": [
        "timep"
      ]
    },
    {
      "required": [
        "timep-or-sntp"
      ]
    },
    {
      "required": [
        "ntp"
      ]
    }
  ],
  "additionalProperties": false
};

console.log(jsf(schema));
```

**Comment by abys890** [comment]
Thanks for the update... 
The fix looks reverse of what is expected. oneOf means in an array only one should pick.. Now what i get is "allOf", all the four values are placed in the request. Below is one sample generated.
1.
{
    "ntp": true,
    "sntp": true,
    "timep-or-sntp": true,
    "timep": true
}


2.
{
    "ntp": true,
    "sntp": false,
    "timep": false,
    "timep-or-sntp": false
}


3.
{
    "timep-or-sntp": true,
    "ntp": false,
    "timep": false,
    "sntp": false
}


4.
{
    "timep-or-sntp": true,
    "sntp": true,
    "ntp": true,
    "timep": false
}


5.
{
    "ntp": true,
    "timep-or-sntp": true,
    "timep": false,
    "sntp": true
}

6.
{
    "ntp": false,
    "timep": true,
    "sntp": true,
    "timep-or-sntp": true
}

7.
{
    "timep": false,
    "timep-or-sntp": false,
    "ntp": true,
    "sntp": false
}


8.
{
    "sntp": true,
    "timep": false,
    "timep-or-sntp": false,
    "ntp": true
}

9.
{
    "timep-or-sntp": true,
    "timep": true,
    "ntp": true,
    "sntp": true
}

**Comment by NABEEL-AHMED-JAMIL** [comment]
Hi, I'm facing this problem
<h3>Error</h3>

```
com.github.fge.jsonschema.core.report.ListProcessingReport: failure
--- BEGIN MESSAGES ---
error: instance matched a schema which it should not have
    level: "error"
    schema: {"loadingURI":"#","pointer":""}
    instance: {"pointer":""}
    domain: "validation"
    keyword: "not"
---  END MESSAGES  ---
```

<h3>Schema</h3>
 
```
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "event fire request v1",
  "description": "json-schema for event fire request v1",
  "type": "object",
  "required": ["userId", "phone", "userName"],
  "not": {
    "allOf": [{
      "required": ["role"]
    }, {
      "required": ["video"]
    }]
  },
  "additionalProperties": false,
  "properties": {
    "userId": {
      "description": "userId required have null",
      "type": "string"
    },
    "phone": {
      "description": "phone required have null",
      "type": "string"
    },
    "userName": {
      "description": "userName required have null",
      "type": "string"
    },
    "role": {
      "type": "object",
      "required": ["roleId", "name"],
      "additionalProperties": false,
      "properties": {
        "roleId": {
          "description": "roleId required have null",
          "type": "string"
        },
        "name": {
          "description": "name required have null",
          "type": "string"
        }
      }    },
    "video": {
      "type": "object",
      "required": ["videoId", "h", "w"],
      "properties": {
        "videoId": {
          "description": "videoId required have null",
          "type": "string"
        },
        "h": {
          "description": "h required have null",
          "type": "string"
        },
        "w": {
          "description": "w required have null",
          "type": "string"
        }
      }
    }
  }
}
```
<h3>Input</h3>

```
{
    "userId": "1d3e",
    "userName": "Nabeel.amd93@gmail.com",
    "phone": "03153817177",
    "role": {
    	 "roleId": "d423",
          "name": "nabeel ahmed"
    },
    "video": {
    	"videoId": "123456d",
    	"h": "25",
    	"w": "25"

    }
}
```

**Comment by pateketrueke** [comment]
Hi @NABEEL-AHMED-JAMIL, could you please open another issue for this?

I mean, it's more related with `not` than `oneOf/allOf`, so it deserves its own space for reviewing.

> tl-dr; the support for `not` schemas is partially supported, so it's not complete yet. It _can_ be improved over time so we need time for more analysis.

**Comment by NABEEL-AHMED-JAMIL** [comment]
Sure and Thank's @pateketrueke
