### ISSUE TITLE
 Error: missing properties if additionalProperties is false and required is empty

### ISSUE THREAD

**Issue by epaillous** [json-schema-faker/json-schema-faker#338]
Hello, 

I am getting an error when trying to validate this json schema : 
```
{
  "title": "Resource 217 - default_representation",
  "type": "object",
  "properties": {},
  "required": [],
  "additionalProperties": false,
  "id": "http://json-schema.org/schema#"
}
```

The error is : 

```
Error: missing properties for:
{
  "title": "Resource 217 - default_representation",
  "type": "object",
  "properties": {},
  "required": [],
  "additionalProperties": false,
  "id": "http://json-schema.org/schema#"
}
```

I am expecting to generate a simple empty json : {} 

Thank you!

**Comment by pateketrueke** [comment]
Yeah, you're totally right, TBH a not very common but pretty valid schema.

Thanks for your feedback, I'll be working on this asap. 👍

**Comment by pateketrueke** [comment]
I just removed the exception, I mean, throwing an error within the exception.

Because this is a truly exception don't you think?

From now on empty objects are returned.
