### ISSUE TITLE
JSF failed to generate valid combinations for large schema

### ISSUE THREAD

**Issue by abys890** [json-schema-faker/json-schema-faker#339]
Am using JSON schema faker for generating input combinations for one of the large schema we have. I use version 0.5.0-rc11. In many cases the JSF generates incomplete input combinations. The Schema validator is not validating the inputs formed with respect to the schema. Please help me to understand the possible cause of this.
Here are some samples  for  your reference.

1. Input generated from the tool.
{
  "ID": {
    "ID_value": 472,
    "ID_element": {
      "tcp-connect": {
        "destination": {
          "host-name": {
            "host-name_value": "amet cupidatat nisi",
            "host-name_element": {
              "PORT-NUM": {
                "PORT-NUM_value": 15090,
                "PORT-NUM_element": {
                  "source": {}
				
                }
              }
            }
          }
        }
      }
    }
  }
}

Expected:
{
  "ID": {
    "ID_value": 472,
    "ID_element": {
      "tcp-connect": {
        "destination": {
          "host-name": {
            "host-name_value": "amet cupidatat nisi",
            "host-name_element": {
              "PORT-NUM": {
                "PORT-NUM_value": 15090,
                "PORT-NUM_element": {
                  "source": {
					"IP-ADDR":{
						"IP-ADDR_value":"3.4.5.6",
						"IP-ADDR_element":{
							"PORT-NUM":1026
							}
						}
					}
                }
              }
            }
          }
        }
      }
    }
  }
}

2. Input from tool
{
  "ID": {
    "ID_value": 868
  },
  "responder": {
    "udp-jitter": {
      "IP-ADDR": {
        "IP-ADDR_value": "92.183.43.231",
        "IP-ADDR_element": {}
      }
    }
  }
}

But the "IP-ADDR_element": {} value is not filled.

3.
{
  "ID": {
    "ID_value": 636,
    "ID_element": {
      "enable": true
    }
  },
  "responder": {
    "tcp-connect": {}
  }
}
"tcp-connect": {} value is not filled
4.
{
  "ID": {
    "ID_value": 971,
    "ID_element": {
      "schedule": {}
    }
  },
  "responder": {}
}
"schedule": {} and "responder": {} values are not filled.

The input schema is attached.
Help me to understand the issue. Thanks in advance.
[input.txt](https://github.com/json-schema-faker/json-schema-faker/files/1414722/input.txt)

**Comment by pateketrueke** [comment]
The schema is very large, I saw it has so many references, probably that's the issue but is not your fault...

I mean, JSF has a limit for recursively resolve/generate sub-schemas given by reference, I think the main cause of your issue is that.

I'll increase such limits and try to resolve your schema just for understanding, but sadly this won't be fixed soon... I hope to get some spare time this weekend.

Again, thanks for your feedback!

**Comment by abys890** [comment]
Thank you so much for the immediate and prompt reply.  We have UT tool, developed on top JSF library. If possible could you suggest any workaround for this issue for the time being.

**Comment by pateketrueke** [comment]
Hi, I was working on this for a while and I noticed a few things:

1. You should expect always random output from your schema unless you add constraints to it, this means `required` properties, etc

2. If you want all properties to be present without adding any constraint then just enable `alwaysFakeOptionals` to achieve that, e.g.

```json
{
  "ID": {
    "ID_value": 652,
    "ID_element": {
      "udp-jitter-voip": {
        "destination": {
          "host-name": {
            "host-name_value": "ut",
            "host-name_element": {
              "PORT-NUM": {
                "PORT-NUM_value": 1835,
                "PORT-NUM_element": {}
              }
            }
          }
        }
      }
    }
  },
  "responder": {
    "tcp-connect": {
      "IP-ADDR": {
        "IP-ADDR_value": "47.67.176.187",
        "IP-ADDR_element": {}
      }
    }
  }
}
```

I'm still working on this, but it's already available under the `develop` branch.

If you're able to test this against your schemas it would be very helpful in order to close this issue.

So much thanks for your time and feedback!

**Comment by abys890** [comment]
Thanks for the update... Sure, I will test and update the results..

**Comment by abys890** [comment]
"alwaysFakeOptionals"  option is working for me..  So far the generation of inputs with respect to my schemas are giving proper combinations.
Thanks again for the support.
Also is there is any documentation for JSF library?  So that i can check for the available options and flags, because am seeking for a way to limit the input range for certain keys. Eg.. In case of IP address i need to form the request from a range of x.x.x.1 to x.x.x.15

**Comment by pateketrueke** [comment]
> Also is there is any documentation for JSF library?

The README is all we have by now, sory for that, we'll fix that soon too!

> a way to limit the input range for certain keys. Eg.. In case of IP address i need to form the request from a range of x.x.x.1 to x.x.x.15

That's a new feature request, the built-in generator for ipv4 does not cover such options yet, if you think is easier to add such constraints we're open to PRs!

**Comment by abys890** [comment]
Let me think.. If i get some idea, i will get back to you...

Thank you..
