### ISSUE TITLE
select jsf version on demo page

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#34]
Jsf has several versions published so far. Let's extend gh-pages and browserify all versions and let user choose (a GUI dropdown) online jsf version to generate data

**Comment by tkoomzaaskz** [comment]
Having multiple versions of the same library is npm seems impossible right now: https://github.com/npm/npm/issues/5499. There might be a solution, however, to add static files and freeze the forever for each demo-re-release.

Grunt would scan the version of the package, append it to the browserified filename of the bundle and there would be a list of all versions. But it seems cumbersome.
