### ISSUE TITLE
The example itself doesn't work

### ISSUE THREAD

**Issue by anandheritage** [json-schema-faker/json-schema-faker#341]
If you are reporting a bug, please include the following:

1. the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ (paste the schema, click `Generate example` and then copy and paste the resulting URL from the browser address bar)
2. the result you got
3. the result you expected

**Comment by pateketrueke** [comment]
I don't get you, which example doesn't work?

**Comment by pateketrueke** [comment]
If you meant the examples from the website, yeah, they can fail.

They can fail because we're loading the library from a CDN, if such CDN is not working then the page will not work. This happens too if you have connectivity issues.

I'm closing this since there were no more details provided.
