### ISSUE TITLE
is there a way to provide initial schema instance to the jsf whose data can override the respective random values in the schema instance?

### ISSUE THREAD

**Issue by nit23uec** [json-schema-faker/json-schema-faker#342]

**Comment by ducin** [comment]
Hi,

How about providing a description or at least an example? I'm not sure what do you want to achieve.

**Comment by nit23uec** [comment]
For example in the schema:
{
  "type": "object",
  "properties": {
    "user": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "#/definitions/positiveInt"
        },
        "name": {
          "type": "string"
        },
        "birthday": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        }
      },
      "required": [
        "id",
        "name",
        "birthday",
        "email"
      ]
    }
  },
  "required": [
    "user"
  ],
  "definitions": {
    "positiveInt": {
      "type": "integer",
      "minimum": 0,
      "minimumExclusive": true
    }
  }
}

suppose the faked instance generated is:
{
  "user": {
    "id": 38161771,
    "name": "ex dolore reprehender",
    "birthday": "enim tempor nulla in a",
    "email": "8MJ7iqkQmoxGV@g.tga"
  }
}

Now I want to edit this data and say replace name value with "ducin"
{
  "user": {
    "id": 38161771,
    "name": "ducin",
    "birthday": "enim tempor nulla in a",
    "email": "8MJ7iqkQmoxGV@g.tga"
  }
}
and save this data somewhere
Now I want to regenerate this schema instance but this time I want the name to be prefilled as "ducin" and not any random string. But all other properties can be random like id,birthday and email.

**Comment by ducin** [comment]
You can define your schema with [static values](http://json-schema-faker.js.org/#gist/2dec6d69cddaf8959368307028173b49/0.4.3). Is that it?

**Comment by nit23uec** [comment]
@ducin Not exactly. I don't want to change my schema definition as editing of the data is a frequent step.

**Comment by ducin** [comment]
still difficult for me to understand your intentions. Do you want to:
1. produce a sample out of a schema
2. modify the sample
3. (now here comes what you ask for) sample modifications cause modifying the schema back?
Do you want to create some kind of an observable object that would modify its source schema, basing on what property has been changed?

**Comment by pateketrueke** [comment]
> Now I want to regenerate this schema instance but this time I want the name to be prefilled as "ducin" and not any random string.

This means you want to modify the schema, so you need a modified schema the next time you want generate a new sample...

IMO you could attach a new attribute and register a wrapper for it, e.g.

```js
jsf.define('fixedValue', (value, schema) => {
  // read from schema and return a new value
});
```

And so, in your schema, you can do this:

```json
{
  "properties": {
    "name": {
      "type": "string",
      "fixedValue": true
    }
  }
}
```

Of course all the logic behind "how to read the stored value from elsewhere and return it" is up to you.

**Comment by pateketrueke** [comment]
Another way to solve this is using enabling the option `useDefaultValue` to get such value from the given schema.

This way you can put any value you want as `default` and it will be used instead, e.g.

https://github.com/json-schema-faker/json-schema-faker/blob/958f8d98ed763bb3f7c317fe989398a7f04622d3/spec/schema/core/option/useDefaultValue.json
