### ISSUE TITLE
Invalid URI generated?

### ISSUE THREAD

**Issue by arrkaye** [json-schema-faker/json-schema-faker#343]
http://json-schema-faker.js.org/#gist/f58db80cbf52c12c623166090240d964

Result: "PDVvJAPaJf"
Expected: Something of the form "http://...." or "xxx://..."

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier

**Comment by pateketrueke** [comment]
Actually is totally valid, as URI reference, not an absolute one.

Probably the built-in generator should alternate more formats to be flexible?

**Comment by arrkaye** [comment]
It would be good to get absolute ones. Some libraries don't validate the relative ones against the JSON Schema - am raising a separate issue with them too.

**Comment by pateketrueke** [comment]
Having some options for handling such cases, e.g. `jsf.option({ absoluteURIs: true })` would work for you?

I mean, I'll keep the actual behavior, but adding such constraints for specific cases.

Thanks for your feedback!
