### ISSUE TITLE
add values as example1.png  change  '.' character by another 

### ISSUE THREAD

**Issue by guldoe** [json-schema-faker/json-schema-faker#353]
I'm trying to add a static resource like example1.png, example2.png, ... 

Example where test it 
http://json-schema-faker.js.org/#gist/7b6da6b2f761f4ae0978c598bb190691/0.5.0-rc11

The main problem is always changing my character by another. 
Schema:
 logo: {
      type: 'string',
      pattern: 'example1.png|example2.png|example3.png',
  },

2. the result you got
![screen shot 2017-12-18 at 12 23 43](https://user-images.githubusercontent.com/6005590/34103800-5e8de9be-e3ee-11e7-872a-05f696c140f8.png)

**Comment by guldoe** [comment]
solution:  
We can escape .  with \\ 
Example: 
pattern: 'example1\\.png|example2\\.png|example3\\.png',

**Comment by pateketrueke** [comment]
In your case a better regexp: `example\d\.png` will cover all your examples.

**Comment by ronalson** [comment]
> just if someone get to this issue looking for a solution:

I managed to achieve the dot character using the brackets `[.]` notation:

input: `"pattern": "^([0-9]{2}[.][0-9]{3}[.][0-9]{3}/[0-9]{4}-[0-9]{2})$"`

output: `["27.712.140/6386-62"]`

Using either `\` or `\d\.` I couldn't  make it work properly.

**Comment by pateketrueke** [comment]
Yeah, nice trick, any special character inside `[` and `]` are taken as literals, good catch! 🍻
