### ISSUE TITLE
Floating point when using multipleOf

### ISSUE THREAD

**Issue by adelura** [json-schema-faker/json-schema-faker#379]
Hi, I just started to play with your library and noticed one thing:

``` js
let jsf = require('json-schema-faker');
let seed = [ 0.25546874766962246, 0.06559633646612273 ];
jsf.option({ random: () =>seed.shift() });

let schema = {
  "type": "number",
  "multipleOf": 0.01
};

jsf.resolve(schema).then(function(sample) {
  console.log(sample); // 13119267.290000001
});
```
What I expect here is two decimal places at most. I can imagine that you might be aware of that as this project looks mature, but I couldn't find any issue related to that.

**Comment by pateketrueke** [comment]
Nice issue, you're totally right, it should generate a two-decimal number instead.

So much thanks for your feedback, I'll be fixing this soon, if you found something else please let us know. 😉

**Comment by pateketrueke** [comment]
This is getting complex: https://github.com/mafintosh/is-my-json-valid/issues/172

I'm trying to understand this properly, using this validator: https://json-schema-validator.herokuapp.com/

```
[ {
  "level" : "error",
  "schema" : {
    "loadingURI" : "#",
    "pointer" : ""
  },
  "instance" : {
    "pointer" : ""
  },
  "domain" : "validation",
  "keyword" : "multipleOf",
  "message" : "remainder of division is not zero (13119267.290000001 / 0.01)",
  "value" : 13119267.290000001,
  "divisor" : 0.01
} ]
```

> The value `13119267.290000001` is not valid, but `0.91` is, of course, multiple of `0.91` right?

It depends on how validators treat this: https://runkit.com/pateketrueke/5b9ef02f3cede20011d5f06f

The results are weird, seriously!

- `tv4` validates both values (it is correct?)
- `is-my-json-schema` invalidates the long `.290000001` remainder
- `ajv` and `z-schema` both invalidates `0.91` as `multipleOf: 0.01` ... why?

We'll try to generate an appropriate value for `multipleOf` as long validators don't get it wrong.

I think rounding up `13119267.290000001` to `13119267.29` is the best choice and it's easier to solve.

Any thoughts?

- @1mafintosh (is-my-json-valid)
- @1geraintluff / @2Bartvds (tv4)
- @1zaggino (z-schema)
- @1epoberezkin (ajv)

**Comment by Jeffersondyj** [comment]
Hello，I just found another problem when multipleOf is float

    let jsf = require('json-schema-faker');

    let schema = {
        "type": "number",
        "multipleOf": 0.01,
        "minimum": 7,
        "maximum": 10
    };

    jsf.resolve(schema).then(function(sample) {
        console.log(sample);
    });

It was expected to be a number between 7 and 10, just like 7.01, or 9.99
but it turn out to be a number between 0 and 3, just like 0.52, 2.88

Then I found the source code: https://github.com/json-schema-faker/json-schema-faker/blob/master/src/lib/types/number.js

line38 to line50,  in line50, should `return min + num` instead of `return num`

And in this ut, https://github.com/json-schema-faker/json-schema-faker/blob/master/tests/schema/core/issues/issue-252.json
when minimum is zero, the ut will be passed. So maybe we should add a ut when minimum is not zero

Thank you very much for your replying.

**Comment by pateketrueke** [comment]
Interesting issue, feel free to change the code as you think and submit it as PR!

I'll be checking this as soon as I can, any help is very appreciated.

**Comment by GaryStrange** [comment]
Hi, was the original issue resolved?

I just ran a schema through the online .org site and it didn't generate fake values that were faithful to my multipleOf definitions.

Thanks,
Gary

**Comment by pateketrueke** [comment]
Hi @GaryStrange I think it is solved, but you know, there could be regressions.

¿Can you share the schema and output you got? Thank you!

**Comment by GaryStrange** [comment]
It appears to be non-deterministic so if you have enough 'number' attributes you can increase your chances of exposing the problem.

enter...

{
  "QTYORDERED": {
    "type": "number",
    "multipleOf": 1e-7
  },
  "QTYORDERED2": {
    "type": "number",
    "multipleOf": 1e-7
  },
  "QTYORDERED3": {
    "type": "number",
    "multipleOf": 1e-7
  },
  "QTYORDERED4": {
    "type": "number",
    "multipleOf": 1e-7
  },
  "QTYORDERED5": {
    "type": "number",
    "multipleOf": 1e-7
  }
}

into 

https://json-schema-faker.js.org/

and you should see at least on fake with more than 7 d.p

**Comment by pateketrueke** [comment]
Woah, you're using `1e-7` as a multiple, do you think is a common case?

**Comment by lucas-weje** [comment]
Hi,

I am experiencing the same problem as @GaryStrange with the multipleOf definitions.

Currently working with SAP data types, and you can see a snippet of my schema below:
![image](https://user-images.githubusercontent.com/82023618/129553944-41298560-2a00-47a6-b0b4-ca1e8b0387e6.png)

Using jsf.generate() on the schema I am then returned this:
![image](https://user-images.githubusercontent.com/82023618/129554062-9c7f0ff6-3b66-480a-896b-68cf4e000369.png)

Here you can see 'CDEC31_0' does not conform to the multipleOf = 1.

**Comment by pateketrueke** [comment]
Got it, I think we could spent some time rewriting a simple solution for multipleOf, then integrate it back to JS, what do you think?
