### ISSUE TITLE
OneOf/AnyOf Json Schema Validation not working

### ISSUE THREAD

**Issue by shubhamhpe** [json-schema-faker/json-schema-faker#386]
Schema file:
```
{
  "title": "timesync",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "sntp": {
      "type": "boolean",
      "default": false,
      "description": "Update the system clock using SNTP."
    },
    "timep": {
      "type": "boolean",
      "default": false,
      "description": "Update the system clock using TIMEP."
    },
    "timep-or-sntp": {
      "type": "boolean",
      "default": true,
      "description": "Update the system clock using TIMEP or SNTP."
    },
    "ntp": {
      "type": "boolean",
      "default": false,
      "description": "Update the system clock using NTP."
    },
    "uri": {
      "type": "string",
      "description": "The URI of the configuration entity",
      "readonly": true
    }
  },
  "oneOf": [
    {
      "required": [
        "sntp"
      ]
    },
    {
      "required": [
        "timep"
      ]
    },
    {
      "required": [
        "timep-or-sntp"
      ]
    },
    {
      "required": [
        "ntp"
      ]
    }
  ],
  "additionalProperties": false
}
```
-----------------------------------------------------------------------------------
Output:
Sending request...
PUT /rest/v5/config/timesync
```
{
    "ntp": false,
    "sntp": true,
    "timep": false,
    "uri": "aliquip culpa veniam enim",
    "timep-or-sntp": false
}
```
Response code: 400
```
{
    "Error": "JSON OneOf validation failed: 'sntp'",
    "Command": "timesync"
}
```
-----------------------------------------------------------------------------------

It is just checking the properties and not the OneOf Validation. It should not show all the properties in the request. Also, sometimes it shows true for more than one properties.
It should show only one property that too 'true'.
So, Expected Output:
```
< HTTP/1.1 200 OK
< Server: eHTTP v2.0
< Connection: keep-alive
< Content-Type: application/json
< Transfer-Encoding: chunked
< RequestId:
<
{
    "uri": "/rest/v5.0/config/timesync",
    "sntp": true
}
```

**Comment by pateketrueke** [comment]
Which version you're using?

On `0.5.0-RC-13` seems to be working, but the latest `0.4.7` isn't.

Definitely a `4.x` issue to be solved, or just upgrade to the latest RC which'll be the next stable.

**Comment by shubhamhpe** [comment]
Hi, I am using 0.5.0-rc11 version which is not a 4.x version but still the things are not working.

**Comment by pateketrueke** [comment]
I just tested the schema using RC13 and it worked, previous releases still have this bug.

**Comment by pateketrueke** [comment]
Hi, this is fixed (I hope so) on `RC15` :tada:

**Comment by shubhamhpe** [comment]
Hi, I am using RC15 but still the issue exists.

**Comment by pateketrueke** [comment]
Hi again, please provide a complete schema to explore the issue.

Use the online sandbox and/or post the JSON properly here (using the formatting tools), thank you!

**Comment by shubhamhpe** [comment]
Hi, you can consider the same schema which is given above, one thing is that I am setting **alwaysFakeOptionals** option to be true. But the tool should always fake the data after satisfying the oneOf/ anyOf condition.

**Comment by pateketrueke** [comment]
Oh, I see, once you enable alwaysFakeOptional the distinction from oneOf/anyOf is not working anymore!

Definitely the behavior should be the same, I'll fix this asap... thank you for your feedback!

**Comment by pateketrueke** [comment]
I hope this is already solved on `develop`, closing this.
