### ISSUE TITLE
How to get not random unique id number

### ISSUE THREAD

**Issue by mtk3d** [json-schema-faker/json-schema-faker#387]
I have a problem with generate ids in my json.
I want to get unique id number in range from 1 to 100. Is that possible with this package? 
I'm trying to use `autoIncremet`, but then values starts from random number.

**Comment by pateketrueke** [comment]
The default implementation for `autoIncrement` lacks of that support, however you can redefine it in order to make it work as you want: https://github.com/json-schema-faker/json-schema-faker/blob/master/ts/index.ts#L123-L137

Example:

```js
jsf.define('autoIncrement', (value, schema) => {
  if (!this.offset) {
    this.offset = value.initialOffset || schema.initialOffset || 1;
  }

  if (value === true) {
    return this.offset++;
  }

  return schema;
});

const schema = {
  properties: {
    aList: {
      type: 'array',
      items: {
        properties: {
          id: {
            type: 'integer',
            initialOffset: 100,
            autoIncrement: true,
          },
        },
        required: ['id'],
      },
    },
  },
  required: ['aList'],
};

console.log(jsf(schema));
```

If that works for you, please let us know. ;-)

**Comment by mtk3d** [comment]
Yes, its work for me very well. Thanks, for your help :D

**Comment by pateketrueke** [comment]
I think this should be implemented by default, I'll add this patch to the next releases. 🍺
