### ISSUE TITLE
Showing Output with some of the properties of Schema

### ISSUE THREAD

**Issue by shubhamhpe** [json-schema-faker/json-schema-faker#391]
Code along with schema:

var jsf = require('json-schema-faker');

var schema = {
    "$schema": "http://json-schema.org/draft-04/schema#", 
    "description": "VLAN configuration data.", 
    "title": "Vlan", 
    "type": "object", 
    "sql.max_rows": 4094, 
    "properties":
    {
        "uri":
        {
            "description": "The URI of the configuration entity", 
            "type": "string", 
            "readonly": true
        }, 
        "vlan_id":
        {
            "description": "The unique ID of the VLAN. IEEE 802.1Q VLAN identifier (VID)", 
            "minimum": 1, 
            "maximum": 4094, 
            "type": "integer", 
            "sql.not_null": true
        }, 
        "name":
        {
            "description": "Name of the VLAN.", 
            "type": "string", 
            "maxLength": 32, 
            "sql.not_null": true, 
            "sql.unique": true
        }, 
        "is_jumbo_enabled":
        {
            "description": "Whether Jumbo is enabled.", 
            "type": "boolean"
        }, 
        "is_voice_enabled":
        {
            "description": "Whether Voice is enabled.", 
            "type": "boolean"
        }, 
        "is_dsnoop_enabled":
        {
            "description": "Whether DSNOOP is enabled.", 
            "type": "boolean"
        }, 
        "is_dhcp_server_enabled":
        {
            "description": "Whether DHCP SERVER is enabled.", 
            "type": "boolean"
        }, 
        "is_management_vlan":
        {
            "description": "Whether vlan is a management vlan", 
            "type": "boolean"
        }
    }, 
    "additionalProperties": false
};

jsf.resolve(schema).then(function(sample) {
  console.log(sample);
  // "[object Object]"
});
---------------------------------------------------------------------------------------------------------------
Output 1:

{ uri: 'ipsum eiusmod dolore',
  vlan_id: 1701,
  name: 'ipsum enim' }

Output 2: 
{ uri: 'Excepteur et mollit velit' }

Output 3: {}

Output 4: 
{ uri: 'sint et nulla do',
  vlan_id: 2631,
  name: 'aliquip ',
  is_jumbo_enabled: false,
  is_voice_enabled: true }
-------------------------------------------------------------------------------------------------------------

Expected Output:
{
    "uri": "/vlans/5",
    "vlan_id": 567,
    "name": "Vlan5",
    "is_voice_enabled": false,
    "is_jumbo_enabled": false,
    "is_dsnoop_enabled": false,
    "is_dhcp_server_enabled": false,
    "is_management_vlan": false
}

It should be something like this, but here it is showing only some of the properties which are given in the schema file. Here there is nothing like OneOf/AnyOf. It should show all the keys/properties but the values can be faked data.

**Comment by pateketrueke** [comment]
> **It should show all the keys/properties** but the values can be faked data.

By design that'll never happen, let me explain:

- Properties are faked randomly, those that they're never set as `required` will never be generated
- Only properties you set as required, e.g. `"required": ["uri"]` will be generated always...

So, you shouldn't expect _optional properties_ unless you force them:

- By adding them as `required`
- Or setting `jsf.option({ alwaysFakeOptionals: true })`

PS: please use proper formatting every time you post code...

**Comment by shubhamhpe** [comment]
Thanks a lot. It's working fine now.
