### ISSUE TITLE
UnhandledPromiseRejectionWarning: ReferenceError: sub is not defined

### ISSUE THREAD

**Issue by shubhamhpe** [json-schema-faker/json-schema-faker#392]
code along with schema:

var jsf = require('json-schema-faker');

var schema = {
  "title": "timesync",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "sntp": {
      "type": "boolean",
      "default": false,
      "description": "Update the system clock using SNTP."
    },
    "timep": {
      "type": "boolean",
      "default": false,
      "description": "Update the system clock using TIMEP."
    },
    "timep-or-sntp": {
      "type": "boolean",
      "default": true,
      "description": "Update the system clock using TIMEP or SNTP."
    },
    "ntp": {
      "type": "boolean",
      "default": false,
      "description": "Update the system clock using NTP."
    }
  },
  "anyOf": [
    {
      "required": [
        "sntp"
      ],
      "not": {
        "required": [
          "timep",
          "timep-or-sntp",
          "ntp"
        ]
      }
    },
    {
      "required": [
        "timep"
      ],
      "not": {
        "required": [
          "sntp",
          "timep-or-sntp",
          "ntp"
        ]
      }
    },
    {
      "required": [
        "timep-or-sntp"
      ],
      "not": {
        "required": [
          "sntp",
          "timep",
          "ntp"
        ]
      }
    },
    {
      "required": [
        "ntp"
      ],
      "not": {
        "required": [
          "sntp",
          "timep",
          "timep-or-sntp"
        ]
      }
    }
  ]
};

jsf.resolve(schema).then(function(sample) {
  console.log(sample);
  // "[object Object]"
});
------------------------------------------------------------------------------------------------------------------
Output:
C:\Users\Downloads\json-schema-faker>node abcjsf.js
 (node:15000) UnhandledPromiseRejectionWarning: ReferenceError: sub is not defined
    at traverse (C:\Users\Downloads\json-schema-faker\node_modules\json-schema-faker\lib\index.js:1122:33)
    at traverse (C:\Users\Downloads\json-schema-faker\node_modules\json-schema-faker\lib\index.js:1129:16)
    at run (C:\Users\Downloads\json-schema-faker\node_modules\json-schema-faker\lib\index.js:1249:22)
    at C:\Users\Downloads\json-schema-faker\node_modules\json-schema-faker\lib\index.js:1408:37
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
(node:15000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
----------------------------------------------------------------------------------------------------------------

Expected:
{
"sntp": true
}

**Comment by pateketrueke** [comment]
Hi, please use the formatting blocks for proper syntax hilighting and such: it's very difficult to read and catch issues in your code...

Now, I've checked out the generated code and of course there's a bug, a really big one!

Actually is just a type, I'll fix that asap and release a patch soon!

Thanks for your feedback. 💣
