### ISSUE TITLE
Extending faker for use custom local is not working

### ISSUE THREAD

**Issue by frangeris** [json-schema-faker/json-schema-faker#393]
Trying to use a custom locale extending faker is not working.

```javascript
const jsf = require('json-schema-faker')
jsf.extend('faker', () => require('faker/locale/en_US'))
jsf.resolve(require('../schemas/post-orgs.json')).then(schema => {
  console.log(schema)
})
```
The content should be **English** but its using other locale (default)... de?

```javascript
{
        id: 'do sunt Ut',
        name: 'minim officia Ut',
        logo: 'fugiat magna',
        phone: 'incididunt non dolore nulla in',
        country: 'reprehenderit',
        address: 'sint consectetur est',
        taxId: 'ut eiusmod',
        currency: 'sint',
        extra: 'mollit dolor'
}
```
What's going on here?

**Comment by pateketrueke** [comment]
Hi, thanks for your feedback!

Let me explain you:

- The default text used for generating strings is _latin_, just basic `lorem ipsum` stuff
- Depending on how is defined your schema and the right usage of `faker` keywords it'll work or not

A good example of this: https://json-schema-faker.js.org/#gist/1902737e7bef9573af02a3fc49761c13

Can you show the schema you're using for?

**Comment by frangeris** [comment]
Got it, it's a basic schema:

```json
{
  "title": "post-orgs",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "logo": {
      "type": "string"
    },
    "phone": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },
    "address": {
      "type": "string"
    },
    "taxId": {
      "type": "string"
    },
    "currency": {
      "type": "string"
    },
    "extra": {
      "type": "string"
    }
  }
}
```

I understand about the format for the output from faker, but that's not the problem, the problem is the language used, I need English, I don't care about the format....

**Comment by pateketrueke** [comment]
> I need English, I don't care about the format....

That's the problem: in order to use languages from faker, you need to add `faker` constraints to your values.

So, this is basically fine _but wrong_:

```json
{
  "type": "string"
}
```

Instead you must setup a `faker` prop:

```json
{
  "type": "string",
  "faker": "internet.email"
}
```

Check out a faker.js reference to know the possible paths you can take: https://github.com/Marak/faker.js/#api-methods

**Comment by frangeris** [comment]
Ok, got it now, I though all string were in German, but using faker its ok,

thanks!
