### ISSUE TITLE
Random value for given key/property

### ISSUE THREAD

**Issue by shubhamhpe** [json-schema-faker/json-schema-faker#394]
**JSON Schema:**

{
  "title": "ro",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "enable": {
      "type": "boolean",
      "default": false,
      "description": "Enable"
    },
    "disable": {
      "type": "boolean",
      "default": "false",
      "description": "Disable"
    },
    "action": {
      "description": "Configure the action.",
      "$ref": "#/definitions/action_ref_1"
    },
    "uri": {
      "type": "string",
      "description": "The URI",
      "readonly": true
    }
  },
  "anyOf": [
    {
      "required": [
        "enable"
      ],
      "not": {
        "required": [
          "disable"
        ]
      }
    },
    {
      "required": [
        "disable"
      ],
      "not": {
        "required": [
          "enable"
        ]
      }
    },
    {
      "required": [
        "action"
      ]
    }
  ],
  "definitions": {
    "action_ref_1": {
      "type": "object",
      "block": {
        "type": "boolean",
        "default": true,
        "description": "Block and log."
      },
      "anyOf": [
        {
          "required": [
            "block"
          ],
          "not": {
            "required": [
              "log"
            ]
          }
        },
        {
          "required": [
            "log"
          ],
          "not": {
            "required": [
              "block"
            ]
          }
        }
      ],
      "log": {
        "type": "boolean",
        "description": "Log traffic."
      }
    }
  }
}

**Output:**
In RC13 I am getting error (sub is not defined) which is the issue no. 392 And in RC11 I am getting the following output:

{
  "disable": true,
  "uri": "aliquip qui fugiat",
  "enable": false,
  "action": {
    "ut2": -62959594
  }
}

So, the problem here is how come it is taking random string values for the "action" property, it should be "block" or "log" only and then it's value should be true or false as it is a boolean attribute.

**Expected output:**

{
  "disable": true,
  "uri": "aliquip qui fugiat",
  "enable": false,
 "action": {
        "block": true
    }
}

**Comment by pateketrueke** [comment]
Please, can you edit your message and user proper code-blocks?

Also feel free to use the online at https://json-schema-faker.js.org/ to test your schema and/or prepare a better example.

Thank you!

**Comment by pateketrueke** [comment]
Update: I notices you're using `not` keywords and the library is broken, I'll publish a patch right now to have a stable version of this.

**Comment by pateketrueke** [comment]
Hi, this is fixed (I hope so) on `RC15` :tada:
