### ISSUE TITLE
Regex pattern generating invalid data

### ISSUE THREAD

**Issue by Gabology** [json-schema-faker/json-schema-faker#398]
For the following schema:

```json
{
  "type": "object",
  "properties": {
    "countryCode": {
      "type": "string",
      "minLength": 1,
      "maxLength": 3,
      "pattern": "^[0-9]{1,3}?$"
    },
    "nationalNumber": {
      "type": "string",
      "minLength": 1,
      "maxLength": 14,
      "pattern": "^[0-9]{1,14}?$"
    }
  },
  "required": ["countryCode", "nationalNumber"]
}
```

This data was generated:

```json

{
  "countryCode": " ",
  "nationalNumber": "255359182"
}

{
  "countryCode": "11",
  "nationalNumber": " "
}

```

In both cases the generated string will not match the regexp `^[0-9]{1,3}?$` and `^[0-9]{1,14}?$` respectively. This was tested on version 0.5.0-rc15 and can easily be reproduced.

**Comment by pateketrueke** [comment]
Hi, thanks for your feedback!

In your regexps you're using `?` that just makes the whole expression optional.

Just remove it from the expression, is not needed as long you're using anchors and fixed length, etc.

**Comment by pateketrueke** [comment]
> So I don’t believe the regex is the issue here.

We're using [randexp](https://www.npmjs.com/package/randexp) to generate random values from regexps.

Please consider open an issue/PR on that library, that way we all benefit from it. 

> You may confirm that by trying the generated data in another JSON validator, it will not validate.

Yeah, of course it'll not validate.

I'm not expert on RegExp but when I removed the `?` it worked.

**Comment by pateketrueke** [comment]
Won't fix. I think it's `randexp` concern.
