### ISSUE TITLE
Json schema faker english language

### ISSUE THREAD

**Issue by vijaybernad** [json-schema-faker/json-schema-faker#404]
If you are reporting a bug, please include the following:

How to set Json-schema-faker default language as english

1. the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ 
var schema = {
                                    "name": {
                                        "legal": {
                                            "type": "string",
                                            "minLength": 1,
                                            "faker": 'name.findName'
                                        }
                                    }
                                }
2. It is generating data but in a different language("dolore sit id deserunt " not sure what language )
3. the result should be in English. Guide me how to do.I tried extending faker it works but i don't want to extend .

**Comment by Odrin** [comment]
@pateketrueke can you give an example, please? I can't find information in documentation.

**Comment by pateketrueke** [comment]
In order to use faker.js languages you must setup it first: https://github.com/json-schema-faker/json-schema-faker#user-content-advanced-usage-of-fakerjs-and-chancejs

**Comment by matthewsmkim1** [comment]
Is it still possible to use faker.js languages? I noticed that the link above just takes you to the homepage for JSON Schema Faker, and doesn't have instructions on how to set it up

**Comment by pateketrueke** [comment]
Nice catch, right link is: https://github.com/json-schema-faker/json-schema-faker/blob/master/docs/USAGE.md#user-content-advanced-usage-of-fakerjs-and-chancejs
