### ISSUE TITLE
Enum with negative number is not generated

### ISSUE THREAD

**Issue by danziamo** [json-schema-faker/json-schema-faker#405]
Error occurred in latest jsf
schema i used
```
{
  "id": "num",
  "type": "integer",
  "enum": [-4]
}
```
Result is NaN.
Expeced: -4

looks like it works on older versions.

**Comment by pateketrueke** [comment]
You're reight, it's ignoring the `enum`, if you remove the `type` seems to work...

Definitely an issue, thanks for your feedback. 👍

**Comment by pateketrueke** [comment]
Fixed on `develop`. :bomb:
