### ISSUE TITLE
[Feature request] Relative JSON paths 

### ISSUE THREAD

**Issue by ehmicky** [json-schema-faker/json-schema-faker#406]
Shouldn't JSON paths be relative to the current object? At the moment, `$` is resolved to the root object. However I believe one of the main use cases will be to retrieve a sibling. This is also the approach (although without using JSON paths) of similar libraries like [`mocker-data-generator`](https://github.com/danibram/mocker-data-generator).

```
const jsf = require('json-schema-faker');

jsf.option({ resolveJsonPath: true, optionalsProbability: 1 });

jsf({ 
  type: 'object',
  properties: { 
    a: { 
      type: 'object', 
      properties: {
        b: { 
          type: 'object',
          properties: {
            c: { type: 'string' },
            d: { jsonPath: '$.a.b.c' } // Should probably just be `$.c`
          }
        }
      }
    }
  }
}); 
```

**Comment by pateketrueke** [comment]
Yeah!

Actually this is an issue, see: https://github.com/json-schema-faker/json-schema-faker/issues/400#issuecomment-382077127

I also consider this very useful but we need to define basic semantics for this, any idea is very welcome.

Thanks for your feedback!

**Comment by pateketrueke** [comment]
Yeah, but then we wouldn't be able to match data, or at least not with pure json-path (a mixture of json-ref-pointers + json-path could be...)

Having to resolve from the current object just reduce the possibilities, and in such case just doing `#{relativeProperty}` will suffice.

I think we can even prefix json-path expressions to set the `root` on many ways, e.g.

```json
{
  "jsonPath": "#/relative/from/root/object$.and.with.json.path"
}
```

or...

```json
{
  "jsonPath": {
    "root": "#/relative/from/root/object",
    "query": "$.and.with.json.path"
  }
}
```

Of course they're just ideas but we're free to propose.

Just think about the possiblities! 😄

**Comment by ehmicky** [comment]
That sounds like a really good idea.

This means the default `root` could be `#`, i.e. like the current behavior.

When it comes to JSON references, the following would need to be figured out:
  - should relative JSON pointers be supported? One possible problem is that very few libraries currently support it. `json-schema-ref-parser` does not.
  - should external URIs be resolved? If so, should they be resolved at the same time as the other JSON references?

Another concern would be: isn't the `$ref` property already covering some of the use case here? Would this be partial duplicate of features/code (e.g. for external URIs resolution), i.e. they should be merged?

Finally I think there should be an easy way to simply refer to siblings value. This is probably one of the main use cases, and `"jsonPath": "#/sibling$"` might look too cryptic.

**Comment by pateketrueke** [comment]
It's been a while but now I'm realize that relative json-path references are already supported:

```json
{ 
  "type": "object",
  "properties": { 
    "a": { 
      "type": "object", 
      "properties": {
        "b": { 
          "type": "object",
          "properties": {
            "c": { "type": "string" },
            "d": { "jsonPath": "$..c" }
          }
        }
      }
    }
  }
}
```

Using `$..c` will access the property `c` from the current node.

If you think we really need this feature please let me know. 🍻

**Comment by ehmicky** [comment]
No that works indeed, thanks!
