### ISSUE TITLE
Default `resolveJsonPath` to `true`

### ISSUE THREAD

**Issue by ehmicky** [json-schema-faker/json-schema-faker#407]
Should `resolveJsonPath` option default to `true`? 

I think this is a very useful feature. Also since `resolveJsonPath` is not a standard JSON schema property (nor likely to be), there should be no conflicts.

Another option would be instead to not have an option at all:
  - during traversal, check if any schema object has a `jsonPath` property
  - after traversal is completed, fire the `resolve()` function or not accordingly

**Comment by pateketrueke** [comment]
Definitely it shall be, IMO it's fine setting `resolveJsonPath` as true by default. 👍 

Any other suggestion is very welcome.

Thanks for your feedback!

**Comment by ehmicky** [comment]
Great!

There might be a slight performance drawback because of the deep traversal performed by the JSON path resolution function.

**Comment by pateketrueke** [comment]
Yeah, but as you say we can check that while traversing, so I hope we don't re-cycle too much.

**Comment by pateketrueke** [comment]
Done in `develop`! 🍻
