### ISSUE TITLE
[Feature request] Support `dependencies` keyword

### ISSUE THREAD

**Issue by ehmicky** [json-schema-faker/json-schema-faker#409]
This is a JSON schema v4 property.

I'm not sure this is something you would consider useful, I just wanted to bring it up to see what you think.

The form `"dependencies": ["propA", "propB"]` might re-use the same logic as the `required` property.

However the form using a object as value is probably much more complex to implement. 

Also since the introduction of `if|then|else` in JSON schema v7, it's been flagged as "potentially deprecated", depending on the community feedback on `if|then|else`.

Thanks again for your work on this great library.

**Comment by pateketrueke** [comment]
I want to keep this as simple as we can, but as flexible as we really need.

As long schemas are inter-operable or compatible I think it'll be fine, you said we can re-use the logic behind `required` to achieve `dependencies` but it's really the only way?

I would like to explore usage cases where `dependencies` are much more clear than `required` properties.

Do you have something in mind?

**Comment by ehmicky** [comment]
I am not sure what you mean by "clear usage cases", could you provide an example?

Correct me if I'm wrong but I think `dependencies` is similar to `if|then|else` + `required`, specifically:
  - `{ "dependencies": { "propA": { type: "string" } } }` is same as `{ "if": { "required": ["propA"] }, "then": { "type": "string" } }`
  - `{ "dependencies": { "propA": ["propB"] } }` is same as `{ "if": { "required": ["propA"] }, "then": { "required": ["propB"] } }`

Which means if the `if|then|else` keywords were implemented (which might be hard), `dependencies` could re-use its logic.

**Comment by ehmicky** [comment]
Yes this looks good, great!

**Comment by ehmicky** [comment]
Thanks for the work put into this @pateketrueke!
