### ISSUE TITLE
Having two properties that have the same value

### ISSUE THREAD

**Issue by NERDYLIZARD** [json-schema-faker/json-schema-faker#419]
How do I create the schema for an object that contains two properties having the same value?

I want the property "id" and "slug" to have the same value.
```
{
      "id": "a2084ca2-bfa4-472e-b27a-30067755d512",
      "slug": "a2084ca2-bfa4-472e-b27a-30067755d512"
}
```
My schema:
```
{
  "type": "object",
  "properties": {
    "cards": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "faker": "random.uuid",
            "unique": true
          },
          "slug": {
            "type": "string",
            "faker": "random.uuid",
            "unique": true
          },
        },
        "required": ["id", "slug"]
      }
    }
  },
  "required": ["cards"]
};
```

**Comment by pateketrueke** [comment]
Hi, we have something like `#{siblingProp}` to access those generated values, saddly is not refined at the level you want... yet.

Let me think what can I do to improve this feature.

Thanks for your feedback!

**Comment by Otto-AA** [comment]
> Hi, we have something like #{siblingProp} to access those generated values, saddly is not refined at the level you want... yet.

Is this already implemented? I couldn't find documentation for it :/

**Comment by Otto-AA** [comment]
Aside from that, you could use an extension to store the value.

Here is one demonstrating it for an array: https://repl.it/@Otto_AA/JSF-Singleton
("usesBeforeRecalculating" means that after the value has been used x times, it will be recalculated)

**Comment by pateketrueke** [comment]
Fixed on `develop`. 💣

**Comment by ValfarDeveloper** [comment]
I posted an alternative solution here: https://stackoverflow.com/questions/54940463/how-to-use-reference-field-values-generated-in-the-same-json-schema#answer-63553259
