### ISSUE TITLE
optionalsProbability not recalculated for each record in an array?

### ISSUE THREAD

**Issue by jkinzel-r7** [json-schema-faker/json-schema-faker#425]
I'm looking for some clarification on the `optionalsProbability` setting:

Schema: 
```
{
  "type": "object",
  "properties": {
    "records": {
      "type": "array",
      "minItems": 5,
      "maxItems": 20,
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "faker": "name.findName"
          },
          "phone": {
            "type": "string",
            "faker": "phone.phoneNumber"
          },
          "email": {
            "type": "string",
            "faker": "internet.email"
          }
        },
        "required": ["name", "email"]
      }
    }
  },
  "required": ["records"]
}
```

Run with the following: 

`jsf.option({optionalsProbability:0.6})`

**Expected**: Each record in the collection would have a 60% change of getting the optional field (phone in this case).

**Received**: The optional property probability seems to be calculated for the _entire_ collection instead of on an individual basis. The resulting JSON has a 60% chance of having the field on every record in the collection rather than on the individual records in the collection.

**Comment by pateketrueke** [comment]
Oh, this is very interesting, with that schema the `phone` is never generated (`RC15`). 🤔 

I just tested it on `RC12` and I get `phone` sometimes which is good.

Example: https://json-schema-faker.js.org/#gist/53bbc7c818e8f431fcc5add563c1677f/0.5.0-rc12

I think we need to investigate a bit more, thank you!

@manuelmhtr what do you think?

**Comment by pateketrueke** [comment]
Fixed on `develop`. ✌️
