### ISSUE TITLE
Feature: Custom types

### ISSUE THREAD

**Issue by whitlockjc** [json-schema-faker/json-schema-faker#437]
There is already a way to [register a custom format generator](https://github.com/json-schema-faker/json-schema-faker#custom-formats) and it would be nice to be able to do the same for custom types.  I realize this may be a deviation from JSON Schema, so I understand if you want to -1 this, but for formats that build on top of JSON Schema _(like OpenAPI)_ it would be nice to avoid having to sanitize things or reinvent the wheel.  Thoughts?

**Comment by pateketrueke** [comment]
Definitely I don't prefer to support non-standar types, so I would solve this through custom keywords which are bit shorter than custom formats.

**Comment by whitlockjc** [comment]
Can you elaborate on the _"custom keywords"_?

**Comment by pateketrueke** [comment]
Yeah, sorry. 

See this code: https://github.com/json-schema-faker/json-schema-faker/blob/master/ts/index.ts#L115-L160

> In that code, we're employing _custom keywords_ to handle specific use cases, like `pattern` does.
> That way you can produce a value, or even return another schema in exchange.
