### ISSUE TITLE
reusing compiled schemas

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#44]
It would be faster for other tools, relying on jsf, to re-use initially compiled schema. So far, there is `jsf(schema)` used to generate an object, which means that the schema needs to be read each time for each object. Unless I don't know there is a better solition. Is there :)?

E.g. in my grunt jsf plugin: https://github.com/tkoomzaaskz/grunt-jsonschema-faker/blob/master/tasks/jsonschema_faker.js#L49-L51 I need to re-compile the schema in a loop. What I'm thinking of is to provide a way to compile the schema once and enable users to massively generate the schema.

I do use it to generate arrays, that's true. And there are arrays in json schema, that's also true :-). However, when I hold json schemas, I would like to have a single object schema, which I'll use to validate. And I'd prefer to be able to generate a whole collection of test data (which means _not_ including the array in the schema).

Awaiting your feedback, before I move on, Alvaro :beers:

**Comment by pateketrueke** [comment]
I'm a bit lost here, if we could precompile any schema, how it would look?

**Comment by ducin** [comment]
Currently we've got this:

var jsf = require('json-schema-faker');
var fakeObject1 = jsf(schemaObject);
var fakeObject2 = jsf(schemaObject);
var fakeObject3 = jsf(schemaObject);

Note, that each time we want to create a fake object, the schema object needs to be analysed from scratch (traverse->...). And it's only 3 times in above example. Imagine it'd be 1000? Now, I'm using jsf in my [grunt plugin](https://github.com/ducin/grunt-jsonschema-faker), where I just pass a number of items to be repeated from a given schema. This is far away from being optimal. What I suggest is to precompile the schema, e.g.

var jsf = require('json-schema-faker');
var fakePattern = jsf.compile(schemaObject);
var fakeObject1 = fakePattern();
var fakeObject2 = fakePattern()
var fakeObject3 = fakePattern()

The first snippet analyses the schema each time, the second one does this only once - returns a reusable function.

Keep in mind, this is just a draft, it doesn't have to be `jsf.compile`

**Comment by pateketrueke** [comment]
I understand, so the `compile()` method would give us a `new Function()` of pure Javascript code, even this can be saved for later use, etc.

We need some code-generation behind the scenes, I'm right?

**Comment by ducin** [comment]
More or less, yes. But I was not thinking about a "pure" JavaScript (Vanilla JavaScript) function. I was thinking just of a closure that would just reuse everything that is already written.

**Comment by ducin** [comment]
I was thinking of something like turning

    {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "faker": "name.findName"
        },
        "email": {
          "type": "string",
          "faker": "internet.email"
        }
      },
      "required": [
        "name",
        "email"
      ]
    }

into:

    function(){
      return {
        name: faker.name.findName(),
        email: faker.internet.email()
      };
    }

How to do this - it depends on the current structure of JSF.

**Comment by pateketrueke** [comment]
I got it, I see this as a major improvement, so let's work on this on the next weeks. :beers:

**Comment by gausie** [comment]
It would also be good to have something like 

```
var jsf = require('json-schema-faker');
var fakePattern = jsf.compile(schemaObject);
var arrayOfFakes = fakePattern.take(3);
```

**Comment by ducin** [comment]
@gausie this would be a killer feature, but it needs quite a lot of development. I've been thinking about it quite much and I'm afraid we'd need to redesign/refactor quite a lot inside JSF. Of course, it's worth it, but we need more people to do that :) interested in contribution?

**Comment by gausie** [comment]
I would be interested. Once you've worked out how you want to refactor, happy to contribute.
