### ISSUE TITLE
Add the ability to unregister a format

### ISSUE THREAD

**Issue by whitlockjc** [json-schema-faker/json-schema-faker#440]
When `json-schema-faker` registers [custom formats](https://github.com/json-schema-faker/json-schema-faker#custom-formats), it uses a module-level store.  When testing things, it would be nice to be able to unregister custom formats.

**Comment by pateketrueke** [comment]
Gotcha, it'll be on time. Thank you!

**Comment by pateketrueke** [comment]
Fixed on `develop`. :bomb:

Now you can use `jsf.reset()` to remove all added extensions through `jsf.extend()` and `jsf.define()`.

Also, calling `jsf.format('example', null)` or `jsf.format({ example: null })` will remove that format.
