### ISSUE TITLE
OptionalsProbability not working as expected

### ISSUE THREAD

**Issue by Uttakarsh12** [json-schema-faker/json-schema-faker#443]
Schema is attached below please find attachment.

Request generated with :
1.**With probability 0.4**:

```json
{
 "name": {
  "name_value": "\"LkbDa5dQ\""
 }
}
```

2**.With probability 0.6**:

```json
{
    "name": {
        "name_value": "\"AcFa\"",
        "name_reference": {
            "user-name": {
                "cmd_no_form": true
            },
            "reauth-period": {
                "reauth-period": 68867713
            },
            "user-id-tagged": {
                "user-id-tagged_reference": {
                    "user-id-tagged": 3033
                }
            }
        }
    },
    "uri": "exercitat"
}
```

3.**With probability 0.8**:

```json
{
    "name": {
        "name_value": "\"d85mZtO\"",
        "name_reference": {
            "user-name": {
                "user-name_reference": {
                    "user": "in fugiat "
                }
            },
            "user-id-tagged": {
                "cmd_no_form": true
            },
            "reauth-period": {
                "reauth-period": 785284472
            }
        }
    },
    "uri": "aliqua culpa mollit officia sint"
}
```

4. **with probability 1.0**:

```json
{
    "name": {
        "name_value": "\"uixARLPJN\"",
        "name_reference": {
            "reauth-period": {
                "reauth-period": 345006932
            },
            "profile": {
                "cmd_no_form": true
            },
            "user-id": {
                "cmd_no_form": true
            },
            "user-id-tagged": {
                "cmd_no_form": true
            }
        }
    },
    "uri": "sunt sit anim Excepteur"
}
```

As you can see with any probability less than 0.5 it is generating request with only name value whereas at 0.6 it takes 3 additional properties from name-reference and same with 0.8 probability(there is no change in number of properties even after increasing the probability) and at 1.0 all the possible properties are included.

[title.docx](https://github.com/json-schema-faker/json-schema-faker/files/2131036/title.docx)

**Comment by pateketrueke** [comment]
Please attach the schema as a valid `.json` file, the document you've uploaded is bit broken.

Use the online editor to play and save your files: https://json-schema-faker.js.org/

**Comment by Uttakarsh12** [comment]
Try this schema

[title (1).docx](https://github.com/json-schema-faker/json-schema-faker/files/2135950/title.1.docx)

**Comment by pateketrueke** [comment]
Fixed on `develop`. 🍻
