### ISSUE TITLE
Example using $ref not working

### ISSUE THREAD

**Issue by Otto-AA** [json-schema-faker/json-schema-faker#453]
When using the example with refs from the README.md (in nodejs) the return sample is undefined.

Code from the README.md (https://github.com/json-schema-faker/json-schema-faker#using-references):
```javascript
const jsf = require("json-schema-faker"); // Added by me

var schema = {
  type: 'object',
  properties: {
    someValue: {
      $ref: 'otherSchema'
    }
  }
};

var refs = [
  {
    id: 'otherSchema',
    type: 'string'
  }
];

jsf.resolve(schema, refs).then(function(sample) {
  console.log(sample.someValue);
  // undefined instead of the expected random string ("voluptatem")
});
```

It throws no error or warning, but simply resolves with `undefined`.

**Environment**
Node: 8.11.3
JSF: 0.5.0-rc15

**Comment by pateketrueke** [comment]
Definitely an issue, if we enable `optionalsProbability` as `0.5` works, also if we enable `alwaysFakeOptionals`.

Both are workarounds but the default behavior should, eventually, generate a value.

Thank you for submitting this, I'll be addressing this asap.

**Comment by pateketrueke** [comment]
Fixed on `develop`. ✌️
