### ISSUE TITLE
[Feature Request] Custom async format

### ISSUE THREAD

**Issue by Otto-AA** [json-schema-faker/json-schema-faker#454]
## Feature request
A custom format which is handled asynchronously. (Indicated by returning a promise / accepting a `done` parameter)
```javascript
jsf.format('asyncId', function() {
  return new Promise((resolve, reject) => resolve('id'));
});
```

## Use case
In my case, I would use it to save a mongoose document to a database and then return the id of it. This way other models who reference this can be tested with valid ids.

## Workarounds
(1) Use some specifier (e.g. `"__Mongoose_User_Id"`) for jsf and modify the created schema afterwards.
(2) Wait until all asynchronous formats are resolved before calling `jsf.resolve` and somewhere store these values. JSF has synchronous format functions which then return these stored values.

Edit: I haven't tested them, but at least the principle behind these workarounds should work:
- [Helper class][helperClass]
- [jsf.resolve wrapper][wrapper]

I would like to hear your thoughts about it :)

[wrapper]: http://www.typescriptlang.org/play/#src=%2F%2F%20%40ts-ignore%0D%0Aimport%20jsf%20from%20%22json-schema-faker%22%3B%0D%0A%0D%0Aclass%20JsfAsyncFormatWrapper%20%7B%0D%0A%20%20%20%20private%20asyncFormatters%20%3D%20%7B%7D%3B%0D%0A%20%20%20%20private%20jsf%3B%0D%0A%0D%0A%20%20%20%20constructor(jsf)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.jsf%20%3D%20jsf%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20addAsyncFormat(name%3A%20string%2C%20func%3A%20()%20%3D%3E%20any)%20%7B%0D%0A%20%20%20%20%20%20%20%20this.asyncFormatters%5Bname%5D%20%3D%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20calc%3A%20func%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20returnValue%3A%20undefined%0D%0A%20%20%20%20%20%20%20%20%7D%3B%0D%0A%20%20%20%20%20%20%20%20this.jsf.format(name%2C%20()%20%3D%3E%20this.getResolved(name))%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20async%20resolve(...args)%20%7B%0D%0A%20%20%20%20%20%20%20%20await%20this.resolveAsyncFormatters()%3B%0D%0A%20%20%20%20%20%20%20%20return%20this.jsf.resolve(...args)%3B%20%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20private%20async%20resolveAsyncFormatters()%20%7B%0D%0A%20%20%20%20%20%20%20%20for%20(const%20key%20in%20this.asyncFormatters)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.asyncFormatters%5Bkey%5D.returnValue%20%3D%20await%20this.asyncFormatters%5Bkey%5D.calc()%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20private%20getResolved(name)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.asyncFormatters%5Bname%5D.returnValue%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20Usage%0D%0Aconst%20schema%20%3D%20%7B%0D%0A%20%20%20%20%22type%22%3A%20%22string%22%2C%0D%0A%20%20%20%20%22format%22%3A%20%22asyncTest%22%0D%0A%7D%3B%0D%0A%0D%0Aconst%20asyncFormatWrapper%20%3D%20new%20JsfAsyncFormatWrapper(jsf)%3B%0D%0AasyncFormatWrapper.addAsyncFormat('asyncTest'%2C%20asyncTest)%3B%0D%0A%0D%0AasyncFormatWrapper.resolve(schema)%0D%0A%20%20%20%20.then(val%20%3D%3E%20console.log(%60resolved%20val%3A%20%24%7Bval%7D%60))%3B%0D%0A%0D%0A%0D%0Afunction%20asyncTest()%20%7B%0D%0A%20%20%20%20return%20Promise.resolve(%22Hello%20from%20the%20asynchronous%20world%22)%3B%0D%0A%7D

[helperClass]: http://www.typescriptlang.org/play/#src=%2F%2F%20%40ts-ignore%0D%0Aimport%20jsf%20from%20%22json-schema-faker%22%3B%0D%0A%0D%0Ainterface%20AsyncFormat%20%7B%0D%0A%20%20%20%20resolve%3A%20()%20%3D%3E%20Promise%3Cany%3E%3B%0D%0A%20%20%20%20returnValue%3A%20any%3B%0D%0A%7D%0D%0A%0D%0Aclass%20JsfAsyncFormats%20%7B%0D%0A%20%20%20%20private%20asyncFormats%3A%20AsyncFormat%5B%5D%20%3D%20%5B%5D%3B%0D%0A%0D%0A%20%20%20%20public%20registerAsSync(func%3A%20()%20%3D%3E%20any)%3A%20()%20%3D%3E%20any%20%7B%0D%0A%20%20%20%20%20%20%20%20this.asyncFormats.push(%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20Promise.resolve(func)%2C%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20returnValue%3A%20undefined%0D%0A%20%20%20%20%20%20%20%20%7D)%3B%0D%0A%0D%0A%20%20%20%20%20%20%20%20return%20()%20%3D%3E%20this.getResolved(this.asyncFormats.length%20-%201)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20public%20resolveAll()%3A%20Promise%3Cany%5B%5D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20Promise.all(%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20this.asyncFormats.map(asyncFormat%20%3D%3E%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20return%20asyncFormat.resolve()%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.then(val%20%3D%3E%20asyncFormat.returnValue%20%3D%20val)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D)%0D%0A%20%20%20%20%20%20%20%20)%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20private%20getResolved(index)%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20this.asyncFormats%5Bindex%5D.returnValue%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%0D%0A%2F%2F%20Usage%0D%0Aconst%20asyncFormats%20%3D%20new%20JsfAsyncFormats()%3B%0D%0Ajsf.format('asyncTest'%2C%20asyncFormats.registerAsSync(asyncTest))%3B%0D%0A%0D%0Aconst%20schema%20%3D%20%7B%0D%0A%20%20%20%20%22type%22%3A%20%22string%22%2C%0D%0A%20%20%20%20%22format%22%3A%20%22asyncTest%22%0D%0A%7D%3B%0D%0A%0D%0A%0D%0AasyncFormats.resolveAll()%0D%0A%20%20%20%20.then(()%20%3D%3E%20jsf.resolve(schema))%0D%0A%20%20%20%20.then(val%20%3D%3E%20console.log(%60resolved%20val%3A%20%24%7Bval%7D%60))%3B%0D%0A%0D%0Afunction%20asyncTest()%20%7B%0D%0A%20%20%20%20return%20Promise.resolve('Hello%20world')%3B%0D%0A%7D%0D%0A%0D%0A

**Comment by Otto-AA** [comment]
I've made a little helper class for this now: https://repl.it/@Otto_AA/JSF-Async-Formats

It works good enough, but I'd prefer it if it was done automatically by JSF :wink:

**Comment by pateketrueke** [comment]
Awesome! TBH I thought on this several time ago. If you ask me, surely I want to see this too!

Let me check out this at detail, it'll require a huge refactor I guess. 🍻

**Comment by Otto-AA** [comment]
Glad that you like the idea!

Btw, I've found out that the same principle works for `jsf.extend`: https://repl.it/@Otto_AA/JSF-Async-Extends

**Comment by Otto-AA** [comment]
> Let me check out this at detail, it'll require a huge refactor I guess.
_I'm not familiar with your code, so it may or may not be helpful_

One way which likely doesn't require huge refactoring would be to iterate through the schema in advance, calculate the outputs (string, number, Promise, etc.) of all random functions and store them somehow. Then wait for all promises  to resolve and replace the generate function with `() => resolvedOutput`. So the asynchronous part is replaced with synchronous functions for further processing.

Or, instead of resolving to values in the main function, resolve to `() => Promise` functions and after the whole processing resolve all values.

Hope this helps ;)

**Comment by Otto-AA** [comment]
Refactoring it to a structure like this could be helpful:
(1) Create structure (e.g. expanding arrays with min-max)
(2.1) Calculate all synchronous values 
(2.2) Get promises for the asynchronouse values
(2.3) Wait until all Promises are resolved
(3) Apply checks (if there are some)

Would this work with this project?

**Comment by pateketrueke** [comment]
> Would this work with this project?

Yeah, it should work.

I also want v5 to be full-async so I'm planning a full cleanup/rewrite.

AFAIK the traversing stuff is sync at this moment, so, changing that API would work fine.

Want to work on a more elaborate PR or it's fine to you to wait 'till v5 lands on?

**Comment by Otto-AA** [comment]
I'm fine with waiting for v5, as my helper class will suffice for my project. (I will also update it to work with placeholders, so some drawbacks from current helper class will be resolved). Also it probably wouldn't make much sense to add this before refactoring?

**Comment by pateketrueke** [comment]
All resources are welcome, even if they're not integrated they're source of knowledge for me.

Thank you.

**Comment by Otto-AA** [comment]
I think I'll go with this version in the meantime: https://repl.it/@Otto_AA/JSF-Async-Extends-Placeholder

The advantages above the others are:
- the async generator is only called if really needed (beneficial for my database tests)
- one can use instances (e.g. for creating multiple users in the same schema)

Still I am looking forward to the feature being added to jsf ;)

**Comment by pateketrueke** [comment]
I think using `async/await` for this will suffice.

**Comment by Otto-AA** [comment]
What would be the difference between "extend" and "keyword" then?

**Comment by pateketrueke** [comment]
- `define()` method will hook custom keywords, [that way is implemented the `pattern` keyword](https://github.com/json-schema-faker/json-schema-faker/blob/master/ts/index.ts#L115-L160) as example. _Keywords_ are those with an special meaning in JSON-Schema, e.g. `type`, `properties`, `multipleOf`, etc.

- `extend()` method will hook custom generators (like faker, chance, etc.) as keywords. This is meant for third party generator only, or anything that can invoked the same way.

- `format()` will register only custom formats, that will work only for `string` types. This can't be async because formatting should work with scalar values only.

**Comment by pateketrueke** [comment]
I think `format` should be sync, otherwise it cannot be used by `jsf.generate()` and it should work as it's pretty simple.
