### ISSUE TITLE
Error thrown when defining object with property called "pattern"

### ISSUE THREAD

**Issue by kylef** [json-schema-faker/json-schema-faker#458]
Given the following schema:

```json
{
  "type": "object",
  "properties": {
    "pattern": {
      "type": "string"
    }
  },
  "required": ["pattern"]
}
```

JSON Schema Faker (0.5.0-rc15) is throwing an error `Expected a regexp or string in /`.

**Comment by pateketrueke** [comment]
Good catch, definitely a bad one.

I'm gonna work on all of this asap, thank you for your feedback.

**Comment by pateketrueke** [comment]
Fixed on `develop`
