### ISSUE TITLE
String maxLength is ignored after 0.5.0-rc12 

### ISSUE THREAD

**Issue by GrahamWalters** [json-schema-faker/json-schema-faker#467]
`maxLength` is being ignored with type `["string", "null"]` in 0.5.0-rc15. Type `"string"` works as expected.

### Input
```json
{
  "type": "object",
  "properties": {
    "user": {
      "type": "object",
      "properties": {
        "name": {
          "type": [
            "string",
            "null"
          ],
          "maxLength": 10
        }
      },
      "required": [
        "name"
      ]
    }
  },
  "required": [
    "user"
  ]
}
```

#### `0.5.0-rc15` generates a string longer than 10 characters:
```json
{
  "user": {
    "name": "amet reprehenderit tempor aliquip"
  }
}
```

#### `0.5.0-rc12` works as expected:
```json
{
  "user": {
    "name": "ve"
  }
}
```

**Comment by pateketrueke** [comment]
Please review if this solves your issue: https://github.com/json-schema-faker/json-schema-faker/pull/464 😉

**Comment by pateketrueke** [comment]
Update: I lied to you, I did a quick test and seems it's really broken.

Thanks your for feedback, I'll be fixing this soon! 💣

**Comment by pateketrueke** [comment]
Fixed on `develop`. 🎉
