### ISSUE TITLE
is posible to specify "examples" as fake source?

### ISSUE THREAD

**Issue by glpunk** [json-schema-faker/json-schema-faker#468]
Hi, this is a question actually: 

When yo use https://jsonschema.net/ to generate schema, it put a "examples" property as sample data: 

`{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "width",
    "height"
  ],
  "properties": {
    "width": {
      "$id": "#/properties/width",
      "type": "integer",
      "title": "The Width Schema",
      "default": 0,
      "examples": [
        5
      ]
    },
    "height": {
      "$id": "#/properties/height",
      "type": "integer",
      "title": "The Height Schema",
      "default": 0,
      "examples": [
        10
      ]
    }
  }
}`

Is posible to indicate the faker to use this property as source? of course in this case the result will be always the same. 

I saw something like use choice.pickone, but the schema is different. I am beginner with node/javascript, so excuse me if the question is too much noob. 

Very nice module! best regards.

**Comment by pateketrueke** [comment]
Yeah, it's already implemented through `useExamplesValue` on the `develop` branch.

It'll be released soon, any feedback there is very appreciated: https://github.com/json-schema-faker/json-schema-faker/pull/464

**Comment by glpunk** [comment]
Hi @pateketrueke thanks for your fast response. I'm testing right now and works like I needed/expected,

If I found something I will feedback as you suggest.

amazing! thank you.
