### ISSUE TITLE
Add format UUID support

### ISSUE THREAD

**Issue by MadRabbit** [json-schema-faker/json-schema-faker#469]
Hey there,

Firstly, thanks for the awesome library, it's a joy to use!

Secondly, i think we've found a room for improvement. Apparently the new JSON Schema spec has new format option `"uuid"`, for example:

```
{
  "type": "string",
  "format": "uuid"
}
```

Would be awesome if you could add support for this thing, because right now json-schema-faker explodes with this:

```
Error: unknown registry key "uuid" in /properties/id
      at run (node_modules/json-schema-faker/lib/index.js:1381:19)
      at jsf (node_modules/json-schema-faker/lib/index.js:1424:12)
.....
```

❤️ your work

**Comment by pateketrueke** [comment]
Thank you!

I think we could add that format as built-in, but it would be better not just adding one, do you mind on something else?

**Comment by MadRabbit** [comment]
Oh, i'm mostly concerned about the thing exploding, that's pretty much it. i'm using `"faker": "random.uuid"` option to generate the actual value. so as long as it stops failing, i'm a happy camper ;)

**Comment by pateketrueke** [comment]
I think it's fixed now on `master`... I just added a few. 🍻
