### ISSUE TITLE
Properties missing / object randomly appearing empty

### ISSUE THREAD

**Issue by kace91** [json-schema-faker/json-schema-faker#472]
Using the last version of the library, with the option to always generate optional parameters, I still get missing properties - object elements whose parameters aren't generated. Also, half the time the example generated is just {}.

That result isn't present in earlier versions of the library - 0.5.0-rc1 seems to behave well for example.

Pasting this schema in the online tool and generating examples several times will show what I mean:

```
{
    "$id": "application/json",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "Autogenerated schema from MCType",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "data": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "aPropertyIMadeUp": {
                    "type": "string"
                },
                "anotherProperty": {
                    "type": "object",
                    "properties": {
                        "yetAnotherProperty": {
                            "type": "string",
                            "enum": ["CCC", "IBAN", "SWIFT", "CLABE", "LIC", "RN", "CCI", "CBU"]
                        },
                        "name": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false,
                    "required": []
                },
                "thisIsSomethingElse": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "yetAnotherProperty": {
                            "type": "string",
                            "enum": ["COMMON", "CREDIT", "CREDIT_EXTENSION", "SAVINGS", "MONEY_MARKET", "SAVINGS_EXTENSION"]
                        },
                        "name": {
                            "type": "string"
                        }
                    },
                    "required": []
                },
                "accountType": {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "yetAnotherProperty": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        }
                    },
                    "required": ["yetAnotherProperty"]
                }
            },
            "required": ["aPropertyIMadeUp", "anotherProperty"]
        }
    },
    "required": []
}
```

**Comment by kace91** [comment]
@pateketrueke Hi, I tried your tip and it mostly works, thank you! However, there's a case where I'm still not getting the desired results... Setting on the 'alwaysFakeOptionals' option causes some of my schemas to always return an empty array. 

Here's an example you can try on the website, where setting on/off the mentioned property can trigger the effect:

```
{
    "$id": "data",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "description": "blablabla",
    "type": "array",
    "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "one": {
                "type": "string"
            },
            "two": {
                "type": "string"
            },
            "three": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "id": {
                        "type": "string",
                        "enum": ["ENUM1"]
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": ["id", "name"]
            },
            "four": {
                "anyOf": [{
                    "type": "string",
                    "pattern": "^(\\d{4})-(\\d{2})-(\\d{2})$"
                }, {
                    "type": "string"
                }]
            }
        },
        "required": ["one", "two", "three", "four"]
    }
} 


```

Is there anything I've missed? I can't see why optionals affect arrays in that way, and the basic array example  (N-TimesRepeated) is not affected by this potential bug for some reason

**Comment by pateketrueke** [comment]
It's fixed now but it won't be released soon, the bug was that `minItems/maxItems` were undefined (which is fine), but when `alwaysFakeOptionals` gets enabled those undefined values produce NaN and hence it not works as expected.

I think you can set `minItems/maxItems` within your array schema to solve this.

**Comment by skipjack** [comment]
@pateketrueke I'm seeing the same issue on `^0.5.0-rc16` with the following configuration:

``` js
SchemaFaker.option({
    resolveJsonPath: true,
    alwaysFakeOptionals: true,
    minItems: 1,
    maxItems: 1,
    optionalsProbability: 1
})
```

`alwaysFakeOptionals` and `minItems` are not behaving as they did in previous versions. Glad to hear this was resolved though. Is #481 almost there now or is that release still a ways off?

**Comment by pateketrueke** [comment]
I hope it so, can you help us to test if this is fixed as you expected?

**Comment by skipjack** [comment]
Ok so I think I set up local testing correctly. I used the steps above and rebuilt anytime I changed the code. _Sidenote:_ It would be nice if there was a `watch` script for local testing that keeps rebuilding when files are saved.

It seems `alwaysFakeOptionals` is fixed but only works when `fixedProbabilities` is set to `true`. Can you elaborate on `fixedProbabilities` a bit? I read the docs:

> If enabled, then `optionalsProbability: 0.5` will always generate the half of values (default: `false`)

But I don't understand the use case. If someone sets `optionalsProbability` or `alwaysFakeOptionals` (which just sets `optionalsProbability` behind the scenes), wouldn't they always want `optionalsProbability` to be respected?

**Comment by pateketrueke** [comment]
`optionalsProbability` is not FIXED, this means you'll get _random probabilities_ within given limits.

If you enable `fixedProbabilities: true` then always you'll get the same probabilities.

**Comment by skipjack** [comment]
Ok, I see now. Had to reread the `optionalsProbability` description. So maybe `alwaysFakeOptionals` should set both `optionalsProbability` to `1` and set `fixedProbabilities` to `true`? Otherwise the `generate` method won't _always fake optional_ properties/items right?

**Comment by pateketrueke** [comment]
> So maybe alwaysFakeOptionals should set both optionalsProbability to 1 and set fixedProbabilities to true? Otherwise the generate method won't always fake optional properties/items right?

That is actually my bet about the meaning of `alwaysFakeOptionals` for sure.

If you agree probably I'll update the behavior before releasing.
