### ISSUE TITLE
Latest release `v0.5.0-rc16` modifies input parameter

### ISSUE THREAD

**Issue by ehmicky** [json-schema-faker/json-schema-faker#473]
Since `v0.5.0-rc16` a `thunk` property gets sometimes added to the input parameter. 

```js
const jsonSchemaFaker = require('json-schema-faker');

const schema = { type: 'object', properties: { prop: { oneOf: [{ type: 'string' }] } } };
const result = jsonSchemaFaker.generate(schema);
console.log(schema);
```

prints:

```js
{ type: 'object',
  properties: { prop: { thunk: [Function: thunk] } } }
```

I'm not sure if this indicates a bigger issue.

If `json-schema-faker` modifies input parameters (which is probably not intended), this would require caller to deep clone parameters to avoid mutations, which would significantly decrease performance.

**Comment by pateketrueke** [comment]
Totally agree, it should never mutate the given input.

Thanks for your feedback, I'll be fixing that asap.
