### ISSUE TITLE
Decimal number generated instead of integer

### ISSUE THREAD

**Issue by zposten** [json-schema-faker/json-schema-faker#474]
I recently upgraded from 0.3.6 to 0.5.0-rc16.  A schema that was working find previously, no longer generates integer IDs.

The schema:
```json
 {
   "type": "object",
   "required": ["users"],
   "properties": {
     "users": {
       "type": "array",
       "minItems": 1,
       "maxItems": 1,
       "items": {
         "type": "object",
         "required": ["id"],
         "properties": {
           "id": {
             "type": "number",
             "chance": {
              "integer": {
                "min": 30,
                "max": 99999999
              }}}}}}}}
```

An alternative schema (only specifying the id property, the rest is the same), that generates an identical **incorrect** result is:

```json
"id": {
  "type": "number",
  "unique": true,
  "minimum": 1
}
```

The result generated with 0.5.0-rc16:

```json
{
  "users": [
    {
      "id": 81140660.65164801
    }
  ]
}
```

I'm expecting the id property to be filled with an integer, not a decimal number.

**Comment by pateketrueke** [comment]
Just use `"type": "integer"` instead. 👍

**Comment by zposten** [comment]
You know, that makes a lot of sense.  I had just assumed that since it "worked" with an earlier version it should work now.  Thank you @pateketrueke!
