### ISSUE TITLE
How to duplicate a local value

### ISSUE THREAD

**Issue by zposten** [json-schema-faker/json-schema-faker#475]
My goal is to make a field which is a duplicate of the `"id"` field, with a different name.  I have read through #11 and it looks like with the current 0.5.0-rc16 (since rc12), this should be possible using local references.  

Using the specific example provided in #11, I can get local references to work using faker and an email, but I cannot get them to work for what seems like the simplest case, duplication.

A simple key-value in the schema, `"idCopy": "#{id}"`,  generates static text output instead of substituting the local value, `"idCopy": "#{id}"`

[Here](https://gist.github.com/zposten/0d90d78998ca505d545319a778589909) is the full schema that fails on [json-schema-faker.js.org](https://json-schema-faker.js.org/).

Then I tried creating a custom extension in order to copy the value.  The extension method was getting called, but the parameter it gets called with is always `undefined`.

```json
// (partial) schema
"idCopy": {
  "type": "string",
  "custom": {
    "copy": "#{id}"
  }
}
```

```js
// config
import jsf from 'json-schema-faker'
let custom = { copy: val => val }
jsf.extend('custom', () => custom)
```
```json
// output
{
  "id": 35268306,
  "idCopy": "undefined",
  "firstName": "Andreane",
  "lastName": "McKenzie",
  "email": "Andreane99@gmail.com"
}
```

This seems like a bug, but I could just be doing it wrong.  If so, I apologize in advance!

**Comment by zposten** [comment]
I'm so baffled.  This just started working for me.  I'm sorry for wasting your time.

**Comment by pateketrueke** [comment]
Hi there's no waste of time, on `rc16` we added a `template` keyword for handle simple cases without extending:

```json
{
  "type": "object",
  "properties": {
    "foo": {
      "type": "string"
    },
    "bar": {
      "template": "#{foo}"
    }
  },
  "required": ["foo", "bar"]
}
```

I think the only side-effect here is that it copies values as strings, but it can be refined on time.

Thanks for your feedback!
