### ISSUE TITLE
Override default  format "date-time"

### ISSUE THREAD

**Issue by boredland** [json-schema-faker/json-schema-faker#483]
1. the JSON Schema content that fails:
```
{
  "occurredAt": {
    "type": "string",
    "format": "date-time"
  }
}
```
2. the result I got:
```
{
  "occurredAt": "1994-10-28T10:33:32.900Z"
}
```
3. the result I expected:
```
{
  "occurredAt": "1994-10-28T10:33:32.9Z"
}
```
The problem is, that for some reason I expect trailing zeros in dates, but apparently the default for date-time keeps them. Is there a method to override the default handling with sth like `.replace(/0+Z/gm,"Z")`?

**Comment by pateketrueke** [comment]
Actually there's no way to re-format a generated value, at least not from the outside.

I'm not sure if what you're looking for is standard or not, is up to you, but of course you can override default formatters:

```js
jsf.format('date-time', () => {
  return new Date().toISOString().replace(/0+Z$/g, 'Z');
});
```

The only problem is that you must generate the value by hand, there is no way yet to re-format already generated values.

A more radical option is: if you convince me trailing zeros are optional, and are completely valid I could add that fix over generated `date-time` values.

PS: I already tested and seems like trailing zeros are optional, so may I add the fix?

**Comment by boredland** [comment]
I would appreceate that!

**Comment by pateketrueke** [comment]
Cool, fixed on the current PR for RC17!
