### ISSUE TITLE
Default value not working.

### ISSUE THREAD

**Issue by GhostNr1** [json-schema-faker/json-schema-faker#485]
When I use default I thought it was starting from that number. The same with autoincrement. 
I'm using 0.5.0-rc16

My schema:
`{
  "type": "object",
  "properties": {
    "id2": {
      "type": "integer",
      "minimum": 1,
      "default": 1,
      "autoIncrement": true
    },
    "sent": {
      "type": "array",
      "minItems": 10,
      "maxItems": 10,
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1,
            "default": 1,
            "autoIncrement": true
          }
        }
      },
      "required": ["id"]
    }    
  },
  "required": ["sent", "id2"]
}`

My result
`{
	"sent" : [{
			"id" : 5285166
		}, {
			"id" : 61491617
		}, {
			"id" : 76941539
		}, {
			"id" : 91165587
		}, {
			"id" : 39869491
		}, {
			"id" : 40555773
		}, {
			"id" : 48449552
		}, {
			"id" : 68691122
		}, {
			"id" : 38389376
		}, {
			"id" : 57767587
		}
	],
	"id2" : 75993346
}
`

Expected outcome:
{
	"sent" : [{
			"id" : 1
		}, {
			"id" : 2
		}, {
			"id" : 3
		}, {
			"id" : 4
		}, {
			"id" : 5
		}, {
			"id" : 6
		}, {
			"id" : 7
		}, {
			"id" : 8
		}, {
			"id" : 9
		}, {
			"id" : 10
		}
	],
	"id2" : 1
}

**Comment by pateketrueke** [comment]
You must enable `useDefaultValue` either on the web-app, or with code: `jsf.option({ useDefaultValue: true })` to make it work.

**Comment by GhostNr1** [comment]
If I add that flag then all my Ids get 1 instead of increment. But that might be intended? Would be good to have a starting point and increment from that number?

**Comment by pateketrueke** [comment]
Yeah, `default` meaning is just that: returns the given value.

Try `initialOffset` which is a special keyword we added for companion of `autoIncrement`, e.g.

```json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer",
        "initialOffset": 1,
        "autoIncrement": true
      }
    }
  }
}
```
