### ISSUE TITLE
Generating invalid string data on regex pattern

### ISSUE THREAD

**Issue by rafamel** [json-schema-faker/json-schema-faker#486]
For:

```javascript
jsf.option({ alwaysFakeOptionals: false, requiredOnly: true });
jsf.generate({
  type: 'string',
  minLength: 8,
  maxLength: 20,
  pattern: '^[a-zA-Z0-9_]+$'
 });
```

I'm getting strings like `kzF kzF kzF kzF` (with spaces) on `json-schema-faker@0.5.0-rc16`

**Comment by pateketrueke** [comment]
Good catch!

Seems like adding `minLength` produce bad values.

That occurs because the all generator will try to fill the given constraints, and in this case, is generating some random string just to fill `minLength` which is expected.

The thing, is we're using any string value, and we're not taking into account if `pattern` is given.

I'm going to solve this asap, thank you for your feedback!

**Comment by rafamel** [comment]
This is a simple enough regex, however, for a more complex regex, it would be good to not "extend" a string, but rather generate a string of any given length from the pattern itself -for any given regex. How do you currently generate strings from a pattern?

**Comment by pateketrueke** [comment]
We're using [randexp](https://www.npmjs.com/package/randexp) to generate random values from given patterns.

I agree with you that we must re-generate a value until it matches the given `minLength/maxLength` accordingly.

A simple loop for would be enough, right?

**Comment by rafamel** [comment]
Hi Alvaro, yeah, that's what I was pointing towards. That strategy will be valid for a subset of patterns, but not for all patterns. You need to take into account patterns don't necessarily just check for certain characters or numbers being used, but also their position. Take the regex `/^A[CD]{1,5}B$/`; say we want a 8 chars string: this pattern will match the string `"ACDDCCDB"`, but not `"ACDBACDB"`; hence, the string must be generated from the start taking the pattern into account, without the repetition strategy, for the desired length. This means the regex to string generation library should have a way to specify either the desired length, or a minimum/maximum length for the pattern. I believe this could be done by modifying the regular expression with a lookahead, but I doubt the library you're using supports it. I might make sense to open a FR issue/PR to the library so a min/max character range can be added as a requirement (there might be cases in which a range can't be fulfilled according to the pattern, in which case it should fail).

**Comment by pateketrueke** [comment]
How we deal with this?

```json
{
  "type": "string",
  "pattern": "A[CD]{1,6}B",
  "minLength": 6
}
```

Can patterns conflict with given constraints?

**Comment by rafamel** [comment]
Yeah, precisely my point. In this case the `pattern` and the `minLength` cannot be satisfied at the same time and the data generation should throw an error.

**Comment by pateketrueke** [comment]
The only way to know if something is impossible to fulfill is through validation, and certainly we don't validate input schemas.

User is encouraged to provide valid schemas, otherwise will be harder to fake something valid.

I'll try a simple loop before asking for changes to third-party dependencies.

So much thank for your feedback!

**Comment by rafamel** [comment]
Hi Alvaro. Unfortunately, as I pointed out earlier in the conversation, that strategy will not work for most regex patterns. There are several distinct cases that I might have failed to separate adequately when making the points:

* When the schema **is valid** and the loop strategy **is valid:** this is the case for regex `/^[a-zA-Z0-9_]+$/` coupled with any `minLength` or `maxLength`, as it doesn't contain any inner constraints length for a specific set of characters.
* When the pattern **is valid** but the loop strategy **is not valid:** this is the case for the regex `^A[CD]{1,6}B$` coupled with any `minLength` and/or `maxLength` that allows the string to have at least one of between 3 and 8 characters (as an example, a value of 8 for `minLength` will allow only a string of 8 characters, as the pattern itself cannot have more than 8 characters; in this case, the resulting string can **only** have 8 chars; while with a value of 7, the resulting string could have 7 or 8 characters, and so on). As you can see here, a random length generated string might look like `"ACDB"`; if we want a string with 6 characters, we couldn't extend the pattern and do `"ACDBAC"` or `"ACDBDB"`, those will be invalid, as only the characters `C` and `D` are allowed in the inner positions of the pattern, for a minimum of 1 and a maximum of 6. Therefore, the loop strategy will always provide an invalid string for this valid schema.
* When the pattern **is not valid** because the `minLength` and/or the `maxLength` cannot be fulfilled for the regex: this is the case for the regex `^A[CD]{1,6}B$` coupled with any `minLength` and/or `maxLength` that forces the string to have less than 3 or more than 8 characters.

**Comment by pateketrueke** [comment]
AFAIK randexp does not have a way to specify the desired length of any given expression, it has a MAX constant but is for patterns like `.*` where it can take too much time/space for.

But for the pattern `^A[CD]{1,6}B$` I don't see a way to tell that to the library, if a simple loop would not suffice, what other strategies could we take on this?

**Comment by BobCochran** [comment]
I'm experiencing this issue also: it is repeatable for me. I need to study regular expressions more to thoroughly understand what @rafamel is saying in his excellent discussion. I also need to get more experience with this API and with Faker.js as well; I've only just started using it. 

`$ node --experimental-modules rafamel_test.mjs
(node:2506) ExperimentalWarning: The ESM module loader is experimental.
8B 8B 8B 8B
$ node --experimental-modules rafamel_test.mjs
(node:2517) ExperimentalWarning: The ESM module loader is experimental.
lxVr6zizlw
$ node --experimental-modules rafamel_test.mjs
(node:2528) ExperimentalWarning: The ESM module loader is experimental.
3mZ58sPDq4
$ node --experimental-modules rafamel_test.mjs
(node:2539) ExperimentalWarning: The ESM module loader is experimental.
4 4 4 4 4 4 4 4
------
$ node --version
v10.14.2
----
from package-lock.json: json-schema-faker-0.5.0-rc16`

**Comment by pateketrueke** [comment]
Thanks for your interest on this topic, definitely a complicated one.

I'll be trying simple solutions on this while we receive more feedback.

**Comment by pateketrueke** [comment]
Yeah, I finally agree; for `pattern` stuff the best is that `randexp` supports it.

I think I'll open an issue to get some feedback too, thank you!
