### ISSUE TITLE
"title" not being treated as an annotation keyword

### ISSUE THREAD

**Issue by Edward-Knight** [json-schema-faker/json-schema-faker#489]
JSON Schema:
```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "patternProperties": {
    "test": {
      "type": "null"
    }
  },
  "properties": {
    "test": {
      "title": "short description"
    }
  },
  "required": ["test"]
}
```

Generated example:
```javascript
{
  "test": {
    "title": "short description"
  }
}
```

Expected result:
```javascript
{
  "test": null
}
```

**Comment by pateketrueke** [comment]
Why you're describing `test` both under `properties` and `patternProperties`?

What's the merge strategy for both subschemas?

**Comment by Edward-Knight** [comment]
As far as I'm aware, both subschemas should apply.
I provided a minimal example of a schema, perhaps a more reasonable example would be:
```javascript
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "patternProperties": {
    ".*_int$": {
      "type": "integer"
    }
  },
  "properties": {
    "big_int": {
      "title": "short description",
      "minimum": 100
    },
    "normal_int": {
      "title": "short description"
    },
    "small_int": {
      "title": "short description",
      "maximum": 100
    }
  },
  "required": ["big_int", "normal_int", "small_int"]
}
```

Generated example:
```javascript
{
  "big_int": 38892212,
  "normal_int": {
    "title": "short description"
  },
  "small_int": -69958968
}
```

Expected result:
```javascript
{
  "big_int": 38892212,
  "normal_int": 12345,
  "small_int": -69958968
}
```

**Comment by pateketrueke** [comment]
Excellent, so the main idea is pairing given `properties` with `patternProperties` as they match.

I think this is doable, let me check what can I do.

Thanks for your feedback!

**Comment by Edward-Knight** [comment]
No problem!

As well as the mis-pairing of `properties` and `patternProperties`, I believe (if I've understood the specification correctly), that the `title` field should be being completely ignored as it's an "annotation keyword".
