### ISSUE TITLE
jsf or jsf.generate is not defined

### ISSUE THREAD

**Issue by AlessandroCimarelli** [json-schema-faker/json-schema-faker#491]
Hello,
I integrated json-schema-faker.js into an html page, but I have a problem with the latest version.

in my code using version 4.2 I can get a correct response:

var parametersInput = d [body] ['parametersInputBody'];
var schemaConverter = jsf (parametersInput);
var body = JSON.stringify (schemaConverter, null, 3);

while if I use the latest version using the following code:

var parametersInput = d [body] ['parametersInputBody'];
var schemaConverter = jsf.generate (parametersInput);
var body = JSON.stringify (schemaConverter, null, 3);

I have as an error:

jsf not defined

With the new version, what function do I need to recall in order to have a correct response?

thank you
Alessandro

**Comment by pateketrueke** [comment]
The latest RC-16 exports itself as `window.JSONSchemaFaker` so you can use it:

```js
const jsf = window.JSONSchemaFaker;

console.log(jsf.generate(...));
```

**Comment by AlessandroCimarelli** [comment]
now it works properly
thank you
Alessandro
