### ISSUE TITLE
Tests helper is swallowing errors, schema tests potentially falsely-positive.

### ISSUE THREAD

**Issue by chris-miaskowski** [json-schema-faker/json-schema-faker#493]
I have forked your repository to add support for oas2 'example' field and when I add 'failing' tests to the suite I have noticed that they pass (`yarn test:schema`). I have investigated the issue and it looks like the helpers.js file is swallowing errors.

```js
  }).catch(error => {
    if (typeof test.throws === 'string') {
      expect(error).to.match(new RegExp(test.throws, 'im'));
      // added:
      // return;
    }

    if (typeof test.throws === 'boolean') {
      if (test.throws !== true) {
        throw error;
      }
    }
    // (I think) it should be 
   // else {
      // throw error;
   // }
  });
```

When added these lines in my fork it turned out a lot of the schema tests are failing. E.g:
- `description": "should handle time",`
- `optionalsProbability not recalculated for each record in an array?`

This is potentially a critical issue since may be covering hidden bugs.

Let me know if this is a good spot or if I'm doing something wrong.

**Comment by pateketrueke** [comment]
Hi, please share the test you trying to run, thank you!

**Comment by chris-miaskowski** [comment]
To reproduce simply 'unmute' errors in helpers.js and run yarn
test:schemas. Tests will fail. If you dont notice any failures I will post
a screenshot tmr.

śr., 20.02.2019, 18:12: Alvaro Cabrera Durán <notifications@github.com>
napisał(a):

**Comment by pateketrueke** [comment]
I tried your changes and effectively few errors appeared, I got 6 errors so far.

**Comment by chris-miaskowski** [comment]
Yup, that's the issue! :)

śr., 20.02.2019, 23:39 użytkownik Alvaro Cabrera Durán <
notifications@github.com> napisał:

**Comment by pateketrueke** [comment]
I've patched this on the `develop` branch, could you push the changes and try your tests again?

**Comment by pateketrueke** [comment]
I think this is done as `develop` seems stable now.
