### ISSUE TITLE
Empty object returned for a complex schema

### ISSUE THREAD

**Issue by constantOut** [json-schema-faker/json-schema-faker#494]
Hello guys, awesome work !!!
This issue isn't much of problem for me, but I thought project might benefit from having additional test cases.
1. the JSON Schema content that failed : 
`https://github.com/mParticle/mparticle-firehose-java-sdk/blob/master/examples/json/EventProcessingRequest.json`
2. the result you got : 
`{}`
3. the result you expected: 
Well, here goes an example `https://github.com/mParticle/mparticle-firehose-java-sdk/blob/master/examples/json/EventProcessingRequest.json`

**Comment by pateketrueke** [comment]
That schema does not look valid, or at least, seems like is not following any spec.

Valid schemas are in: https://github.com/mParticle/mparticle-firehose-java-sdk/tree/master/examples/json/schema

Is one from them?

**Comment by constantOut** [comment]
Well, for https://github.com/mParticle/mparticle-firehose-java-sdk/blob/master/examples/json/schema/EventProcessingRequest_schema.json same result

**Comment by pateketrueke** [comment]
The schema looks fine, just enable `alwaysFakeOptionals` to generate the values.

This is because that schema does not have any `required` properties, which is fine, but in this case they're used for populate the generated objects.

IMO it should not be necessary to enable `alwaysFakeOptionals`, so I'll recheck how we're solving them; btw, the schema you provided produce a nice bug after several runs, so I'll be working from there...

So much thanks for your feedback!

**Comment by vitorcamachoo** [comment]
+1

**Comment by pateketrueke** [comment]
This is working on the latest RC-16 published, which version are you using?

Also, please share some code from any reference/subschema used to understand better.

**Comment by vitorcamachoo** [comment]
Im using the latest available version v0.5.0-rc15. Since the momento I define `alwaysFakeOptionals: true` or `optionalsProbability: 1`, it returns empty.

**Comment by pateketrueke** [comment]
Please upgrade and retry, also try first on the online webapp to figure out: if it works there then you must use the latest RC-16 instead.

**Comment by vitorcamachoo** [comment]
I've tried online with the following schema and it don't work https://gist.github.com/vitorcamachoo/138b62828cb307a4830e38e2cd5588ce

**Comment by pateketrueke** [comment]
Interesting, I just tried the same schema and worked: https://json-schema-faker.js.org/#gist/4c3445871d86160b15cf1b334e9fc8b2

This time I did not enabled that options because the schema had `required` fields.

**Comment by vitorcamachoo** [comment]
If you try with this schema, you will see two empty arrays (current, escrow):
```json
{
  "account-response": {
    "title": "Account Response",
    "type": "object",
    "properties": {
      "current": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/current-account"
        }
      },
      "escrow": {
        "type": "array",
        "items": {
          "$ref": "#/definitions/current-account"
        }
      }
    },
    "required": [
      "current"
    ]
  },
  "definitions": {
    "current-account": {
      "title": "Current Account",
      "type": "object",
      "properties": {
        "number": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "balance": {
          "type": "number"
        },
        "currency": {
          "type": "string"
        }
      },
      "required": [
        "number",
        "name",
        "balance",
        "currency"
      ]
    }
  }
}
```

**Comment by pateketrueke** [comment]
Gotcha! Yeah, after enabling `alwaysFakeOptionals` both values are gone.

I need time to investigate this, so much thanks for your feedback!
