### ISSUE TITLE
BUG jsf.option('key', 'value') does not work

### ISSUE THREAD

**Issue by fogine** [json-schema-faker/json-schema-faker#496]
Documentation defines that its possible to set options in the following format:  

```javascript

jsf.option('optionName', 'value');
jsf.option({ optionName: 'value' });

```

When [looking at the code](https://github.com/json-schema-faker/json-schema-faker/blob/master/src/api/option.js#L13) Implementation actually supports only the second way of setting option value (that is through a map object)...

> jsf.option('optionName', 'value');

behaves like getter only, doesnt set the value

**Comment by pateketrueke** [comment]
Thank you, definitely it should work both ways!
