### ISSUE TITLE
Any option to generate always the same data?

### ISSUE THREAD

**Issue by vitorcamachoo** [json-schema-faker/json-schema-faker#497]
My question is, if there's any option to generate the same values, or any way on generation to know that exists a fixtures.json generated and only generate new fields that these file don't have. This is because we're using this file for test purposes and every time we generate the file, the values are different and we need to update snapshot every time (react environment).

**Comment by pateketrueke** [comment]
You can provide a _seed_ through the `random` option:

```js
jsf.option({ random: () => 0.42 });
```

Now, each time a value is generated will return the same based on this.

Just note that this will affect all generated values, play around with a list of seeds to generate more variations.
