### ISSUE TITLE
jfs.generate crashes with custom "format"

### ISSUE THREAD

**Issue by michaelyfan** [json-schema-faker/json-schema-faker#498]
_If you are reporting a bug, please include the following:_

_1. the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ (paste the schema, click `Generate example` and then copy and paste the resulting URL from the browser address bar)_

json-schema-faker.js.org is unfortunately not giving me a URL, but here is the schema content:
```
{
  "required": [
    "longitude"
  ],
  "type": "object",
  "properties": {
    "longitude": {
      "title": "Longitude",
      "type": "string",
      "format": "decimal"
    }
  }
}
```

This results in error `unknown registry key "decimal" in /properties/longitude` because this param has a `format` that `json-schema-faker` does not handle. This can be pasted into json-schema-faker.js.org to get the error.

As per the Swagger 2.0 specification, 

> ...the format property is an open string-valued property, and can have any value to support documentation needs.

I work with multiple clients that could give me any kind of swagger doc with any kind of format (`decimal`, `xyz`, `abra-cadabra`, etc...) , not necessarily limited to those specified by the Swagger spec, `email`, and `uuid`. 

_2. the result you got_

Running `jfs.generate` on this schema gives the error `unknown registry key "decimal" in /properties/longitude.

_3. the result you expected_

Running `jfs.generate` on this schema should result in fake data generated.

I understand that not all `format`s can be handled, since there's no way to predict what a client's swagger doc will have. But I think that if a `format` is not recognized, the faker should generate something that matches the param's type (in this case it's `string`) to best approximate fake data, instead of throwing an error.

**Comment by pateketrueke** [comment]
I like your idea of relaxing the unknown-formats, definitely not all formats are supported and can be a lot more!

So much thanks for your feedback, I'll be working on this asap!

**Comment by devagarwal007** [comment]
Hey I this fixed, seems not fixed beucase i am getting an error

C:\Test\Test\node_modules\json-schema-faker\dist\main.cjs:2213
          throw new Error(`unknown registry key ${utils_default.short(value.format)}`);
                ^
Error: Error while resolving schema (Error: unknown registry key "postal-code"

"zip_code": {
    "type": "string",
    "description": "The zip code or postal code",
    "format": "postal-code",
    "nullable": true,
    "example": "07093"
  }
  
  can you please help here?

**Comment by pateketrueke** [comment]
@devagarwal007 I see, the format for `postal-code` is not built-in on the library, feel free to add it on your code, see https://github.com/json-schema-faker/json-schema-faker/blob/master/docs/USAGE.md#custom-formats for reference.
