### ISSUE TITLE
Using jsonPath property in json schema returns a random string instead of the value in the given path

### ISSUE THREAD

**Issue by MarialenaShiamma** [json-schema-faker/json-schema-faker#499]
Hello, I am trying to test the `jsonPath `property from my JavaScript application which generates some mock data based on my mock schema. I have also tried to test `jsonPath` with the online https://json-schema-faker.js.org/ .  Using any of the above ways, the `jsonPath` returns a random string instead of the id I am referring to ( `"jsonPath": "$..properties.test.items.properties.id"`)

Validating the same schema using [this ](https://jsonpath.curiousconcept.com)site, causes no issues and the value I am trying to re-use is picked up correctly using the `jsonPath`.

Is there anything I should import in my JavaScript code/mock data generator to make this work, or what I am trying to do is not supported perhaps by my json-schema version?

Some of the paths I have tried to use are:
`$..id`
`$..test.items.properties.id`
`$..test.id`

This is my json schema:
```
{
  "title": "teest",
  "type": "object",
  "required": [
    "test"
  ],
  "properties": {
    "test": {
      "type": "array",
      "minItems": 1,
      "maxItems": 3,
      "uniqueItems": true,
      "items": {
        "type": "object",
        "required": [
          "id",
          "samples"
        ],
        "properties": {
          "id": {
            "type": "string",
            "enum": [
              "1,",
              "2",
              "3"
            ]
          },
          "samples": {
            "type": "array",
            "uniqueItems": true,
            "items": {
              "type": "object",
              "properties": {
                "test2": {
                  "type": "string",
                  "jsonPath": "$..properties.test.items.properties.id"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

What I get using the above schema is:
```
{
  "test": [
    {
      "id": "3",
      "samples": [
        {},
        {
          "test2": "eiusmod Duis"
        },
        {
          "test2": "qui reprehenderit ipsum eu nulla"
        }
      ]
    },
    {
      "id": "2",
      "samples": [
        {
          "test2": **"ipsum"**
        },
        {},
        {
          "test2": **"aute fugiat es"**
        }
      ]
    }
  ]
}
```

And what I am expecting to see is:
```
{
  "test": [
    {
      "id": "3",
      "samples": [
        {},
        {
          "test2": "eiusmod Duis"
        },
        {
          "test2": "qui reprehenderit ipsum eu nulla"
        }
      ]
    },
    {
      "id": "2",
      "samples": [
        {
          "test2": **"3"**
        },
        {},
        {
          "test2": **"3"**
        }
      ]
    }
  ]
}

```

**Comment by pateketrueke** [comment]
All `jsonPath` properties will be resolved after a sample is generated, so your paths MUST point to the generated result instead.

Using pointers to the schema itself will not work as you expected.

Also, I'm `uniqueItems` will take forever since the generated values can be fewer, try remove that property to see.

**Comment by pateketrueke** [comment]
I found the issue, you enumerated `1,` so that's the reason, also using `$..test[*].id` seems to be working too.

**Comment by pateketrueke** [comment]
But yeah, the `uniqueItems` constraint is too strong and the possible values are so few that can't be completed!

**Comment by MarialenaShiamma** [comment]
Thank you very much for your quick response.

I changed the schema to:

```
{
  "title": "teest",
  "type": "object",
  "required": [
    "test"
  ],
  "properties": {
    "test": {
      "type": "array",
      "minItems": 1,
      "maxItems": 3,
      "items": {
        "type": "object",
        "required": [
          "id",
          "samples"
        ],
        "properties": {
          "id": {
            "type": "string",
            "enum": [
              "1,",
              "2",
              "3"
            ]
          },
          "samples": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "test2": {
                  "type": "string",
                  "jsonPath": "$..test[*].id"
                }
              }
            }
          }
        }
      }
    }
  }
}
```

I removed the unique entries and the `jsonPath` refers to the generated output instead of the schema.

In https://json-schema-faker.js.org/ and my JavaScript code I still don't see this example working.

Is there anything i should do or am I doing something wrong?

Thanks again.

**Comment by pateketrueke** [comment]
Remember to enable `resolveJsonPath` option, either on the webapp UI (see options menu) or through code `jsf.option({ resolveJsonPath: true })`

Also remove `type` from properties using `jsonPath`, otherwise it'll not work: that's an issue, I'll be working on that asap.

**Comment by MarialenaShiamma** [comment]
Thanks for this.. I confirm that it is working in the online platform.

But it is not working in my javascript code. When i execute the script it shows `"jsonPath": "$..test[*].id"` instead of the value.

Here is the code that generates the schema.

```
var jsf = require('json-schema-faker');
var mockDataSchema = require('./mockDataSchema');
var fs = require('fs');

jsf.extend('faker', () => require('faker'));

jsf.option({
  resolveJsonPath: true,
  alwaysFakeOptionals: true,
});

var json = JSON.stringify(jsf(mockDataSchema));

fs.writeFile("./src/api/db.json", json, function (err) {
  if (err) {
    return console.log(err);
  } else {
    console.log("Mock data generated.");
  }

});
```

**Comment by pateketrueke** [comment]
Make sure you're getting the latest `json-schema-faker@0.5.0-rc16` version installed, also try `jsf.generate(...)` or use the async API, [read here](https://github.com/json-schema-faker/json-schema-faker/tree/develop/docs#architecture).

**Comment by MarialenaShiamma** [comment]
I am using the latest, but I will have a look again and i may find a solution for this.
Thanks again for explaining me how this should work!

**Comment by pateketrueke** [comment]
I assume it's working since website reflects stable code, closing.

**Comment by morganney** [comment]
FWIW it wasn't working for me while using `json-schema-faker@0.5.0-rc16`, I had to bump my version to `0.5.0-rc22`.
