### ISSUE TITLE
fake: "name.findName" generate random string rather than random name

### ISSUE THREAD

**Issue by JIACHENG135** [json-schema-faker/json-schema-faker#500]
If you are reporting a bug, please include the following:

1. the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ (paste the schema, click `Generate example` and then copy and paste the resulting URL from the browser address bar)
2. the result you got
3. the result you expected
const authorschema = {
    type:'object',
    properties:{
        id:{
            $ref:'#/definitions/positiveInt'
        },
        username:{
            type:"string",
            "faker":"name.findName"
        }
    },
    required: ['id', 'username'],
      definitions: {
        positiveInt: {
          type: 'integer',
          minimum: 0,
          exclusiveMinimum: true
        }
      }
}
I got:  { id: 64121993, username: 'non ut incididunt cillum' },
I expected: {id:156846415,username:'Tom Bruce"

**Comment by pateketrueke** [comment]
Please, search for similar issues before opening a new one:

Your problem is described [here](https://github.com/json-schema-faker/json-schema-faker/issues/480).
