### ISSUE TITLE
Expected generation of arrays

### ISSUE THREAD

**Issue by christophdebaene** [json-schema-faker/json-schema-faker#502]
I have the following schema. 
That models a forum that contains multiple topics and a topic contains multiple posts.

```json
{
  "title": "Forum",
  "type": "object",
  "properties": {
    "Id": {
      "type": "string"
    },
    "Topics": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Topic"
      }
    }
  },
  "definitions": {
    "Topic": {
      "type": "object",
      "properties": {
        "Id": {
          "type": "string"
        },
        "Posts": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Post"
          }
        }
      }
    },
    "Post": {
      "type": "object",
      "properties": {
        "Id": {
          "type": "string"
        }
      }
    }
  }
}
```

I enabled the `alwaysFakeOptionals` and `fixedProbabilities` and have set the `minItems` and `maxItems` to 1.

The following was generated, but I expected to have some data about topic and post?

```json
{
  "Id": "tempor irure fugiat reprehenderit labore",
  "Topics": []
}
```

**Comment by pateketrueke** [comment]
Definitely is not working on the current RC or stable branch, but I tested it out against the `develop` branch is just worked!

I'll add a test case for covering this and then I'll update the current PR for the next RC.

So much thanks for your feedback!

**Comment by dvrvrm** [comment]
Can we add develop branch in node_modules?

**Comment by pateketrueke** [comment]
Yes, you can with `npm i json-schema-faker/json-schema-faker#develop` as I just uploaded the files to GitHub! 🎉

**Comment by morphatic** [comment]
🤦‍♂️ 

I installed the `develop` branch as you suggested. That took care of the array generation problem, but now it doesn't seem to respect `alwaysFakeOptionals`. It only generates `required` properties.

Here's how my options are defined:

```js
// set jsf options
jsf.option({
  alwaysFakeOptionals: true,
  optionalsProbability: 1.0,
  fixedProbabilities: true
})
```

Am I doing something wrong?

**Comment by pateketrueke** [comment]
Hi @morphatic can you share the schema you're using as input? Thank you! 🙏

**Comment by groot321** [comment]
I am facing a similar issue , array is empty . any solution?

**Comment by pateketrueke** [comment]
Hi @groot321 can you provide more details?

- Which version you're using
- The schema you're using
- The code you're using

Thank you!
