### ISSUE TITLE
genrate all properties even non-required

### ISSUE THREAD

**Issue by wjs7740** [json-schema-faker/json-schema-faker#503]
can i genrate all properties whitout require?
maybe an option like generateAll

**Comment by wjs7740** [comment]
I set option alwaysFakeOptions: true, but it seems 50:50 generate,Did jsf
 support 100% generate?

**Comment by pateketrueke** [comment]
Also set `optionalsProbability: 1` which means 100%, so 0.5 mean 50% and so on.

Checkout all available options: https://github.com/json-schema-faker/json-schema-faker/tree/master/docs#available-options

**Comment by pateketrueke** [comment]
Just make sure you're installing the latest RC or the `json-schema-faker/json-schema-faker#latest` version from this repo.

**Comment by wjs7740** [comment]
hi pateketrueke ,
thanks for your reply,
following is my code,i set the option as u say ,but it seems dosent word, also 50% generate.
Is there anything wrong with me?
`import jsf from 'json-schema-faker'; // "json-schema-faker": "^0.5.0-rc16",
var schema = {
  type: 'object',
  properties: {
    user: {
      type: 'object',
      properties: {
        id: {
          $ref: '#/definitions/positiveInt',
          default: '123'
        },
        name: {
          type: 'string',
          default: 'wjs'
          // faker: 'name.findName'
        },
        email: {
          type: 'string',
          format: 'email',
          faker: 'internet.email'
        }
      },
      required: []
    }
  },
  required: [],
  definitions: {
    positiveInt: {
      type: 'integer',
      minimum: 0,
      exclusiveMinimum: true
    }
  }
};

jsf.option({
  alwaysFakeOptions: true,
  optionalsProbability: 1,
});
var aStudentData = jsf.generate(schema);`

**Comment by pateketrueke** [comment]
OK, current RC-16 is broken about, please install `json-schema-faker/json-schema-faker#latest` and repeat your tests.

**Comment by addynaik** [comment]
when i try to install the latest it says 

```
> npm install --save json-schema-faker/json-schema-faker#latest
npm ERR! code 1
npm ERR! Command failed: git checkout latest
npm ERR! error: pathspec 'latest' did not match any file(s) known to git
npm ERR!
```

**Comment by pateketrueke** [comment]
My fault, the tag is `#develop` sorry for that!

**Comment by addynaik** [comment]
even the develop didnt seem to work for me. 
```
jsf.option({ useExamplesValue: 'true', alwaysFakeOptionals: 'true', optionalsProbability: 1 });
const payload = jsf.generate(resolvedSchema);
console.log(payload);
```

still in this it only shows required elements

**Comment by pateketrueke** [comment]
Please use `true` values, a quoted `'true'` is not correct.

Also, if this is still failing for you please share your schema to understand.

**Comment by addynaik** [comment]
i tried using `true` but it didnt work but i found the problem.. looks like additionalProperties in the schema is messing something up. 

```
console.log(jsf.generate({
  additionalProperties: false,
  required: ['prop1'],
  properties: {
    prop1: {
      type: 'string',
      enum: ['test1', 'test2'],
    },
    prop2: {
      type: 'string',
      enum: ['test3', 'test4'],
    },
  },
}));
//-> { prop1: 'test2' }
console.log(jsf.generate({
  required: ['prop1'],
  properties: {
    prop1: {
      type: 'string',
      enum: ['test1', 'test2'],
    },
    prop2: {
      type: 'string',
      enum: ['test3', 'test4'],
    },
  },
}));
//-> { prop1: 'test1', prop2: 'test3' }
```

I also found another quirk.. in this case additionalProperties doesnt matter

```
console.log(jsf.generate({
  additionalProperties: false,
  required: ['prop1'],
  properties: {
    prop1: {
      type: 'string',
      examples: ['test1', 'test2'],
    },
    prop2: {
      type: 'string',
      examples: ['test3', 'test4'],
    },
  },
}));
//-> { prop1: 'test1' }
console.log(jsf.generate({
  required: ['prop1'],
  properties: {
    prop1: {
      type: 'string',
      examples: ['test1', 'test2'],
    },
    prop2: {
      type: 'string',
      examples: ['test3', 'test4'],
    },
  },
}));
//-> { prop1: 'test2' }
```
