### ISSUE TITLE
generating unique array of enums may cause infinite loop 

### ISSUE THREAD

**Issue by wisdom-yzh** [json-schema-faker/json-schema-faker#506]
when the enum size is less than array size.

test case:

```json
{
  "type": "object",
  "properties": {
    "test": {
      "type": "array",
      "items": {
        "type": {
          "enum": [
            "a",
            "b",
            "c",
            "d",
            "e"
          ]
        }
      },
      "maxItems": 10,
      "uniqueItems": true
    }
  }
}
```

the code below may be wrong?

limit-- should be put outside if block

```javascript
  while (tmp.length !== items.length) {
    walk(traverseCallback(value.items || sample, path, resolve));
    
    if (!limit) {
      limit -= 1; // ?
      break;
    }
  }
```

https://github.com/json-schema-faker/json-schema-faker/blob/a6a6635b055b1d20ba24ec23e89f00e87a91fd08/src/types/array.js#L28

**Comment by pateketrueke** [comment]
IMHO `uniqueItems && enumValues.length <= maxItems` should throw an exception instead, a kind of pre-validation of what can be possible.

Anyway the point you made is true, that `limit -= 1` seems to be in a wrong place.

Let me see if I can fix this, thank you!

**Comment by pateketrueke** [comment]
Fixed on RC!

**Comment by wisdom-yzh** [comment]
thanks, it's efficient

**Comment by luismaldonadov** [comment]
I've briefly search on issues and found this exact same issue for me. Thanks for fixing it
