### ISSUE TITLE
"Cannot convert undefined or null to object" with anyOf + default

### ISSUE THREAD

**Issue by alixaxel** [json-schema-faker/json-schema-faker#508]
On https://json-schema-faker.js.org/#gist/5f81f118fbd4eac01ccacf23a061a8b9

This valid JSONSchema snippet:

```json
{
  "anyOf": [
    {
      "type": "boolean"
    },
    {
      "type": "null"
    }
  ],
  "default": null
}
```

Fails with:

> Cannot convert undefined or null to object in /

If the `default` is moved inside the `type: null` block:

```json
{
  "anyOf": [
    {
      "type": "boolean"
    },
    {
      "type": "null",
      "default": null
    }
  ]
}
```

Then it works as expected: https://json-schema-faker.js.org/#gist/5f81f118fbd4eac01ccacf23a061a8b9

**Comment by pateketrueke** [comment]
Hello and good catch @alixaxel 🍻 ,

I'll include this on the next RC!
