### ISSUE TITLE
"Can not convert undefined or null object" $ref inside of a $ref

### ISSUE THREAD

**Issue by dmg2** [json-schema-faker/json-schema-faker#509]
About a week ago I utilized this tool to generates some data for my schema. Today I attempted to do the same but got the error "Cannot convert undefined or null object". My schema has not changed so I thought it was a bit odd. I realized that the website was recently updated. Upon further inspection it seems that json-schema-faker is having an issue when a $ref reference further references another $ref, but I am not sure entirely what the issue is. Attached is the schema that was working a week ago.
[oc2ls-v1.0-wd14.txt](https://github.com/json-schema-faker/json-schema-faker/files/3254582/oc2ls-v1.0-wd14.txt)

**Comment by pateketrueke** [comment]
Yeah, I also noticed some issues with these new RC; most of them I think are related with upgrading dependencies.

I'll investigate a bit more on this, so much thanks for your feedback!
