### ISSUE TITLE
AlwaysFakeOptionals doesn't work anymore

### ISSUE THREAD

**Issue by jdinunzio** [json-schema-faker/json-schema-faker#510]
**Schema:** Anything with optional properties

```json
{
  "type": "object",
  "properties": {
    "foo": {  "type": "string"   },
    "bar": {  "type": "string"   }
  },
  "required": [  ],
  "additionalProperties": false
}
```

**Config:**
```javascript
jsf.option({ alwaysFakeOptionals: true });
```

version: latest **0.5.0-rc16/rc17**
Result got: {}
Result expected: {"foo": "xxx", "bar": "yyy"}

When tested with **0.5.0-rc9**, the expected result is generated.

**Comment by pateketrueke** [comment]
Interesting, if you remove `additionalProperties` it works!

Definitely it should work even if we don't set `alwaysFakeOptionals`, I'll be fixing this asap.

So much thanks for yout feedback.

**Comment by aeneasr** [comment]
Would it be possible to release this change? Thank you!

**Comment by pateketrueke** [comment]
Hi @aeneasr , currently I can't release because more stuff is broken. Please use a previous RC16, or the latest stable that haven been proved:  0.5.0-rc9

Thank you!

**Comment by oktapodia** [comment]
Any update on that one?

**Comment by pateketrueke** [comment]
Sorry for that, It'll take a few more weeks, I don't have enough spare time to do so...

**Comment by oktapodia** [comment]
@pateketrueke Should be fix with my PR, can I do a PR on master so you can hotfix on npm?

**Comment by pateketrueke** [comment]
Thanks for your submission, I'll see if I can release a patched version asap!

**Comment by divino5** [comment]
Hi, any updates on this?

**Comment by XVincentX** [comment]
@pateketrueke Are you planning to release this as an RC any time soon? We've experiencing this same bug in Prism 

https://github.com/stoplightio/prism/issues/715

**Comment by pateketrueke** [comment]
Which branch is appropriate to solve your issue?

I'm not sure if I ported the fix to `master`, can you help me to verify if this is true?

If not, I'll be porting it asap to publish a new RC, thank you. 🙏

**Comment by XVincentX** [comment]
I think it’s ported already. We just need to publish it. 

Enviado do meu iPhone
