### ISSUE TITLE
Version strings not updated in 0.5.0-rc17

### ISSUE THREAD

**Issue by Edward-Knight** [json-schema-faker/json-schema-faker#511]
A few version strings haven't been updated to `rc-17`. The most obvious one is in `index.js`:
https://github.com/json-schema-faker/json-schema-faker/blob/b86fb26ca822d31833b91b1a1f07b0234bf9bd2c/src/index.js#L152

This causes the incorrect version to be reported:
```
> var jsf = require("json-schema-faker")
undefined
> jsf.version
'0.5.0-rc16'
```

**Comment by pateketrueke** [comment]
Sure, we'll fix that asap, thanks for your report!

**Comment by pateketrueke** [comment]
FTR; sadly we can't republish RC17 with a fix, so I think it will become deprecated and a new RC will be released for it.
