### ISSUE TITLE
Suggestion: remove package-lock.json

### ISSUE THREAD

**Issue by IanSavchenko** [json-schema-faker/json-schema-faker#513]
Since this is a library and not an application, there is no sense to have a package-lock file, because when you publish a new version, package-lock is not submitted to npm. This can lead to situations when "it works on my computer", but doesn't work for users. Additionally, it produces unnecessary diffs with every package.json update.

Recently, there was a nice article about all this: https://www.twilio.com/blog/lockfiles-nodejs. 

Thanks for all the great work ❤️

**Comment by pateketrueke** [comment]
I'll read that article and see what can I do, so much thanks for your feedback! 🍻

**Comment by pateketrueke** [comment]
FTR; I just added `package-lock.json` to the `files` to include that on publish, it is added... but, which way is better having ot not having a lock-file? 🤔

**Comment by IanSavchenko** [comment]
> FTR; I just added `package-lock.json` to the `files` to include that on publish, it is added... but, which way is better having or not having a lock-file? 🤔

It may be added, but when `json-schema-faker` is installed from `npm`, it does not have `package-lock.json`, so won't make any difference to users. Except, that you may end up with different dependencies as a developer.

**Comment by pateketrueke** [comment]
Updates:

- Adding it to the `files`, I tried `npm pack` and effectively `package-lock.json` is there
- Installing it from the `*.tar` (what `npm i` does) the lock-file is still there, and working

I'm OK with removing that file, but if it works as expected, just by adding it to `files` I think is better.

What do you think?

**Comment by IanSavchenko** [comment]
As [npm docs](https://docs.npmjs.com/files/package-lock.json#description) say


> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package. It shares a format with npm-shrinkwrap.json, which is essentially the same file, but allows publication. This is not recommended unless deploying a CLI tool or otherwise using the publication process for producing production packages.


So even if you manage to publish package-lock.json to npm and users get it, it will not be considered.

**Comment by pateketrueke** [comment]
Ok, sounds good to me.

Actually I've been doing some stuff that actually doesn't deserve their package-lock.json to be published, and it's working pretty well... I think we can do the same here.

So much thanks for your input! :beers:
