### ISSUE TITLE
Problems with pattern-property (call of randexp)

### ISSUE THREAD

**Issue by webersteffen** [json-schema-faker/json-schema-faker#515]
Hello,

we have a little problem with the generation of fake data for our json-schema. Our schema worked fine since now. The problem occurs when we use the property pattern like so:

...
"testproperty": {
          "$id": "#/myid",
          "type": "string",
          "title": "title",
          "examples": [
            "4388469000004"
          ],
          "pattern": "[0-9]{13}"
        },
...

This is a cutout from a lager json-schema

Following error occurs:

TypeError: Cannot read property 'prototype' of undefined at Object.randexp (https://unpkg.com/json-schema-faker@0.5.0-rc17/dist/bundle.umd.min.js:37:2834) at Object.value (https://unpkg.com/js

If I remove the "pattern" property from the schema, it will generate as expected. 

I´am not sure if this is a problem with json-schema-faker or the randexp package.

**Comment by pateketrueke** [comment]
I'm not sure, I think is a problem in between, I need to investigate a bit more.

So much thanks for your feedback!

**Comment by tnarik** [comment]
The same issue can be tested with the TD json-schema (Draft 07) from [Web Of Things](https://w3c.github.io/wot-thing-description/#json-schema-for-validation). I'm not sure if the issue is new or not though, as it is the first time I tried to use JSON Schema Faker.

**Comment by ArthurFlageul** [comment]
I have the same problem with the following payload:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "minProperties": 1,
  "maxProperties": 1,
  "patternProperties": {
    "^.{1,64}$": {
      "type": "object",
      "properties": {
        "abc": {
          "type": "string"
        },
        "abc2": {
          "type": "string"
        }
      }
    }
  }
}
```

I'm getting:
`randexp@https://unpkg.com/json-schema-faker:37:2832 object/</<@https://unpkg.com/json-schema-faker:37:14518 object/<@https://unpkg.com/json-schema-faker:37:14440 object@https://unpkg.com/json-schema-f`

**Comment by pateketrueke** [comment]
Hi @ArthurFlageul ¿it is possible for you to test the previous RC16?
