### ISSUE TITLE
Missing types definition

### ISSUE THREAD

**Issue by idantene** [json-schema-faker/json-schema-faker#516]
Even though the `README.md` says `deprecated — TypeScript sources are not longer used, however d.ts definitions will be updated on time.`, there seems to be no `d.ts` definitions anywhere and so the package is only usable if one silences TypeScript with `@ts-ignore`.

**Comment by pateketrueke** [comment]
I would not say "package is unusable for TypeScript" because it is, only the definitions are missing.

AFAIK lacking of `.d.ts` definitions does not make this unusable, just less friendly to use for vs-code users or for typescript-users that are familiar with.

To me is bit complicated to build this definitions by hand because I'm not familiar with Typescript, but if someone else is able to do so we'll be happy to accept its PR, how about you?

**Comment by idantene** [comment]
True, that was an exaggeration. Of course one can simple `// @ts-ignore` the warning and use the package as is. It's very un-TypeScript-y :grinning: 

I'll look into it -- can't promise anything. For the time being I am using it with `@ts-ignore`.

I guess [dts-gen](https://github.com/microsoft/dts-gen) is a good place to start, though.

**Comment by pateketrueke** [comment]
Sure, I believe you can do it better than me, thank you! 👌

**Comment by JounQin** [comment]
When will this be published???

**Comment by pateketrueke** [comment]
Hi @JounQin I would like to release a new RC this weekend, please stay on the track! :beers:

**Comment by JounQin** [comment]
@pateketrueke It seems the definition is incorrect actually.

See https://github.com/json-schema-faker/json-schema-faker/blob/a869eb5794a0f22b98d0ed186255d22578c932fc/index.d.ts#L56

`generate` must not return `void`.

[`@types/json-schema-faker`](https://unpkg.com/browse/@types/json-schema-faker@0.5.1/index.d.ts) is correct.

If you're not going to make sure the typings are correct, I suggest let it as-is, do not maintain the typings here.

**Comment by pateketrueke** [comment]
Yeah, I just pushed a draft and it may not be correct, I am not very familiar with TS but I've been learning a bit.

**Comment by JounQin** [comment]
> Yeah, I just pushed a draft and it may not be correct, I am not very familiar with TS but I've been learning a bit.

@pateketrueke Then please do not release it before you understand completely and test it by a `.test.d.ts` file correctly. 😂 

Cheers. 🍺
