### ISSUE TITLE
Change the JSON Path dependency

### ISSUE THREAD

**Issue by XVincentX** [json-schema-faker/json-schema-faker#517]
Hey,

I've been using JSON Schema Faker in Stoplight for a while and it has been working great; however I'm personally facing some issues with the JSON Path dependency.

The jsonpath implementation that this library uses right now (https://github.com/dchester/jsonpath) has a number of shortcomings. Most importantly, it does some weird things with esprima. This has caused some interop issues (in particular when packaging some modules), and bloats the dependency size.

We are maintaining a fork of this project with the sole purpose of replacing the JSON path dependency with a fork of it which does not do weird things.

On the other hand, we've been using successfully https://github.com/s3u/JSONPath for a while, and I think it'd be great to switch JSON Schema Faker as well.

* 13% the size when minified - 11kb versus 79kb.
* No more esprima or weird globals stuff.
* Significantly more performant - https://github.com/andykais/json-querying-performance-testing.

Would you be open to a PR changing the dependency? Another solution would be to make sure this library would use the bundled version of JSON Path and not the raw source ones.

**Comment by pateketrueke** [comment]
Please! Currently I'm rewriting the object generator due many regressions we had on latest RC, so I'll not touch the json-path support atm; feel free to replace it and/or see if the latter option also can be. 👌

**Comment by XVincentX** [comment]
Cojonudo!

**Comment by XVincentX** [comment]
@pateketrueke #518
