### ISSUE TITLE
Error: unknown registry key "ascii_printable" 

### ISSUE THREAD

**Issue by weaming** [json-schema-faker/json-schema-faker#523]
If you are reporting a bug, please include the following:

1. 
```
{
  "additionalProperties": false,
  "required": [
    "name"
  ],
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "format": "ascii_printable"
    }
  }
}
```
2. the result you got: `Error: unknown registry key "ascii_printable" at S (https://unpkg.com/json-schema-faker@0.5.0-rc17/dist/bundle.umd.min.js:37:11495) at https://unpkg.com/json-schema-faker@0.5.0-rc17/dist/bundl`
3. the result you expected: should works properly

**Comment by pateketrueke** [comment]
Hi, is `ascii_printable` a supported format by the spec? 🤔 

Please stick to standard keywords, and, if you want to use your own formats use `jsf.format()` prior usage, see the docs: https://github.com/json-schema-faker/json-schema-faker/blob/master/docs/USAGE.md#custom-formats
