### ISSUE TITLE
An object only has one property and this property is not required will generate wrong result sometimes

### ISSUE THREAD

**Issue by shuxiaotai** [json-schema-faker/json-schema-faker#528]
1. As you see, an object only has one property, and this property is not required
```javascript
{
  "type": "object",
  "properties": {
    "field": {
      "type": "string"
    }
  }
}
```
the result sometimes like this ( I think this is correct through the second example below)
```javascript
{}
```
at other times  like this in  https://json-schema-faker.js.org (I think this is a bug through the second example below)
```javascript
{
  "field": "sed irure aute Duis"
}
```
2. When an object has two properties and both are required, like this
```javascript
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "string"
    }
  },
  "required": [
    "name",
    "age"
  ]
}

//result
{
  "name": "Lorem aliquip",
  "age": "sed Excepteur"
}
```
when properties aren't required, like this
```javascript
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "string"
    }
  }
}

//result
{}
```
this example show when properties aren't  required the result is {}, so the first example seems to be a bug
3. This problem exists in any object, not just the top-level object
```javascript
{
  "type": "object",
  "properties": {
    "person": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "age": {
          "type": "string"
        }
      }
    }
  }
}
```
the result sometimes like this
```javascript
{
  "person": {}
}
```
at other times  like this
```javascript
{}
```

**Comment by pateketrueke** [comment]
Yeah, it is an issue, can you repeat your tests against the `develop` branch?

I've been rewriting the object generator due these inconsistencies.

**Comment by shuxiaotai** [comment]
> Yeah, it is an issue, can you repeat your tests against the `develop` branch?
> 
> I've been rewriting the object generator due these inconsistencies.

I have tested it in the `tests/schema/core/issues` directory of the develop branch，this is my code
```javascript
[
  {
    "description": "should solve #528",
    "tests": [
      {
        "description": "one property is not required and result is empty",
        "schema": {
          "type": "object",
          "properties": {
            "field": {
              "type": "string"
            }
          }
        },
        "valid": true,
        "equal": {}
      },
      {
        "description": "one property is not required and result is not empty",
        "schema": {
          "type": "object",
          "properties": {
            "field": {
              "type": "string"
            }
          }
        },
        "valid": true,
        "equal": {
          "field": "sed irure aute Duis"
        }
      },
      {
        "description": "deep object and this property is not required and result is empty",
        "schema": {
          "type": "object",
          "properties": {
            "person": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "age": {
                  "type": "string"
                }
              }
            }
          }
        },
        "valid": true,
        "equal": {}
      },
      {
        "description": "deep object and this property is not required and result is not empty",
        "schema": {
          "type": "object",
          "properties": {
            "person": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "age": {
                  "type": "string"
                }
              }
            }
          }
        },
        "valid": true,
        "equal": {
          "person": {}
        }
      }
    ]
  }
]
```

### The result of the first time

![image](https://user-images.githubusercontent.com/16969675/66096129-8b9e3080-e5cc-11e9-9877-52214da692c3.png)

### The second time

![image](https://user-images.githubusercontent.com/16969675/66096152-a2dd1e00-e5cc-11e9-8902-75fc7bc5e51c.png)

2）3）are correspond to the first example I mentioned earlier
4）5）are correspond to the third example I mentioned earlier

So the problem I mentioned earlier also exist in the `develop` branch. I hope my tests are correct, If there is any mistake, please help me to correct it, thank you.

**Comment by pateketrueke** [comment]
Ok, there is a bit of confusion here.

Object properties will be generated randomly, no matter if you're not _requiring_ then explicitly, and that's the default.

Once you `require` some of them, then these _required_ properties will be generated every time.

Non-required properties are optional, but they can appear randonmly.

To get consistent, deterministic results, each time, you MUST configure `alwaysFakeOptionals`, `optionalsProbability` and `fixedProbabilities` to achieve precise results.

See docs: https://github.com/json-schema-faker/json-schema-faker/tree/master/docs#available-options

**Comment by shuxiaotai** [comment]
> Ok, there is a bit of confusion here.
> 
> Object properties will be generated randomly, no matter if you're not _requiring_ them explicitly, and that's the default.
> 
> Once you _require_ some of them, then these `required` properties will be generated every time.
> 
> Non-required properties are optional, but they can appear randonmly.
> 
> To get consistent, deterministic results, each time, you MUST configure `alwaysFakeOptionals`, `optionalsProbability` and `fixedProbabilities` to achieve precise results.
> 
> See docs: https://github.com/json-schema-faker/json-schema-faker/tree/master/docs#available-options

Thank you
