### ISSUE TITLE
jsf.resolve() hangs with circular reference when alwaysFakeOptionals is true

### ISSUE THREAD

**Issue by publicus** [json-schema-faker/json-schema-faker#530]
First, thank you **very much** for your work on this project! I'm really grateful for the work you've put into it. What a great library.

This issue report follows https://github.com/json-schema-faker/json-schema-faker/issues/92#issuecomment-396583590. I'm running version `0.5.0-rc19`.

Using the following schema, which includes a circular reference, will cause the tab to hang / crash when `alwaysFakeOptionals` is checked.

<img width="437" alt="Screen Shot 2019-10-14 at 11 40 39 AM" src="https://user-images.githubusercontent.com/3667562/66764311-7e5c2e00-ee77-11e9-810e-700e6668d10c.png">

```
{
  "type": "object",
  "definitions": {
    "collectionDef": {
      "additionalProperties": false,
      "properties": {
        "a": {
          "items": {
            "$ref": "#/definitions/aDef"
          },
          "type": "array"
        },
        "b": {
          "type": "string"
        }
      },
      "type": "object",
      "required": ["b", "a"]
    },
    "aDef": {
      "additionalProperties": true,
      "properties": {
        "subA": {
          "items": {
            "$ref": "#/definitions/aDef"
          },
          "type": "array"
        },
        "b": {
          "type": "string"
        }
      },
      "type": "object"
    }
  },
  "properties": {
    "name": {
      "type": "string",
      "faker": "name.findName"
    },
    "email": {
      "type": "string",
      "faker": "internet.email"
    },
    "collection": {
      "$ref": "#/definitions/collectionDef"
    }
  },
  "required": ["name"]
}
```

**Actual result:** `json-schema-faker` hangs / generates data infinitely.

**Expected result:** From #129, is my understanding correct that `json-schema-faker` should *not* hang in this case, but rather should choose a "max. traversal depth" and stop generating data after going that number of levels deep?

**Comment by pateketrueke** [comment]
Seems to be fixed on `development`, I'll update the website once released!

**Comment by pateketrueke** [comment]
Interesting, seems like it's only happening on the `master` branch, so even if released it continues hanging... but on `develop` is fixed now!

**Comment by publicus** [comment]
@pateketrueke, thank you for all of your work on this project! Thank  you, also, for taking a look at this issue report.

I can confirm that the issue doesn't happen in the `develop` branch! Is there anything that would be helpful to you in getting this change working in `master`, as well?

**Comment by pateketrueke** [comment]
I'm planning to merging develop on master this weekend as it seems stable now, thank you! :beers:
