### ISSUE TITLE
Is there support for random properties?

### ISSUE THREAD

**Issue by parsifal-47** [json-schema-faker/json-schema-faker#537]
Hi, is there a way to generate random properties?
For example, if I put the following schema:

```
{
  "type": "object"
}
```

all I get is `{}`, however this is not the only way to satisfy given schema.

Thanks!

**Comment by pateketrueke** [comment]
Sure, just add `minProperties` to your schema, e.g.

```json
{
  "type": "object",
  "minProperties": 10
}
```

> Hint: please read how json-schema works, there are many properties you can use to fulfill such kind of requirements. 😉

**Comment by parsifal-47** [comment]
oh, thanks a lot!
