### ISSUE TITLE
RangeError: Invalid time value at Date.ISOString

### ISSUE THREAD

**Issue by nmonteca** [json-schema-faker/json-schema-faker#539]
Total beginner here.

I am getting an "Error: RangeError: Invalid time value" when having a schema such as below. This used to work against a much older version. 

![image](https://user-images.githubusercontent.com/18653444/69775655-59780c00-11d4-11ea-9ce3-5b8b0a1125e3.png)

I validated the schema if its correct. 
![image](https://user-images.githubusercontent.com/18653444/69775746-b378d180-11d4-11ea-9dd0-b52b64c9deef.png)

**Comment by nmonteca** [comment]
It did work with **"format": "full-date"**
Reading online discussion that may explain this.

**Comment by nmonteca** [comment]
Did work for 0.5.0-rc16 version.

**Comment by pateketrueke** [comment]
Interesting, let me see if I can fix this, thank you!

**Comment by TroyLDay** [comment]
I've experienced this as well, looks like a fix is not imminent :(    
I'm getting to know this lib... Is a custom format a way to work around this issue temporarily?

**Comment by pateketrueke** [comment]
Well, I just peaked at the code and I noticed that higher values, say `4950-12-91` are being generated by the `pattern` regex... so, we could use a more precise regex instead, or we can try to clamp those values if date formats are used, what do you think?

**Comment by pateketrueke** [comment]
Update: only `date|date-time|datetime|time` are supported and that's the reason of the Range error because those values are being formatted after being generated.

The regex generated an out-of-range date, and using `new Date(...)` yielded the invalid date, hence the issue.

Using the clamp strategy as a quick-solution worked pretty well.

Now, accordingly on [this comment](https://github.com/json-schema-org/json-schema-spec/issues/483#issuecomment-343964993) the `date` format would be a synonym for `full-date` so I think we will honor this on time.

**Comment by TroyLDay** [comment]
Thank you patekretueke for the attentiveness and quick response! I'll give it a try in my next available cycle.

**Comment by pateketrueke** [comment]
Yeah, no worries, I'll do my best to release this and other pending work this weekend, thank you!

**Comment by lhimstedt** [comment]
@pateketrueke Have you found a solution? Because the problem persists. I'm using a very precise regex for the pattern, only leap years and leap seconds aren't covered.
It's quite annoying, I've start analysing the source files to find a solution, but I think this will take some time.

**Comment by lhimstedt** [comment]
@pateketrueke Have you found a solution? Because the problem persists. I'm using a very precise regex for the pattern, only leap years and leap seconds aren't covered.
It's pretty annoying, I've started analyzing the source files to find a solution, but I think this will take some time.

**Comment by lhimstedt** [comment]
@pateketrueke I've created a PR (#705) with a new clampDateTime and updated clampDate method.

Could it be that the NPM package is outdated? Because I can't find the clampDate method in the NPM package.

**Comment by pateketrueke** [comment]
Hi @lhimstedt can you confirm which version are you using locally?

**Comment by lhimstedt** [comment]
@pateketrueke used 0.5.0-rcv.42
