### ISSUE TITLE
re-using multiple subschemas between schema files

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#54]
I've got a very big schema (thousands of files), which I have finally split into multiple files (according to [docs](https://github.com/pateketrueke/json-schema-faker#using-references)). There is one "master" schema and over a dozen of chunk-schemas. I want to reuse simple structures between all of them, such as:

```
  "tinyId": {
    "type": "integer",
    "minimum": 1,
    "maximum": 100
  }
```

When I had one big file, I used to keep everything in `definitions`, just like below:

```
{
  //...
  "definitions": {
    "random": {
      "tinyId": {
        "type": "integer",
        "minimum": 1,
        "maximum": 100
      },
      "smallId": {
        "type": "integer",
        "minimum": 1000,
        "maximum": 1000000
      },
      "id": {
        "type": "integer",
        "minimum": 1000000,
        "maximum": 1000000000
      },
  //...
```

but after splitting the files, it breaks (definitions aren't resolved correctly.

What am I doing wrong? Does jsf support sharing subschemas between multiple files? Can I make one file that would hold many re-usable schemas?

**Comment by pateketrueke** [comment]
How you are defining those refs?

**Comment by ducin** [comment]
Below is what I've managed to do - it's a working solution, but I'm not sure, whether it's the simplest possible.

main file (customer) - the one that references the rest:

    {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "$ref": "random.bigId"
        },
        "externalId": {
          "$ref": "random.id"
        },
        "accounts": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "customer.account"
          }
        },
        "addresses": {
          "type": "array",
          "minItems": 1,
          "maxItems": 3,
          "items": {
            "$ref": "customer.address"
          }
        },
        //...
      },
      "required": [
        "id",
        "externalId",
        //...
      ],
      "definitions": {
        "random": {
          "tinyId": {
            "id": "random.tinyId",
            "type": "integer",
            "minimum": 1,
            "maximum": 100
          },
          "smallId": {
            "id": "random.smallId",
            "type": "integer",
            "minimum": 1000,
            "maximum": 1000000
          },
          //...
        }
      }
    }

It has `id` and `externalId` attributes defined in the local definitions sections. It has also `accounts` and `addresses` attributes that rely on external references.

The account (external reference) is:

    {
      "id": "customer.account",
      "type": "object",
      "properties": {
        "id": {
          "$ref": "random.hash"
        },
        "number": {
          "$ref": "random.accountNumber"
        },
        "name": {
          "type": "string",
          "faker": "finance.accountName"
        },
        "balance": {
          "type": "number",
          "faker": {
            "finance.amount": [
              0,
              1000000,
              2
            ]
          }
        },
        "currency": {
          "type": "string",
          "faker": "finance.currencyCode"
        }
      },
      "required": [
        "id",
        "number",
        "name",
        "balance",
        "currency"
      ]
    }

You can see that it has `"$ref": "random.hash"` or `"$ref": "random.accountNumber"` references, that are fetched from customer file (the main one).

Well, it was I blind shot (I didn't expect that), but it works :) Anyway, sharing common definitions between whole packages of files is an interesting topic.

**Comment by revelt** [comment]
+1, I came here for the same thing. Currently, exact references by `id` fail with a message on the UI "Buffer is not defined", for example:

```json
{  
   "type":"object",
   "id":"a",
   "properties":{  
      "obj1": {
        "type":"object",
        "id": "obj1",
        "properties": {
          "b": {
            "type": "string"
          },
          "c": {
            "type": "string"
          }
        }
      },
      "obj2": {
        "type": "object",
        "$ref": "obj1"
      }
   }
}
```

The files I'm working with are cross-referencing using id's and not the "inner-references" example in style `"#/definitions/positiveInt"`, by ID.

Basically, it would be awesome to inner-reference by both **ID** (new feature) and by **path** (existing feature, using `#/...`).

**Comment by pateketrueke** [comment]
I'm not sure if using that kind of identifiers is completely valid, e.g.

- https://json-schema-validator.herokuapp.com/ is not working
- https://www.jsonschemavalidator.net/ works perfectly

IMO I think both identifiers are valid, but I'm not sure if this is widely true...

Anyway I just added a quick-lookup mechanism for resolving this kind of self-references by id.

@revelt please let me know if you're using this kind of references from different files at the same time, it will help me to understand better this topic.

BTW this is solved under the `develop` branch.

**Comment by revelt** [comment]
@pateketrueke quite some time passed, my brain is wiped on this subject :) I think I tried to implement the validation on my JSONs and went as far as here during R&D but dropped it, reverting back to simple normalisation (where a new key in one JSON from a set of JSONs triggers key added to the rest of a set of files). I both create and manage my JSONs and am the only user so I guess I can afford that.

Anyway thanks for your work, I appreciate it and will try to tap the new version. Best luck!
