### ISSUE TITLE
Regex pattern only containing caret crashes the browser tab

### ISSUE THREAD

**Issue by skinnedpanda** [json-schema-faker/json-schema-faker#540]
`"pattern": "^"` crashes the tab in Chrome, even after reload. Have to delete json-schema-faker.js.org locally stored data. No messages in the console. Seems to be stuck in an endless loop.

This happens both when pasting in a schema, or editing inline.

**Comment by pateketrueke** [comment]
Hi, can you provide a failing schema that can I use to test this out?

**Comment by skinnedpanda** [comment]
`{
  "comment": {
  "description": "Comment field",
  "maxLength": 254,
  "minLength": 1,
  "type": "string",
  "pattern": "^"
  }
}`

**Comment by pateketrueke** [comment]
Woah, that definitely hangs things out!

I'm testing against the `develop` branch and yes, it smells like a nice one.

Good catch, now I need to find the root-cause of this, so much thanks for your input. 🍻

**Comment by skinnedpanda** [comment]
Gracias a ti/vosotros! This is the most awesome JSON-tool I have used so far.
