### ISSUE TITLE
Allow a user to set a depth for circular $refs, or a $ref depth minimum and maximum

### ISSUE THREAD

**Issue by publicus** [json-schema-faker/json-schema-faker#544]
As I understand, [currently](https://github.com/json-schema-faker/json-schema-faker/blob/develop/src/lib/core/run.js#L139), for circular `$ref`s, JSF will randomly select a depth to render, between 1 and 3. 

I have code working, based on https://github.com/json-schema-faker/json-schema-faker/pull/543 (it needs the `minItems` and `maxItems` arguments in order to work), to add a "`refDepth`" API option.

Before I open a PR for this, I'd just like to check, is this an idea you'd be open to? If so, would you prefer a single `refDepth` option, or a `refDepthMin` and `refDepthMax`?

**Comment by pateketrueke** [comment]
Yeah, I believe we can replace those magic numbers from code and use options for them, as long you add at least one test covering such behavior, and most stuff remains the same I'm OK.
