### ISSUE TITLE
Using chance.unique

### ISSUE THREAD

**Issue by chrisk8er** [json-schema-faker/json-schema-faker#549]
Hi guys, this is my first time using JSON schema faker. I have trouble with chance.unique.

this is my code:
```
// Fields with unique values.
  uniqueItemProperties: [
    'id',
    'type'
  ],

  // Fields in the model.
  properties: {
    id: { type: 'ID' },
    type: { type: 'string', maxLength: 20, chance: { unique: [[ 'administrator', 'dispatcher', 'customer service'], 1 ] } }
  },
```
I want some unique result  in type property based on arrays that I passed.

this is what I expected:
```
"roles": [
    {
      "id": 1,
      "type": "administrator"
    },
    {
      "id": 2,
      "type": "dispatcher"
    },
    {
      "id": 3,
      "type": "customer service"
    }
  ],
```
i just want a unique value on the type keys.

but I got this error:
```
Error: Chance: The first argument must be a function.
```

I don't know how to passing function argument on a unique object.
hope you can help me... Thank You

**Comment by pateketrueke** [comment]
You don't need to use `chance.unique` for that, using a simple `enum` will do the trick, e.g.

```json
{
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "type": { "enum": ["administrator", "dispatcher", "customer service"] }
    },
    "required": ["type"]
  }
}
```

Is that what you're looking for?

**Comment by pateketrueke** [comment]
> Error: Chance: The first argument must be a function.

Please remember schemas should be portable, and since JSON does not allow functions to be serialized I won't add such support on jsf.

Closing in favor of `enum` as alternative.

**Comment by rodoabad** [comment]
@pateketrueke if we ever need to use `chance.unique` and not an enum, how would we do it?

**Comment by pateketrueke** [comment]
In the specific case for `chance.unique` is not possible since it requires functions as arguments.

Most function calls would work if they receive plain objects or arrays as arguments — since JSON does not support functions... you get the idea.

As the last option, you can implement your own `chance` wrapper, e.g.

```js
jsf.define('chanceUnique', (value, schema, prop, cur) => {
  // you may want to check what value, schema, prop and cur are..
  return chance.unique(chance.state, 5);
});
```

Now your schema can use such prop:

```json
{
  "type": "string",
  "chanceUnique": true
}
```

**Comment by rodoabad** [comment]
OH. VERY NICE. @pateketrueke we'll update our repo with this. Thanks!

**Comment by rodoabad** [comment]
@pateketrueke is there a way where I can tie this back with using `chance` as a parent property or `x-chance` for those in v2? Right now this would be a separate property.
