### ISSUE TITLE
Bug: schema not updated.

### ISSUE THREAD

**Issue by sbuisson** [json-schema-faker/json-schema-faker#552]
hello,
suddently (i think it worked yesterday)
when i click on generate example, it don't take my current shema, but a previous version. If i use an example, it will work, but if i modify the schema, it will stay the original schema who will generate data

**Comment by sbuisson** [comment]
It suddently fix. I don't know what happen

**Comment by pateketrueke** [comment]
Oh I see, so the webap is buggy!

Closing as duplicate of #553
