### ISSUE TITLE
Bug: not required field are not filled (options are good)

### ISSUE THREAD

**Issue by sbuisson** [json-schema-faker/json-schema-faker#553]
In this shema d, the field b is not generated unless i put it as required, even if the option "generate only requered is not checked"

{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "operationImport",
  "type": "object",
  "required": [
    "a"
  ],
  "properties": {
    "a": {
      "$ref": "#/definitions/A"
    },
    "b": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/B"
      }
    }
  },
  "definitions": {
    "A": {"type":"string"},   "B": {"type":"string}
  }
}

**Comment by pateketrueke** [comment]
The webapp is still outdated I guess, running the example locally works.

I'll be working on the webapp soon, so much thanks for your feedback.
