### ISSUE TITLE
Issue with pattern in email

### ISSUE THREAD

**Issue by mast7860** [json-schema-faker/json-schema-faker#554]
while generation of email Id, there seems to be issue with 
We are using . to for replacing the fake string , at the same time , emailId's have . before the domain.
So the needed . gets replaced with the string
have tried the sample from test site as well https://json-schema-faker.js.org

"emailAddr": {
      "type": "string",
      "chance": {
        "email": {
          "domain": "fake.com"
        }
      },
      "pattern": ".+@fake.com"
    }

  "emailAddr": "IYT@fakeIcom"

**Comment by pateketrueke** [comment]
Hi, the `pattern` property MUST be a regex-pattern, the `.` is a special-metacharacter in RegExp that means _anything_ so that's why it's being replaced randomly.

Please escape that character before, e.g. `.+@fake\.com`

**Comment by mast7860** [comment]
Thank . 
 I was aslo with single escape before and didnt work . double escape does work .
"pattern": ".+@fake\\.com".

**Comment by pateketrueke** [comment]
Yeah, sorry for that, within JSON you must escape _the escape character_ because it needs to be encoded as-is, to be passed to the RegExp generator.

```json
"pattern": ".+@fake\\.com"
```
