### ISSUE TITLE
[BUG] `const` as a property

### ISSUE THREAD

**Issue by RingOfStorms** [json-schema-faker/json-schema-faker#558]
Bug report:
Cannot use `const` as a property of an object, it seems to think it is the const of the json-schema definition of itself as the output.

1. the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ (paste the schema, click `Generate example` and then copy and paste the resulting URL from the browser address bar)

https://json-schema-faker.js.org/#gist/e668d5e002ec79ce56002eba9a041468
```json
{
  "type": "object",
  "properties": {
    "const": {
      "type": "string",
      "pattern": "\\d\\w\\d\\w+"
    }
  },
  "required": [
    "const"
  ]
}
```

2. the result you got
```json
{
  "type": "string",
  "pattern": "\\d\\w\\d\\w+"
}
```

3. the result you expected
```json
{
  "const": "0O7IO"
}
```

You can see it do what is expected by changing the property name to anything other than `const`

**Comment by pateketrueke** [comment]
Interesting issue, definitely const should should be taken into account.

So much thanks for your input!

**Comment by RingOfStorms** [comment]
Thank you!
