### ISSUE TITLE
Change Order so that custom generate to be superior than enum

### ISSUE THREAD

**Issue by Jeffersondyj** [json-schema-faker/json-schema-faker#559]
Example

    var Mock = require('mockjs');
    jsf.extend ('mock', function () {
        return {
            mock: function (xx) {
                return Mock.mock(xx);
            }
        };
    });

And this schema: 

    {
            type: 'integer',
            enum: [1, 4, 5],
            mock: {
                mock: "@integer(1,3)"
            }
    }

expected to be 1,2,3. But in fact the result is 1,4,5.

Can we raise the priority for custom generate? 

Thank you for your replying.

**Comment by pateketrueke** [comment]
Yeah that sounds like a good idea, but I need to explore if moving that will not break anything.

Aside of this, I would like schemas to be very portable, and adding so much extensions will degrade its portability.

But that's only my opinion, and not all cases deserve the same treatment!

So much thanks for your input.

**Comment by Justineo** [comment]
I think custom generators are closer to users actual needs. `enum` shouldn't ignore the result of generators.
