### ISSUE TITLE
Allow for faker.js locale to change the required AST when using Browserify

### ISSUE THREAD

**Issue by whitlockjc** [json-schema-faker/json-schema-faker#56]
faker.js has this nifty ability to require individual locales as [documented here](https://github.com/Marak/faker.js#individual-localization-packages).  The idea is that when using Browserify, you could use `require('faker/locale/en_US')` and only end up with the `en/en_US` locales being in the AST used by Browserify instead of having all locales in the AST.

Right now, json-schema-faker does not allow the consumer to take advantage of this so when I use Browserify to bundle my project, I end up with an extra 751 files in my Browserify bundle.  Here is how I came up with this number:

```
// require('faker');
browserify --list testing.js | wc -l
     862

// require('faker/locale/en_US');
browserify --list testing.js | wc -l
     111
```

This has an impact on file size too, even with this one line module the file size is most than 3 times the size.  All of this being said, is there a way to address this?  I've got some ideas but before I spend the time, I wanted to make sure this was in fact a real issue and I wasn't missing something.

Also, if you know of a Browserify recipe to handle this without altering json-schema-faker I'm all ears.  I've looked into a few options but never found anything that worked.

**Comment by ducin** [comment]
Hi @whitlockjc, first of all, single-locale-faker.js is a new feature that has been added in v3.0.0, as far as I know. When I added extending dependent libs, it was not there - that's why this feature is not supported yet.

I took a quick look at how does this line of faker work:
```js
// loads only de locale
var faker = require('faker/locale/de');
```
so it's:
```js
var Faker = require('../lib');
var faker = new Faker({ locale: 'de', localeFallback: 'en' });
faker.locales['de'] = require('../lib/locales/de');
faker.locales['en'] = require('../lib/locales/en');
module['exports'] = faker;
```
original faker lib (the main one) is loaded in normal way. Then the locale is being set. And such - locale-set faker is returned. When used with browserify, all is inherited automatically (only the set language is being used).

Well, I see that currently existing extending of jsf is incompatible with the new feature of faker.js, unfortunately :( The only way I see is to modify the [container.js file](https://github.com/pateketrueke/json-schema-faker/blob/master/lib/util/container.js) which holds current instances of dependent libs and to inject modified faker there. [This line](https://github.com/pateketrueke/json-schema-faker/blob/master/lib/util/container.js#L8):
```js
faker: require('faker')
```
would have to be parametrized and replaced by `require('faker/locale/XYZ')`. That's the place. But the question is - how to design the outer API, i.e. how should the jsf end-user configure faker.js? How to make it similar to handling chance.js?

@pateketrueke let us know your opinion :)

Mainly it's a problem that in current JavaScript you can do 10000 things in 1000000 different ways and there;s no way to make them all compatible with each other...

**Comment by ducin** [comment]
PS @whitlockjc have you removed the other issue/comment (Extending low-level dependencies (#12)
)?

**Comment by whitlockjc** [comment]
Yes I did.  I didn't want to cross post and after looking into faker.js, I think this is a separate issue.

**Comment by pateketrueke** [comment]
This works:

```javascript
jsf.extend('faker', function() {
  // just ignore the passed faker instance
  var faker = require('faker/locale/de');
  return faker;
});
```

**Comment by whitlockjc** [comment]
That doesn't seem to help.  While I can replace the faker instance, Browserify's AST still has all of the locales that faker includes by default when using `require('faker')`.  I tried the following and they all end up with 898 files included in the Browserify bundle.

```js
'use strict';

var jsf = require('json-schema-faker');

jsf.extend('faker', function () {
  return require('faker/locale/en_US');
});
```

```js
'use strict';

var jsf = require('json-schema-faker');

jsf.extend('faker', function (faker) {
  faker = require('faker/locale/en_US');

  return faker;
});
```

**Comment by pateketrueke** [comment]
Yeah, sorry, I'm not taking in account that.

I'm trying this:

```bash
$ browserify -r faker | wc -l # 39958
$ browserify -r faker/locale/de:faker | wc -l # 15213
```

That would work for you?

**Comment by whitlockjc** [comment]
Great idea!  I didn't even know about that Browserify feature.  With `browserify --list -r json-schema-faker/node_modules/faker/locale/en:faker testing.js | wc -l` I only get `147` files instead of `896`.

Thanks a lot!

**Comment by ducin** [comment]
Hey guys,

I know this issue has been resolved, but each time anybody asks about something, it means, our docs could be better :) so I've extended the jsf documentation (see https://github.com/ducin/json-schema-faker/blob/master/README.md#extending-dependencies).

And I think it'd be good to add it to the docs. But, to be honest, I didn't get the trick with browserify and the abstract syntax tree. Is it  how to bundle jsf, using browserify, with replacing entire-full-localized faker with only single-localized faker? Could you please suggest what we can add to the docs with what @whitlockjc was asking about?

**Comment by whitlockjc** [comment]
This actually does not work.  When using `-r faker/locale/en:faker`, it does not work when building standalone libraries: https://github.com/substack/node-browserify/issues/1120  To save you having to dig into the linked issue, imagine I have a module like this:

**my-module.js**
```js
module.exports.init = function (options) {
  // ...
};
```

If I browserify my bundle using `browserify -s MyModule my-module.js`, I get a global object called `MyModule` that has an `init` function.  When I use the same approach but with the faker locale fix, which looks like `browserify -s MyModule -r faker/locale/en:faker my-module.js`, I get a global `MyModule` object but with the contents of `json-schema-faker/node_modules/faker/locale/en.js`.  The reasoning for this is documented in the browserify issue.  I guess until browserify can support this, we can't call it a fix.

**Comment by pateketrueke** [comment]
I understand.

Would be possible to make this in a two-step build process?

If you first create the bundle for `faker/locale/en:faker`, then include it using the `--external` option.

**Comment by whitlockjc** [comment]
The biggest problem I've run into is most of the support for external libraries and such usually don't apply to dependencies, which json-schema-faker is for my application.  So while I could use the `browser` option in my `package.json` or a plethora of other transforms, they only alter the content of the files in my module, not the dependencies of my module.  So I'm not sure how this will change things.  I'll think keep experimenting and if I make progress, I'll let you know.

**Comment by whitlockjc** [comment]
I did find a solution that works: https://github.com/apigee-127/sway/commit/7670613d8a9f29c43434084d3bb91bf86931af4d  It uses the [pathmodify](https://github.com/jmm/pathmodify) browserify plugin.

**Comment by pateketrueke** [comment]
Awesome!

**Comment by pateketrueke** [comment]
FTR; since `v0.5.x` dependencies for external generators are not bundled anymore, use `jsf.extend()` for registering them on your entry points.

**Comment by whitlockjc** [comment]
Can you explain how this might impact someone, and how they might need to work around it?  If an RTFM is enough, don't be afraid to point me in the right direction.

**Comment by pateketrueke** [comment]
Actually it depends only on entry-points and `require` calls, our current "main" is:

```js
module.exports = require('./lib')
  .extend('chance', function() {
    try {
      return require('chance').Chance();
    } catch (e) {
      return null;
    }
  })
  .extend('faker', function() {
    try {
      return require('faker');
    } catch (e) {
      return null;
    }
  });
```

If you're requiring `json-schema-faker` as is it would include as well `chance`, `faker`, etc.

Instead you can require `json-schema-faker/lib` and provide the rest yourself, allowing you to reduce the bundle size, that's exactly what the "main" `index.js` does.

The impact should be minimum trust me, furthermore, this has advantages:

```js
// bloated entry-point
'use strict';

var jsf = require('json-schema-faker');

jsf.extend('faker', () => require('faker/locale/en_US'));

// slim entry-point
'use strict';

var jsf = require('json-schema-faker/lib');

jsf.extend('faker', () => require('faker/locale/en_US'));
```

The syntax has no changes, and I think is better than relying on pathmodify as you did.

**Comment by pateketrueke** [comment]
For further insights, see `build` scripts on both branches `master` for edge releases, and `v0.4.x` for legacy releases.

**Comment by pateketrueke** [comment]
Actually using `json-schema-faker/lib` was not encouraged since the `main` points to it by default, so using `require('json-schema-faker')` should be the right way.

That was because previously we were shipping `faker` and `chance` dependencies, and `lib` was a bare module without them.

Please let me know if this works for you.

Thanks for your feedback!
