### ISSUE TITLE
How can I prevent the faker for using null values

### ISSUE THREAD

**Issue by openStove** [json-schema-faker/json-schema-faker#561]
I would like the faker to generate a JSON out of a Schema, but I want the JSON to have all values set to something. Until now, I wasn't able to prevent it for generating some value with null

How could I do that ?

**Comment by pateketrueke** [comment]
Hi, please share the schema you're using to get the whole picture.

Currently we have an option for something similar, you can enable it as:

```js
jsf.option('defaultInvalidTypeProduct', 'string'); // any valid type
```

**Comment by pateketrueke** [comment]
I was thinking a little about this, probably adding support for all possible types, e.g.

```js
jsf.option('defaultInvalidTypeProduct', ['string', 'number'])
```

May be?
