### ISSUE TITLE
Pre-release labelling is not semver-compatible

### ISSUE THREAD

**Issue by 0rzech** [json-schema-faker/json-schema-faker#563]
Would it be possible to change pre-release labelling from `X.Y.Z-<something>N` to`X.Y.Z-<something>.N` to make it work with [semver](https://github.com/npm/node-semver) and [renovate](https://github.com/renovatebot/renovate)? As of now, the part after hyphen is sorted alphabetically including numbers, like explained [here](https://github.com/renovatebot/config-help/issues/111#issuecomment-428885398).

**Comment by pateketrueke** [comment]
Sure, so much thanks!

**Comment by 0rzech** [comment]
Pre-release versions work fine now (0d2f7dc, be758b2). Thanks a lot!
