### ISSUE TITLE
How do I generate dependent fields?

### ISSUE THREAD

**Issue by arnabguptadev** [json-schema-faker/json-schema-faker#564]
Great library - we are using this extensively to generate synthetic data.

Question - if a schema has two fields - field1 and field2 that depend on each other - e.g. BirthDate and DeceasedDate (DeceasedDate comes later) - some other cases are more complicated, is there a way to solve this?

I use the callback facility extensively and implemented my own functions to set values. But the define-registered override only returns the value specified and the schema, not the value of the actual json generated thus far, so that the current value can be set programmatically. 

For example if a callback handed a partially created json with BirthDate - we could set the DeceasedDate to a value since that date OR if it handed DeceasedDate first, we could set both so the library could skip BirthDate. Something along those lines.

Any suggestions welcome. Thanks again for the good work!

**Comment by pateketrueke** [comment]
Can you share what you're doing?

I want to understand exactly the scenario you're describing but I need more detail.

**Comment by arnabguptadev** [comment]
Sure, consider this JSON schema:
```
{
   "properties": {
        "BirthDate": {
             "type": "string",
             "format": "date"
        },
        "GraduationDate": {
             "type": "string",
             "format": "date"
        }
   }
}
```

Here. I can use JSON schema faker and the faker library to generate two random date values for each. But logically the GraduationDate value should be _after_ BirthDate. Currently, that cannot be controlled or enforced since the values are generated independently - making them sometimes right, sometimes wrong.

Is there a way to create a hook so I can either set both values programmatically or change the faking spec on the fly based on the other value?

May be there is a way to do this. Any suggestions will help.

**Comment by pateketrueke** [comment]
Probably what you need is only declaring `dependencies`, e.g.

```json
{
   "properties": {
        "BirthDate": {
             "type": "string",
             "format": "date"
        },
        "GraduationDate": {
             "type": "string",
             "format": "date"
        }
   },
   "dependencies": {
     "BirthDate": ["GraduationDate"]
   }
}
```

That's exactly what it means, if `BirthDate` is present then `GraduationDate` should be present too.

**Comment by arnabguptadev** [comment]
But how does that help to ensure that GraduationDate value should be after BirthDate?

**Comment by pateketrueke** [comment]
Well, that's a different topic, I think adding a custom keyword could work:

```js
jsf.define('afterDate', (value, schema, prop, cur) => {
  const birthDate = cur[value]; // value is "BirthDate"
  return new Date(birthDate);
});
```

To make it work you must add that keyword on your schema:

```json
{
   "properties": {
        "BirthDate": {
             "type": "string",
             "format": "date"
        },
        "GraduationDate": {
             "type": "string",
             "format": "date",
             "afterDate": "BirthDate"
        }
   },
   "dependencies": {
        "BirthDate": ["GraduationDate"]
   }
}
```

The remaining issue is that you should generate the date value by hand... but actually it would be useful to have something like `g.date.after(birthDate, 'years')` — what do you think?

**Comment by arnabguptadev** [comment]
Thank you! I do use the define call. And the example you have fiven is exactly what should work - i.e. the callback providing the current value:

I just wasn't sure it was passing that back. The documentation for defining custom keywords has this:

```
// 3.5 - extend keywords with custom generators
jsf.define('myProp', (value, schema) => schema);
```
May be it says elsewhere, but it dies not mention it passes back current value of the objet being generated as your last comment shows in example. That current value is all I need.

**Comment by pateketrueke** [comment]
Sorry, I'll update that back on the docs, but sure `prop` and `cur` will help you.

**Comment by arnabguptadev** [comment]
I will close this issue now. I really appreciate your help a lot!
