### ISSUE TITLE
How to generate unique values or tie values together

### ISSUE THREAD

**Issue by rodoabad** [json-schema-faker/json-schema-faker#566]
I'm wondering if this is possible with schema faker.

```
[
  {
    make: 'Honda',
    model: 'Civic'
  },
  {
    code: 'BMW',
    type: '2 series'
  },
  {
    code: 'BMW',
    type: '3 series'
  }
]
```

i.e. When code = BMW, then 2 or 3 series only.

**Comment by pateketrueke** [comment]
Currently there's no way to _check for values_ and then generate something based on that, I did not found any keyword on the JSON-Schema spec.

The stuff you can try is using `oneOf`, and then describing the possible schemas, etc.

**Comment by rodoabad** [comment]
Thanks, @pateketrueke as always we can handle this on the JS side after passing from schema faker. Thanks.

**Comment by arnabguptadev** [comment]
@rodoabad  - I had a slightly similar requirement as you may see from the discussion here - https://github.com/json-schema-faker/json-schema-faker/issues/564

It should be possible to write custom handlers to do this. I have not done this yet though. So far I have been doing like you plan to do - generate the fake value, then programmatically update it.

**Comment by pateketrueke** [comment]
Yeah, we can always hooks custom code through custom properties, e.g.

```js
jsf.define('fixThis', (value, schema, prop, cur) => {
  return fixItemsFrom(value); // do your work...
});
```

And then, you just declare such prop in your schema:

```json 
{
  "fixThis": true,
  "type": "array",
  "items": {
    ...
  }
}
```

**Comment by rodoabad** [comment]
@pateketrueke 

For something like...


```
type: object
minProperties: 3
useDefault: true
additionalProperties:
  type: array
  uniqueItems: true
  minItems: 3
  items:
    type: string
    x-chance:
      string

```

How do I use a formatter for the keys in a dictionary?

```
{
  "nulla1": [ <-----
    "c)FFhVosW",
    "8Z(I]X4!Nm9(aP4MHaK",
    "L[iHV^1)OL[CzDoEAv"
  ],
  "nulla_0a": [ <-----
    "T%x&0wQlCtLItk",
    "J&w9v",
    "Wij*16)Zt"
  ],
  "sunt_4": [ <-----
    "Cyi3(fr5Z$[V",
    "Zm#b4n",
    "2gp[YKJyoDLEWrt",
    "Ee4XO)t]livu&jANmNS",
    "X!V5Ar8c"
  ]
}
```

**Comment by pateketrueke** [comment]
Currently there's no way to format the keys added by `additionalProperties`, only if you use `patternProperties` you can pick the format for them as they are declared as regexp.
