### ISSUE TITLE
Unexpected behavior for allOf 

### ISSUE THREAD

**Issue by rachidlamouri** [json-schema-faker/json-schema-faker#567]
Version: `0.5.0-rcv.24`

This is a fairly contrived example, but I'm working on a library that takes user input and deeply merges it with data generated by jsf. I need to be able to control the length of the arrays that are created by jsf, so to test my code I used the following example:

Input JSON
```json
{
  "allOf": [
    {
      "type": "array",
      "items": [
        {
          "type": "integer",
          "minimum": 3
        },
        {
          "type": "integer",
          "minimum": 3
        }
      ],
      "additionalItems": false
    },
    {
      "type": "array",
      "items": [
        {
          "type": "integer",
          "maximum": 10
        },
        {
          "type": "integer",
          "maximum": 10
        }
      ],
      "additionalItems": false
    }
  ]
}
```

Actual Result from http://json-schema-faker.js.org/
```json
[
  74025346,
  94122464,
  -26341658,
  -84133810
]
```

Expected Result
An array of two integers where each integer is between 3 and 10 inclusive.

<hr>

I dug into the source code and printed out `sub` within the `run` method within the `if (Array.isArray(sub.allOf))` block. I got the following result which explains the fake data I was getting. However I would expect items to only have 2 schemas, not 4.

```javascript
{
  type: 'array',
  items: [
    { type: 'integer', minimum: 3 },
    { type: 'integer', minimum: 3 },
    { type: 'integer', maximum: 10 },
    { type: 'integer', maximum: 10 }
  ],
  additionalItems: false
}
```

**Comment by pateketrueke** [comment]
> However I would expect items to only have 2 schemas, not 4.

The `allOf` strategy actually merges all members (not an extend operation), so it's perfectly expected to have 4 schemas as result of that merge.

>  An array of two integers where each integer is between 3 and 10 inclusive.

It's better to start with that statement instead of juggling around with contrived schemas.

```json
{
  "type": "array",
  "items": {
    "type": "integer",
    "minimum": 3,
    "maximum": 10
  },
  "minItems": 2,
  "maxItems": 2
}
```

Is this what you're looking for? 🤔

**Comment by RachiLam** [comment]
> Is this what you're looking for? 

I'm not looking for a specific schema. I'm trying to make my library compatible with json-schema-faker and the rules of json-schema. My library produces functions that take partial user input, combine them with data generated by json-schema-faker and produces data that adheres to the original schema. Part of my strategy for getting jsf to generate data that is compatible with the user input is to take list array schemas and convert them to tuple array schemas. So although the example looks contrived its a very real example for my library.

> The allOf strategy actually merges all members (not an extend operation), so it's perfectly expected to have 4 schemas as result of that merge.

I understand what this strategy does for object schemas. For example the following schema:

```javascript
{
  allOf: [
    {
      type: 'object',
      properties: {
        field1: { type: 'string' },
      },
      required: ['field1'],
    },
    {
      type: 'object',
      properties: {
        field2: { type: 'number' },
      },
      required: ['field2'],
    },
  ],
}
```

After merging each of the allOf schemas:
```javascript
{
  type: 'object',
  properties: { 
    field1: { type: 'string' },
    field2: { type: 'number' }
  },
  required: [ 'field1', 'field2' ]
}
```

This strategy makes sense for objects, however this strategy does not make sense for the example I provided. According to the json-schema documentation each schema in an `allOf` should be evaluated independently of the others. For my original example, if json-schema-faker produces an array of 4 items then it is not adhering to the rules of the original schemas which each expect only 2 items in the array.

**Comment by pateketrueke** [comment]
> For my original example, if json-schema-faker produces an array of 4 items then it is not adhering to the rules of the original schemas which each expect only 2 items in the array.

Okay, I understand now what you're expecting.

I'm not pretty sure how to solve the root-cause, but you're welcome to improve our implementation.

The current strategy, as I said, is just a merge — in this case, how the members of `allOf` should be treated? For validation purposes makes perfect sense doing each by one, but... we're generating values, so in case of `items` they should be merged also independently, and not just concatenate the `items` array.

Regardles if what i'm describing is true you're very welcome to patch what we have, if it works for your it'll work for everyone! 🍻
