### ISSUE TITLE
alwaysFakeOptionals with type: ["string", "null"]

### ISSUE THREAD

**Issue by ndbroadbent** [json-schema-faker/json-schema-faker#568]
I've just started using `type: ["string", "null"]` in my schema so that people can send `null` for optional fields. I've been using `json-schema-faker` to generate random data for my schema with `alwaysFakeOptionals`, and I think `["string", "null"]` is now causing it to pick one of these randomly.

Would it be possible to add a special case for the `type: ["string", "null"]` convention, so that `json-schema-faker` ignores this and just uses `string`? Thanks!

**Comment by pateketrueke** [comment]
Interesting, if the type has `null` listed, ignore it and pick whatever else from the list?

**Comment by Renrhaf** [comment]
This feature could be useful, I agree.
Maybe using a key like "fakerIgnore" to exclude types during generation of fakes ?
```
{
  ...
  "oneOf": [
    {
      "type": "null",
      "fakerIgnore": true
    },
    {
      "type": "string"
    }
  ]
  ...
}
```

**Comment by AtakanColak** [comment]
I also would like to express a need to ignore null values for nullable fields. I'd like to generate a sample JSON from a JSON Schema, but I need to have all of the fields to have a non-null value.

**Comment by Adrian-ATG** [comment]
I don't think that the fix actually addressed the issue - the request was that given a property that has:
`"type": ["string", "null"]` then it would be interpreted as `"type": "string"`.
This would result in a JSON object that always includes a string value and never null.

The omitNulls flag still generates a JSON object with null values, but then it removes the nulls so the property does not exist in the object at all.

**Comment by zachkirsch** [comment]
I agree, `omitNulls` does not seem to fix this!
