### ISSUE TITLE
Required properties that result in empty objects get removed

### ISSUE THREAD

**Issue by mayacoda** [json-schema-faker/json-schema-faker#569]
I'm working with a schema that describes a lot of dictionaries of things. I've run into the problem that JSON Schema Faker removes objects which are required, but do not have a minimum number of properties. Validation of the fake JSON fails because these required properties are missing. I'm not using any options flags, just running `jsf.generate(schema)`

This is the schema
```
{
  "type": "object",
  "properties": {
    "things": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  },
  "required": [
    "things"
  ]
}
```

actual
```
{}
```

expected
```
{
  "things": {}
}
```

**Comment by pateketrueke** [comment]
Interesting, if you add `minProperties` inside your things object it'll work, but... I guess it would be nice if actually generates random props, so min-props can be randomized if not present?

**Comment by mayacoda** [comment]
The trouble with adding `minProperties` is that the `things` object is entirely valid if empty. By adding a non-zero `minProperties`, I would break validation in other places. Adding `minProperties: 0` generates the same result as above.

**Comment by pateketrueke** [comment]
We can implicitly add a random minimum of props if `additionalProperties` is present may be?

**Comment by mayacoda** [comment]
That might work, but ideally I'd like for empty objects which are required to not be removed. In certain cases, my code correctly handling empty objects is exactly what I want to test with dummy data. This is why it feels like a bug rather than a missing feature.

I'll open a PR with a suggested fix. I think I've figured out how to make what I want to happen. Then you can let me know if it even makes sense 😃

**Comment by pateketrueke** [comment]
Awesome, please go ahead. Thank you!

**Comment by mayacoda** [comment]
I've created and linked a pull request. I have to say thank you for making development and testing so easy in this project!

The idea behind the PR is to call the `clean` function after each `traverse` call returns a result, so a given subschema's `required` property can be taken into account. I ran into issues with the `refDepth` test and had to modify how `maxDepth` is calculated for each schema resolution. In my implementation, the maximum ref depth is taken, which I'm not happy with, but it was the only way I could figure out how to get the `refDepth` tests to pass. Otherwise, the result would always stop recursing sooner than expected.

**Comment by pateketrueke** [comment]
Awesome work! And so much thanks for solving it, as it already passed CI I'll merge it right now.

**Comment by RachiLam** [comment]
When the problem you're having was resolved 15 hours ago ... 😮

**Comment by mayacoda** [comment]
@pateketrueke Any idea when this will be released? 😁

**Comment by pateketrueke** [comment]
Hi @mayacoda surely not today, I want to see if I can fix/merge more stuff on this weekend, hopefully on sunday I'll release a new RC.
