### ISSUE TITLE
External file $refs cause an error

### ISSUE THREAD

**Issue by publicus** [json-schema-faker/json-schema-faker#571]
First, thank you for your ongoing work on this library!

I think that the `develop` branch is unable to handle external file `$ref`s that are on the local filesystem. I've added an example test (which fails) in [this forked branch](https://github.com/arcus/json-schema-faker/tree/fix-external-file-refs) -- a specific file comparison is [here](https://github.com/json-schema-faker/json-schema-faker/compare/develop...arcus:fix-external-file-refs?expand=1).

The failing schema looks like this:

```
"properties": {
  "person": {
    "$ref": "../../../external-ref-files/issue-TBD-external-ref.json#/definitions/externalExample"
  }
}
```

and the external `$ref` like this:

```
{
  "definitions": {
    "externalExample": {
      "type": "string"
    }
  }
}
```

I've confirmed this behavior both when the external `$ref` file is in the same directory as the main schema, and also when the external file is in the calling shell's `pwd`. I've also confirmed that it fails with absolute paths.

When running the tests mentioned above with `npm run dev`, I get an error:

```
     Cannot read property 'properties' of undefined (50 of 50)
      at visit (node_modules/is-my-json-valid/index.js:141:27)
      at /path/to/json-schema-faker/node_modules/is-my-json-valid/index.js:543:9
      at Array.forEach (<anonymous>)
      at visit (node_modules/is-my-json-valid/index.js:540:31)
      at compile (node_modules/is-my-json-valid/index.js:565:3)
      at module.exports (node_modules/is-my-json-valid/index.js:594:10)
      at checkSchema (tests/schema/validator.js:55:13)
      at /path/to/json-schema-faker/tests/schema/helpers.js:75:9
      at async Promise.all (index 0)
```

I know that this behavior used to work, so I'm not sure whether this is due to a change in `jsonschema-ref-parser`. **I've narrowed down that commenting out [this line](https://github.com/json-schema-faker/json-schema-faker/blob/develop/src/lib/index.js#L114) fixes the error** (for this test). I'm not sure what that line does, though, as I wasn't able to find relevant documentation about `fixedRefs` in the [`jsonschema-ref-parser` documentation](https://apitools.dev/json-schema-ref-parser/docs/options.html).

I'd be grateful to talk through this, and happy to help contribute to fixing it, if you agree that it's a bug! I'm at a point now where, to progress, I think I need guidance on what `fixedRefs` is doing. Does this look like a bug to you?

Again, thank you for your work!

**Comment by pateketrueke** [comment]
`fixedRefs` is the [default loader](https://github.com/json-schema-faker/json-schema-faker/blob/develop/src/lib/index.js#L97-L107) strategy for jsonschema-ref-parser, they are ordered and since `fixedRefs`' order is 1 it runs first.

In this handler we're only check if the requested ref is present within `$refs`, if not then the remaining resolvers are used in order: file, http.

If you commented that line it means no custom loader is used, and given `$refs` are not longer suitable for user extension — consider, instead, fixing what `fixedRefs` does in the particular case you're describiing.

Remember you can provide a `cwd` to hint file-loader to resolve properly, make sure you're setting it up accordingly during the `jsf(schema, refs, cwd)`. calls.

**Comment by publicus** [comment]
@pateketrueke, thank you very much for that guidance! I had read about `file` and `http` in the [`jsonschema-ref-parser` documentation](https://github.com/APIDevTools/json-schema-ref-parser/blob/master/docs/options.md), but hadn't understood that other loaders could have arbitrary names (hence my confusion about `fixedRefs`).

I've opened #573 just now to propose a change.

**Comment by pateketrueke** [comment]
> but hadn't understood that other loaders could have arbitrary names

Yeah, and me being very bad at naming things... 😆

**Comment by publicus** [comment]
@pateketrueke Just to confirm: I'm happy to close this issue at this point; do you prefer to leave it open?

(I'm writing just because I'm not sure whether you're waiting on me to close it, so I wanted to check.)

**Comment by pateketrueke** [comment]
It'll be closed as soon I merge it back to master, don't worry about closing it rn. :)

I'll be working on that this weekend, thank you.

**Comment by publicus** [comment]
Ok, thank you! : )
