### ISSUE TITLE
Can´t use library cause an error

### ISSUE THREAD

**Issue by vikktor1989** [json-schema-faker/json-schema-faker#576]
Hi, I´m trying to use this library to generate some fake data in Angular 9, but I can´t cause an error when I tried to visualize the data throw de console.
I use this code in my app.component.ts
`
import { Component } from '@angular/core';
import jsf from 'json-schema-faker';

const schema = {
  type: 'object',
  properties: {
    user: {
      type: 'object',
      properties: {
        id: {
          $ref: '#/definitions/positiveInt'
        },
        name: {
          type: 'string',
          faker: 'name.findName'
        },
        email: {
          type: 'string',
          format: 'email',
          faker: 'internet.email'
        }
      },
      required: ['id', 'name', 'email']
    }
  },
  required: ['user'],
  definitions: {
    positiveInt: {
      type: 'integer',
      minimum: 0,
      exclusiveMinimum: true
    }
  }
};

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  
  // @ts-ignore
  faker() {
    // use the async-version (preferred way)
    jsf.resolve(schema).then(sample => {
      console.log(sample);
      // "[object Object]"

      console.log(sample.user.name);
      // "John Doe"
    });
  }
}`

And, in the app.component.html I use 
`<button (click)="faker()"> Log </button>`

When I used ng serve to test the result in the console I got this error:
VM356 vendor.js:15247 ERROR TypeError: json_schema_faker__WEBPACK_IMPORTED_MODULE_1___default.a.resolve is not a function
    at AppComponent.faker (VM354 main.js:172)
    at AppComponent_Template_button_click_0_listener (VM354 main.js:183)
    at executeListenerWithErrorHandling (VM356 vendor.js:29744)
    at wrapListenerIn_markDirtyAndPreventDefault (VM356 vendor.js:29786)
    at HTMLButtonElement.<anonymous> (VM356 vendor.js:54471)
    at ZoneDelegate.invokeTask (VM355 polyfills.js:412)
    at Object.onInvokeTask (VM356 vendor.js:47104)
    at ZoneDelegate.invokeTask (VM355 polyfills.js:411)
    at Zone.runTask (VM355 polyfills.js:180)
    at ZoneTask.invokeTask [as invoke] (VM355 polyfills.js:493)

Maybe is something I´m doing wrong. 
Greetings

**Comment by pateketrueke** [comment]
Can you confirm which version is installed in your package.json?

You should have installed the latest RC, which currently is `0.5.0-rcv.24` — probably this is the issue.

**Comment by vikktor1989** [comment]
Problem solved. I had another version. Thanks for your help!!

**Comment by sanuradhag** [comment]
> Problem solved. I had another version. Thanks for your help!!

what was the angular version and the json-schema-faker version?
