### ISSUE TITLE
Found false positive tests that are supposed to throw

### ISSUE THREAD

**Issue by rachidlamouri** [json-schema-faker/json-schema-faker#579]
In this PR https://github.com/json-schema-faker/json-schema-faker/pull/578 I forced the schema tests to fail if "throw" was specified on the test case, but the test didn't actually throw. I'm opening this issue as an action item to investigate some tests that should be throwing, since that's out of scope for the linked PR. The linked PR just skips the tests for now.

**Comment by RachiLam** [comment]
Started working on this https://github.com/RachiLam/json-schema-faker/tree/fix-579

**Comment by RachiLam** [comment]
@pateketrueke I couldn't figure out the best way to fix the other 6 tests. When  #578 gets merged I'll put a PR up for the one test I fixed.
