### ISSUE TITLE
An anniversary? ;)

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#58]
Soon we'll reach 100 stars on github. What d'ya think of introducing a logo for jsf? Here's my fast suggestion:

![json-schema-faker](https://cloud.githubusercontent.com/assets/375027/9182532/3cdcc220-3fab-11e5-900a-997dc28b60fb.jpg)

this is where the original image comes from: http://www.devilsgarage.com/character-design/the-illusionist/

**Comment by pateketrueke** [comment]
I like it, I hope the author can grant permission of use. :+1:
