### ISSUE TITLE
Utils.validate does not behave as stated

### ISSUE THREAD

**Issue by rachidlamouri** [json-schema-faker/json-schema-faker#580]
The comment before utils.validate is run states:

> // test every value from the enum against each-oneOf
> // schema, only values that validate once are kept

The function itself returns true when the value is invalid for at least one schema, which is not the same as being valid for only one schema.

```javascript
function validateValueForOneOf(value, oneOf) {
  return !oneOf.every(schema => validateValueForSchema(value, schema));
}
```

The following schema test case will fail:

```json
{
  "only": true,
  "description": "should apply oneOf for overlapping minimum/maximum",
  "schema": {
    "type": "integer",
    "enum": [1, 2, 3, 4, 5, 6, 7, 8, 9],
    "oneOf": [
      {
        "minimum": 2,
        "maximum": 6
      },
      {
        "minimum": 4,
        "maximum": 8
      }
    ]
  },
  "repeat": 10,
  "valid": true
},
```

**Comment by RachiLam** [comment]
I already have a fix for this. Will make a PR shortly
