### ISSUE TITLE
Json-schema-faker doesn't work as expected with "contains" keyword

### ISSUE THREAD

**Issue by dsolanki97** [json-schema-faker/json-schema-faker#585]
Input Schema 
`{
  "type": "object",
  "required": [
    "Header"
  ],
  "properties": {
    "Header": {
      "type": "object",
      "required": [
        "Address"
      ],
      "properties": {
        "Address": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "AddressTypeCode"
            ],
            "properties": {
              "AddressTypeCode": {
                "type": "string"
              }
            }
          },
          "minItems": 2,
          "allOf": [
            {
              "contains": {
                "required": [
                  "AddressTypeCode"
                ],
                "type": "object",
                "properties": {
                  "AddressTypeCode": {
                    "type": "string",
                    "enum": [
                      "ST"
                    ]
                  }
                }
              }
            },
            {
              "contains": {
                "required": [
                  "AddressTypeCode"
                ],
                "type": "object",
                "properties": {
                  "AddressTypeCode": {
                    "type": "string",
                    "enum": [
                      "SF"
                    ]
                  }
                }
              }
            }
          ]
        }
      },
      "description": "Encloses all document header elements."
    }
  }
}`

Result from : https://json-schema-faker.js.org/
`{
  "Header": {
    "Address": [
      {
        "AddressTypeCode": "est adipisicing magna cillum voluptate"
      },
      {
        "AddressTypeCode": "cillum in sint dolor"
      }
    ]
  }
}`

Expected Result : 
`{
  "Header": {
    "Address": [
      {
        "AddressTypeCode": "ST"
      },
      {
        "AddressTypeCode": "SF"
      }
    ]
  }
}`

**Comment by pateketrueke** [comment]
Interesting, I haven't heard of the `contains` keyword yet, seems like we should just ignore it, thanks for your input!

**Comment by dsolanki97** [comment]
Didn't knew that faker does not support "contains". Will be great if it would be supported in the future.

**Comment by pateketrueke** [comment]
> Didn't knew that faker does not support "contains". Will be great if it would be supported in the future.

Yeah, I'll consider that but not sure (yet) how it should behave then. Thank you!

**Comment by McPetersonGH** [comment]
I second the support for contains groups!

**Comment by Hades32** [comment]
@pateketrueke just got caught by this. Why can't we just generate one item that conforms to the `contain`'s json schema and place it at a random (valid) index in the array after it has been filled randoms?

**Comment by pateketrueke** [comment]
> Why can't we just generate one item that conforms to the contain's json schema and place it at a random (valid) index in the array after it has been filled randoms?

Sounds doable that way, let me know if you want to tackle this, I'll investigate later otherwise. Thank you!
