### ISSUE TITLE
Empty required objects are not generated

### ISSUE THREAD

**Issue by phb** [json-schema-faker/json-schema-faker#586]
Json schema:
```
{
  "id": "Profile",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "object",
      "properties": {
        "foo": {
          "type": "object",
          "properties": {}
        }
      },
      "required": [
        "foo"
      ]
    }
  },
  "required": [
    "firstName"
  ]
}
```

I would expect this to always generate.
```
{
"firstName": {
"foo": {}
}
```

But instead it generates
```
{
  "firstName": {}
}
```

This seems to happen because of the clean() method in run.js that removes empty objects.

**Comment by pateketrueke** [comment]
You're right, that should work now under `develop` if you want to test it out — I'll be releasing a patch soon, thank you!

**Comment by phb** [comment]
Hi @pateketrueke, thanks for this. in develop I'm seeing another issue where required (empty) objects are generated with null. I'm trying to figure out a testcase and will post here.

**Comment by pateketrueke** [comment]
Thank you, that would help me to solve and close this sooner!

**Comment by phb** [comment]
Hi @pateketrueke, I haven't yet been able to reproduce the 'null' issue with a schema I can share. However, the following schema fails to generate a required object when it should.

issue-586.json:
```
[
    {
      "description": "Nested object sometimes null",
      "tests": [
        {
          "description": "Make  sure not  null",
          "schema": {
            "id": "Profile",
            "type": "object",
            "properties": {
              "firstName": {
                "type": "object",
                "properties": {
                  "foo": {
                    "type": "object",
                    "properties": {
                        "bar": {
                            "type": "object",
                            "properties": {}
                        }
                    },
                    "required": [
                        "bar"
                    ]
                  }
                }
              }
            },
            "required": [
              "firstName"
            ]
          },
          "valid": true
        }
      ]
    }
  ]
```

With latest develop and using         'alwaysFakeOptionals': true,  this generates

```
{
  "firstName": {
    "foo": {}
  }
}
```

**Comment by phb** [comment]
Figured it out.
It's a difference between json-schema draft-v04 and the latest draft which I'm (notably, not using any fancy new features). In my schema I set
required: [], which is valid in the latest json-schema but not in v04.

That in turn triggers this code in object.js
```
  if (!allowsAdditional
    && propertyKeys.length === 0
    && patternPropertyKeys.length === 0
    && utils.hasProperties(value, 'minProperties', 'maxProperties', 'dependencies', 'required')
  ) {
    // just nothing
    return null;
  }
```

Even though I believe JSF only supports draft-04, I suspect that anytime the above condition triggers it'll end up with an invalid schema (as null is not a valid object) -- that said, I haven't dug too deep into the code.


Thank you
/Johan

**Comment by phb** [comment]
The actual issue is a bug in utils.js:clean.

Whenever that function recurses, it passes the same schema, instead of an updated schema for the new field. Ie, specifically on line 401 it needs to pass schema.properties[k].

with that said, I don't know what. the behaviour should be if there are things like additionalProperties etc, so will leave the proper fix to someone more experienced in the codebase.

FYI @mayacoda

**Comment by phb** [comment]
I just filed #587 which is a related issue.

@pateketrueke What is the purpose of the 'cleaning' of the generated data? To me it seems like it adds a lot of complexity and I don't see any real point -- why should the faker remove empty objects if the schema claims empty objects are OK?

**Comment by cmawhorter** [comment]
and this will only happen if the object is a child and not top-level property. 

for example, with this:

```json
{
  "type": "object",
  "properties": {
    "tags": {
      "type": "array",
      "maxItems": 3,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "tag": {
            "type": "string",
            "minLength": 1,
            "maxLength": 20
          },
          "attributes": {
            "type": "object",
            "maxProperties": 4,
            "additionalProperties": {
              "type": "string"
            }
          }
        },
        "required": [
          "tag",
          "attributes"
        ]
      }
    },
    "metadata": {
      "type": "object",
      "maxProperties": 20,
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}
```

that generates the following, which includes the empty object "metadata" but not empty object "attributes".
```js
{
  // these entries should include: `"attributes": {}`
  "tags": [
    {
      "tag": "exe"
    },
    {
      "tag": "ea"
    },
    {
      "tag": "ex tempor Lorem"
    }
  ],
  "metadata": {}
}
```

i have not found a workaround other than to manually parse/fix the result.
