### ISSUE TITLE
Data is not getting generated for all the properties, few properties are missing.

### ISSUE THREAD

**Issue by KarthikGowdaUN** [json-schema-faker/json-schema-faker#592]
Data is not getting generated for all the properties, have to try couple of times, then only it gets generated for all the properties.
Even if the data is generated, not all the objects inside an array will have all the properties, out of 5 objects, only one will have all the properties..
Attached is the schema file, which i used for testing purpose.

**Suggestion** : If the element is an array, try copying all the properties in all the objects or just return the object, which has all the properties.
[schema_v4.txt](https://github.com/json-schema-faker/json-schema-faker/files/4778250/schema_v4.txt)

**Comment by pateketrueke** [comment]
Can you test the same schema against the develop sources? Thank you!

**Comment by KarthikGowdaUN** [comment]
@pateketrueke , I tested this in angular project installing it via npm, tried both 
npm install typescript-json-schema-faker
npm install json-schema-faker

by calling asyncFake() and resolve() method..it doesn't produce the data for all the properties, have to recursively call the methods..

Regards,
Karthik

**Comment by pateketrueke** [comment]
Which version are you using then?

I tried your schema in our online webapp and seems to be working: https://json-schema-faker.js.org/#gist/38b5265c5f54eea8c7d6c65948b7b616

**Comment by KarthikGowdaUN** [comment]
@pateketrueke , I'm using the latest version.

I tried the below schema in both online webapp as well as npm package. It's not generating any value, page is becoming unresponsive
[schema_v4_1.txt](https://github.com/json-schema-faker/json-schema-faker/files/4869467/schema_v4_1.txt)

**Comment by pateketrueke** [comment]
I see, the references in such schema are causing too much recursion: `Error: RangeError: Maximum call stack size exceeded`

I'll investigate more about this issue, thank you!
