### ISSUE TITLE
The $ref not working as expected

### ISSUE THREAD

**Issue by sshim-cb** [json-schema-faker/json-schema-faker#595]
I'm not sure if this is a bug or misconfigurations from my end:
1. {
                    $id: 'chat',
                    type: 'array',
                    minItems: 1,
                    maxItems: 1,
                    items: {
                        type: 'object',
                        properties: {
                            conversationTimestamp: {
                                type: 'string'
                            },
                            conversationId: {
                                type: 'string'
                            },
                            content: {
                                type: 'object',
                                properties: {
                                    contentType: {
                                        enum: ['CHAT']
                                    },
                                    participants: {
                                        type: 'array',
                                        items: {
                                            type: 'object',
                                            properties: {
                                                participantId: {
                                                    type: 'string'
                                                },
                                                participantType: {
                                                    type: 'string',
                                                    enum: ['AGENT', 'CLIENT', 'TYPE_UNKNOWN']
                                                },
                                                participantName: {
                                                    type: 'string'
                                                }
                                            },
                                            required: ['participantId', 'participantType']
                                        }
                                    },
                                    conversationContent: {
                                        type: 'array',
                                        items: {
                                            type: 'object',
                                            properties: {
                                                participantId: {
                                                    type: 'string',
                                                    $ref:
                                                        '#/items/properties/content/properties/participants/items/properties/participantId'
                                                },
                                                text: {
                                                    type: 'string'
                                                },
                                                timestamp: {
                                                    type: 'string'
                                                },
                                                id: {
                                                    type: 'string'
                                                }
                                            },
                                            required: ['participantId', 'text', 'timestamp']
                                        }
                                    }
                                },
                                required: ['contentType', 'participants', 'conversationContent']
                            }
                        },
                        required: ['conversationId', 'conversationTimestamp', 'content'],
                        additionalProperties: true
                    }
2. when I call the jsf.resolve(), I would like to see the participantId in participants array in conversationContent.
3. I still see random value for the participantId in conversationContent.

Please advise and thank you in advance!

**Comment by pateketrueke** [comment]
Hi, please give appropriate format to your JSON-Schema, otherwise is difficult to read it.

Also try to see if your same schema works on the online tool: https://json-schema-faker.js.org/ — Thank you!

**Comment by sshim-cb** [comment]
```
{
   "$id": "chat",
   "type": "array",
   "minItems": 1,
   "maxItems": 1,
   "items": {
      "type": "object",
      "properties": {
         "conversationTimestamp": {
            "type": "string"
         },
         "conversationId": {
            "type": "string"
         },
         "content": {
            "type": "object",
            "properties": {
               "contentType": {
                  "enum": [
                     "CHAT"
                  ]
               },
               "participants": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "properties": {
                        "participantId": {
                           "type": "string"
                        },
                        "participantType": {
                           "type": "string",
                           "enum": [
                              "AGENT",
                              "CLIENT",
                              "TYPE_UNKNOWN"
                           ]
                        },
                        "participantName": {
                           "type": "string"
                        }
                     },
                     "required": [
                        "participantId",
                        "participantType"
                     ]
                  }
               },
               "conversationContent": {
                  "type": "array",
                  "items": {
                     "type": "object",
                     "properties": {
                        "participantId": {
                           "type": "string",
                           "$ref": "#/items/properties/content/properties/participants/items/properties/participantId"
                        },
                        "text": {
                           "type": "string"
                        },
                        "timestamp": {
                           "type": "string"
                        },
                        "id": {
                           "type": "string"
                        }
                     },
                     "required": [
                        "participantId",
                        "text",
                        "timestamp"
                     ]
                  }
               }
            },
            "required": [
               "contentType",
               "participants",
               "conversationContent"
            ]
         }
      },
      "required": [
         "conversationId",
         "conversationTimestamp",
         "content"
      ],
      "additionalProperties": true
   }
}
```
Above is the schema, and I also tried in the website and didn't find any luck.

**Comment by pateketrueke** [comment]
Can you elaborate on what you're expecting from? Thank you!

This is what I got from the webapp:

```json
[
  {
    "conversationId": "ea proident non",
    "conversationTimestamp": "sunt",
    "content": {
      "contentType": "CHAT",
      "participants": [
        {
          "participantId": "proident minim reprehenderit eu",
          "participantType": "CLIENT"
        },
        {
          "participantId": "non anim",
          "participantType": "CLIENT"
        },
        {
          "participantId": "ad sunt anim tempor",
          "participantType": "TYPE_UNKNOWN",
          "participantName": "mollit ut"
        },
        {
          "participantId": "laboris deserunt do enim",
          "participantType": "CLIENT",
          "participantName": "in proident officia"
        }
      ],
      "conversationContent": [
        {
          "participantId": "sint veniam amet commodo voluptate",
          "text": "non sed tempor",
          "timestamp": "officia laborum ut",
          "id": "nisi magna ut consequat cupidatat"
        },
        {
          "participantId": "laboris sed consectetur",
          "text": "velit",
          "timestamp": "exercitation nisi dolore eiusmod",
          "id": "ipsum"
        },
        {
          "participantId": "consequat minim",
          "text": "id",
          "timestamp": "cupidatat",
          "id": "ea in elit qui id"
        },
        {
          "participantId": "tempor adipisicing in",
          "text": "nostrud commodo",
          "timestamp": "aute ut",
          "id": "magna consequat"
        },
        {
          "participantId": "mollit magna qui dolor",
          "text": "esse culpa",
          "timestamp": "et Ut",
          "id": "ex"
        }
      ]
    }
  }
]
```

**Comment by sshim-cb** [comment]
I want to see the participantId in conversationContent array to be referenced from participantId in participant array.

**Comment by pateketrueke** [comment]
Sorry, I misread your initial comments:

> I would like to see the participantId in participants array in conversationContent.

OK but `$ref`s does not work that way, they are for referencing other schemas but that does not mean values are actually linked...

> I still see random value for the participantId in conversationContent.

And that's fine, because using a `$ref` will only refer to that schema, not the value...

Instead you must use jsonPath in order to match from generated results, e.g.

```json
{
  "$id": "chat",
  "type": "array",
  "minItems": 1,
  "maxItems": 1,
  "items": {
    "type": "object",
    "properties": {
      "conversationTimestamp": {
        "type": "string"
      },
      "conversationId": {
        "type": "string"
      },
      "content": {
        "type": "object",
        "properties": {
          "contentType": {
            "enum": [
              "CHAT"
            ]
          },
          "participants": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "participantId": {
                  "type": "string"
                },
                "participantType": {
                  "type": "string",
                  "enum": [
                    "AGENT",
                    "CLIENT",
                    "TYPE_UNKNOWN"
                  ]
                },
                "participantName": {
                  "type": "string"
                }
              },
              "required": [
                "participantId",
                "participantType"
              ]
            }
          },
          "conversationContent": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "participantId": {
                  "type": "string",
                  "jsonPath": "$..content.participants[*].participantId"
                },
                "text": {
                  "type": "string"
                },
                "timestamp": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                }
              },
              "required": [
                "participantId",
                "text",
                "timestamp"
              ]
            }
          }
        },
        "required": [
          "contentType",
          "participants",
          "conversationContent"
        ]
      }
    },
    "required": [
      "conversationId",
      "conversationTimestamp",
      "content"
    ],
    "additionalProperties": true
  }
}
```

Enable that with `jsf.option({ resolveJsonPath: true })` before generating a sample:

```json
[
  {
    "conversationId": "laborum quis in sit",
    "conversationTimestamp": "ut ut",
    "content": {
      "contentType": "CHAT",
      "participants": [
        {
          "participantId": "eu",
          "participantType": "AGENT",
          "participantName": "Excepteur veniam et tempor"
        },
        {
          "participantId": "culpa",
          "participantType": "CLIENT",
          "participantName": "consequat consectetur Excepteur sit enim"
        },
        {
          "participantId": "consectetur",
          "participantType": "TYPE_UNKNOWN",
          "participantName": "exercitation"
        },
        {
          "participantId": "ad",
          "participantType": "CLIENT",
          "participantName": "Excepteur ad veniam"
        },
        {
          "participantId": "laboris aliqua",
          "participantType": "CLIENT",
          "participantName": "ipsum laboris dolor sunt"
        }
      ],
      "conversationContent": [
        {
          "participantId": "eu",
          "text": "dolore mollit",
          "timestamp": "ea anim ut irure labore",
          "id": "laboris aliquip culpa fugiat anim"
        },
        {
          "participantId": "consectetur",
          "text": "dolor deserunt",
          "timestamp": "sed",
          "id": "commodo ut"
        },
        {
          "participantId": "ad",
          "text": "dolore aliqua",
          "timestamp": "ea commodo",
          "id": "dolore sunt"
        },
        {
          "participantId": "laboris aliqua",
          "text": "nulla",
          "timestamp": "ut incididunt dolore Duis sunt",
          "id": "sint anim"
        },
        {
          "participantId": "consectetur",
          "text": "sint cupidatat sit",
          "timestamp": "velit enim in pariatur est",
          "id": "irure"
        }
      ]
    }
  }
]
```

PS: the website is broken when you enable jsonPath there, sorry for that — I'll be fixing it asap, thank you!
