### ISSUE TITLE
Json Schema Faker produces sometimes namespaces uuids, sometimes not

### ISSUE THREAD

**Issue by XVincentX** [json-schema-faker/json-schema-faker#600]
@pateketrueke It seems like something has broken this. The new file I can find has the same "problem" we fixed some time ago. Is there anything I am missing? I can't find where the specific change happened. https://github.com/json-schema-faker/json-schema-faker/blob/master/src/lib/generators/coreFormat.js#L24

_Originally posted by @XVincentX in https://github.com/json-schema-faker/json-schema-faker/pull/526_

This seems to be a regression on something we fixed some time ago.

**Comment by XVincentX** [comment]
@pateketrueke Unfortunately the problem seem to be back again with rc28:

https://app.circleci.com/pipelines/github/stoplightio/prism/7151/workflows/d9b7419d-cd03-4f3f-8474-db365c288375/jobs/14464

**Comment by pateketrueke** [comment]
Thanks for noticing it @XVincentX — I just deprecate RC28 and released RC29, double checked the regression is gone! :beers:
