### ISSUE TITLE
Randomly required properties based on the same enum reference type aren't generated

### ISSUE THREAD

**Issue by yanekk** [json-schema-faker/json-schema-faker#601]
I'm having troubles with generating objects from schema which has two properties based on the same reference. The problem is the the second property is not always generated (totally random).
Example schema:
```
{
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "property1": {
      "$ref": "#/definitions/Enum"
    },
    "property2": {
      "$ref": "#/definitions/Enum"
    }
  },
  "definitions": {
    "Enum": {
      "type": "integer",
      "description": "",
      "enum": [ 1 ]
    }
  }
}
```
Running it on the https://json-schema-faker.js.org/ with the default options (I also checked different, most probable options set) always generates `property1`, but the `property2` appears from only time to time, while it's expected to be consistent since both properties aren't marked as optional. Moreover, switching order of those properties makes `property2` to appear everytime, but `property1` only occassionally.

**Comment by pateketrueke** [comment]
Interesting, seems like we have an outdated version on the running webapp.

Please install `v0.5.0-rcv.27` in your project, it seems to be working now.

**Comment by yanekk** [comment]
@pateketrueke I thought the same, but I double checked it and the version in my setup is up to date. What's more is that the https://json-schema-faker.js.org/ the same behaviour is observable - it's just matter of enough number of clicking on "Generate example" button. So it raises a question of version on the webpage then. I also didn't mention I'm running both (node.js and webpage) on Windows.

I also fetched newest master from Github and created a test with the same parameters as above. The result is not deterministic, but it fails after few tries. I'll attach the test code once I get back to my work PC.

**Comment by yanekk** [comment]
Here's the test:
```javascript
import { expect } from 'chai';
import { v1 as generateGuid } from 'uuid';
import jsf from '../../../src/lib';

describe('Enum Generation', () => {
  it('should generate enum value based on a provided ref', () => {
    jsf.option({
      alwaysFakeOptionals: true,
    });

    const schema = {
      type: 'object',
      additionalProperties: false,
      properties: {
        property1: {
          $ref: '#/definitions/Enum',
        },
        property2: {
          $ref: '#/definitions/Enum',
        },
      },
      definitions: {
        Enum: {
          type: 'integer',
          description: '',
          enum: [1],
        },
      },
    };
    jsf.format({
      guid() {
        return generateGuid();
      },
    });

    for (let i = 0; i < 100; i++) {
      const generated = jsf.generate(schema);
      expect(Object.keys(generated)).to.contain('property1').and.to.contain('property2');
      expect(generated.property1).to.be.eq(1);
      expect(generated.property2).to.be.eq(1);
    }

    return jsf.resolve(schema).then(generated => {
      expect(Object.keys(generated)).to.contain('property1').and.to.contain('property2');
      expect(generated.property1).to.be.eq(1);
      expect(generated.property2).to.be.eq(1);
    });
  });
});
```
It deliberately repeats the generation few times since the error is undeterministic. What's interesting is the test fails on master (which is juuust after `0.5.0-rcv27` mentioned above) but not on develop:

test result on master:
```
  1) Enum Generation
       should generate enum value based on a provided ref:
     AssertionError: expected [ 'property1' ] to include 'property2'
      at Context.<anonymous> (tests\unit\generators\enum.spec.js:42:17)
      at processImmediate (internal/timers.js:456:21)
      at process.topLevelDomainCallback (domain.js:137:15)
```

test result on develop:
```
  Enum Generation
    √ should generate enum value based on a provided ref
```
Running tests on Windows 10, Node.JS v14.4.0

**Comment by pateketrueke** [comment]
Interesting, I think it's time to make develop our new master, because it is getting outdated overtime...

**Comment by pateketrueke** [comment]
Hi, new version released from develop branch this week! 💣 

Could you help me on adding your test? (preferably as json, see how other issues are tested/covered on the tests folder)

**Comment by yanekk** [comment]
> Hi, new version released from develop branch this week! 💣
> 
> Could you help me on adding your test? (preferably as json, see how other issues are tested/covered on the tests folder)

here's the schema test. I put it into `schema/core/issues/issue-601.json`. Surprisingly, it gives three different results: 
 - all two properties are generated
 - no properties are generated
 - only property1 is generated
I haven't encounter a situation of property2 generated alone.

```
[
  {
    "description": "Generation of two required properties based on the same enum reference type",
    "tests": [
      {
        "description": "make sure required properties based on the same enum reference type are always generated",
        "schema": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "property1": {
              "$ref": "#/definitions/Enum"
            },
            "property2": {
              "$ref": "#/definitions/Enum"
            }
          },
          "definitions": {
            "Enum": {
              "type": "integer",
              "description": "",
              "enum": [ 1 ]
            }
          }
        },
        "repeat": 100,
        "equal": {
          "property1": 1,
          "property2": 1
        },
        "valid": true
      }
    ]
  }
]
```
Another observation: setting `alwaysFakeOptionals` in the JSON always returns both properties. Does it mean that if the property is not in the "required" list of the schema, it won't be generated? The test I presented earlier has the `alwaysFakeOptionals` set, yet it throws error occasionally.

**Comment by pateketrueke** [comment]
Thank you, lets examine what happened:

- all two properties are generated — nice!
- no properties are generated — also good
- only property1 is generated — great, but it should generate property2 instead sometimes...

> Does it mean that if the property is not in the "required" list of the schema, it won't be generated?

No, by default all non-required properties are shuffled and generated randomly (hence property2 should appear eventually alone) and required are always genereted.

I liked the result of the tests but having property2 never generated alone smells like a bug... 🤔
