### ISSUE TITLE
Fields missing when using "allOf" inside "definitions"

### ISSUE THREAD

**Issue by grammati** [json-schema-faker/json-schema-faker#603]
Required fields are missing when using `allOf` in a definition.

https://json-schema-faker.js.org/#gist/9fcfc92927101eef178b89c19c2d9f02

Output:

```
{
  "a": "pariatur culpa",
  "d": "ipsum dolor"
}
```

Expected: should have fields `b` and `c`.

Thanks!

**Comment by pateketrueke** [comment]
Interesting, seems to be fixed on current develop branch, can you take a look? Thank you!

**Comment by grammati** [comment]
Yes, it does work as expected on the develop branch. That's great!

Are there npm packages published from the develop branch?

**Comment by pateketrueke** [comment]
Sadly no, let me schedule a merge/release from develop branch back to master this week, I'll update this post once done.

**Comment by pateketrueke** [comment]
Released as RC 28, also the webapp is up-to-date and working with your schema! :beers:
