### ISSUE TITLE
YAML output

### ISSUE THREAD

**Issue by zepatrik** [json-schema-faker/json-schema-faker#609]
Adding a YAML/... output option would be nice. I know that one could convert the resulting JSON to YAML or something else, but my use case actually requires directly outputting YAML. I would like to add `"description"` tags to the output in the form of comments. That way I can auto-generate parts of the documentation. Is this something you would merge? I have written something similar in go but very specific for one project. My hope is that we can replace it with JSON Schema Faker.

**Comment by pateketrueke** [comment]
Sounds like a very interesting idea, but how you'll manage the convertion? e.g.

```json
{
  "type": "integer",
  "minimum": 600,
  "maximum": 700,
  "multipleOf": 7,
  "exclusiveMinimum": true,
  "description": "something useful to spit out as YAML comment?"
}
```

Invoking `jsf.generate()` will return a random integer, so how the yaml-output would work? 🤔

**Comment by zepatrik** [comment]
I would like your example to e.g. result in:
```yaml
# something useful to spit out as YAML comment?
630
```

**Comment by zepatrik** [comment]
The explicit problem right now is auto generating https://golangci-lint.run/usage/configuration/#config-file from https://github.com/SchemaStore/schemastore/pull/1312

**Comment by pateketrueke** [comment]
Oh I got you now, interesting use-case I hope you're using `default` or using a fixed seed to always generate the same sample, otherwise you'll get random samples each time you generate your YAML.

I like the idea, I mean, but still not sure how you're going to acomplish it — so, if you want to tackle this one feel free to open a PR once you have something working.

> Just thinking loudly, if you wrap every generator in yaml-mode, you could generate the output you'll need?

**Comment by zepatrik** [comment]
I had a quick look at the code, I will draft a PR once I figure out how to approach this. I might add some kind of context where you could add meta stuff like comments that can then be used for rendering, just to make this reusable for the future.

**Comment by liuxiran** [comment]
Sound cool and it will be helpful for me too, may I ask how's this issue going? @zepatrik

**Comment by zepatrik** [comment]
Did not come back to it unfortunately, but definitely on my list. As a workaround you could use this script for now: https://github.com/ory/docusaurus-template/blob/91d8e8bf6149063b40e879ecbee997dad0951bad/scripts/config.js

**Comment by liuxiran** [comment]
> Did not come back to it unfortunately, but definitely on my list. As a workaround you could use this script for now: https://github.com/ory/docusaurus-template/blob/91d8e8bf6149063b40e879ecbee997dad0951bad/scripts/config.js

Thanks very much for providing a great solution, and looking forward to one day it become a common feature of `json-schema-fake`, thanks again~
