### ISSUE TITLE
Fails to fully generate schemas that include a $ref in an allOf key

### ISSUE THREAD

**Issue by prometheas** [json-schema-faker/json-schema-faker#613]
Hey there. First of all, thanks for this wonderful library!

I believe I've found a problem. I'm reporting it now, and will soon have a look to see if I can knock out a fix (mind you I'm saying that rather naively, as I've not even peeked at the sources).

Here's some JS that demonstrates the problem:

```js
const jsf = require('json-schema-faker');

jsf.option({ alwaysFakeOptionals: true });

const basicSchema = {
    components: {
        schemas: {
            A: {
                allOf: [
                    { $ref: '#/components/schemas/B' },
                    { $ref: '#/components/schemas/C' },
                ],
            },
            B: {
                type: "object",
                properties: {
                    bProp: {
                        type: "string",
                        format: "date-time",
                    },
                },
                required: ['bProp'],
            },
            C: {
                type: "object",
                properties: {
                    cProp: {
                        type: "number",
                        required: true,
                    },
                },
            },
        },
    },
};

console.log(jsf.generate(basicSchema.components.schemas.A));
// => {}
```

My expectations—given that `A` has `$ref`s to both `B` and `C`, and that both `B.bProp` and `C.cProp` are each defined as "required" in their ways—that `jsf.generate()` ought to produce a composite of these two schemas.

Instead, I get `{}`.

So, either I've found a bug, or I've incorrectly implemented my schema (though this doesn't seem likely because a number of validators produce exactly the validation behavior I'm expecting).

**Comment by pateketrueke** [comment]
Well, you're passing `basicSchema.components.schemas.A` as the schema, there's no way to resolve from `#/components` if they're not present on the schema, or passed as additional refs. 🤔

**Comment by prometheas** [comment]
Hey there. Sorry, you closed this issue before I had even had the chance to read your replies.

While I'm able to reproduce this solution, I must confess that I remain unconvinced that I haven't found a `$ref` resolution bug, as `#/path/to/node` is meant to be [the correct way](https://json-schema.org/understanding-json-schema/structuring.html#extending) to resolve an absolute JSON path within the same file.

The situation I'm working with is where I have one large JSON schema file, where ALL entities are defined under `#/components/schemas`, many of which are composed of sub-schemas using `allOf` + `$ref`. This swagger definition works as expected on the hosting API, as well as when validating sample data with AJV (as well as in whatever Python library our API is using).

It's possible that I'm falling victim to some insidious misunderstanding of particulars, but between my read of the spec—and given the performance of our schema for validating our data—I feel like either I'm misusing JSF, or JSF isn't properly resolving these refs (… or, well, perhaps both).

**Comment by pateketrueke** [comment]
Yeah, sorry for that, but I'm not seeing any issue on JSF — using local references (e.g. definitions) is well proven as you can see on our [tests](https://github.com/json-schema-faker/json-schema-faker/search?q=definitions).

The issue you posted is entirely related on how json-references work, let me try to explain:

First, you have an arbitrary object with three sub-schemas, and that's fine, the references you're using are relative to the root of the whole schema, e.g. `#/components/schemas/B`

So, in order to being able to resolve them, you MUST pass the whole `basicSchema` object, and not just `basicSchema.components.schemas.A` — remember: references are relative to the root of any given schema.

But you just passed `basicSchema.components.schemas.A` and that's only:

```js
{
    allOf: [
        { $ref: '#/components/schemas/B' },
        { $ref: '#/components/schemas/C' },
    ],
}
```

At this point, JSF needs to resolve those refs, but from where? Can you see there is no `components` prop in this object?

That's the root-cause of your issue, but if you pass the whole schema (as it should be, in order to resolve relative -to the root- references) as:

```js
const basicSchema = {
    components: {
        schemas: {
            A: {
                allOf: [
                    { $ref: '#/components/schemas/B' },
                    { $ref: '#/components/schemas/C' },
                ],
            },
            B: {
                type: "object",
                properties: {
                    bProp: {
                        type: "string",
                        format: "date-time",
                    },
                },
                required: ['bProp'],
            },
            C: {
                type: "object",
                properties: {
                    cProp: {
                        type: "number",
                        required: true,
                    },
                },
            },
        },
    },
};

console.log(jsf.generate(basicSchema).components);
```

Then references are perfectly resolved, because thay can resolved against the whole schema, starting from its root.

Of course, you need to access to `components[.schemas]` later because there is not top-level schema definition, so the whole object is used as fallback for traversing and generating fake stuff.

**Comment by pateketrueke** [comment]
Update: oh my, I found it actually works but just calling `jsf.resolve()` but not `jsf.generate()` — I'm looking into it! 🐛

**Comment by prometheas** [comment]
Hey! This is wonderful news.

So the upshot here, then, is what? Assuming that I've got that full Swagger file loaded into a symbol `mySwagger` and I would like to generate a fake `#/components/schemas/SomeModel` that is composed of references, would this now be the correct way to generated a `SomeModel` data structure?:

```js
const generatedData = jsf.generate(
  mySwagger.components.schemas.SomeModel,  // ref the specific schema against which I wish to generate data
  mySwagger  // full swagger definition, to allow JSF access to its composite $ref definitions
);
```

**Comment by prometheas** [comment]
Additionally, the most recent release I'm seeing here is from 1 September. Any guidance around when this fix might make it out to NPM? 🙂

**Comment by pateketrueke** [comment]
Hi, you can install the dependency directly from github to test your code? I'll be releasing during this week.

Now, about your swagger question, remember: local references resolve against the given schema, if you don't pass the whole schema it will not work.

Giving the swagger definition as refs will not work either, because those refs have no `id` — I mean, relative refs cannot be passed separatedly.

**Comment by prometheas** [comment]
OK, I can explore that, but I'm running into the following error when running directly from Github:

```
Error: Cannot find module '/Users/main/temp/jsf-test/node_modules/json-schema-faker/dist/main.cjs.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:682:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/yanni/temp/image-test/jsf-test.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/yanni/temp/image-test/node_modules/json-schema-faker/package.json',
  requestPath: 'json-schema-faker'
}
```

There are probably a number of ways to address this, but the first idea that comes to mind is whether adding a `package.json#/scripts/postinstall` script that generates the missing artifact mightn't be the simplest solution?

In case it's useful, I've installed the package at the new revision into my test project as follows:

```sh
npm install --save json-schema-faker/json-schema-faker\#971be18
```

And then running the following script in node to produce the error:

```js
const jsf = require('json-schema-faker');
```

**Comment by prometheas** [comment]
OK, I can explore that, but I'm running into the following error when running directly from Github:

```
Error: Cannot find module '/Users/main/temp/jsf-test/node_modules/json-schema-faker/dist/main.cjs.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:682:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/yanni/temp/image-test/jsf-test.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/yanni/temp/image-test/node_modules/json-schema-faker/package.json',
  requestPath: 'json-schema-faker'
}
```

There are probably a number of ways to address this, but the first idea that comes to mind is whether adding a `package.json#/scripts/postinstall` script that generates the missing artifact mightn't be the simplest solution?

In case it's useful, I've installed the package into my test project as follows:

```sh

```

And then running the following script in node to produce the error:

```js
const jsf = require('json-schema-faker');
```

## UPDATE:

Actually, it seems more complicated than that. I tried `cd`ing into the install dir to run `npm run build` manually, which failed due to the absence of `tarima`.   So I tried updating the `build` task to prepend `npx`, but that then failed because `concat` was found missing:

```
npm run build

> json-schema-faker@0.5.0-rcv.29 build /Users/main/temp/image-test/node_modules/json-schema-faker
> npx tarima -mfqe production

npx: installed 130 in 6.456s
0 files were built in 0.03s

> json-schema-faker@0.5.0-rcv.29 postbuild /Users/main/temp/image-test/node_modules/json-schema-faker
> npm run copy:vendor && concat -o dist/bundle.js dist/vendor.js dist/main.umd.min.js


> json-schema-faker@0.5.0-rcv.29 copy:vendor /Users/main/temp/image-test/node_modules/json-schema-faker
> concat -o dist/vendor.js node_modules/json-schema-ref-parser/dist/ref-parser.min.js node_modules/jsonpath-plus/dist/index-umd.min.js

sh: concat: command not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! json-schema-faker@0.5.0-rcv.29 copy:vendor: `concat -o dist/vendor.js node_modules/json-schema-ref-parser/dist/ref-parser.min.js node_modules/jsonpath-plus/dist/index-umd.min.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the json-schema-faker@0.5.0-rcv.29 copy:vendor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yanni/.npm/_logs/2020-11-02T16_45_49_796Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! json-schema-faker@0.5.0-rcv.29 postbuild: `npm run copy:vendor && concat -o dist/bundle.js dist/vendor.js dist/main.umd.min.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the json-schema-faker@0.5.0-rcv.29 postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/yanni/.npm/_logs/2020-11-02T16_45_49_815Z-debug.log
```

**Comment by pateketrueke** [comment]
Remember to install dependencies before running scripts, seems like you omitted the `npm ci` step.

**Comment by prometheas** [comment]
Following up regarding the upcoming release 😊… my team and I are really looking forward to this crucial (for us) fix.

**Comment by prometheas** [comment]
Just saw the availability of the updated package! Thanks, @pateketrueke 🙏🏼❤️🎉
