### ISSUE TITLE
Issues with generating floats from schema via CLI tool

### ISSUE THREAD

**Issue by rmaunder** [json-schema-faker/json-schema-faker#617]
Hi
I am experiencing an issue with generating floating point values in a schema. Example:

Example schema:
`{
  "title": "test",
  "type": "object",
  "properties": {
    "an_int": {
      "type": "number",
      "minimum": 0.0,
      "maximum": 20.5
    },
    "a_float": {
      "type": "number",
      "minimum": 0.01,
      "maximum": 20.1
    },
    "out_of_bounds": {
      "type": "number",
      "minimum": 0.0,
      "maximum": 0.8
    }
  },
  "required": [ "an_int", "a_float", "out_of_bounds"]
}`

This works fully as expected on https://json-schema-faker.js.org/ - all three properties floats:
`{
  "an_int": 20.351611543377484,
  "a_float": 8.111301107018784,
  "out_of_bounds": 0.2445306625701644
}`

However running local on Mac with
json-schema-faker@0.5.0-rcv.29
installed / invoked via : https://github.com/oprogramador/json-schema-faker-cli

I consistently get output like:
{"an_int":19,"a_float":3.01,"out_of_bounds":1}
{"an_int":12,"a_float":8.01,"out_of_bounds":1}
etc

where:
- 'an_int' is always an_int if it's minimum is set to whole float number (0.0) even if maximum has decimals
- 'a_float' appears as float if the minimum has some decimal digits, and seems to have same precision as minimum
- 'out_of_bounds' is generated as  0 to 1 (not respecting the 0.8 limit).

This is so inconsistent with expected and online tool results, that I suspect it might be an issue with the CLI tool: https://github.com/oprogramador/json-schema-faker-cli
and how the output of jsf is being captured/returned? Either that or something in a library etc.

I'm mainly working with Python on Mac / Linux so I didn't want to get too much into the weeds of JS but be able to just call a util from command line. So this was looking ideal until this issue came up.

Can you suggest best place to start looking for the possible cause?
Thanks
Richard

**Comment by pateketrueke** [comment]
Not sure if such CLI is outdated or applying a different set of options, however, you could try the built-in CLI that we shipped on JSF few weeks ago: `jsf < yourschema.json`

**Comment by rmaunder** [comment]
Hi thanks for such quick reply. Can you give me a bit more detail on how I do this? jsf got added as a dependency of the cli tool when I did:  npm install -g json-schema-faker-cli

However I've no idea how to run your new CLI. 'jsf' isn't seen as an executable / script anywhere I can see. I'm on a Mac if it matters....

(Sorry as you can see I'm really a JS/node novice, so not sure how to do this)

**Comment by pateketrueke** [comment]
Just install jsf globally `npm i -g json-schema-faker` and you'll get the `jsf` on your PATH.

**Comment by rmaunder** [comment]
Excellent. I now get what look like valid results

rick@spamspam schema % jsf < scratch.json
{"an_int":7.638542698224293,"a_float":6.056155104633829,"out_of_bounds":0.3978676249177509}

Looks like a issue with the other CLI tool. I'm sure it used to work a few months ago, so something in it or my local setup broke. I'll open a case with that but I guess it is effectively obsolete now you can run jsf directly.

Thanks again for the help!
Richard
