### ISSUE TITLE
Please support a default format callback API

### ISSUE THREAD

**Issue by secreter** [json-schema-faker/json-schema-faker#621]
I got the error message below:
> Uncaught Error: Error: unknown registry key "color"

I know I can fix this by using format('color',cb) function. But my jsonschema is from users ,I can't list every format . I wish there is a default format callback function can deal with unexpected format string ,so that my platform does not crash.

**Comment by pateketrueke** [comment]
That's not  really needed, just disable `jsf.option({ failOnInvalidFormat: false })` to get rid of those errors.

**Comment by secreter** [comment]
yes, it works fine, thank you.
