### ISSUE TITLE
mixing minProperties / maxProperties with required

### ISSUE THREAD

**Issue by Spirch** [json-schema-faker/json-schema-faker#622]
from https://json-schema-faker.js.org/
select option alwaysFakeOptional

schema:
{
  "type": "object",
  "required": [
    "val1"
  ],
  "minProperties": 1,
  "maxProperties": 1,
  "properties": {
    "val1": {
      "type": "string"
    },
    "val2": {
      "type": "string"
    }
  }
}

result:
{
  "val1": "mollit",
  "val2": "culpa dolor adipisicing veniam voluptate"
}

expected:
{
  "val1": "mollit"
}

remove the required and it will behave properly, only one will be generated

**Comment by pateketrueke** [comment]
Good catch! Let me investigate this one, thank you.
