### ISSUE TITLE
Unexpected `allOf` behavior with pointer and minProperties

### ISSUE THREAD

**Issue by Smolations** [json-schema-faker/json-schema-faker#625]
This _may_ be related to #622, but I'm getting some unexpected results when trying to use `allOf`. My main goal is to create an object that references a slew of countries (with at least US and CA), and then a smaller subset of those countries (again, with at least US and CA). 

Just a dictionary of countries (abbreviated list for readability):
```js
// definitions/countries.js
export default {
  type: 'object',
  properties: {
    AL: { enum: ['Albania'] },
    CA: { enum: ['Canada'] },
    KY: { enum: ['Cayman Islands'] },
    MR: { enum: ['Mauritania'] },
    YT: { enum: ['Mayotte'] },
    VI: { enum: ['U.S. Virgin Islands'] },
    GB: { enum: ['United Kingdom'] },
    US: { enum: ['United States'] },
    UY: { enum: ['Uruguay'] },
  },
  required: ['US', 'CA'], 
  additionalProperties: false,
};
```

An api response representation referencing the above:
```js
// presenters/countries.js
export default {
  type: 'object',
  properties: {
    countries: { $ref: '#/definitions/countries' },
    countries_priority: {
      allOf: [
        { $ref: '#/definitions/countries' },
        { maxProperties: 3 },
      ],
    },
  },
  required: [
    'countries',
    'countries_priority',
  ],
  additionalProperties: false,
};
```

When I run `jsf.generate({ allOf: [{ $ref: '#/presenters/countries' }] })`, I get a wide array of random responses for `result.countries_priority` as I refresh the page:
```js
{magna__f: false, est_56b: "mollit tempor laborum nisi"}
{sced: 7}
{US: "United States", CA: "Canada"}
{US: "United States", CA: "Canada", CN: "Mauritania", NE: "Uruguay", TD: "Albania"}
```

Strangely, the number of properties never exceeds 5 in this scenario. Also strange, when I set `alwaysFakeOptionals: true`, the response looks like the last two above OR it's an empty object. 

I would expect to receive, for `result.countries_priority`, an object with _either_ 2 or 3 properties with `alwaysFakeOptionals: false`, and _exactly_ 3 properties with `alwaysFakeOptionals: true`:
```js
{US: "United States", CA: "Canada"} // ONLY possible when alwaysFakeOptionals === false
{US: "United States", CA: "Canada", NE: "Uruguay"}  // possible regardless of alwaysFakeOptionals
```

**Comment by pateketrueke** [comment]
Interesting example, I would investigate this asap, thank you!
