### ISSUE TITLE
[Circular schema] max call stack in case de-referenced circular schema

### ISSUE THREAD

**Issue by paztis** [json-schema-faker/json-schema-faker#632]
In case of a schema with circular references, that is re-referenced with **@apidevtools/json-schema-ref-parser** for example
Circularity is not supported

version: 0.5.0-rcv.33

```

jsf.option({
    alwaysFakeOptionals: true
}, undefined);
const jsf = require('json-schema-faker');

const schema2 = {
    type: 'object',
    properties: {
        prop3: {type: 'number'},
        prop4: {type: 'number'},
        pointer: null
    }};

const schemaRoot = {
    type: 'object',
    properties: {
        prop1: {type: 'string'},
        prop2: {type: 'string'},
        pointer: schema2
    }
}

schema2.properties.pointer = schemaRoot;

const fake = jsf.generate(schemaRoot);
console.log(fake);
```

result 
```
const jsf = require('json-schema-faker');

const schema2 = {
    type: 'object',
    properties: {
        prop3: {type: 'number'},
        prop4: {type: 'number'},
        pointer: null
    }};

const schemaRoot = {
    type: 'object',
    properties: {
        prop1: {type: 'string'},
        prop2: {type: 'string'},
        pointer: schema2
    }
}

schema2.properties.pointer = schemaRoot;

const fake = jsf.generate(schemaRoot);
console.log(fake);
```

I crashed in getRefs function
I;ve test a local fix that resolves it;
```
function getRefs(refs, schema) {
    var $refs = {};

    if (Array.isArray(refs)) {
      refs.forEach(function (_schema) {
        $refs[_schema.$id || _schema.id] = _schema;
      });
    } else {
      $refs = refs || {};
    }

    function walk(obj, ancestors = []) {
      if (!obj || typeof obj !== 'object') { return; }
      if (ancestors.includes(obj)) {return;}
      if (Array.isArray(obj)) { return obj.forEach((item) => {return walk(item, [...ancestors, obj])}); }

      var _id = obj.$id || obj.id;

      if (typeof _id === 'string' && !$refs[_id]) {
        $refs[_id] = obj;
      }

      Object.keys(obj).forEach(function (key) {
        walk(obj[key], [...ancestors, obj]);
      });
    }

    walk(refs);
    walk(schema);

    return $refs;
  }
```

but it crashes after in **traverse** function if alwaysFakeOptional is on

Testable in sandbox https://codesandbox.io/s/stoic-northcutt-zzukl?file=/package.json (just run **node start** in terminal)

**Comment by pateketrueke** [comment]
Well, in terms of JSON-Schema that is not a circular reference, or at least is not a `$ref` pointing to itself, etc.

I mean, circular references are totally supported: https://apitools.dev/json-schema-ref-parser/docs/#circular-refs

What you're describing is a circular-reference at Javascript level which is not supported because we're trying to deal with JSON-Schema objects, and those should not have "live" references to other objects.

**Comment by paztis** [comment]
In my usage I cannot
I've got an enormous schema.
Sub parts of the app are using subparts of the schema. They've got pointers to it, but not to root schema

That's why I de-reference everything. Because without pointer to the topLevel schema, supParts of the app are unable to resolve the references.

Now, dereferencing seems to be a common practice.
@apidevtools/json-schema-ref-parser has 765,894 weekly download. Its older version json-schema-ref-parser has 930,838 weekly download.
So potentially, support the javascript circularity correctly might be important in your module

**Comment by pateketrueke** [comment]
Do you know if it's possible to `bundle()` your schema? https://apitools.dev/json-schema-ref-parser/docs/ref-parser.html#bundleschema-options-callback

> imho the benefit of using JSON-Schema is being very portable, if we build them in Javascript it's fine, but then we need to consider making it portable back, otherwise issues like this arise; also consider that having to support circular references in Javascript will be under a perf-cost, what do you think?

**Comment by paztis** [comment]
yes
It can use it before calling your faker, but bundle is asynchronous, and I need your call in a synchronous way

**Comment by pateketrueke** [comment]
Gotcha, what would be the best path to take then? Ignore circular references?

**Comment by paztis** [comment]
Perhaps do like the refs ? Allow a deep number ?
If deep is 3, we recurse 3 times ?

On my side I will try to develop a re-read lib. It can be useful

**Comment by pateketrueke** [comment]
I'm still unsure of this thing, sounds like ignoring the purpose of `$ref` by referencing stuff entirely on Javascript... 🤔
