### ISSUE TITLE
Setting "alwaysFakeOptionals" to true prevents generation of random object types

### ISSUE THREAD

**Issue by gabjauf** [json-schema-faker/json-schema-faker#633]
Hello 😄 

**Given**
`faker.option('alwaysFakeOptionals', true);` as a configuration

**Actual**
`faker.generate({ type: "object" })` returns `{}`

**Expected:**
`faker.generate({ type: "object" })` should return a non empty object
ex: `{ in_cab: false, in45: -78587670 }`

**Comment by pateketrueke** [comment]
Yeah, nice use-case, thanks for your input.
