### ISSUE TITLE
Allow stable ordering of fields

### ISSUE THREAD

**Issue by Hades32** [json-schema-faker/json-schema-faker#640]
I'm often clicking generate very often to get a feel of what could happen with the schema I created. Unfortunately, this not only changes the values of the keys (and possibly their existence) but also their order.

I wish there was an option to always output the keys in the same (e.g. sorted) order to make it easier to visually inspect the output changes.

**Comment by pateketrueke** [comment]
That sounds useful, we could sort the keys after the schema is generated, let me see what can I do, thanks for your input!
