### ISSUE TITLE
Feature: Higher order formatters

### ISSUE THREAD

**Issue by Xiphe** [json-schema-faker/json-schema-faker#642]
I would really like to be able to annotate a formatter/converter for values

```ts
import { generate, addConverter, extend } from 'json-schema-faker'
import faker from 'faker'
import format from 'date-fns/format'

extend('faker', () => faker)

addConverter('string', (value) => String(value))
addConverter('formattedDate', (value, options) => format(options[0], value))

generate({ 
  "type": "object",
  "properties": {
    "propA": {
      "type": "string",
      "faker": "datatype.number",
      "as": "string"
    },
    "fullName": {
      "type": "string",
      "faker": "date.past",
      "as": { "formattedDate": [["yyyy-MM-DD"]] }
    }
  }
})
```

**Comment by pateketrueke** [comment]
Looks great, but how standard it could be? I mean, using the `format` keyword is not enough? 🤔

**Comment by Xiphe** [comment]
Thanks! Afaik, the `format` keyword currently works standalone makes the `faker` keyword irrelevant.

I can currently achieve a similar effect by either extending faker or creating custom formats, but the power im after would combine the both :)

We could as well use `format` and make it receive the generated value from previous mock-data generators. The format implementation could then decide if it wants to use the value or not.

**Comment by pateketrueke** [comment]
I like the later option, if we can use `format` after `faker` then it could be a win-win, because you'll be following the standard and registering a custom formatter is totally expected, just because adding custom keywords could not be a solution for everyone.

**Comment by Xiphe** [comment]
Agree, actually I was tending towards the solution at first, then proposed the other api in order to not potentially interfere with the current behaviour.

I'll try to prepare a PR for this in the next days

**Comment by Xiphe** [comment]
Had a look at the code today and honestly couldn't find a comfortable spot to add the feature in. Might not have the time to do this on my own, sorry!

**Comment by pateketrueke** [comment]
I just confirmed that `format` was applied after `faker` calls, but the formatters were bit broken.

This way you can register any custom formatter that would run after to any generator.
