### ISSUE TITLE
$refs not working in webpack/browser environment even within a single file

### ISSUE THREAD

**Issue by spicemix** [json-schema-faker/json-schema-faker#643]
Sorry I don't have much time to do a full repro path for you, but I do have a working workaround, and it's all dependent on the context anyway.

I have a schema with $ref="#/definitions/MyType" and the definitions being dereferenced are all in the same file with the refs. I'm testing an Angular 11 app inside Cypress with webpack like so:

```typescript
import * as jsf from 'json-schema-faker';
...
    cy.fixture('jsonSchema').then((schema: any) => {
      jsf.resolve(schema.definitions.MyType)
        .then((fakeData) => {
          console.log('fakeData', fakeData);
        });
```

You would think it would be able to resolve them even when in a browser environment but I get the error that 

```
main.umd.js:3109 Uncaught (in promise) Error: Error while resolving schema (Error resolving $ref pointer "http://localhost:4200/#/definitions/MyType". 
Token "definitions" does not exist.)
    at eval (main.umd.js:3109)
```

I tried various things like passing the schema or schema.definitions in the second parameter, the cwd in the third parameter, the baseUrl of the test, etc nothing worked. But this worked fine:

`npm i -D @apidevtools/json-schema-ref-parser `

```typescript
import * as $RefParser from '@apidevtools/json-schema-ref-parser';
...
    cy.fixture('jsonSchema').then((cySchema: any) => {
      $RefParser.dereference(cySchema, (err: any, schema: any) => {
        if (err) {
          console.error(err);
        } else {
          console.log('schema', schema);
          jsf.resolve(schema.definitions.MyType)
            .then((fakeData) => {
              console.log('fakeData', fakeData);
            });
        }
      });
    });
```

So apparently json-schema-ref-parser is setting up the working directory in a webpack-survivable way and json-schema-faker is not. I can work this way for now OK but it's something people will probably bang into a bunch. Thanks for this useful tool!

**Comment by spicemix** [comment]
> You should never pass partial schemas like `jsf.resolve(schema.definitions.MyType)` because the `#/definitions/` fragments are taken from its root `schema` and this way you're just passing a broken schema with no `definitions` et all.

I've got several definitions in that schema, how then do I generate fake MyTypes? I can understand your point for the second parameter to jsf.resolve. But my workaround works fine and just passing the whole schema in parameter 1 doesn't work. Thanks!

**Comment by pateketrueke** [comment]
You can extend your schema to resolve any definition from it, e.g. `jsf.resolve({ ...schema, $ref: '#/definitions/MyType' })`

**Comment by spicemix** [comment]
> You can extend your schema to resolve any definition from it, e.g. `jsf.resolve({ ...schema, $ref: '#/definitions/MyType' })`

OK that worked and I will close this although this report can be taken as a documentation bug as it's likely a very common situation and I can't find your solution in the documentation as it stands. Thanks!

**Comment by pateketrueke** [comment]
>  this report can be taken as a documentation bug as it's likely a very common situation and I can't find your solution in the documentation as it stands

Totally agree, we'll address that lack documentation, so much thanks for your feedback!
