### ISSUE TITLE
Faker and Chance options are not respected when `type` is an array

### ISSUE THREAD

**Issue by jcuffe** [json-schema-faker/json-schema-faker#645]
I first found this while working with "nullable" schemas, where the `type` is an array: `[ "string", "null" ]`. However, while trying to circumvent the issue by removing the null type, I discovered that this affects all schemas where the type is represented as an array.

#### Example Chance schema:
```
{
  "type": [
    "string"
  ],
  "chance": "guid"
}
```

#### Got
`"mollit"`

#### Expected
`"cf8774fc-e885-5216-9963-c7a572ddd969"`, or similar

#### Example Faker:
```
{
  "type": [
    "string"
  ],
  "faker": {
    "fake": "{{name.lastName}}, {{name.firstName}} {{name.suffix}}"
  }
}
```

#### Got:
Generated Lorem

#### Expected
Faker data

**Comment by pateketrueke** [comment]
Interesting, I think this can be fixed easily, let me think what can I do, thank you!

**Comment by pateketrueke** [comment]
Hi, I just tested this locally against our current `master` and seems this issue is gone, can you help us on confirm this? Thank you!

**Comment by emb03** [comment]
Has this been fixed and released in a mew version?

**Comment by pateketrueke** [comment]
@emb03 it seems so!
