### ISSUE TITLE
Concat faker fields

### ISSUE THREAD

**Issue by leocharrua** [json-schema-faker/json-schema-faker#653]
Hello. I'm trying to concat to faker fields, like this:

 "contact": {
                "type": "string",
                "maxLength": 1000,
                "default": null,
                "faker": "faker.fake(\"{{name.findName}} - {{phone.phoneNumber}}\")"
 },

But this produces this error:

UnhandledPromiseRejectionWarning: Error: Error while resolving schema (TypeError: Cannot read property 'fake("{{name' of undefined

Any help would be appreciated.

Thanks

**Comment by pateketrueke** [comment]
Gotcha, that's not supported yet, but if you ask me we could enhance the `template` keyword to support also calling other generators (like Faker.js) and json-path, etc.

Would you like to jump in? Otherwise I'll be working on that over the following weeks.

Thank you!

**Comment by leocharrua** [comment]
Thanks. That's worked wonderfull!!!
