### ISSUE TITLE
Option to avoid generating additional properties

### ISSUE THREAD

**Issue by michaelmior** [json-schema-faker/json-schema-faker#656]
Aside from modifying the input schema, is there any way to avoid generating additional properties not explicitly given in the schema? I understand I can generate only required properties. However, I would like to generate both required and optional properties, but not any other property which is not explicitly listed.

**Comment by pateketrueke** [comment]
There is a `fillProperties`  that is enabled by default, just disable it to achieve what you want.

**Comment by michaelmior** [comment]
It seems like it would be relatively easy to add an option to avoid generating unlisted properties if you were willing to accept such a PR. In my case, I'm intending to automate data generation from a large number of schemas. It would be much cleaner to control this with `json-schema-faker` than having to traverse the schema to add `"additionalProperties": false` to every object.

**Comment by falko-apheris** [comment]
> When fillProperties is disabled, then no more properties will be added, but it'll honor additionalProperties if given.
@pateketrueke I found that not working, additionalProperties with a $ref were not renderd
