### ISSUE TITLE
minLength is not satisfied when there is a pattern

### ISSUE THREAD

**Issue by efebarlas** [json-schema-faker/json-schema-faker#659]
When I ask the faker to generate a string that has a minimum length and a pattern requirement, occasionally the minimum length is not satisfied.
An example:
 
![Screenshot from 2021-06-29 12-35-15](https://user-images.githubusercontent.com/43009963/123835426-83287600-d8d6-11eb-8e61-ee68f89e99d2.png)

This might be caused by the fixes associated for issue #540. A better solution to the fix for that issue could be to exit the loop only if the string hasn't been changed for the last 3, or 5, loops. This avoids infinite loops, and increases the probability that the generated string will pass the minimum length.

**Comment by pateketrueke** [comment]
In understand, can you help to see if this is a problem with randexp itself? Thank you!

**Comment by efebarlas** [comment]
I don't think this has to do with randexp because the related code does not make calls to randexp specifying desired length of output. In fact, randexp does not support this. What json-schema-faker is doing currently, is to append strings generated by randexp until it reaches desired length. There are problems with this solution as well (words from a language of a regex appended together may or may not satisfy the regex), but they aren't easy to solve.

This is the code snippet dealing with string generation, it is in core/utils.js:
`while (value.length < min) {
        prev = value;

        if (!schema.pattern) {
          value += `${random.pick([' ', '/', '_', '-', '+', '=', '@', '^'])}${value}`;
        } else {
          value += random.randexp(schema.pattern);
        }

        // avoid infinite-loops while filling strings, if no changes
        // are made we just break the loop... see #540
        if (value === prev) break;
      }
`
 It avoids infinite-loops by exiting when the generated string is empty. However, this causes minLength violations. What can be done to minimize the probability of this happening, is to check the value after three or more loops to see if it hasn't changed. 
This solution, will not fix the problem of words appended together not satisfying a regex (that is more difficult to solve). But it will at least solve the violations of minLength.

**Comment by pateketrueke** [comment]
Got it, do you mind in opening a small PR for it?

**Comment by efebarlas** [comment]
Then we increase the risk of the generated string not matching the provided regex pattern.

**Comment by pateketrueke** [comment]
Gotcha, I think that's the risk of some regexps... please go ahead, breaking the loop would suffice.

I'm not sure if the end-user should deal with the results, or, throwing an exception would be better?

I also think an optional to handle such behavior, most users would be fine with the bad result, while others would like to be warned about the hard-to-solve regexp?
