### ISSUE TITLE
browser delivery broken in 0.5.0-rcv.35 delivery

### ISSUE THREAD

**Issue by paztis** [json-schema-faker/json-schema-faker#663]
Since 0.5.0-rcv.35 delivery, imports like

```
import jsf from 'json-schema-faker';

jsf.option({
   ...
});
```

are failing because only {} is exported, so jsf.options is crashing with NPE

My project is bundled with Webpack, and the browser version of jsf is used (main.iife.js)

**Comment by paztis** [comment]
it was working correctly with previous version (umd)

**Comment by pateketrueke** [comment]
Gotcha, sadly esbuild does not support UMD atm, webpack is not able to load ESM modules instead?

**Comment by paztis** [comment]
I have thousand of modules. Rules are take browser field, or module, or main

**Comment by pateketrueke** [comment]
Gotcha, you cannot change that order? Otherwise I think next release should be UMD instead on IIFE, just let me find a way to produce such output.

**Comment by paztis** [comment]
A change is not possible, or it means hardcording a rule especially for this module and I prefer not.

**Comment by pateketrueke** [comment]
Update: I hope [esbuild can handle UMD format](https://github.com/evanw/esbuild/pull/1331) soon, is just matter of time!

**Comment by paztis** [comment]
Cool
