### ISSUE TITLE
[discussion] [help needed] freeze property values

### ISSUE THREAD

**Issue by hellboy81** [json-schema-faker/json-schema-faker#67]
Is there possible to freeze property value in item schema?

``` js
// Fake Mongo item generator
// type paramter is optional
// If no type specified  - random value should be generated (0 or 1)
// If type specified -  {'type': type} should be returned
module.exports.mongoItem = function(type) {
    var itemSchema = { 
           type: {
                type: 'integer',
                enum: [0, 1] // type can be zero or one
            },
            required: ['type']
    }
   return jsf(itemSchema)
```

**Comment by ducin** [comment]
@hellboy81 sorry, I can't understand what you need. Can you write it more precisely?

**Comment by hellboy81** [comment]
```
mongoItem() -> {type: 0} or {type: 1} // Randomly generated, this is default functionality
mongoItem(0) -> {type: 0} // Freeze value
mongoItem(1) -> {type: 1}  // Freeze value
```

This is only sample, another fields are also presented in schema.

**Comment by hellboy81** [comment]
Issue: for some test cases `type` value is important due on 
```js
if (item.type === 0) {
...
}
```

for another test cases `type` value doesn't matter.

**Comment by ducin** [comment]
As far as I understand your problem, it's not possible yet, since JSON Schema is a *structure*, and what you need is a parametrized function. We are considering dynamizing JSON Schema Faker to work on functions, but it can take some time until we get there.

**Comment by hellboy81** [comment]
As I mentioned the only workaround at the moment is

```js
var item = jsf(itemSchema)

if (type) {
  item.type = type
}

return item
```

**Comment by ducin** [comment]
If you want such workaround, you might use:

```js
module.exports.mongoItem = function(type) {
    var itemSchema = { 
           type: {
                type: 'integer',
                enum: [0, 1] // type can be zero or one
            },
            required: ['type']
    }
   if (type) { itemSchema.type.enum = [type]; } // only this line is added
   return jsf(itemSchema)
```

assuming you don't check whether the parameter passed is either 0 or 1 (you assume it's correct). Then you just overwrite the `enum` property. If you've got an enum with 1 value, you've got 100% percent guarantee it will be them one to use.

**Comment by pateketrueke** [comment]
Using a custom format wouldn't help?

**Comment by hellboy81** [comment]
>Using a custom format wouldn't help?

sample?

**Comment by hellboy81** [comment]
> if (type) { itemSchema.type.enum = [type]; } // only this line is added

This does not work properly if `type` = 0

**Comment by hellboy81** [comment]
should be refactored  to array

**Comment by hellboy81** [comment]
Off/2: How can share definitions between multiple schemes?

As I mentioned this is valid definition for `mongoId` and can be shared between mulitple document schemes:

```js
definitions: {
            mongoId: {
                type: 'string',
                chance: {
                    hash: {
                        casing: 'upper',
                        length: 32
                    }
                }
            }
        }
```

**Comment by pateketrueke** [comment]
> sample? 

A: [Custom formats](https://github.com/json-schema-faker/json-schema-faker/blob/master/README.md#custom-formats)

> Off/2: How can share definitions between multiple schemes?

A: [Https://github.com/json-schema-faker/json-schema-faker/blob/master/README.md#using-references](Using references)

**Comment by hellboy81** [comment]
>In order to achieve that you can use refaker and then use the resolved schemas:

I am still don't understand.

How can I refactor this code to have the **only one** `mongoId` definition :

```js
var itemSchema = {
        type: 'object',
        properties: {
           _id: {
               $ref: '#/definitions/mongoId',
          },
         ......
        },
       definitions: {
            mongoId: {
                type: 'string',
                chance: {
                    hash: {
                        casing: 'upper',
                        length: 32
                    }
                }
            }
       }
}


var subItemSchema = {
        type: 'object',
        properties: {
           _id: {
               $ref: '#/definitions/mongoId',
          },
         ......
        },
       definitions: {
            mongoId: {
                type: 'string',
                chance: {
                    hash: {
                        casing: 'upper',
                        length: 32
                    }
                }
            }
       }
}

```

**Comment by hellboy81** [comment]
Should I use additionally [refaker](https://github.com/json-schema-faker/refaker) ?

**Comment by pateketrueke** [comment]
No, refaker is only if you have local or remote references, is not your case.

I think the main example would be enough:

```javascript
var schema = {
  type: 'object',
  properties: {
    _id: {
      $ref: 'commonSchemaId#/definitions/mongoId'
    }
  }
};

var refs = [
  {
    id: 'commonSchemaId',
    definitions: {
      mongoId: { ... }
    }
  }
];

var sample = jsf(schema, refs);
```

**Comment by hellboy81** [comment]
Can I change definition

```
itemSchema.type.enum = [type]
```

if type scheme is defined in `refs`  ?

**Comment by pateketrueke** [comment]
I think the best way of handling this is having different schemas for all cases:

```json
{
  "id": "FreezeValues",
  "type": "object",
  "required": ["zero", "one", "both"],
  "properties": {
    "zero": { "$ref": "#/definitions/justZero" },
    "one": { "$ref": "#/definitions/justOne" },
    "both": { "$ref": "#/definitions/zeroOrOne" }
  },
  "definitions": {
    "zeroOrOne": {
      "anyOf": [
        { "$ref": "#/definitions/justZero" },
        { "$ref": "#/definitions/justOne" }
      ]
    },
    "justZero": {
      "type": "integer",
      "enum": [0]
    },
    "justOne": {
      "type": "integer",
      "enum": [1]
    }
  }
}
```

**Comment by pateketrueke** [comment]
Instead of using enums with just one value you'll be able to use `default` values, which is even shorter.

I'll be fixing this soon so I'm closing this to make less noise on my head.
