### ISSUE TITLE
Bug: generates produces unexpected key/value pairs

### ISSUE THREAD

**Issue by kennyhyun** [json-schema-faker/json-schema-faker#670]
0.5.0-rcv.38

## Json schema

```json
{
  "type": "object",
  "properties": {
    "orderId": {
      "type": "integer",
      "minimum": 1
    },
    "orderTotal": {
      "type": "number"
    },
    "paymentReference": {
      "type": "string"
    },
    "addressBookId": {
      "type": "integer",
      "minimum": 0
    }
  }
}
```

## Result

```json
{
  "orderTotal": 14324423.575465024,
  "consectetur74f": false,
  "Lorem_e": true
}
```

## Expected

```json
{
  "paymentReference": "veniam non laborum officia",
  "orderTotal": -91954830.98461987,
  "orderId": 79570890,
  "addressBookId": 55914108
}
```

It generates property sometimes but many cases have unexpected key/value pairs.

![image](https://user-images.githubusercontent.com/5399854/128018045-5f3629e4-0fa6-41cd-b7b6-c8cc0fe38c8f.png)

**Comment by pateketrueke** [comment]
By default random props are always generated, unless you set `additionalProperties` to `false` in your schema.

Such behavior can be disable using the following options:

```js
jsf.option({
  fillProperties: false, // by default is true, it adds random props if enabled
  alwaysFakeOptionals: true, // by default is false, props are pick randomly if disabled
});
```

- If you don't enable `alwaysFakeOptionals` then only `required` props are generated.
- If you don't disable `fillProperties` then the generated object would have additional props.

**Comment by kennyhyun** [comment]
@pateketrueke thanks for the reply.
I was using some old versions rc16~23 but recently updated to rcv38 and had these random properties.

```json
{
  "type": "object",
  "properties": {
    "orderId": {
      "type": "integer",
      "minimum": 1
    },
    "orderTotal": {
      "type": "number"
    },
    "paymentReference": {
      "type": "string"
    },
    "addressBookId": {
      "type": "integer",
      "minimum": 0
    }
  },
  "additionalProperties": false
}
```

Confirmed this stops generating random properties.
It's good to know such that options. I'll put those in my code.

Thanks for the nice utility BTW
