### ISSUE TITLE
Typedoc option "optionalsProbability" boolean instead of number

### ISSUE THREAD

**Issue by bobo96run** [json-schema-faker/json-schema-faker#684]
If you are reporting a bug, please include the following:

1. the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ (paste the schema, click `Generate example` and then copy and paste the resulting URL from the browser address bar)

Not applicable

2. the result you got

Not applicable

3. the result you expected

Not applicable

First and foremost, thank you for this tool!

This report does not directly relate to how the tool works, but only about its TypeScript type definition file `json-schema-faker/index.d.ts`

https://github.com/json-schema-faker/json-schema-faker/blob/9839e210adcc65967d59ce90ff258e662d0903f3/index.d.ts#L15

option `optionalsProbability` is currently defined as type `boolean` like other options, whereas according to the documentation (and how the tool works), it should be a number between 0 and 1, or `false`.

https://github.com/json-schema-faker/json-schema-faker/tree/9839e210adcc65967d59ce90ff258e662d0903f3/docs#available-options

https://github.com/json-schema-faker/json-schema-faker/blob/9839e210adcc65967d59ce90ff258e662d0903f3/docs/README.md#L116

**Comment by pateketrueke** [comment]
Oh, this is definitely a mistake on our side.

I'll be fixing this asap, thank you!
