### ISSUE TITLE
Single example property versus array examples

### ISSUE THREAD

**Issue by benjamin-mogensen** [json-schema-faker/json-schema-faker#694]
Hi!
- Is there any support for `example` property?
- Or is it only `examples` array that will work?
- If the latter, would it be possible to include support for single `example` values as well?

I am not an expert on this projects API, but would adding this to `traverse.js` line 45 work:
```js
if(optionAPI('useExamplesValue') && schema.example) {
  return { value: utils.typecast(null, schema, () => schema.example, context };
}
```

**Comment by pateketrueke** [comment]
You're right, I think is not supported yet, and also it could be easy to implement, want to try a PR? Thank you!

**Comment by benjamin-mogensen** [comment]
Ok I will give it try :)

**Comment by benjamin-mogensen** [comment]
Getting permission denied when trying to push my branch - anything I need to do to be able to push a branch to this repo?

**Comment by pateketrueke** [comment]
Oh yeah, did you forked it properly? It is not possible to push directly until you're inside the organization, as an ooutcomer, you must fork and then open a pull-request as required, can I help you on this process?

**Comment by benjamin-mogensen** [comment]
Ahh ok... let me try that, never did a fork... will do! Learning something new haha

**Comment by benjamin-mogensen** [comment]
I have tried to fork, branch and create a PR - not sure if all is following your standards, but you can have a look and see if OK https://github.com/json-schema-faker/json-schema-faker/pull/695

**Comment by pateketrueke** [comment]
Hey, I'm closing this since as we already landed your first PR, thank you!
