### ISSUE TITLE
Provide Faker Parameters Without Polluting Schema

### ISSUE THREAD

**Issue by ghost** [json-schema-faker/json-schema-faker#702]
I've not been able to figure out how I can specify faker types for properties, externally to the schema as we don't want to pollute the schema with parameters for generating fake data:
```
email: {
          type: 'string',
          format: 'email',
          faker: 'internet.email'
        }
```
An instead do something like this `jsf.define('email', { faker: 'internet.email' });`

**Comment by pateketrueke** [comment]
Closing as author deleted his account, sorry!
