### ISSUE TITLE
Ref with depth >0 is not working

### ISSUE THREAD

**Issue by thinking-aloud** [json-schema-faker/json-schema-faker#709]
Hi, when trying to use ref that is not used on the top level it simply does not work and generates random entries.
I created an example to reproduce:

https://codesandbox.io/s/empty-node-js-forked-ivmrk5?file=/src/index.js

It generates a **customer** with **id** and **name**.
This is then used to generate a **project** with the **customer_name** and **customer_id**. The name is fine, but the id is wrong (see assert).

**Comment by hashbou** [comment]
Hello, I can confirm this. I was having issues with `codesandbox` and thus just replicated the example to `stackblitz`: https://stackblitz.com/edit/node-4phzrj?file=index.js

**Comment by pateketrueke** [comment]
@hashbou well, it just happened to be a typo in your repro:

```diff
const projectSchema = {
  type: "object",
  properties: {
    _id: {
      type: "object",
-     propterties: {
+     properties: {
        customer_id: { $ref: "customer_id" }
      },
      required: ["customer_id"]
    },
    customer_name: { $ref: "customer_name" }
  },
  required: ["_id", "customer_name"]
};
```
