### ISSUE TITLE
stable releases

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#71]
Hi @pateketrueke and @whitlockjc,

Recently we've had a situation where the `master` branch travis status turned into `failing` with no code changes. There were only docs changes. Actually, this one is still not fixed. I've got no idea on how did this happen...

What I would like to achieve is to make `master` branch stable 100%, both npm and github. And to achieve that, we need passing travis builds. There is a [guideline](https://github.com/json-schema-faker/json-schema-faker/blob/master/CONTRIBUTING.md) stating that all changes for upcoming releases shall go to `develop` branch. And somewhere, somehow, we've made a mistake...

Do you know what was the problem? Do you have any suggestions on what can we improve to avoid such situation in future? The only thing I can think of is that upgrading dependencies should be done in `develop` branch as well and maybe this caused the instability.

**Comment by pateketrueke** [comment]
Totally agree.

> Do you know what was the problem? 

I merged that by mistake, I adhere to you on respecting the guidelines.

**Comment by ducin** [comment]
Guess that one is outdated :)
