### ISSUE TITLE
Error when generating sample data with relative Filepaths and not unique id's

### ISSUE THREAD

**Issue by Emdave10** [json-schema-faker/json-schema-faker#711]
Bello is the schema i want to generate sample data for "Description.json:
```
{
    "info": "Schema demo",
    "oneOf": [
        {
            "type": "object",
            "info": [
                [
                    "Demo1",
                    "Demo2"
                ],
                "For example:",
                [
                    " - Demo3",
                    " - Demo4"
                ]
            ],
            "properties": {
                "_meta": {
                    "$ref": "Meta.json"
                },
                "_type": {
                    "enum": [
                        "Description"
                    ]
                },
                "after": {
                    "$ref": "Text.json",
                    "info": "TextDemo"
                },
                "before": {
                    "$ref": "Text.json",
                    "info": "This text appears before context"
                }
            },
            "additionalProperties": false,
            "examples": [
                {
                    "before": "TextDemo",
                    "after": "TextDemo"
                }
            ]
        },
        {
            "$ref": "Text.json",
            "info": [
                [
                    "TextDemo"
                ]
            ]
        }
    ],
    "title": "Description"
}
```
And below is the code i am using to generate the sample data:
```
const jsf = require('json-schema-faker');
var stringify = require('json-stringify-safe');


// 1.0 - first, we need a working (and valid) `schema`
const schema = require('./Schemas/Description.json')

// 1.1 - optionally, you can provide used `refs`
const refs = "./Schemas"

// 1.2 - additionally, you can provide a `cwd` for local references
//const cwd = `${__dirname}/Schemas`;

// 2.1 - resolve and generate complex schemas with remote references
const asyncValue = jsf.generate((schema), refs);
console.log(asyncValue)
```

But when i try to use that code, I have my schemas: Description.json which im generating sample data for in the "Schemas" directory alongside the references: "Text.json and Meta.json" since they. are all in the same directory but instead when i run the code it gives the following error below which is in summary saying it cant find "Text.json" referenced even when its in the same directory called "Schemas" as "Description.json" which im trying to create sample data for, is there something I am doing wrong in this sense. Giving each schema a unique id and loading them works but i cant afford to add a unique id to all schemas and use those id's as the refs  as they are over 100 so i want to continue using filepaths to dereference  correctly and generate sample data, but i may be doing it wrong so i would appreciate corrections to ensure it works well for me. Heres the error i get below:

```
/projects/JSON_SCHEMA/Domain/node_modules/json-schema-faker/dist/main.cjs.js:2430
          throw e;
          ^
 
Error: Reference not found: Text.json
    at recursiveUtil.resolveSchema (/projects/JSON_SCHEMA/Domain/node_modules/json-schema-faker/dist/main.cjs.js:2273:21)
    at traverse (/projects/JSON_SCHEMA/Domain/node_modules/json-schema-faker/dist/main.cjs.js:2092:16)
    at traverse (/projects/JSON_SCHEMA/Domain/node_modules/json-schema-faker/dist/main.cjs.js:2130:50)
    at run (/projects/JSON_SCHEMA/Domain/node_modules/json-schema-faker/dist/main.cjs.js:2418:24)
    at Function.jsf.generateWithContext (/projects/JSON_SCHEMA/Domain/node_modules/json-schema-faker/dist/main.cjs.js:6100:14)
    at Function.jsf.generate (/projects/JSON_SCHEMA/Domain/node_modules/json-schema-faker/dist/main.cjs.js:6102:51)
    at Object.<anonymous> (/projects/JSON_SCHEMA/Domain/JsonSchemaGen.js:15:24)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)

```

Glad to tip if it works !

**Comment by pateketrueke** [comment]
Hi, I think you're misusing the options:

- The `refs` value should be an array-or-object of loaded schemas, not a string
- The `cwd` is right, but you're not passing it to the `resolve()` call

Using the `generate()` method will work only with all given `refs` as expected:

```js
const schema = require('./Schemas/Description.json');
const refs = [
  require('./Schemas/Text.json'),
  require('./Schemas/Meta.json'),
];

console.log(jsf.generate(schema, refs));
```

> The solution above will work only if you're using the `id` from the loaded schemas as the `$ref` values, they should match, otherwise It'll not work.

Using the `resolve()` method instead, it'll use the `cwd` for resolving through the filesystem:

```js
const schema = require('./Schemas/Description.json');
const cwd = `${__dirname}/Schemas`;
const refs = [];

jsf.resolve(schema, refs, cwd).then(console.log);
```

> This solution will work fine for your use-case, because you're using `$ref` values that should resolve against the given `cwd`, otherwise it'll lookup at the given `refs` as fallback.

I hope this helps, thanks for your feedback!

**Comment by Emdave10** [comment]
> Hi, I think you're misusing the options:
> 
> * The `refs` value should be an array-or-object of loaded schemas, not a string
> * The `cwd` is correct, but you're not passing it to the `resolve()` call
> 
> Using the `generate()` method will work only with all given `refs` as expected:
> 
> ```js
> const schema = require('./Schemas/Description.json');
> const refs = [
>   require('./Schemas/Text.json'),
>   require('./Schemas/Meta.json'),
> ];
> 
> console.log(jsf.generate(schema, refs));
> ```
> 
> > The solution above will work only if you're using the `id` from the loaded schemas as the `$ref` values, they should match, otherwise It'll not work.
> 
> Using the `resolve()` method instead, it'll use the `cwd` for resolving through the filesystem:
> 
> ```js
> const schema = require('./Schemas/Description.json');
> const cwd = `${__dirname}/Schemas`;
> const refs = [];
> 
> jsf.resolve(schema, refs, cwd).then(console.log);
> ```
> 
> > This solution will work fine for your use-case, because you're using `$ref` values that should resolve against the given `cwd`, otherwise it'll lookup at the given `refs` as fallback.
> 
> I hope this helps, thanks for your feedback!

Thank you very much that did work, the only problem with this issue before its closed is that on the last line when i do the `jsf.resolve(schema, refs, cwd).then(console.log);` the console log output is stored in a json file called "data.json" but it stores it as an object as shown below instead of a json object with json formatting, I wanted to know if there are any adaptations i could give to the previosu code to ensure that the the console log output which gets stored in the "data.json" file stores it as a JSON object rather than a normal object with no JSON formatting as shown below 
![image](https://user-images.githubusercontent.com/89699792/185080035-1638bb23-d560-4a27-8c25-eb2a8dd27a99.png)

**Comment by pateketrueke** [comment]
> [...] the console log output is stored in a json file called "data.json" but it stores it as an object as shown below instead of a json object with json formatting

Well, that exact part is up to you, because `console.log` just prints out to the screen, but it will not save a file.

If you want to save the contents into a file, then try using the `fs` module and `JSON.stringify` to convert that object into a JSON string.

```js
const fs = require('fs');
jsf.resolve(schema, refs, cwd).then(result => {
  fs.writeFileSync('data.json', JSON.stringify(result));
});
```

I hope that helps, see you!
