### ISSUE TITLE
It looks like `jsf.generate()` is deprecated but it's not

### ISSUE THREAD

**Issue by pmcelhaney** [json-schema-faker/json-schema-faker#712]
```ts
import JSONSchemaFaker from "json-schema-faker";

JSONSchemaFaker.generate({ type: "string" });
//  ^ @deprecated — calling JSONSchemaFaker() is deprecated, call either .generate() or .resolve()'
```

_Calling_ JSONSchemaFaker as a function is deprecated. Using it as an object is not. But I don't think there's a way to make that distinction in JSDoc / TypeScript.

To get around this problem, I suggest adding a named export, `JSONSchemaFaker` that has the same properties as the default export but is not a function. 

```ts
// Named export instead of default export
import { JSONSchemaFaker } from "json-schema-faker";

// No deprecation warning. 
JSONSchemaFaker.generate({ type: "string" });

// This would be a type error as the named JSONSchemaFaker export is not callable
JSONSchemaFaker();
```

**Comment by pateketrueke** [comment]
@pmcelhaney can you provide more details for a minimal repro? Thank you!

**Comment by pmcelhaney** [comment]
@pateketrueke minimal repo is in the report. Paste that into VSCode in a project that has json-schema-faker installed and you should see a squiggly line with the warning. 

If you don’t see it, let me know and I’ll check again. It might depend on a plug-in and/or ESLint rule. 

Regardless, reproduction isn’t really necessary. The message “calling JSONSchemaFaker() is deprecated, call either .generate() or .resolve()” is a JSDoc comment. This is more of a documentation / usability issue than a bug.

**Comment by pmcelhaney** [comment]
I'm also happy to send a PR with my suggested fix!

**Comment by pateketrueke** [comment]
Please, thank you! :)

**Comment by pmcelhaney** [comment]
@pateketrueke What other bundling / module issues do you have? Now that I'm familiar with the codebase I may be able to help with those.

**Comment by pateketrueke** [comment]
Well, actually do we have some integrations tests that validate the CJS, ESM and UMD exports. If they pass I don't see any other issue, however third-party modules (json-schema-ref-parser) is likely working bad when consumed on webapps as it does not bundles fine, but that's another issue. Thank you!
