### ISSUE TITLE
Enum and oneOf will generate "NaN"

### ISSUE THREAD

**Issue by Mustang-Galaxy** [json-schema-faker/json-schema-faker#713]
Error occurred in latest jsf
schema i used

"valueType": {
  "description": "类型",
  "enum": ["Int", 1, "String", 2, "Float", 3, "Boolean", 4],
  "oneOf": [{ "type": "string" }, { "type": "integer" }]
}

Result is "valueType: null"

version: 0.5.0-rcv.44
@pateketrueke

**Comment by pateketrueke** [comment]
Nice catch, thank you!

**Comment by Mustang-Galaxy** [comment]
> Nice catch, thank you!

the case is 
random(enum) = 'Int'
random(oneOf) = { "type":  "string" }

will go to 

https://github.com/json-schema-faker/json-schema-faker/blob/0c5b4ba8eff652ad71b9f9c784aee0ec56f796e1/src/lib/core/utils.js#L172

value = 'int'
parseInt(value, 10) = NaN

**Comment by Mustang-Galaxy** [comment]
hey, guy   
will you fix it？@pateketrueke

**Comment by pateketrueke** [comment]
hey, sure! I'll fix it, but once I have some spare time... thank you!

**Comment by Mustang-Galaxy** [comment]
> hey, sure! I'll fix it, but once I have some spare time... thank you!

ok, fine, thank you so much
