### ISSUE TITLE
throw "Error: TypeError: Cannot read property 'value' of null" for specific json schema

### ISSUE THREAD

**Issue by werifu** [json-schema-faker/json-schema-faker#719]
If you are reporting a bug, please include the following:

1. the JSON Schema content that fails - preferably using http://json-schema-faker.js.org/ (paste the schema, click `Generate example` and then copy and paste the resulting URL from the browser address bar)

This is a valid json schema
```json
{
  "type": "object",
  "properties": {},
  "required": [],
  "additionalProperties": false,
  "$schema": "https://json-schema.org/draft-07/schema"
}
```

3. the result you got

![image](https://user-images.githubusercontent.com/53432474/191202233-74fbdb7e-2510-419b-a15a-cadf6d219ac2.png)

5. the result you expected

Gernerate an empty json {}

**Comment by pateketrueke** [comment]
Hi @werifu good catch! Definitely is a use-case, I'll be fixing it asap, thank you!
