### ISSUE TITLE
cleaning up branches

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#72]
There are two branches we might not need:
* [fix-issue-62](https://github.com/json-schema-faker/json-schema-faker/tree/fix-issue-62)
* [docs/testing](https://github.com/json-schema-faker/json-schema-faker/tree/docs/testing)

Is it OK to remove them? FYI: Before releasing `0.2.1`,I didn't do a merge commit (I don't like that), instead, I did a git rebase. And there were few minor conflicts I resolved. Anyway, now, when you compare those branches with master on github, you might see they're not merged in, because, literally, they're not. But their code might be there already. Therefore I need to know if I can remove them.

I can see in https://github.com/json-schema-faker/json-schema-faker/pull/65 that `fix-issue-62` migt be removed,,,

BTW, The http://json-schema-faker.js.org demo page is updated to 0.2.1.

**Comment by pateketrueke** [comment]
> Is it OK to remove them?

Yes, please. :beers:

For  `docs/testing` is only the README inside the `spec` folder.

**Comment by ducin** [comment]
Done.
