### ISSUE TITLE
Support "duration" format type

### ISSUE THREAD

**Issue by alii** [json-schema-faker/json-schema-faker#720]
I am converting the docker-compose JSON schema spec (https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json), and it would be cool to support the string format "duration"

Spec can be found: https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats

**Comment by pateketrueke** [comment]
Yeah, I think we can support such format as well, do you mind on implementing such as a PR, thank you!
