### ISSUE TITLE
dependencies update

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#73]
Need to bump up dependencies, https://david-dm.org/json-schema-faker/json-schema-faker

**Comment by ducin** [comment]
Just read that there is a platform that does the job automagically, http://greenkeeper.io. It is free for open-source projects. I'd give it a try. @pateketrueke, what d'ya think?

**Comment by pateketrueke** [comment]
Sure thing! :beers:

**Comment by ducin** [comment]
There was a little bit of chaos here, sorry for that. We've had two changes: `develop` branch changes and dependencies version bumps by greenkeeper. I haven't seen that the tests for develop *fail* and I merged it into master... but I rolled it back immediately.

Then I made the new 0.2.2 version with greenkeeper only and it passes https://travis-ci.org/json-schema-faker/json-schema-faker/builds/84592408 so I'm releasing it out (new chance.js has been released, causing our deps to be out of date).

So *the good thing* is that greenkeeper seems to solve the problem of dependencies for us, whilst *the bad thing* is that the `develop` branch remains unstable and needs more work.

**Comment by ducin** [comment]
* work done.
* `release-0.2.2-only-greenkeeper` deleted, since it has served it's role (it's the new `master`).
* `release-0.2.2` deleted, since 0.2.2 has been taken and `develop` needs more work.
* the `greenkeeper-update-all` branch is used by greenkeeper, so I guess we shall leave it alone.
