### ISSUE TITLE
(min|max)Length seems to be ignored when specifying a pattern

### ISSUE THREAD

**Issue by chrisns** [json-schema-faker/json-schema-faker#74]
```javascript
"reason": {
  "type": "string",
  "pattern": "^([A-Za-z0-9- ]+)$",
  "minLength": 0,
  "maxLength": 5
},
```
results in strings exceeding the length

**Comment by ducin** [comment]
@chrisns shouldn't your regex be just `^([A-Za-z0-9- ]{0,5})$`?

**Comment by chrisns** [comment]
yes, I can do that and it works fine and not have it in the ```minLength``` + ```maxLength```
but that does make it less readable

**Comment by ducin** [comment]
Anyway, there is a problem here if properties are in conflict. If we've got following definition:
```
"reason": {
  "type": "string",
  "pattern": "^([AAAAA|BBBBB|CCCCC])$",
  "minLength": 0,
  "maxLength": 2
},
```
(regex is an alternative of 5-char long strings + the maximum length is 2, which conflicts)
How should such definition behave? I can see following options:
* try to analyse the semantics of a regex - seems extra difficult and not sure if doable
* execute the regex pattern first and then see if it should be trimmed down (... or extended?) to fit the min/max size. This doesn't solve the entire problem, but is predictable at least.
Any other ideas?

**Comment by chrisns** [comment]
ummm good point, I don't know, its not going to stop you writing invalid schemas really.
I guess we'd need to refer to the order rules are applied in some of the larger validators
