### ISSUE TITLE
Option `alwaysFakeOptionals` causes `additionalProperties` to generate the wrong type.

### ISSUE THREAD

**Issue by ar185356** [json-schema-faker/json-schema-faker#749]
When `alwaysFakeOptionals` is enabled, data generated for a schema with `additionalProperties` of a specified type, will often generate properties of the wrong type. In the example below, every additionalProperty must be a string, although when `alwaysFakeOptionals` is enabled, it generated numbers and booleans too.

1. JSON Schema Content  
Enable `alwaysFakeOptionals`
```json
{
  "properties": {
    "fields": {
      "type": "object",
      "additionalProperties": {
        "type": "string"
      }
    }
  }
}
```

2. Actual Result

As you can see below the additional properties generated are strings, a number and a boolean. This only happens if `alwaysFakeOptionals` is true. 
```json
{
  "fields": {
    "ad_112": false,
    "ex__f": -53137584.11285665,
    "ut_87": "ad aute",
    "reprehenderit_17": "Duis culpa eiusmod in",
    "do_1": "ipsum sed ut dolore",
    "nostrud_": "labore esse"
  }
}
```

3. Expected Result

This should only generate string values as any other type is not valid.
```json
{
  "fields": {
    "ad_112": "a string",
    "ex__f": "another string",
    "ut_87": "ad aute",
    "reprehenderit_17": "Duis culpa eiusmod in",
    "do_1": "ipsum sed ut dolore",
    "nostrud_": "labore esse"
  }
}
```

**Comment by liangskyli** [comment]
I have a similar problem when enabling alwaysFakeOptions

**Comment by liangskyli** [comment]
similar problem see #750

**Comment by liangskyli** [comment]
this issue reason is:
when set additionalProperties in JSON Schema, and use anyType to generate random attributes
anyType ===>  const ALLOWED_TYPES = ['integer', 'number', 'string', 'boolean'];
so additional properties generated are strings, a number and a boolean. but this only happens if alwaysFakeOptionals is true.
AnyType is used when alwaysFakeOptions is true

src/lib/types/object.mjs line 195-201
```
  if (!extraProperties.length && !neededExtras && allowsAdditional && fixedProbabilities === true) {
    const limit = random.number(0, max);

    for (let i = 0; i <= limit; i += 1) {
      props[words(1) + hash(limit[i])] = anyType;
    }
  }
```
