### ISSUE TITLE
0.5.0 has no dist dir

### ISSUE THREAD

**Issue by lusyn** [json-schema-faker/json-schema-faker#767]
https://www.npmjs.com/package/json-schema-faker?activeTab=code
![image](https://github.com/json-schema-faker/json-schema-faker/assets/8433821/5e90c8ac-0b25-4085-a9e6-e3acf6c779fd)

where is the dist dir?

**Comment by pateketrueke** [comment]
@lusyn good catch, I totally missed to prebuild files before publishing! 😭
