### ISSUE TITLE
This relative module was not found:      * ./vendor.js in ../node_modules/json-schema-faker/dist/main.mjs

### ISSUE THREAD

**Issue by ma-x-x** [json-schema-faker/json-schema-faker#769]
<img width="1213" alt="image" src="https://github.com/json-schema-faker/json-schema-faker/assets/20221017/e4727eca-ddc8-4225-91ee-fe005d8c19a5">

**Comment by pateketrueke** [comment]
Yeah, the current release is broken, I'm gonna fix it!

**Comment by ma-x-x** [comment]
您好，我已经收到您的来件，我会尽快处理的。祝您工作生活愉快。                                              ——BastogneYu
