### ISSUE TITLE
[question] [discussion] [help needed] Generating json object with random key

### ISSUE THREAD

**Issue by hellboy81** [json-schema-faker/json-schema-faker#77]
How can I generate object with random key that has following schema:

``` js
{
            type: 'string',
            chance: {
                hash: {
                    casing: 'upper',
                    length: 32
                }
            }
}
```

Key should be generated on the basis of previous schema ([random](http://git.io/vWkVJ) upper-cased string with length 32)

``` js
{
   "110B949E3BF0FE7C0DC15A17F04FA53E": { // Fake object is generating based on another schema 
      ... // Some fields
    }
}

```

**Comment by ducin** [comment]
Hi @hellboy81, you can't do that *in one step*, I mean, json-schema-faker doesn't allow you to do such thing out of the box.

But if you do need such feature, you might just divide generating above document into two steps:
 * generate the key and store it as a string
 * use the key as a part of a dynamically-generated json-schema.
This will do the trick.

There is very little chance we'd like to implement such feature into json schema faker. And that's because jsf is just a tiny superset of json-schema standard: we add very little to the standard, but provide big functionality. The more we stick to the standard, the more other javascript tools could integrate with jsf. The more we distance from the schema, the more difficult it'd be to integrate.

Do you need something further?

**Comment by pateketrueke** [comment]
Or you can use `patternProperties` as follows:

```json
{
  "type": "object",
  "patternProperties": {
    "[A-Z\\d]{32}": {
      "type": "string"
    }
  }
}
```

As it follows the json-schema standards I think it would be enough?

**Comment by ducin** [comment]
@pateketrueke didn't know about this feature. Now I have a question here - how can we make this dynamically generated attribute required? I've pasted your code into [our demo](json-schema-faker.js.org) and it randomly gets either the dynamic thing generated or whole being empty.

**Comment by pateketrueke** [comment]
I've missed it but using `minProperties` does the trick:

```json
{
  "type": "object",
  "patternProperties": {
    "[A-Z\\d]{32}": {
      "type": "string"
    }
  },
  "minProperties": 1
}
```

**Comment by hellboy81** [comment]
@ducin  OK, this is not a part of JSON-Schema specification _draft-04_

**Comment by ducin** [comment]
@hellboy81 ORLY? Look at [this](http://json-schema.org/example2.html), the find (ctrl+f): `patternProperties` - it is a part of the [json schema validation](http://json-schema.org/latest/json-schema-validation.html#anchor64). At least that's what I can see.

@pateketrueke not sure what you mean: *you missed it*, like, you can't remind what was the right attribute to set, but it does exist? Or you don't know whether it exists or not? ;) the trick you wrote above works for simple cases, but it doesn't seem to scale, if you want to customize the object with required attributes and optional attributes and all the rest that json schema provides.

**Comment by pateketrueke** [comment]
@ducin yeah, sorry for that, I've missed that property in the given example.

And yeah, is very difficult to ensure required `patternProperties` all the time, I think we need to explore edge cases for that. ;)

After some research most people say that using min/max properties would be a solution.

I didn't get a better idea and JSON-schema is not clear about that.

**Comment by ducin** [comment]
Seems like @hellboy81 's question leads to a gap in json schema standard. @pateketrueke no worries! :beers:

**Comment by lzrski** [comment]
Hello. Thanks for json-schema-faker. I use it for simple property based testing and it works like a charm most of the times.

One of the times when it doesn't is with multiple patternProperties. Consider this (coffeescript):

```coffeescript
fake = require 'json-schema-faker'

schema =
  type: 'object'
  minProperties: 1
  maxProperties: 20
  patternProperties:
    '.*': type: 'string'

console.log fake schema
```

The output is:

```json
{
  "F@^B\\(\\mdp[eKj>qUbzj7\"QwAmbK,5RTgqV6/'tu#y4IAfc;2N[N7wPlz~tnoFf'OlF/rfw=^^SWpGc\\|h(j# Q)k9\"tNYuL": "ma",
  "velit9f36": {},
  "Ut1750": {},
  "dolorc00bb": {},
  "animb8e86": {},
  "sit842e9f": {},
  "magnac5b9978": {},
  "tempor173d": {},
  "ex23e707d": {},
  "indb17c3f": {},
  "esse4763fb": {},
  "mollita10f79": {}
}
```

As you can see only the first property is correctly generated. Rest are empty objects.

I've also noticed that first property always has much longer and more complicated name.

**Comment by ducin** [comment]
Cześć @lzrski :) I will take a look at this. Can't guarantee when, but I'll try to do that soon. Seems like it's a one-liner minor issue, hopefully ;)

**Comment by ducin** [comment]
btw, @lzrski could you create a separate issue for that? I think it's different than @hellboy81 asked. Your issue is just a clear bug.
