### ISSUE TITLE
Run in browser crash: Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by wmzy** [json-schema-faker/json-schema-faker#773]
![image](https://github.com/json-schema-faker/json-schema-faker/assets/5526525/3112af57-939e-4a4f-b3b4-afbbcbf480de)

reproduction link： https://stackblitz.com/edit/vitejs-vite-tzptty?file=src%2Fmain.ts

Does [the process.env.VERSION](https://github.com/json-schema-faker/json-schema-faker/blob/a42196599df7790b83aa87a9856534bf94ea9b52/src/lib/index.mjs#L188) should be replaced at build time?

**Comment by pateketrueke** [comment]
Good catch! Seems to be working now: https://stackblitz.com/edit/vitejs-vite-ofxser?file=src%2Fmain.ts 🎉
