### ISSUE TITLE
Required property within empty

### ISSUE THREAD

**Issue by litianyiliwei** [json-schema-faker/json-schema-faker#776]
![image](https://github.com/json-schema-faker/json-schema-faker/assets/7813324/6ba15c05-c3da-4883-850a-aa993f4fe958)

**Comment by pateketrueke** [comment]
Hi, I think the results are correct, in your regex you have `^$` as part of the potential matches, and that actually means an empty string...

**Comment by litianyiliwei** [comment]
sorry，thanks
