### ISSUE TITLE
"global is not defined" when running with storybook

### ISSUE THREAD

**Issue by zmen** [json-schema-faker/json-schema-faker#777]
When running storybook with json-schema-faker as dependency, it show the error: 
![image](https://github.com/json-schema-faker/json-schema-faker/assets/11732386/f238afc0-2483-40d8-b99d-bfb9145f4b5e)

which is cased by `patch.js`:
![image](https://github.com/json-schema-faker/json-schema-faker/assets/11732386/0aff270c-cb68-4095-94b8-9fc4cd1d5c17)

`process` is defined doesn't ensure it's running in node, so before reading 'global' it's better to make sure that it is defined as well.

**Comment by zmen** [comment]
@pateketrueke I am consuming `/dist/main.mjs` as it is declared as `module` in package.json.

Inside `main.mjs` it imports `vendor.js` directly:

![image](https://github.com/json-schema-faker/json-schema-faker/assets/11732386/cb09e485-c925-4a7a-bcd2-90cb890c4d14)

And following is the content of vendor.js:
![image](https://github.com/json-schema-faker/json-schema-faker/assets/11732386/493748d7-3796-44c3-b916-a5373aad4a02)

**Comment by pateketrueke** [comment]
Sorry, you're right. Let me see if I can ship a new version with a patch, thank you!

**Comment by LuigiAlice** [comment]
Hi,

we are running into the same problem without storybook.
Is there still a fix available for version 0.5.3 or above?
Can you check, if "global" exists?

**Comment by JacobWennebro** [comment]
Running into this issue as well trying to bundle it with Vite
