### ISSUE TITLE
"global is not defined"

### ISSUE THREAD

**Issue by LuigiAlice** [json-schema-faker/json-schema-faker#780]
I get a console.log output from vendor.js:

"global is not defined"

In package.json:

`"json-schema-faker": "0.5.3",`

Usage:
`import { JSONSchemaFaker as jsf } from 'json-schema-faker';`

**Comment by JacobWennebro** [comment]
Same issue occurs for me trying to use 0.5.3 with Vite, previous 0.5.0-rcv.46 is able to be bundled fine.

**Comment by LuigiAlice** [comment]
Yes, old version works.GrüßeLuigi AlicePer Mobiltelefon gesendet.
-------- Ursprüngliche Nachricht --------Von: Jacob ***@***.***> Datum: 10.10.23  16:26  (GMT+01:00) An: json-schema-faker/json-schema-faker ***@***.***> Cc: LuigiAlice ***@***.***>, Author ***@***.***> Betreff: Re: [json-schema-faker/json-schema-faker] "global is not defined"
  (Issue #780) 
Same issue occurs for me trying to use 0.5.3 with Vite, previous 0.5.0-rcv.46 is able to be bundled fine.
