### ISSUE TITLE
Improperly handling 'allOf' block

### ISSUE THREAD

**Issue by Dygerati** [json-schema-faker/json-schema-faker#80]
I've got an issue that stems from a schema something like the one below. I can also reproduce on your web-based generator [here](http://json-schema-faker.js.org/).
```
{
	"allOf": [{
		"required": ["order"],
		"properties": {
			"order": {
				"type": "string"
			}
		}
	}, {
		"required": ["id"],
		"properties": {
			"id": {
				"type": "number"
			}
		}
	}]
}
```

If I plug in the proceeding schema, all but the last object listed in the *allOf* array is ignored. The output of above is as follows:
```
{
  "id": 75693268
}
```

When it should also include the "order" property outlined in the first object. Any thoughts?

**Comment by pateketrueke** [comment]
Yes, I know that issue and actually your json-schema MUST work as you expect.

I'll fix that asap, thanks for your feedback!

**Comment by Dygerati** [comment]
Great, thanks!

**Comment by pateketrueke** [comment]
It works! :beers:

http://json-schema-faker.js.org/#{%22allOf%22%3A[{%22required%22%3A[%22order%22]%2C%22properties%22%3A{%22order%22%3A{%22type%22%3A%22string%22}}}%2C{%22required%22%3A[%22id%22]%2C%22properties%22%3A{%22id%22%3A{%22type%22%3A%22number%22}}}]}

**Comment by Dygerati** [comment]
That was fast! And it works great; thanks!
