### ISSUE TITLE
Generate ONLY required fields?

### ISSUE THREAD

**Issue by Dygerati** [json-schema-faker/json-schema-faker#81]
Is it possible, when generating JSON, to limit it to only the required fields? Right now it mandates required fields and randomizes the others. 

We're trying to use this to generate auto-updating documentation, and including non-required properties could confuse things.

**Comment by pateketrueke** [comment]
Yeah, I think it's possible.

Using `jsf(schema, refs, true)` could be a strict-version for...

Even more, did you think in another possible "options" to take into account?

**Comment by Dygerati** [comment]
Thanks, although those parameters don't seem to have any impact. 

Looking at the source code I don't actually see a 3rd argument? What "options" do you mean?

**Comment by pateketrueke** [comment]
> Looking at the source code I don't actually see a 3rd argument? What "options" do you mean?

I'd mean, it's not implemented yet, just I've draw how it can be used:

```javascript
jsf(schema, { requiredOnly: true })
jsf(schema, { strict: true })
jsf(schema, refs, true)
jsf(schema, true)
// etc...
```

I think this feature would add much value so I'll implement this asap. :beers:

**Comment by Dygerati** [comment]
Awesome, much thanks!

**Comment by bitdivine** [comment]
Hello,

Thanks for what looks to be a promising library!  has there been any progress on requiredOnly?  I'm actually interested in `requiredOnly:false` as at the moment I'm getting the required properties and none other.  Happy to help if you are super-busy!

Regards, Max

**Comment by bitdivine** [comment]
Demo showing that at the moment optional properties are not generated:  http://json-schema-faker.js.org/#%7B%22type%22%3A%22object%22%2C%22required%22%3A%5B%22pink%22%5D%2C%22properties%22%3A%7B%22pink%22%3A%7B%22type%22%3A%22integer%22%7D%2C%22blue%22%3A%7B%22type%22%3A%22integer%22%7D%7D%7D

**Comment by pateketrueke** [comment]
Well, that's not implemented yet, and I think it will be very helpful... also I guess it must be refactored a bit because the solution is not clever.

I'm not super-busy, let me think about this.

Thanks for your feedback!

**Comment by bitdivine** [comment]
My workaround for now:  Add some of the optional elements to the required list.  I have it easy in that I don't have any pattern properties in this part of the code! :-)


    function requireSome(schema){
        if (schema.type === "object"){
                schema.required = uniq([].concat
                ( Object.keys(schema.properties).filter(()=>Math.random()<=0.8)
                , schema.required ||[]
                ));
                Object.keys(schema.properties).forEach((k)=>requireSome(schema.properties[k]));
        }
    };

Once you have thought, please let me know if you'd like me to code.  This is a big field so I don't expect one solution to fit everything.  I guess one can try to deal with the most common cases cleanly and reliably.

**Comment by ducin** [comment]
After we're done with TS migration, [the outer JSF API](https://github.com/json-schema-faker/json-schema-faker/blob/9bcff00e0ba2ffba080914275598a04f3cc6b9bf/ts/index.d.ts#L50-L54) would need to get updated:

```
interface jsfAPI {
  (schema: JsonSchema, refs?: any): any;
  format: Function;
  extend: Function;
}
```

with whatever jsf api we come up with. This interface states what end users might do with imported node jsf module.

**Comment by pateketrueke** [comment]
@bitdivine 

> has there been any progress on requiredOnly?

Yes, finally landed to `develop` branch. :tada:

By default `requiredOnly` is always `false`, so optional properties are being generated as well.
