### ISSUE TITLE
Spec "should handle maximum" failed

### ISSUE THREAD

**Issue by pateketrueke** [json-schema-faker/json-schema-faker#82]
I ran this: `while grunt spec --no-lint; end` :+1: (some time later... boom! :bomb:)

**Comment by ducin** [comment]
@pateketrueke could you please provide a little bit more descriptive information :)? Does it mean that `grunt spec` task fail randomly or what?

**Comment by pateketrueke** [comment]
@ducin well, the grunt task is not failing per-se, just sometimes the faked values are not what the spec is expecting and the spec fails then... I don't know how test this edge cases, may be using some property-based testing?

Of course since jsf is using `faker.js` to generate its random numbers I'm not sure if this is our issue.

**Comment by ducin** [comment]
I must say I haven't seen this spec failing through entire process of typescript migration. I consider it as a *won't fix*...

**Comment by ducin** [comment]
Ok, so I've used the spec json schema, created a simple test file and ran it inside a 1..100 loop and the result states that the error is not here anymore. I guess the migration might have solved the bug:

```
$ for i in {1..100}
> do
>   node test.js
> done
25
29
27
21
24
25
27
21
24
23
27
22
27
20
20
26
20
21
28
25
28
28
24
21
26
24
26
20
20
26
26
23
28
24
28
24
22
20
22
29
25
22
26
25
26
22
24
20
28
21
20
22
20
21
29
27
25
29
27
26
23
26
20
26
26
28
24
23
29
25
23
23
24
22
26
26
27
28
22
26
21
23
22
21
22
28
27
28
27
28
20
26
20
23
27
28
25
27
27
26
```
Closing that one.
