### ISSUE TITLE
Gracefully handle unrecognised types

### ISSUE THREAD

**Issue by XVincentX** [json-schema-faker/json-schema-faker#83]
Hello!
First of all, thanks a lot for the great library.

During our usage, we're dealing with some schemas which have an unrecognised `type`, such as `customStructure` and so on.

Actually faker throws an exception, as you can see here.

![image](https://cloud.githubusercontent.com/assets/1416224/11535031/4999867c-9912-11e5-974e-02f085316a57.png)

It would be great if it could gracefully handle the situation like an empty string, or a default provided value, or skipping the field at all.

Would you be interested in a PR fixing this thing? Which approach do you think would be the best one?
Cheers!

**Comment by ducin** [comment]
Hello Vincenzo :) now we meet here :)

Two questions:
1. What exactly throws the error - faker.js or json-schema-faker?
2. Could you provide examples of schemas? It'd be a lot easier for us, knowing what exactly we're deadline with.

**Comment by XVincentX** [comment]
No, that's incredible! YOU? :+1: 

By the way:
Reproducing the error is very simple and it can be done directly from your [online demo page](http://json-schema-faker.js.org/)

```json
{
  "type": "customStruct"
}
```

Putting this as schema and then clicking **Generate Sample** is enough to trigger the error in the console.

Actually, I am quite sure the problem is in `json-schema-faker` in [traverse.js#L35](https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/util/traverse.js#L35)

Is that enough to discuss the thing or - do you need other details?

**Comment by pateketrueke** [comment]
> Is that enough to discuss the thing or - do you need other details?

I guess that feature could be implemented easily for allowing us to provide custom types or fallbacks. :+1:

This could take a time for me to solve that, since I think it's related to #81 about settings for alter the default jsf behavior.

Any suggestion for the option-name?

**Comment by ducin** [comment]
@pateketrueke Honestly I don't see the relation between Vincenzo's error and #81. This task is about handling the "unknown schema type" error - we can, for example, throw new type of exception, a meaningful one.

And what would the custom setting override, I mean, what exact behavior?

**Comment by pateketrueke** [comment]
Actually jsf will fail on unrecognized types: there is no support for extending what is built-in.

This behavior is not an exception, we could easily add some aliasing for fallback without throwing errors.

I thought both issues are related because jsf has no support for these options.

**Comment by ducin** [comment]
Ok, so do you think of this option as a map of unsupported->supported types, e.g. Custom1 -> number, Custom2 -> string? Or a fallback function? In that case - what could it do? And what would the user benefit - would the schema execute anyway?

If we can't extend the built-in types, then a schema that contains Invalid types shall not be executed, I think. Invalid things should just fail - and a SchemaError, when thrown, might be just more descriptive for the user.

I'm *not* against this fallback, just trying to understand the intention ;)

**Comment by pateketrueke** [comment]
> If we can't extend the built-in types, then a schema that contains Invalid types shall not be executed

Well, **we can**... indeed both parts (generators/validators) may support them aswell, if you want to validate against a custom type the validator will fail and it's ok. If you provide the validation support for that type then everything works as expected.

Unrecognized keywords _may_ be treated as warnings, sometimes are just errors and jsf must understand that.

Looking at http://json-schema.org/schema there is a "regexp" and jsf is missing it... plop!

Currently I don't know how to fake valid "regex" values, but we can easily ignore-or-fallback it, or use a callback for picking a random regexp from other places, etc.

In a "strict" mode we should throw exceptions because mistakes are not allowed, but in other scenarios you don't want that.

JSON-Schema is not (and shall not be) limited to its built-in types, what can we do?

I'm "planning" some options for that:

- **strict** (fail asap, otherwise will use fallback-types, etc.)
- **nonEmpty** (delete empty properties, items, values, etc.)
- **maxDepth** (for recursive sub-schemas until that depth)
- **defaultsOnly** (use _defaults_ only, otherwise will fail if missing)
- **requiredOnly** (related to #81, skip all optional properties)
- **customTypes** (simple mapping for fallback-types, callbacks, etc.)
- _something else?_

I'm not sure if this would be ok... let me know ;)

**Comment by igorshmukler** [comment]
Sorry. I could not figure out how to message maintainer. I used json-schema-faker and it seems that oneOf is broker instead doing "some or none" Of. i guess oneOf currently does anyOf, but I am not positive.
Let me know if I can be of assistance supplying a test, or something...

**Comment by pateketrueke** [comment]
@igorshmukler I guess you're trying to open an [new issue](https://github.com/json-schema-faker/json-schema-faker/issues/new) right?

And yes, actually in jsf anyOf/oneOf are mostly equivalent, I didn't know that oneOf should mean "some or none" do you have a reference for that detail?

PS: please open a new issue, we continue the discussion there.

**Comment by ducin** [comment]
sorry for the delay, @XVincentX, going back to the topic. By that time we've migrated our source from JavaScript into TypeScript and now it's easier to reason about the code and to find the bugs, extend, etc :)

Going back to what you initially suggested. As far as I understand it *now*, you'd like to pass an option to jsf stating whether it should or should not fail when an invalid type is being passed. SO currently you can do:

```
var jsf = require('json-schema-faker');
var schema = {...};
var sample = jsf(schema);
```
And a simple solution here might be overriding default jsf behavior, such as:
```
var jsf = require('json-schema-faker');
var schema = {...};
jsf.options({
  "failOnInvalidTypes": false
});
var sample = jsf(schema);
```
Is that what you meant?

BTW, TypeScript would be perfect here to restrict allowed string for option names :dancer:

**Comment by XVincentX** [comment]
Exactly. Actually I am solving the problem with a `try/catch` block (see here https://github.com/apiaryio/refract-message-body-generator/pull/5/commits/a49f275fdaa58bebeb3cb3f07400d998d9607dc9), but I would love to pass a flag and avoid that.

**Comment by ducin** [comment]
fuck no! Apiary is using json-schema-faker? Can we state that officially as our business success usecase :heart_eyes: :question:

**Comment by pateketrueke** [comment]
> Apiary is using json-schema-faker? :heart_eyes:

**Comment by XVincentX** [comment]
That's an unusual request! Let me escalate the thing, but I do not see any blocking issue here! 👍

**Comment by ducin** [comment]
@pateketrueke blocker on my way :( it's not difficult to add the funcionality, but I want everything to be covered with tests. And now, each schema is validated against `z-schema`. And this validator doesn't allow any non existent types and it simply fails and I got no idea how to make the inner test validation pass... don't want to do ugly hacks

**Comment by ducin** [comment]
Found a temporary overcome. The `"valid": <boolean>` in each test spec states whether `z-schema` shall be fired against such unit. So in this case it's not (valid: false). I'm positively surprised myself, but it does the job :)

when having (we have this actually):
```
jsf.option({
  'failOnInvalidTypes': false
});
```
the tests pass with no error (since the new flag for @XVincentX is turned off) and z-schema is silent because it's not fired. But if I switch the flag to:
```
jsf.option({
  'failOnInvalidTypes': true
});
```
which is the default, then we'd get:
```
................................F.........................................

Failures:

  1) failOnInvalidType option (C:/Users/tomasz.ducin/Development/json-schema-faker/json-schema-faker/spec/core/option/failOnInvalidType.json) should handle failOnInvalidType option
    Message:
      Error: unknown primitive "unknown" in /type
```
so inho it does the job well enough.

**Comment by ducin** [comment]
Following code:
```
var jsf = require('./index');
var schema = {
  "type": "nonExistentType"
};
console.log(jsf(schema));
```
results with:
```
$ node test.js
C:\Users\tomasz.ducin\Development\json-schema-faker\json-schema-faker\lib\core\run.js:56
            throw new Error(e.message + ' in ' + '/' + e.path.join('/'));
            ^

Error: unknown primitive "nonExistentType" in /type
    at run (C:\Users\tomasz.ducin\Development\json-schema-faker\json-schema-faker\lib\core\run.js:56:19)
    at jsf (C:\Users\tomasz.ducin\Development\json-schema-faker\json-schema-faker\lib\index.js:6:12)
    at Object.<anonymous> (C:\Users\tomasz.ducin\Development\json-schema-faker\json-schema-faker\test.js:72:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3
```
whereas following:
```
var jsf = require('./index');
jsf.option({
  'failOnInvalidTypes': false
});
var schema = {
  "type": "nonExistentType"
};
console.log(jsf(schema));
```
results with:
```
$ node test.js
null
```

**Comment by ducin** [comment]
`0.3.1` has been released. @XVincentX please try it out and give feedback.

**Comment by oscary25** [comment]
I uninstalled gel pack (--save) and it worked!
###
