### ISSUE TITLE
If a custom format is defined may be useful to override default formats as well

### ISSUE THREAD

**Issue by andrescardona** [json-schema-faker/json-schema-faker#88]
Hi,

Currently i see that a customer has some variations on basic data formats, like date-time they manage a slightly different format, so i can't override unless i add to the current schemas a faker or a chance attribute. Wouldn't be better to have it flexible so we can also override default behaviour?

Made a pull request with my suggestion :) https://github.com/json-schema-faker/json-schema-faker/pull/87

**Comment by ducin** [comment]
Hi @andrescardona! Thanks for your contribution. Could you please give any examples of the situation described?

**Comment by andrescardona** [comment]
Yeah, currently for date-time, the client just want to have the following format 'yyyy-MM-dd HH:mm:ss:SSS' wich differs from the standard iso-xxxx one by the 'T' in the middle, now if i want to generate those, i would have to add to the current client schemas a faker or another property and the idea is to leave those schemas as they are :)

**Comment by ducin** [comment]
Ok, maybe I didn't make myself clear enough :) I'd ask you to provide an example schema for described situation. I assume that it would behave in a different way in current jsf and in your modified version.

Sorry to bother you but it makes it a lot easier for us to handle any submissions (see CONTRIBUTING.ms) :)

**Comment by pateketrueke** [comment]
Yeah, it sounds good but a well defined example would be better, even with tests/specs. ;)

**Comment by pateketrueke** [comment]
Only a though: if you override the default `date-time` format then your json-schema will not be reusable for others since aren't following the standards. The "right way" would be defining a custom format for that, this way other tools that understand JSON-Schema will no bother you.

**Comment by andrescardona** [comment]
Oh, ok the json schema is just as the standard
```
...{... "startDate": {"type": "string", "format": "date-time"} ...}
```
But, the Json mapper in the server has an specific date format, Of course i don-t want to promote like an specific case scenario as a general one, but i checked in validations libraries for example and the default format validation can be overwritten, I-m agree that the proper way to do this is to have a custom format in the schema, like my-date-time, but i see it like a flexibility improvement, if the user wants to add extra validation to default data types it wold be able to.

**Comment by zanona** [comment]
I might be wrong but I don't see benefits while having built-in formats overriding custom ones.

```json
{ "email": { "type": "string", "format": "email" } }
```
Supposing I only want to emit internet emails based on a schema without having to change the definition itself. It should be quite a common use case where the email format is validated elsewhere and it's just not possible to change or add new attributes on the schema itself.

So:
```js
jsf.formats('email', function (gen) {  return gen.faker.internet.email(); });
```
Should certainly prevail over the default email format handler.

**Comment by pateketrueke** [comment]
Please read our [CONTRIBUTING](https://github.com/json-schema-faker/json-schema-faker/blob/develop/CONTRIBUTING.md) guidelines. :beers:

**Comment by ducin** [comment]
note that since `v0.3` the API changed in just one place: from `jsf.formats` to `jsf.format`

**Comment by pateketrueke** [comment]
That behavior is corrected now, custom formats has precedence over built-in ones. 👍
