### ISSUE TITLE
include distribution files

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#90]
`jsf` might be successfully used in the browser, not only in Node.js.
This task is to include `dist/jsf.js` and `dist/jsf-min.js` into the repository for each new version.
Grunt needs to be extended with grunt-browserify.
@pateketrueke are you ok with that?

**Comment by pateketrueke** [comment]
I think it's ok, are you planning publish both for bower and jspm?

**Comment by ducin** [comment]
Originally I was thinking about cdnjs ;) it might be a little painful for the first time, https://github.com/cdnjs/cdnjs#important---no-more-manual-submissions, haven't done that auto-script. But I think cnd.js might be a good idea.

**Comment by ducin** [comment]
@pateketrueke how do you think - is it better to name the file `jsf.js` or `json-schema-faker.js`?

**Comment by pateketrueke** [comment]
Oh nice, cdnjs is a good starting point!

And I think that `jsf` is more an abbreviation, officially would be `json-schema-faker` for consistency.

**Comment by ducin** [comment]
Released in `v0.2.7`.
A tiny problem is that the minified (or uglified, whatever...) version is not that smaller :( but I didn't manage to investigate why, I think I'm doing it correctly.

**Comment by pateketrueke** [comment]
Seems like many modules like `Buffer` are being included as well, other issues are locales and such: as long I know are just browserify options (not sure if `off|on` are treated as real booleans).

It would be interesting if we can build as many languages faker/chance supports, e.g.

- json-schema-faker.es.js
- json-schema-faker.de.js
- json-schema-faker.en.js
- json-schema-faker.it.js

Related: #56

**Comment by ducin** [comment]
Damn... seems like the `grunt-parts` is not allowing me to include any other grunt on top level :( Can you [take a look at it](https://travis-ci.org/json-schema-faker/json-schema-faker/builds/105462572#L353)? Or maybe it's me who messed something...

**Comment by ducin** [comment]
Let's continue the locales thing in #91.

And let's close this issue once the build is fixed. I'd be for creating a separate issue for reducing the build size.

**Comment by pateketrueke** [comment]
> Can you take a look at it? Or maybe it's me who messed something...

Sure, let me checkout your branch, and btw I'm thinking on switch to npm-scripts for those tasks.

**Comment by ducin** [comment]
The cdnjs task is in progress since few days, I hope to have it finished soon: https://github.com/cdnjs/cdnjs/pull/6844

**Comment by ducin** [comment]
:microphone: Woohoo! :trumpet: `jsf`:saxophone: has :musical_keyboard: finally :violin: arrived :guitar: to :bomb: cdnjs!!! :microphone:
https://www.cdnjs.com/libraries/json-schema-faker
