### ISSUE TITLE
loading only specified dependencies

### ISSUE THREAD

**Issue by ducin** [json-schema-faker/json-schema-faker#91]
I've got an idea for that. There was a long discussion in the #56 thread about magical options of browserify. But I think I've got another idea. I took a look at [faker.js' individual localization packages](https://github.com/Marak/faker.js#individual-localization-packages). It is a damn simple yet working concept, sounds a lot easier for me:
* by default, you've got the main [index.js file](https://github.com/Marak/faker.js/blob/master/index.js) which has static `require` calls, browserify works perfect
* above that, each language has its own *entry file* in the [locale directory](https://github.com/Marak/faker.js/tree/master/locale), e.g. [es_MX](https://github.com/Marak/faker.js/blob/master/locale/es_MX.js) - which is an alternative main file, browserify will work perfectly as well
So above what faker.js supports and I'm pretty sure Marak won't break it in the future.

So what I was thinking is to reuse faker.js' localized browserify and, mainly, reuse the whole concept behind CommonJS/browserify. The fundamental file here is [lib/util/container.js](https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/util/container.js#L5-L11) and it's requires. What I'm thinking right now is to:
* modify our codebase so that those native `require` calls go to the top file (but the container can stay where it is, nevermind)
* the `lib/index.js` stays as the main file as it is now - it load everything.
* additionally, we provide a *template* js file (not really JS, let's say, a code *macro* file) that would get processed by grunt, gulp, whatever text preprocessor and will result in a certain cofniguration that has been passed. I want to be able to add certain languages to faker.js, but also, I want ot be able to throw out each of faker, chance, randexp, if the consumer doesn't wish to use them. The good thing is that *container* throws an exception when a generator is not found, as expected - in other words - if you bundle jsf without chance and you fire a schema including chance, you'd get the error.
* provide examples of how to use that. The text processor might be even underscore templates + browserify run afterwards.

I think it's pretty easy and a flexible solution.

So I see this as an alternative solution to #56. I've opened new thread, since it's a completely different concept.

**Comment by pateketrueke** [comment]
Te solution used on Faker.js is very clear, of course we can do the same.

About the template macro, we can do something like this?

```js
var jsf = require('json-schema-faker/support');
jsf.set('faker', function() {
  return require('faker/locales/es_MX');
});
module.exports = jsf;
```

This way the entry-point will export only what it needs because the `support` script would have an empty container, etc.

The resulting bundle would contain a localized faker and nothing else.
