### ISSUE TITLE
Error thrown when schema has allOf within anyOf 

### ISSUE THREAD

**Issue by tauren** [json-schema-faker/json-schema-faker#96]
The following code throws an Error:

``` js
import faker from "json-schema-faker"
let schema = {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Schema that contains anyOf with an allOf",
  "anyOf": [
    {
      "allOf": [
        {
          "properties": {
            "id": {
              "type": "integer"
            }
          }
        },
        {
          "properties": {
            "name": {
              "type": "string"
            }
          }
        }
      ],
      "required": ["id","name"]
    }
  ]
}
let result = faker(schema);
```

This produces the following error:

```
Error: missing properties for {"$schema":"http://json-schema.org/draft-04/schema#","title":"Schema that contains anyOf with an allOf","id":"http://json-schema.org/draft-04/schema#","allOf":[{"properties":{"id":{"type":"integer"}}},{"properties":{"name":{"type":"string"}}}],"required":["id","name"]} in /
```

The problem is the logic that verifies `properties` exist if `required` exist:
https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/types/object.js#L17-L20

The `allOf` objects need to be merged before running that logic, which I thought this code is doing:
https://github.com/json-schema-faker/json-schema-faker/blob/master/lib/index.js#L40-L50

Perhaps that code is never run on the object when an `allOf` is within an `anyOf`?

I'd be happy to submit a PR to fix this, but I'm not sure where the appropriate place is to fix it. Advice?

**Comment by pateketrueke** [comment]
Sorry for the inconveniences, this issue is now solved on `develop`.

I'm closing this in order to release soon! :beers:
